### ISSUE TITLE
Make ProductsSearchProvider search contents in other languages

### ISSUE THREAD

**Issue by tobias-kuendig** [OFFLINE-GmbH/oc-mall-plugin#1]
The [`ProductsSearchProvider.php`](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/search/ProductsSearchProvider.php) currently only searches for contents in the main language. To search through other languages it has to be extended to also look in `rainlab_translate_attributes`. 

For an example on how to do that see https://github.com/OFFLINE-GmbH/oc-site-search-plugin/blob/develop/classes/providers/RainlabBlogResultsProvider.php#L83

**Comment by alxy** [comment]
@tobias-kuendig I believe this can be closed.
