### ISSUE TITLE
Add taxes with country restrictions only when shipping to one of these countries

### ISSUE THREAD

**Issue by tobias-kuendig** [OFFLINE-GmbH/oc-mall-plugin#10]

**Comment by damsfx** [comment]
Thinks You can have multiple shipping taxes from one country for the same product.  

ex:
- Standard shipping (5-7 days) : 4 €
- Express delivery  (2-4 days) : 12 €
- Fedex 24h : 22 €

**Comment by tobias-kuendig** [comment]
I don't understand what you mean. Do you mean you can have multiple taxes per shipping method?

**Comment by tobias-kuendig** [comment]
@damsfx I know what you mean now. You can already restrict a shipping method to a specific set of countries.

What this issue is tracking is the tax that is added to the shipping price, which can have it's own country restrictions as well.
