### ISSUE TITLE
Site search integration

### ISSUE THREAD

**Issue by matteo-palazzo** [OFFLINE-GmbH/oc-mall-plugin#1000]
Hy guys, does `offline/oc-site-search-plugin` support Mall? The plugin page on OctoberCMS states that it does, but in the docs on github Mall is not mentioned. I've installed both Mall and Sitesearch on my site, but in the Sitesearch config page I cannot see the Mall section. Am I missing something? I'm on October 3.2.15, Mall 3.0.11 and Sitesearch 1.7.3

Thanks!

**Comment by tobias-kuendig** [comment]
Mall comes with SiteSearch support out-of-the-box. You should not have to enable anything manually. Isn't the search working as expected?

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/search/ProductsSearchProvider.php#L15

**Comment by matteo-palazzo** [comment]
Hi Tobias! My fault, it works perfectly. It was a stupid distraction error. Sorry guys!
