### ISSUE TITLE
Price and stock overview, undefined array key "type"

### ISSUE THREAD

**Issue by matteo-palazzo** [OFFLINE-GmbH/oc-mall-plugin#1003]
Hi guys!

If you try to edit any values of the "Price and stock overview" modal, **then click outside the table** and submit, you'll get an error 500 "Undefined array key "type"". 

It's pretty weird because if you don't click outside the table, the form is submitted correctly. Looks like the `_price_table_modal:104` is sending `this.state` without `{type: 'product'}`, but at the initial state - when modal is rendered - the value is present. I guess is fault of the `table` widget, but I'm not able to track down exactly when the value is lost...

I'm on a clean installation of OctoberCMS v3.2.21 and Mall v3.0.11.

Can you reproduce the error?
Thanks!

![Screenshot 2023-03-09 at 17-57-45 Edit product October CMS](https://user-images.githubusercontent.com/83695398/224105202-ea6b00aa-8378-4eeb-98cd-953c5441d2ca.png)

**Comment by tobias-kuendig** [comment]
That's a very strange bug indeed! Fixed in 4a678c3
