### ISSUE TITLE
Twig security not allowed method problem

### ISSUE THREAD

**Issue by inalto** [OFFLINE-GmbH/oc-mall-plugin#1005]
Hello,
I get this error in the cart

Twig\Sandbox\SecurityNotAllowedMethodError: Calling any method on a "OFFLINE\Mall\Classes\Totals\TotalsCalculator" object is blocked in "/home/quiyou/public_html/plugins/offline/mall/components/cart/table/total.htm" at line 10. in /home/quiyou/public_html/modules/system/twig/SecurityPolicy.php:181

on October 3.2.22

i try to look into this issue

**Comment by kevin-invato** [comment]
We also had this issue, try adding this to your env file: 

`CMS_SECURITY_POLICY_V1=true`

**Comment by tobias-kuendig** [comment]
Thank you @inalto and @kevin-invato. Compatibility with October's new security policy has been improved in v3.0.13.
