### ISSUE TITLE
Custom fields ajax bug in OCMS v3.2

### ISSUE THREAD

**Issue by kevin-invato** [OFFLINE-GmbH/oc-mall-plugin#1006]
Hi guys,

Question: I keep getting a javascript error when a custom field on a product is changed (checkbox checking/unchecking ie.)

I get the following error:

`Uncaught TypeError: (target || document).dispatchEvent is not a function`

This is coming from the scripts.htm in the product component:

`$body.on('change', '[data-mall-custom-field]', function () {
                $.request('onChangeConfiguration', {
                    form: $form,
                    loading: $.oc.stripeLoadIndicator
                })
            });`

Do you (or anyone else) have a fix for this issue? 

Thanks in advance!

- Kevin

**Comment by tobias-kuendig** [comment]
Thank you @kevin-invato, this has been fixed in df07115.
