### ISSUE TITLE
Checkout with zero amount results to Invalid request

### ISSUE THREAD

**Issue by buzmate** [OFFLINE-GmbH/oc-mall-plugin#1009]
Hello. I have an issue when my clients use coupons and the cart total is zero during checkout if they are still required to select the payment method, which is Paypal and on the final step the application tries to get the payment from paypal for zero amount in result the paypal to return:
"Failed to process your payment
Your order has been processed but the payment failed.

Please try again to pay this order.

The following error occurred:
Invalid request - see details"

Any advice? Is there any setting to disable the requirement to select a payment method when the total amount is zero?

**Comment by cyril-design** [comment]
There is a minimum amount to make a transaction (for example for Stripe it is $0.5 US).
In the logic of a free transaction, the payment gateway must be forced into invoice during checkout

**Comment by chocolata** [comment]
Hey, 

This is how I tackled this issue:
[https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/847](https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/847)

Hope it helps!

**Comment by tobias-kuendig** [comment]
Free orders are now bypassing the payment gateway and are immediately marked as paid.

Available in v3.5.0.
