### ISSUE TITLE
quickcheckout stripe is not working

### ISSUE THREAD

**Issue by papppeter** [OFFLINE-GmbH/oc-mall-plugin#1015]
Hi,

Stripe payment method is working only if it is selected as default.

solution would be:

 
           {% if isActiveMethod %}
                <div class="mall-quick-checkout__payment-method-form">
                    {{ __SELF__.renderPaymentForm() | raw }}
                </div>
                {% if this.request.ajax %}
                    {% scripts %}
                {% endif %}
            {% endif %}

in paymentmethod.htm

**Comment by fedorothebowl** [comment]
Nice! Thanks!

**Comment by tobias-kuendig** [comment]
Thank you @papppeter, this is available in v3.0.25.
