### ISSUE TITLE
"Trying to get property 'product' of non-object" when I add a product variant

### ISSUE THREAD

**Issue by DonnerTechQ2** [OFFLINE-GmbH/oc-mall-plugin#1023]
If I turn off the product with variants, the error disappears. I have a mall 1.16.3 with october 1.1.12
![изображение](https://github.com/OFFLINE-GmbH/oc-mall-plugin/assets/97617295/77afa359-1d60-495e-8c10-f24739970ff3)

**Comment by DonnerTechQ2** [comment]
I tried disabling google tag manager in layout, but the product variants still don't work
![изображение](https://github.com/OFFLINE-GmbH/oc-mall-plugin/assets/97617295/59790007-a0f8-49ae-8285-f6034b49698b)


this is the product page if i manually enter the link
![изображение](https://github.com/OFFLINE-GmbH/oc-mall-plugin/assets/97617295/ae17ddd0-dc94-46f5-ba6e-981d8c632036)

Please help me solve this problem

**Comment by tobias-kuendig** [comment]
Try running `php artisan mall:reindex`. If this does not work, check why this if statement does not return the empty colleciton in your case but proceeds to process the variants: https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/Product.php#L503

**Comment by DonnerTechQ2** [comment]
> Попробуйте запустить `php artisan mall:reindex`. Если это не работает, проверьте, почему этот оператор if не возвращает пустую коллекцию в вашем случае, а продолжает обрабатывать варианты: [ https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components /Product.php#L503 ](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/Product.php#L503)

`php artisan mall:reindex `did not work. I was able to solve the array_key_exists() error by replacing $variants->pull($this->getGroupedPropertyValue($this->variant)); with $variants->pull((string) $this->getGroupedPropertyValue($this->variant)); but product variants still do not work, although the product page loads.
![изображение](https://github.com/OFFLINE-GmbH/oc-mall-plugin/assets/97617295/2ffb6a03-190e-4f79-8cae-286747b3f5f3)

About that if statement - I don't know, I don't really understand this code

**Comment by SamBrishes** [comment]
Hello. 

I had a similar issue on October CMS v2, which I was able to solve by parsing the stringed numbers, as shown in [this commit](https://github.com/RatMD/oc-mall-plugin/commit/6264e4d17c2084e772ff7b7c064158838c564243). 

It's part of my PR #1077.

~Sam.

**Comment by SamBrishes** [comment]
Issue should have been fixed with v3.1.0.

Please (re) open or create a new issue if you encounter a similar or different bug.

Thanks.
