### ISSUE TITLE
On v2.0.23 when migrating: The use statement with non-compound name 'Schema' has no effect

### ISSUE THREAD

**Issue by jcongos** [OFFLINE-GmbH/oc-mall-plugin#1027]
After upgrading from v2.0.22 to v2.0.23, migrating gives the following error:
![image](https://github.com/OFFLINE-GmbH/oc-mall-plugin/assets/130073824/0c326013-1d45-4dae-a45e-b394ce27f635)

**Comment by tobias-kuendig** [comment]
This is fixed in v2.0.24
