### ISSUE TITLE
Problem In Adding Address from Backend User: Bad Sql Query Error: should be User Table ?

### ISSUE THREAD

**Issue by Andrea-Tecnotrade** [OFFLINE-GmbH/oc-mall-plugin#1032]
Hello,
i have the following error as i try to create a new address and associate to user:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'offline_mall_customers.name' in 'where clause' (SQL: select count(*) as aggregate from `offline_mall_customers` where (((lower(`offline_mall_customers`.`username`) LIKE %fd%) or (lower(`offline_mall_customers`.`name`) LIKE %fd%) or (lower(`offline_mall_customers`.`surname`) LIKE %fd%) or (lower(`offline_mall_customers`.`email`) LIKE %fd%) or (lower(`offline_mall_customers`.`created_ip_address`) LIKE %fd%) or (lower(`offline_mall_customers`.`last_ip_address`) LIKE %fd%))) and `offline_mall_customers`.`deleted_at` is null)" on line 760 of /var/www/html/octomall/public/vendor/laravel/framework/src/Illuminate/Database/Connection.php

 it looks like the query looking at wrong table, there aren't such fields in offline_mall__ustomers, i think it should be Users table.
I have no error when user signup from front-end.
Can you give me an hint to solce it ?
Thank you for your Collaboration

Andrea Berni 

![Schermata del 2023-07-03 17-40-27](https://github.com/OFFLINE-GmbH/oc-mall-plugin/assets/129889011/e7102d9d-642f-444a-81ba-44b5fdac759e)

**Comment by SamBrishes** [comment]
Fixed.

October tried to map the Mall\Customer model to the RainLab\User column definitions, thus the error occurred. The current solution was to use the RainLab.User model with a custom customer scope.

Part of [Pull Request](https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/1082).
