### ISSUE TITLE
New (custom) Payment Getway

### ISSUE THREAD

**Issue by HomaEEE** [OFFLINE-GmbH/oc-mall-plugin#104]
How I can create new Payment Getway - I want use liqpay in Ukraine [https://www.liqpay.ua/documentation/api/home/](url)

**Comment by tobias-kuendig** [comment]
1. Create a plugin for your custom provider
1. Implement the provider as described here: https://offline-gmbh.github.io/oc-mall-plugin/development/payment-providers.html#implement-a-paymentprovider
1. Register the custom provider as described here: https://offline-gmbh.github.io/oc-mall-plugin/development/payment-providers.html#implement-a-paymentprovider

You can take a look at the Stripe implementation for reference:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/payments/Stripe.php
