### ISSUE TITLE
can't update rainlab/user to 2.0

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#1045]
Hello.
ocms 3.4.10
mall 3.0.21
rainlab/user 1.72

I've updated my composer to `rainlab/user-plugin": "^2.0`

And i'm getting the conflict below. Do I need to update the [Mall composer file](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/8dfaf854bb6f5d725a4113f8de71b54a5e6039ac/composer.json#L26C1-L26C1)?
e.g. `"rainlab/user-plugin": "^2.0"`
Will Mall work OK with user 2.0?
Thanks

```
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - offline/oc-mall-plugin[v3.0.0, ..., v3.0.21] require rainlab/user-plugin ^1.6 -> found rainlab/user-plugin[v1.6.0, ..., 1.x-dev] but it conflicts with your root composer.json require (^2.0).
    - Root composer.json requires offline/oc-mall-plugin ^3.0 -> satisfiable by offline/oc-mall-plugin[v3.0.0, ..., v3.0.21].
```

**Comment by tobias-kuendig** [comment]
Thank you for reporting the issue. Please try v3.0.22 of Mall, it should accept Rainlab 2.0 now.
