### ISSUE TITLE
Double mall.order.shipped event

### ISSUE THREAD

**Issue by vosco88** [OFFLINE-GmbH/oc-mall-plugin#1053]
Hello, 

I would like to extend the plugin after mall.order.shipped event to generate shipping labels via carriers APIs. 
Hoevewer when I set the order as shipped in backend the event is fired twice (once in `afterUpdate` of `Order.php` model and once in `onUpdateTrackingInfo()` in `Orders.php` controller.

Shouldn't this be fired only once? Because within `onUpdateTrackingInfo()` the method `updateOrder` is called which calls the `afterUpdate` or `Order.php`. Although not sure if there is another reason for this.

Thank you.

**Comment by tobias-kuendig** [comment]
I don't see a reason why the Event is fired in the controller. Could you test if everything works as expected if you remove this line: 

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/87a414fc16fc262cb1b516b5eb9bb7d90fa2e356/controllers/Orders.php#L122

Thank you!

**Comment by vosco88** [comment]
It seems to work fine with just the event on the model firing

- order is marked as shipped and moved to shipped state
- `shipped_at` is filled
- event `mall.order.shipped` is fired once
