### ISSUE TITLE
Modifiers or topping group for category or products 

### ISSUE THREAD

**Issue by HomaEEE** [OFFLINE-GmbH/oc-mall-plugin#106]
Ability to create a group of modifiers (price change from color or size) or toppings (for example, for pizza) and assign it to a category or product

**Comment by tobias-kuendig** [comment]
Can you give me a concrete example? There are custom fields that can be assiged to every product where the customer can select options during checkout. 

Maybe this is already what you mean?

https://offline-gmbh.github.io/oc-mall-plugin/development/product-model.html#property-values

**Comment by HomaEEE** [comment]
sorry for the carelessness - this is what you need
