### ISSUE TITLE
Email is not sent when shipping state is updated

### ISSUE THREAD

**Issue by cyril-design** [OFFLINE-GmbH/oc-mall-plugin#1060]
Since this [commit](https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/1053), email is not sent when an order state is marked as shipped.

Because `$order->shippingNotification` is `null` in `orderShipped` method in [MailingEventHandler](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/2abb6a3264d9003161603ff5b5142be58090a34b/classes/events/MailingEventHandler.php#L207C1-L208C1)

I thinks that's why the Event is fired in the controller, see [discussion](https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/1053#issuecomment-1695080093)...

OctoberCMS: 3.51 /
Laravel Framework: 9.52.16 /
Mall: 3.0.26

**Comment by tobias-kuendig** [comment]
Thank you for the report @cyril-design. There was a logic error in setting the property that has been fixed here: 8b6423f

Please let me know if the issue still persists in v3.0.27

**Comment by cyril-design** [comment]
Thanks Tobias !
