### ISSUE TITLE
Abandoned and bots carts

### ISSUE THREAD

**Issue by damsfx** [OFFLINE-GmbH/oc-mall-plugin#1064]
### Bots carts

I see on multiple web site, that Search engine's bots (and other tool like Semrush or UptimeRobot) are creating multiple carts each time they visit the site.  
At this time on one of my site, I have more than 200000 carts in database.  
Can some of you, confirm that you also have a very large number of pending carts.

If this is confirmed, do you think we can exclude the creation of carts for these robots?

### GDPR plugin data retention integration 
I see #379 issue and the cart's model `gdprCleanup()` method.  

This method is labeled as "Delete abandoned shopping carts", but it delete <ins>**all**</ins> carts updated past a date, either they are customer's carts or empty carts.  
So I'm wondering whether the function should be called something else: **Delete all old carts**?
What do you think?

### Cleanning
Meanwhile, if I want to delete all the shopping baskets created by search engine robots, but without deleting my customer's old shopping baskets, do you think is was possible to include this function in the plugin, or would it be better to create this cleaning function in my dedicated plugin (in both case either with the RGPD plugin functionality, or a command)?

**Comment by tobias-kuendig** [comment]
@damsfx see https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/280 for more details. Ideally, a cart will only be created once the user adds a product.

**Comment by damsfx** [comment]
> @damsfx see #280 for more details. Ideally, a cart will only be created once the user adds a product.

Has this already been added to the plugin?
I can't find any reference.

If not, do you want a PR (it will be in the v2 branch - but the feature didn't evolve until the develop version)?

**Comment by tobias-kuendig** [comment]
I haven't had the time to integrate it, so no there is no PR. @Samuell1 once shared some code with me that they come up with. The bigger part of this feature is to test that it still works with the on-the-fly carts.

> If not, do you want a PR (it will be in the v2 branch - but the feature didn't evolve until the develop version)?

That would be awesome!

**Comment by tobias-kuendig** [comment]
Since v3.4.3 carts are no longer created for simple page visits. This should drastically reduce the abandoned cart count.
