### ISSUE TITLE
Order ID in links from checkout result actions

### ISSUE THREAD

**Issue by damsfx** [OFFLINE-GmbH/oc-mall-plugin#1070]
I'm taking a closer look at the links in MALL and I'm wondering: 

Does the link generated in the following section really include the order ID in the parameter?
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/47c34553bce866b47615c2cf9ca331207663079a/components/checkout/resultactions.htm#L2

According to the documentation, the "My account" page should be defined as follows: 
```
title = "Account"
url = "/account/:page?"
layout = "default"
is_hidden = 0
...
```
see: https://offline-gmbh.github.io/oc-mall-plugin/getting-started/theme-setup.html#pages

But the URL does not contain an `order` segment !

If I modify the page URL to `/account/:page?/:order?` all links generated in 
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/47c34553bce866b47615c2cf9ca331207663079a/components/MyAccount.php#L128

contains an un-required order ID.

Did I miss something? Your thoughts?

**Comment by tobias-kuendig** [comment]
@damsfx you are correct, that param is not used. Fixed in 71ac556
