### ISSUE TITLE
Session ID field

### ISSUE THREAD

**Issue by georgijk5** [OFFLINE-GmbH/oc-mall-plugin#1071]
Hi,

We're getting this error message,

`PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'session_id' at row 1`

Could we change the migrations for session_id in cart, wishlist and order tables to be text instead of string? 

Would that be a sufficient fix?

**Comment by tobias-kuendig** [comment]
Do you see what value the plugin is trying to insert into the table? The string should not be longs than 100 chars:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/71ac5567c92d156d033191f7425b30f15c882a4c/classes/traits/cart/CartSession.php#L46C102-L46C105

The `string` column type should be sufficient for that.

**Comment by georgijk5** [comment]
Hi Tobias,

I rechecked the Event Log and just saw that the last occurrence was on Friday, and the error has stopped showing up.

I'll keep on investigating and report back if I find anything.

**Comment by SamBrishes** [comment]
Hello,

closing this issue for now, feel free to re-open if this problem occurs again. 
Thanks

~ Sam.
