### ISSUE TITLE
PDF Invoice

### ISSUE THREAD

**Issue by MateThemes** [OFFLINE-GmbH/oc-mall-plugin#108]
Hello!

First a big thank you for your great ecommerce plugin for OctoberCMS. Such a great ecommerce plugin was really missing on the marketplace.

I want to ask, if it is possible to autogenerate PDF Invoices or if this feature is on your list?

Thank you!

**Comment by tobias-kuendig** [comment]
Thank you for your feedback! It is currently not possible but will be added in a future version eventually. You could implement it yourself by listening to the [`mall.checkout.succeeded`](https://offline-gmbh.github.io/oc-mall-plugin/development/events.html#mall-checkout-succeeded) event.

I'm leaving this issue open to track progress for this feature.

**Comment by MateThemes** [comment]
Okay!

How to I use the mall.checkout.succeeded event? Can you please provide me some help!

Thank you very much!

**Comment by tobias-kuendig** [comment]
In your Plugin.php boot method you can listen for the event and do with it whatever you want (something like generating a PDF).

You'll receive a `OFFLINE\Mall\Classes\Payments\PaymentResult` instance as parameter where you get access to the order.

```php
public function boot()
{
    Event::listen('mall.checkout.succeeded', function($result) {
        info('Checkout succeeded!', ['result' => $result]);
        // $order = $result->order;
    });
}
```

**Comment by timconsidine** [comment]
I tried the above example with v1.1.7
I got exception 
Class 'OFFLINE\Mall\Event' not found
Any ideas ?

**Comment by timconsidine** [comment]
I tried the above example using V1.1.7
I got exception

> Class 'OFFLINE\Mall\Event' not found

Any ideas ?

**Comment by tobias-kuendig** [comment]
```php
public function boot()
{
    \Event::listen('mall.checkout.succeeded', function($result) {
        info('Checkout succeeded!', ['result' => $result]);
        // $order = $result->order;
    });
}
```

Sorry, wasn't clear from my example. You have to use `\Event` or add `use Event;`

**Comment by DrakusorU** [comment]
I would also like to have this option and more importantly to be able to print the invoice myself from the backend.. that would make it so much easier to just click a button, print the invoice and have it sent to the customer.. I find that in the backend having the option to set the invoice number not useful, instead of that the invoice number should be set automatically based on the order number.. 

So... having the option to download and print the invoice in backend ( that I guess would also make it easier for a front-end dev. to implement download for customers ) and also a way to customize the template of the invoice would complete the basic features a store owner would need.. for as I far as I played with this plugin this is the only missing thing I've tripped on..

**Comment by tobias-kuendig** [comment]
This feature has been implemented in f46dd20 and is available in version 1.8.0 via edge updates.

It will be released as a stable update in the comming days.

For anyone that is looking forward to testing this, please report back how it went!

https://offline-gmbh.github.io/oc-mall-plugin/changelog/1.8.0.html

**Comment by tobias-kuendig** [comment]
Released!

**Comment by Dreanad** [comment]
Hello, 
thank you for your work, its a realy great plugin !! 

I have a question, is that possible to get a download button in the orderList page ?

**Comment by tobias-kuendig** [comment]
You can easily add this yourself by extending the backend list and adding a custom partial of yours:
https://octobercms.com/docs/plugin/extending#extending-backend-list

I feel like adding a button by default would clutter up the view. Maybe we can add it as a column that can be added via the list configuration by the user.

If you feel up to it, a PR for this would be welcome. A new `download_invoice` column that is `invisible` by default.
