### ISSUE TITLE
Duplicating Product messes up with Product Images and Variants

### ISSUE THREAD

**Issue by ogalbnafets** [OFFLINE-GmbH/oc-mall-plugin#1081]
Hello there,

thanks for developing and mantaining this plugin!
I'm building a webshop with many products with almost the same properties... So I only want to duplicate a product and change it, but 2 bugs are making it very hard.

OCMS Version: 3.5.14
Mall Version: 3.0.30

1. Duplicate Product with variants
2. The original first product has now the variants also multiple times, also in the new duplicated product sometimes -> see screenshots of copy and original
3. When changing the pictures in the second product, the new images won't appear at the product pages (I also tried to delete the picture-set and creating new pictures). If it helps - in the products component the correct image appears

![grafik](https://github.com/OFFLINE-GmbH/oc-mall-plugin/assets/70335936/02b4b580-ea36-47d1-8ed5-a8732d55f883)
![grafik](https://github.com/OFFLINE-GmbH/oc-mall-plugin/assets/70335936/ce48db64-4c5d-4ee9-bc58-9f9e152cd1d3)

I use this theme, if that helps: Bootstrap 5 Mall Starter

It would be awesome to resolve this issues, I'm happy to help!

**Comment by SamBrishes** [comment]
Hello,

thanks for the bug-report. I was able to reproduce both errors and the fix should be part of the upcoming release (3.2.0). If you need the changes urgently, I recommend adopting the changes from [this commit](https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/7ea8e1e727ee7b5185d263af49567114c0b03d81). The changes are limited to 2 files.

Thanks.

~Sam.

**Comment by ogalbnafets** [comment]
Thank you, the problems are resolved! Thanks for the fast response!
