### ISSUE TITLE
Out of stock message but stock is available

### ISSUE THREAD

**Issue by xyz1123581321** [OFFLINE-GmbH/oc-mall-plugin#1085]
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/traits/cart/CartActions.php#L53

@SamBrishes is there any reason for adding the quantity first then checking for stock validation?

```
 $this->validateStock($variant ?? $product, $quantity);
 $cartEntry->update(['quantity' => $newQuantity]);

```
shouldn't be like this? If so I can make a PR

**Comment by SamBrishes** [comment]
Hello @xyz1123581321.

> is there any reason for adding the quantity first then checking for stock validation?

At least I can't see any valuable reason for this. However, changing the order seems to fix your issue without occurring any new one.

A PR would be very welcome.

Thanks.
