### ISSUE TITLE
Deprecated messages in error log with PHP 8.2 and 8.3

### ISSUE THREAD

**Issue by RickAcb** [OFFLINE-GmbH/oc-mall-plugin#1106]
When we checked the PHP logs we had seen multiple deprecated messages in Offline Mall.

We solved the ones we could find. See https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/1105

**Comment by SamBrishes** [comment]
Hello,

thanks for your pull request, will be released with v3.2.0.

Sincerely,\
Sam.

**Comment by SamBrishes** [comment]
This issue has been fixed and released with v3.2.0 / v3.2.1.
