### ISSUE TITLE
Download Invoice button missing in backend orders.

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#1117]
Hello. 
We recently added stripe as a payment method.
As far as I can tell, in the backend, the "Download Invoice" button has disappeared on the orders page.
It's still there for our old "Sagepay" orders.
Can anyone throw some light on this?
Thanks.

**Comment by SamBrishes** [comment]
Hello,

did you selected the `PDF attachment partial` on the Stripe Payment Method? This partial is used for the invoice creation.

![image](https://github.com/OFFLINE-GmbH/oc-mall-plugin/assets/106578633/e04aa212-7412-4527-a000-f73d2f461c65)

Sincerely,\
Sam.

**Comment by dathwa** [comment]
Yep. Missed that one :)
Thanks
