### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by domugo** [OFFLINE-GmbH/oc-mall-plugin#112]
I get this error installing. I've tried multiple hostings. All the same.

"Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE)" on line 16 of /*/public_html/oct/plugins/offline/mall/models/Currency.php

What might be causing this?

**Comment by tobias-kuendig** [comment]
The plugin requires PHP 7.1, it looks like you are using an older version.

**Comment by Tetraneon** [comment]
Hi,
I try to install this plugin with OCTOBER CMS - v446 and I have the same error with a php 7.1 
```
php -v 
PHP 7.1.26-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jan 11 2019 14:13:16) ( NTS )
```
Any idea ?
Best regards

**Comment by tobias-kuendig** [comment]
Class constant visibility was added in PHP 7.1:
https://secure.php.net/manual/en/migration71.new-features.php#migration71.new-features.class-constant-visibility

If you get the error message above your webserver is not serving your PHP pages with 7.1.

You might have another version than 7.1 configured to be used by Apache/Nginx.

**Comment by Tetraneon** [comment]
You're right.
Just for the others : 
```
$ sudo a2dismod php7.0
$ sudo a2enmod php7.1
$ sudo service apache2 restart
$ sudo update-alternatives --set php /usr/bin/php7.1 
```
Thanks for your work !
