### ISSUE TITLE
"Illegal offset type" on line 105 of ~/app/plugins/offline/mall/classes/traits/CustomFields.php

### ISSUE THREAD

**Issue by cyril-design** [OFFLINE-GmbH/oc-mall-plugin#1124]
Since version 3.2 I have this message.
I have created a [patch](https://github.com/cyril-design/oc-mall-plugin/commit/7eeeac12aa354de489a601f7fdf3a55945364437#commitcomment-141647600)

Thanks !

**Comment by tobias-kuendig** [comment]
Do you have a stacktrace for this issue? I guess solving the return value only hides the real issue, so we need to know where it originated from.
