### ISSUE TITLE
Missing default values in component \offline\mall\components\product\customfields\text.htm for CMS_STRICT_VARIABLES=true

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#1132]
Hello.
Can we please have a default for...
plugins\offline\mall\components\product\customfields\text.htm: {{ item.property.hashId|default(0) }}
Thank-you.

**Comment by tobias-kuendig** [comment]
@dathwa What's the issue this resolves?

**Comment by dathwa** [comment]
> @dathwa What's the issue this resolves?

If I have CMS_STRICT_VARIABLES set to 'true' then the page break.
