### ISSUE TITLE
Can't update to Rainlab\User V3.0

### ISSUE THREAD

**Issue by ogalbnafets** [OFFLINE-GmbH/oc-mall-plugin#1133]
Hello,

when trying to update octoberCMS and the User plugin I get an error from composer

```
  Problem 1
    - Root composer.json requires offline/oc-mall-plugin ^3.2 -> satisfiable by offline/oc-mall-plugin[v3.2.1].
    - offline/oc-mall-plugin v3.2.1 requires rainlab/user-plugin ^1.6|^2.0 -> found rainlab/user-plugin[v1.6.0, ..., v1.7.2, v2.0.0, v2.1.0] but it conflicts with your root composer.json require (^3.0).
```

Is an update planned :) Thanks! Looking forward to try 2FA.

**Comment by ogalbnafets** [comment]
And also rainlab\location-plugin is locked to rainlab/location-plugin (^1.2), there is a new version 2.0.0
Thank you guys :)

**Comment by Andrea-Tecnotrade** [comment]
Hello have you found a solution?

**Comment by ogalbnafets** [comment]
hello, I think the version for Mall in composer is locked - I thought maybe there will be soon an Update for Mall so I didn't want to try out to change composer and to risk anything...

**Comment by tobias-kuendig** [comment]
v3.3.0 of Mall has support for RainLab User 3.0. There might still be some issues left since the plugin changed considerably. Please feel free to report any issues you find.
