### ISSUE TITLE
Free products error. DivisionByZeroError: Division by zero in /offline/mall/classes/pricing/concerns/ApplyDiscounts.php:37

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#1136]
Hello. 
Mall 3.2.1 and gettng this error when user adds to basket.
`DivisionByZeroError: Division by zero in /offline/mall/classes/pricing/concerns/ApplyDiscounts.php:37`

The issue is that some of our products are free for members.
On line 37, can we change

`$products[] = intval(round((100 / $total) * $product->exclusive()->toInt()));`

to something like...?

```
if ($total > 0)
{
  $products[] = intval(round((100 / $total) * $product->exclusive()->toInt()));
}else{
  $products[] = 0;
}
```

BTW, I have a "Free payment" method to cover zero cart totals, but i can imagine a 100% discount might break certain payment methods.

Any other areas where a cart total of zero might break it?
Thank-you.

**Comment by tobias-kuendig** [comment]
Thank you @dathwa, this is fixed in v3.3.0
