### ISSUE TITLE
Wrong price if price start with 0. and has more than 2 decimal example: 0.4567 

### ISSUE THREAD

**Issue by Andrea-Tecnotrade** [OFFLINE-GmbH/oc-mall-plugin#1138]
Hello, 
if add a price from backend in product with more than two decimal ex: 0.34567 also if i chose  5 decimals, the saved price is always 34 and the displayed price is always 0.34000
How can i do? 

Thank you for your collaboration
Sincerely
Andrea Berni

**Comment by tobias-kuendig** [comment]
@Andrea-Tecnotrade there is currently a fixed limit on two decimal places. All prices are multiplied by 100 before they are stored and divided by 100 after they are fetched. This is to circumvent floating point errors.

The factor of 100 limits the stored value to two decimal places.

You could introduce a configuration option to set this to 1000 or 10000, this setting has then to be used everywhere in the codebase where a price is converted (`* 100` or `/ 100`).

**Comment by Andrea-Tecnotrade** [comment]
Thank you very much. Cause i had to sync with erp, i used a couple of trick to create custom addToCart function to calculate righe prices adding an extra /100 or *100 to have the righe price in price json field.
