### ISSUE TITLE
Dropshipping Compatibility

### ISSUE THREAD

**Issue by artistro08** [OFFLINE-GmbH/oc-mall-plugin#114]
If you could create an API that attaches to Printful (or other dropshipping services), It would make OctoberCMS super powerful.  It would also be a great contender against Shopify, WooCommerce, Squarespace, etc.

**Comment by amdad** [comment]
October IS super powerful. But Dropshipping compatibility have nothing to do with October, but with Mall itself. Still, rather not with default Malll. Integration like this for sure can be done. But rather as a separate plugin to extend Mall.

**Comment by artistro08** [comment]
That sounds like a plan. I apologize about the comment, OctoberCMS is super powerful. I agree a new plugin is in order
