### ISSUE TITLE
Optimising `UniquePropertyValuesInCategoriesQuery` logic

### ISSUE THREAD

**Issue by tomaszstrojny** [OFFLINE-GmbH/oc-mall-plugin#1149]
Hi @tobias-kuendig !

We're currently working on a shop that has really many variants. Over a hundred products have 200+ variants.

As you're probably aware, the performance is really slow, as mentioned here:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/744

 I can't find any reasonable way from the business perspective to run from the problem like it was in the issue above so I'm looking the reason behind the problem.

It turns out that the biggest problem is `UniquePropertyValuesInCategoriesQuery`. In my case it's taking over 2 minutes to fetch the results of the query.

I was playing with the query and I think I understand what's causing it - without grouping, the query is returning over 12 milion records. It's the grouping that takes ages (which is understandable!).

I can't imagine any way of optimising the query but I'm thinking about moving the records in initially parsed version to a separate table/cache so that it's much easier for the database to fetch property values for categories. Generating the records could be handled in queue job when updating products, categories or values.

Right now it's only an idea, and I'll work on that but before doing so I wanted to know your opinion, does this sound reasonable and if so are you ok to check my PR when it's ready?

Thanks for great plugin man!

**Comment by tobias-kuendig** [comment]
PR merged and released at v3.4.0, thank you @tomaszstrojny!
