### ISSUE TITLE
Customer Group prices not working

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#1156]
Hello.
OCMS 3.6.29, MALL 3.4.2.
We have a "members" customer group, and special prices for these customers.
Both prices show on the product page, but the customer is always charged full price.
Not sure when this issue started.
I've tested with Mall Demo Theme, and issue is still there.
I'll dig around, but can you please take a look?
Thank-you.

**Comment by dathwa** [comment]
I'm also using Rainlab/User 3.0 - any chance this has affected customer group rices?

**Comment by daftspunk** [comment]
See if this fixes it: 

https://github.com/rainlab/user-plugin/commit/b3e6218ed69cf7dcaea944b5c88cc0fdec1a4a37

**Comment by dathwa** [comment]
Alas, @daftspunk , this made no difference. Just so you are clear "Customer Groups" are specific to the Mall plugin, and nothing to do with "User Groups".
@SamBrishes / @tobias-kuendig - can you possibly comment on this? 
Thank-you.

**Comment by tobias-kuendig** [comment]
Fixed in 9339c6a2, thanks for the report @dathwa. There was a check that failed with RainLab.User 3.0 but was not required in the first place, so it could simply be dropped.
