### ISSUE TITLE
artisan mall:seed results in error: The first name field is required.

### ISSUE THREAD

**Issue by Servery** [OFFLINE-GmbH/oc-mall-plugin#1158]
I am on a fresh October CMS install (without composer, installed with wizard).

Build: 3.6.29
RainLab.User: 3.1.3
OFFLINE.Mall: 3.4.5

When I seed initial data, there is an error:

![Screenshot 2024-08-22 232240](https://github.com/user-attachments/assets/4e8bd0c8-9eab-4e3e-99d9-56b742d029fb)

The fix #1155 is not working for me - if it is the right one for my problem?!

**Comment by tobias-kuendig** [comment]
Thanks @Servery, the seeder was no longer compatible with all RainLab.User plugin versions. This is now fixed in v3.4.6.

**Comment by Servery** [comment]
Thank you for this prompt update. This problem is now solved. ;-)
