### ISSUE TITLE
Free orders no longer require a payment not working?

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#1160]
Hello. I see you've added a "Free orders no longer require a payment" to v3.5.
I've tried switching to demo theme to see how this might work, but not really sure what's supposed to happen.
In my cart i have a free product.
I go to quick checkout, and it's still asking for stripe card details.
Is there something I need to configure?
Thank-you.

**Comment by tobias-kuendig** [comment]
@dathwa the change only happened server side. Mall does no longer initiate a payment if the order is 0, the frontend components have not been updated to hide the payment prompt for free orders.

**Comment by dathwa** [comment]
Just to be clear; as long as i hide all payment options if the cart value is zero, I can click "Place Order", and the order will go thru OK?

**Comment by tobias-kuendig** [comment]
Yes, just make sure you have actually a payment method select (for example in a hidden form field) if you hide the options.

**Comment by dathwa** [comment]
Yip - I've have my own "Free" payment method if cart value is zero.
Thanks for clearing this up :)
