### ISSUE TITLE
Can't download virtual products

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#1162]
Hello.
This is happening on Mall 3.4.5 and Mall 3.5.
I have rainlab/user ^3.0
Virtual product is a PDF, with "login required" = Yes.
Customer purchases virtual product. Download link is available in Orders.
Clicking on the link, when logged in, 
and it fails with the Message "Please log in to continue" (offline.mall::frontend.session.login_required)

See `\plugins\offline\mall\classes\downloads\VirtualProductFileDownload.php`
line 35 `if ($product->file_session_required && ! Auth::getUser()) {`
if I change this to `if ($product->file_session_required && ! Auth::user()) {` it works again. Can we change this?

see https://github.com/rainlab/user-plugin/blob/master/UPGRADE.md#:~:text=New%20Method-,getUser(),-user()
Fine so far.
But search for " Auth::getUser()" in Mall plugin and I come across 23 instances of this old usage.
Seems to be inconsistent.
Can you please explain?
Thanks

**Comment by tobias-kuendig** [comment]
Thank you for bringing this up, @dathwa. This was an oversight when migrating to RainLab.User 3.0. 

v3.5.1 fixes this.
