### ISSUE TITLE
Gateway Timeout 504

### ISSUE THREAD

**Issue by SalvalajoRiccardo** [OFFLINE-GmbH/oc-mall-plugin#1172]
hello,

i have a problem with creation of variants inside products, from version 3.0 of this plugin (v3 of october), the time to create a variant its been increased drastically, up to the point where having more than 20 variants take minutes to create one, when the list of variants is 30/35+ the time to create is about 3/4 minutes each and it throws an error:

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>504 Gateway Timeout</title> </head><body> <h1>Gateway Timeout</h1> <p>The gateway did not receive a timely response from the upstream server or application.</p> <hr> <address>Apache/2.4.29 (Ubuntu) Server at "myurl"Port 80</address></body></html>

and not all the time the variant is created, or a complited one, i tried even with a fresh installation with only one product, but the behavior still exist.

I don't know if it is a know issue or something new, but doing data entry is realy painfull right now, so i want to ask if there is a workaround or it need to be fixed.

Best regards and Thanks for your work.

**Comment by tobias-kuendig** [comment]
@SalvalajoRiccardo please check the query log and/or how any images are created. This way you should be able to find the bottleneck.

**Comment by SalvalajoRiccardo** [comment]
@tobias-kuendig thx for your reply, after testing for few hous, i solved the error 504 by changing some settings in mysql like "innodb_lock_wait_timeout" and global log_output = 'table', now its manageble but still quite slow(30/40sec to create 1 variable), and i encountered another problem, if a product have more then 40 (more o less)  variants, and i change anything in the product, it does not save the changes, and it gives me another error:

Maximum execution time of 300 seconds exceeded in /myurl/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:322

can't understand if the machine is not powerfull enough, too much variants to handle or maybe something else im not considering.

**Comment by tobias-kuendig** [comment]
When you enable Laravel's queue, can you update the product? It can be a MySQL backed queue. Enabling it and saving a product should immediately tell you if this will solve your problem. If you no longer notice the performance issues, use the queue and run queue worker in the background.

I'm not sure what part of the code is causing the problem in your case, but some of the processing is pushed to the queue when it is enabled, so it is worth a try.

**Comment by SalvalajoRiccardo** [comment]
@tobias-kuendig solved with "QUEUE_CONNECTION=database" in my .env, as you suggested , thank you very much for your time and your knowledge, have a good day.
