### ISSUE TITLE
Plugin breaks default theme localization in OctoberCMS v3.6.x

### ISSUE THREAD

**Issue by LZaplata** [OFFLINE-GmbH/oc-mall-plugin#1174]
Hello, I have installed OctoberCMS, create theme and add some localization strings into templates according https://docs.octobercms.com/3.x/cms/themes/localization.html. Everything worked fine until I installed Mall plugin, `_trans` filter stopped woking somehow after that. If I uninstall plugin, localization starts working again. Is this a bug or am I doing something wrong?

**Comment by LZaplata** [comment]
Possible fix is to rewrite `Validator::extend()` on this line https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/next/classes/registration/BootValidation.php#L12 to `$this->registerValidationRule()`.

**Comment by tobias-kuendig** [comment]
Thanks @LZaplata, this is fixed in v3.5.4.
