### ISSUE TITLE
Bug in PaymentMethodSelector component

### ISSUE THREAD

**Issue by vosco88** [OFFLINE-GmbH/oc-mall-plugin#1181]
This change `$this->setVar('paymentMethods', PaymentMethod::getAvailableByCart($this->cart));` which was made here #1169 renders the paymentMethodSelector in quickCheckout not working on the payment step as it references `methods` variable.

Also as a component variable there is `$methods`.

There are two options

1. Change `paymentMethods` back to`methods` which is the easiest and quickest. 
2. Update the paymentMethodSelector component variable and the partial files with `paymentMethods`

But I am not sure if the change from `methods` to `paymentMethods` drives something else as well as I also see some changes in quickch

**Comment by tobias-kuendig** [comment]
Fixed in v3.5.7, thank you @vosco88!
