### ISSUE TITLE
foreach() argument must be of type array|object, null given

### ISSUE THREAD

**Issue by lcver** [OFFLINE-GmbH/oc-mall-plugin#1182]
"foreach() argument must be of type array|object, null given" on line 118 of D:\Project\website\watertec-website\plugins\offline\mall\models\PropertyGroup.php

This happen when I want to remove single or multiple Properties,

**Comment by tobias-kuendig** [comment]
Thank you for the bug report, @lcver! This should be fixed in v3.5.10.
