### ISSUE TITLE
[Proposed Enhancement] Product URL linked to product ID

### ISSUE THREAD

**Issue by letthewriterswrite** [OFFLINE-GmbH/oc-mall-plugin#119]
It would be useful to auto fill the URL field when creating a new product with the Product ID or some kind of unique identifier instead of manually entering it. Makes it easy to create human error.

![image](https://user-images.githubusercontent.com/13875478/52141166-76769980-261a-11e9-94ed-58c3befbe163.png)

**Comment by letthewriterswrite** [comment]
It is not automatically generating for me.

**Comment by amdad** [comment]
It is, at first time before you save. Then it trying to not change itself each time. That would break current url to a product!

**Comment by tobias-kuendig** [comment]
The product model is using October's Sluggable Trait. It's not possible that a model gets created without a unique URL.

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/models/Product.php#L54

Are you creating the product via the backend and then after creation the URL field is empty? Even in the database?

**Comment by letthewriterswrite** [comment]
What's strange is that it only did this error when I created the first product. Now it does automatically create URL. Not sure why.

 On a separate note,why make it editable if it can break?

**Comment by amdad** [comment]
"break" it at will, not by accident. You should be able to change a url if you will, but it shouldn't be breaking each time when you change a Name. That's how it works in other October plugins too. So nothing weird here.

**Comment by letthewriterswrite** [comment]
You can't trust an average user to know this. Must be fail safe for it to be a good design.

**Comment by amdad** [comment]
It does not break anything. It doesn't. URL is part of content creation.  If user is stupid enough to forget that after URL change he lost existing somewhere else links that's his problem. There is another plugin to create redirection. Bad design would be doesn't allow user to change it's own alias. At best, a comment can be added under  alias field. to be sure user know this.

**Comment by tobias-kuendig** [comment]
The user won't break anything by changing the URL. Worst case is that already indexed pages return a 404 error. The shop itself will work just fine. This is the same for any other CMS model that uses slugs. I don't think this plugin needs to handle this any other way. 

If your "average user" doesn't know what an URL is and what changing it might do to the system you need to educate them about this.
