### ISSUE TITLE
Missing button for re-ordering products?

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#1196]
Hello.
There no longer seems to be any way to re-order products in the category section.
And no wayt to drag products around.
Am I missing something?
Thanks. 

![image](https://github.com/user-attachments/assets/1b826110-f344-4e9c-b9d9-d7bdfa39d797)

**Comment by tobias-kuendig** [comment]
What version of October are you using? You should see the new native sort handle that October provides.

**Comment by tobias-kuendig** [comment]
This is fixed in v3.5.16, thank you @dathwa
