### ISSUE TITLE
[BUG] Negative Quantities should not be allowed

### ISSUE THREAD

**Issue by letthewriterswrite** [OFFLINE-GmbH/oc-mall-plugin#121]
I found a bug where if you add a negative quantity to the cart, you get a negative total. I do understand that you can set a minimum quantity in the products section but it should not allow less than 1 to be the minimum. 

![image](https://user-images.githubusercontent.com/13875478/52146151-8f864700-2628-11e9-830d-abd53b8f42b2.png)

**Comment by tobias-kuendig** [comment]
Fixed in 9df7e86, thank you for the bug report!
