### ISSUE TITLE
How To Display the "Additional Description" under the "Details" Tab

### ISSUE THREAD

**Issue by artistro08** [OFFLINE-GmbH/oc-mall-plugin#122]
Title says it all. How do I display this information. Couldn't find any documentation on it

**Comment by tobias-kuendig** [comment]
You can access this field on a `Product` or `Variant` model.

```php
$product->additional_descriptions;
```

or if you are using the `Product` component you can access it on the `item` variable in twig:

```twig
{% for description in item.additional_descriptions %}
    <h3>{{ description.name }}</h3>
	<div>{{ description.value | raw }}</div>
{% endfor %}
```

**Comment by artistro08** [comment]
This worked. Thank you, you're awesome
