### ISSUE TITLE
Negative stock quantites

### ISSUE THREAD

**Issue by alxy** [OFFLINE-GmbH/oc-mall-plugin#127]
Not sure if this a bug or a feature, but currently the seeder sets a negative stock quantity for the jersey: https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/demo/products/Jersey.php#L111

Is this intended? I was thinking a stock can only be equal or greater than zero....

**Comment by amdad** [comment]
I think, that feature,  When you pre-sale. User know he just need to ship -2 for example that wasn't at stock when user bought it. So seller need to get those 2. 

There is a button for allowing sells when Stock quantity is empty.  So minus, tells you how much you sold and need to ship.

**Comment by tobias-kuendig** [comment]
This is indeed intended and can be used exactly as @amdad described.

Also, there is the `allow_out_of_stock_purchases` option for products. You might have a situation where you know you'll get 100 high demand items shipped by a vendor tomorrow but your stock today is only 2. So you can enable `allow_out_of_stock_purchases` to give customers the ability to buy even though your stock will temporarily be negative.
