### ISSUE TITLE
Variant names are not translatable

### ISSUE THREAD

**Issue by alxy** [OFFLINE-GmbH/oc-mall-plugin#128]
Just implementing/configuring the behavior doesnt work out of the box. (Interface works, but data is not saved)

**Comment by tobias-kuendig** [comment]
could it be related to this?
https://github.com/rainlab/translate-plugin/issues/209

**Comment by alxy** [comment]
This sounds very much related - I will implement the provided trait when I find the time.

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/13d710b161bdf65a19f38f974c259bc4997a162c
