### ISSUE TITLE
NullPrice

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#131]
Just installed a fresh OCMS 446 with the Mall bundle.
I added a customer group and price. Now when I try to add the product to the cart...

development.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function where() on null in \public_html\plugins\offline\mall\classes\traits\NullPrice.php:27

My temp fix is to wrap the code on 27 with...
if (isset($related) && !empty($related)) {}

Any permanent fix for this?

Thank-you

**Comment by tobias-kuendig** [comment]
Thank you for the bug report. Could you provide me the full stack trace?

**Comment by dathwa** [comment]
Hi Tobias.

 

[2019-02-04 13:09:45] development.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function where() on null in C:\htdocs\uvukov.co.uk_mall\public_html\plugins\offline\mall\classes\traits\NullPrice.php:29

Stack trace:

#0 C:\htdocs\uvukov.co.uk_mall\public_html\plugins\offline\mall\classes\traits\PriceAccessors.php(49): OFFLINE\Mall\Models\Product->nullPrice(Object(OFFLINE\Mall\Models\Currency), NULL, 'prices', NULL)

#1 C:\htdocs\uvukov.co.uk_mall\public_html\plugins\offline\mall\classes\traits\PriceAccessors.php(62): OFFLINE\Mall\Models\Product->priceRelation(Object(OFFLINE\Mall\Models\Currency), 'prices', NULL)

#2 C:\htdocs\uvukov.co.uk_mall\public_html\plugins\offline\mall\classes\traits\CustomFields.php(27): OFFLINE\Mall\Models\Product->price(Object(OFFLINE\Mall\Models\Currency))

#3 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Support\Collection.php(928): OFFLINE\Mall\Models\Product->OFFLINE\Mall\Classes\Traits\{closure}(Object(OFFLINE\Mall\Models\Currency), 0)

#4 C:\htdocs\uvukov.co.uk_mall\public_html\plugins\offline\mall\classes\traits\CustomFields.php(28): Illuminate\Support\Collection->mapWithKeys(Object(Closure))

#5 C:\htdocs\uvukov.co.uk_mall\public_html\plugins\offline\mall\classes\traits\cart\CartActions.php(57): OFFLINE\Mall\Models\Product->priceIncludingCustomFieldValues(Object(October\Rain\Database\Collection))

#6 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Database\Concerns\ManagesTransactions.php(29): OFFLINE\Mall\Models\Cart->OFFLINE\Mall\Classes\Traits\Cart\{closure}(Object(October\Rain\Database\Connections\MySqlConnection))

#7 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(327): Illuminate\Database\Connection->transaction(Object(Closure))

#8 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(221): Illuminate\Database\DatabaseManager->__call('transaction', Array)

#9 C:\htdocs\uvukov.co.uk_mall\public_html\plugins\offline\mall\classes\traits\cart\CartActions.php(80): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)

#10 C:\htdocs\uvukov.co.uk_mall\public_html\plugins\offline\mall\components\Product.php(233): OFFLINE\Mall\Models\Cart->addProduct(Object(OFFLINE\Mall\Models\Product), 1, NULL, Object(October\Rain\Database\Collection))

#11 C:\htdocs\uvukov.co.uk_mall\public_html\modules\cms\classes\ComponentBase.php(187): OFFLINE\Mall\Components\Product->onAddToCart()

#12 C:\htdocs\uvukov.co.uk_mall\public_html\modules\cms\classes\Controller.php(873): Cms\Classes\ComponentBase->runAjaxHandler('onAddToCart')

#13 C:\htdocs\uvukov.co.uk_mall\public_html\modules\cms\classes\Controller.php(740): Cms\Classes\Controller->runAjaxHandler('onAddToCart')

#14 C:\htdocs\uvukov.co.uk_mall\public_html\modules\cms\classes\Controller.php(373): Cms\Classes\Controller->execAjaxHandlers()

#15 C:\htdocs\uvukov.co.uk_mall\public_html\modules\cms\classes\Controller.php(224): Cms\Classes\Controller->runPage(Object(Cms\Classes\Page))

#16 C:\htdocs\uvukov.co.uk_mall\public_html\modules\cms\classes\CmsController.php(50): Cms\Classes\Controller->run('product/how-to-...')

#17 [internal function]: Cms\Classes\CmsController->run('product/how-to-...')

#18 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): call_user_func_array(Array, Array)

#19 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)

#20 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Routing\Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Cms\Classes\CmsController), 'run')

#21 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Routing\Route.php(169): Illuminate\Routing\Route->runController()

#22 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Routing\Router.php(658): Illuminate\Routing\Route->run()

#23 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))

#24 C:\htdocs\uvukov.co.uk_mall\public_html\plugins\rainlab\translate\classes\LocaleMiddleware.php(29): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))

#25 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): RainLab\Translate\Classes\LocaleMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))

#26 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#27 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))

#28 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))

#29 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#30 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))

#31 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))

#32 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#33 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))

#34 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))

#35 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#36 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))

#37 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))

#38 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#39 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))

#40 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))

#41 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#42 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))

#43 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Routing\Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))

#44 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Routing\Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))

#45 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Routing\Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))

#46 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\october\rain\src\Router\CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))

#47 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))

#48 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))

#49 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))

#50 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))

#51 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))

#52 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))

#53 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))

#54 C:\htdocs\uvukov.co.uk_mall\public_html\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))

#55 C:\htdocs\uvukov.co.uk_mall\public_html\index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))

#56 {main}

**Comment by tobias-kuendig** [comment]
Thank you very much! This bug is fixed in v1.0.20.
