### ISSUE TITLE
Downloads (virtual products)

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#132]
I presume the "downloads" for a product are for virtual products, e.g. a PDF.
How does a customer access their downloads? In my customers order (frontend) I can see no links to a download. Shuld they get a link in the email?

**Comment by artistro08** [comment]
From what I gathered from studying the plugin, they will get an email to download. Also, If they are signed in as a guest, or if they have an account, they will be able to see it on their order page.

**Comment by tobias-kuendig** [comment]
Actually, there currently is no official support for virtual products.

The downloads field is meant to provide data sheets or manuals with a product for the user to download.

You could, however, get this feature working with a few tweaks. You'll have access to all downloads for a product via the `product.downloads` relationship. This can be used in the order mail or the order's list partials to display a download link.

The download link will not be protected. So users could share them. If protected links are needed you'd have to write some manual code.

I'll leave this issue open to track progress since virtual products are a highly demanded feature.

**Comment by dathwa** [comment]
I've tried a loop with product.downloads in the /components/orderslist/productlist.htm partial but it is empty. product.downloads|var_dump returns NULL. It seems like I would need to hack into the core component to render this in the partial. Any tips? Thanks

**Comment by tobias-kuendig** [comment]
Add this: https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/c592f987198f44984e8f451f1ece45db222fb8ec

Then use `{{ product.product.downloads }}` to access the original product's data.

A product is copied when it is added to an order to prevent it from being modified when the original product changes. 

You can use the `product` and `variant` relationships on the `CartProduct` model to access the original data.

This addition will be released in the next release so it's safe to manually patch your model for the time being.

**Comment by dathwa** [comment]
Your suggestion for `{{ product.product.downloads }}` works well in the cart. It won't work in the `plugins/offline/mall/components/orderslist/productlist.htm` partial unless, as you point out, I modify your code.
However, I have a workaround, using routes.php. 
In ther orders list. as long as i have the product ID I can create a link to a protected copy of the file, e.g. something like
`Route::get('/my_download/{id}', function ($id) {
    $download = new Vendor\Package\Components\Downloads;
    return $download->onDownload($id);
});`
For my needs I need to intercept a pdf and stamp it with the customer ID. Not tried it yet, but I think it's promising.
Looking forward to 1.1.0 (spring-time :) ???)- I presume the virtual product will have a more sophisticated protected approach than mine?
Thanks for taking the time to look at this.

**Comment by dathwa** [comment]
Ooops. Completely missed your patch: [c592f98](https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/c592f987198f44984e8f451f1ece45db222fb8ec).
Perfect. Thanks again.

**Comment by bozsokidaniel** [comment]
Hi guys! 

How I can get {{ product.product.downloads }} file path?

Thanks in advance!
Daniel

**Comment by tobias-kuendig** [comment]
Does `{{ product.product.downloads.first().path }}` work?

**Comment by bozsokidaniel** [comment]
Yes, it's working. Thank you for your help!

**Comment by tobias-kuendig** [comment]
This feature is now available in v1.7.0.

https://offline-gmbh.github.io/oc-mall-plugin/changelog/1.7.0.html

https://mall.offline.swiss/en/category/gift-cards

**Comment by PrestaSafe** [comment]
Looks like awesome ! Thanks for this great feature. Services is a really good idea !

**Comment by xyzqtc** [comment]
Do variant virtual products exist?
