### ISSUE TITLE
Color Picker Doesn't Allow Input on Hex field

### ISSUE THREAD

**Issue by artistro08** [OFFLINE-GmbH/oc-mall-plugin#134]
Basically, when you create a variant of a product that includes a color property, the field is disabled. you have to manually pick the color via the dragger.

**Comment by tobias-kuendig** [comment]
I can select the color directly from the swatches. But there is an input field that should not be visible. Can you confirm this is the same issue?

![image](https://user-images.githubusercontent.com/8600029/52287583-b6b38000-296a-11e9-86f2-5615e9ec8a76.png)

**Comment by tobias-kuendig** [comment]
I see what you meant. 

![image](https://user-images.githubusercontent.com/8600029/52287757-101baf00-296b-11e9-9f01-1c37c625f57e.png)


I believe this is October's default behaviour.

**Comment by artistro08** [comment]
Sorry, Could've explained that better. but that's what I meant

**Comment by artistro08** [comment]
Is there a workaround I can use?

**Comment by tobias-kuendig** [comment]
I'm honestly not able to find the issue. It's a default input field but it somehow is not clickable. I'll need to see if it happens outside of the mall plugin as well. It might be an October issue.

**Comment by tobias-kuendig** [comment]
See https://github.com/octobercms/october/issues/4117 for furhter updates.

**Comment by artistro08** [comment]
This is fixed per [#4199](https://github.com/octobercms/october/pull/4199)
