### ISSUE TITLE
Use JSON features of supported databases to store the product index

### ISSUE THREAD

**Issue by tobias-kuendig** [OFFLINE-GmbH/oc-mall-plugin#136]
MySQL 5.7+ and MariaDB 10.2+ are supported

**Comment by tobias-kuendig** [comment]
This is available via edge updates as v1.1.1.

**Comment by amdad** [comment]
Oh, now I understand. No longer need for data chunks in files? That's good, since db should have better performance.

**Comment by tobias-kuendig** [comment]
This feature is available in v1.1
