### ISSUE TITLE
Shipping method rates error

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#137]
Click on CREATE RATES.
Add your From, To and Price.
Click Create.

ErrorException: Trying to get property 'id' of non-object in C:\htdocs\aps.org.uk\public_html\plugins\offline\mall\controllers\ShippingMethods.php:88

If I refresh the page, the new rate IS there, but the price is missing, so I need to edit and update again.

**Comment by tobias-kuendig** [comment]
Thank you very much for your bug report! This has been fixed in 29aed27 and will be released later this week with the v1.1 update.
