### ISSUE TITLE
Subcategories in ul list

### ISSUE THREAD

**Issue by HomaEEE** [OFFLINE-GmbH/oc-mall-plugin#140]
how I can display subcategories in dropdown list?
in menu have only display from one category

**Comment by tobias-kuendig** [comment]
This is actually a bug! Thank you for the report, it has been fixed in v1.1.6.

**Comment by tobias-kuendig** [comment]
Also make sure to run `php artisan cache:clear` after the update since the category tree is cached.

**Comment by HomaEEE** [comment]
unfortunately after clear cache show only parent categories

**Comment by tobias-kuendig** [comment]
Did you update to the latest version?

**Comment by HomaEEE** [comment]
I'm sorry - my mistake. After update - show as done
I will also later do a push with updating the Russian language. Thank you for this plugin

**Comment by tobias-kuendig** [comment]
Alright, no worries! Thank you for the feedback and the bug report!
