### ISSUE TITLE
Product taxes aren't filtered by shipping country

### ISSUE THREAD

**Issue by tobias-kuendig** [OFFLINE-GmbH/oc-mall-plugin#141]
> Problem remains that if I have taxes for different countries, 1 for UK, 1 for USA etc, then *all* the taxes get applied to the product.  There is no check for shipping address, like there is for shipping charge.

@timconsidine via https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/139#issuecomment-465305747

**Comment by tobias-kuendig** [comment]
@timconsidine thank you for this bug report. This issue has been fixed in v1.1.7

**Comment by alxy** [comment]
General legal question: Do taxes apply based on the billing or shipping address?

**Comment by tobias-kuendig** [comment]
With some exceptions it's based on the shipping address:
https://blog.taxjar.com/use-billing-address-shipping-address-calculating-sales-tax/

**Comment by timconsidine** [comment]
Hi

Yes, generally it is based on the shipping address.
I am  based in the UK and we should charge :
- UK VAT if goods are shipped to UK address even if buyer is in another country
- the relevant VAT for a EU country if shipped to  an EU country (rate can vary according to which country)
- zero VAT if an export to “Rest of World” country

I will look at the change you made in 1.1.7

Thank you for your help and clarifications

And also thank you for a really great plugin - it seems to me much better than the Shopaholic

Best wishes



Tim

**Comment by timconsidine** [comment]
Thank you for this fix.
It works now as I would expect, and allows products to have multiple tax rates, one of which is selected according to which tax rate has been allocated for which country.
This is a really great addition - thank you so much.
