### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by jonnydevv** [OFFLINE-GmbH/oc-mall-plugin#142]
Hello,

I'm getting a problem installing plugin.
Running **PHP Version 7.1.26-1** and October build 446:

> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'scotchbox.offline_mall_price_categories' doesn't exist (SQL: select count(*) as aggregate from `offline_mall_price_categories` where `code  
>   ` = old_price)

> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'scotchbox.offline_mall_price_categories' doesn't exist

> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'scotchbox.offline_mall_price_categories' doesn't exist

Can't see any offline_mall tables created.

**Comment by tobias-kuendig** [comment]
How did you install the plugin? Simply run `php artisan plugin:refresh offline.mall` to re-run the setup routines.

**Comment by jonnydevv** [comment]
I've been installing all plugin via command-line.
php artisan plugin:refresh offline.mall was giving me same error. I've uninstalled Rainlab.User and Rainlab.Location. Then run composer update, and installed all RainLab.User, RainLab.Location and Offline.Mall at the end.
I guess the problem was composer update that was missing. Seems like problem had been solved.
