### ISSUE TITLE
Best way to add code after checkout success 

### ISSUE THREAD

**Issue by timconsidine** [OFFLINE-GmbH/oc-mall-plugin#145]
I need to add some code after checkout succeeds (could be for various reasons but in this case to generate a personal url to download a purchased mp3)

I'm reluctant to hack any of the plugin component files, so that future updates can be installed without having to merge changes.

What would be the recommended way to add post-checkout custom code ?

**Comment by tobias-kuendig** [comment]
Create a plugin `Timconsidine.MallExtensions` and add your code in that plugin's `Plugin.php`. Use the event system as described in https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/108#issuecomment-466663751

**Comment by timconsidine** [comment]
That's great - thank you
