### ISSUE TITLE
Quickview for Products

### ISSUE THREAD

**Issue by artistro08** [OFFLINE-GmbH/oc-mall-plugin#146]
I've been trying to create a quickview with products by using a different product page. How would I go about doing that. So Far, I used a different page for quickview products (with a different layout and used this code:

```
{{ quick_view|page({slug: item.slug, variant: item.variantId}) }}
```

am I going the right way about this?

**Comment by artistro08** [comment]
nevermind, forgot the `' '` surrounding the pages

**Comment by StanleyBonhomme** [comment]
@artistro08 How did you achieve this? I'm interested in adding a quick view modal.

**Comment by artistro08** [comment]
I honestly can't remember since it's been so long. I currently don't use this method anymore either. If you were to do a quick view, I would just pull the data from the table using twig and have a pop up in a model via JavaScript
