### ISSUE TITLE
Item with different sizes

### ISSUE THREAD

**Issue by jonnydevv** [OFFLINE-GmbH/oc-mall-plugin#147]
Hello,

I should be missing something in documentation.
I'm trying to create a product with different sizes.
<img width="1291" alt="screenshot 2019-02-26 at 11 29 47" src="https://user-images.githubusercontent.com/2188826/53412912-3ce74300-39ba-11e9-936f-6dc55f30210e.png">
When using variants this way, it shows me multiple products instead of showing dropdown with different sizes.

**Comment by tobias-kuendig** [comment]
If you want to only show the base product set `includeVariants = 0`, is this what you mean?

https://offline-gmbh.github.io/oc-mall-plugin/components/products.html#includevariants-bool

**Comment by jonnydevv** [comment]
No, that's not what I meant. In store frontend, in product page, I want to show a dropdown to select the product size. How can i accomplish this? In backend, inside properties page I can only select one size:
<img width="1316" alt="screenshot 2019-02-26 at 12 12 47" src="https://user-images.githubusercontent.com/2188826/53415101-d9601400-39bf-11e9-8f50-95480d207beb.png">

**Comment by tobias-kuendig** [comment]
Make sure to set `Attribute for variant grouping` to `None`. If you set this to `Size` all the sizes will be split up into separate product pages on the frontend. Set it to `None` and all Variants will be displayed on the same page.

The screenshot in your first comment looked right, the seconds screenshot looks configured wrong. 

Here are the steps to configure everything for a fresh install:

Go to `Catalogue -> Properties -> Size` and make sure the `Use for Variants` option is enabled.

Create a Product and set the `Inventory Management method` to `Article variants`. Now you can create a Variant for each size.

Also see our demo for a example setup: https://mall.offline.swiss/backend/offline/mall/products/update/6

**Comment by jonnydevv** [comment]
Now i was able to set it with your instructions. Thanks for the indications.
