### ISSUE TITLE
Category filters do not work

### ISSUE THREAD

**Issue by dariodread** [OFFLINE-GmbH/oc-mall-plugin#148]
clean installation, category filters do not work

**Comment by artistro08** [comment]
What's your Code? Did you use the mall starter theme?

**Comment by tobias-kuendig** [comment]
@dariodread 	Please provide more information otherwise it's impossibl eto help you. What's your setup? What doesn't work? Any errors?

**Comment by dariodread** [comment]
problem was nginx configuration. With Apache it works!
