### ISSUE TITLE
Properties reordering is broken

### ISSUE THREAD

**Issue by tobias-kuendig** [OFFLINE-GmbH/oc-mall-plugin#15]
> The model must implement the NestedTree or Sortable traits.

**Comment by tobias-kuendig** [comment]
Issue cannot be reproduced. Might have been fixed in the meantime.

**Comment by amdad** [comment]
https://mall.offline.swiss/backend/offline/mall/propertygroups
https://mall.offline.swiss/backend/offline/mall/propertygroups/reorder
