### ISSUE TITLE
Adding a shipping coupon for a variable product doesn't work

### ISSUE THREAD

**Issue by artistro08** [OFFLINE-GmbH/oc-mall-plugin#151]
As the title says, if you create a coupon for using the 'shipping method' method for a variable product, the shipping method doesn't show up in the cart.

**Comment by artistro08** [comment]
I did test this on https://mall.offline.swiss

**Comment by tobias-kuendig** [comment]
Thank you! This is fixed in 0a515cd. The product seleciton dropdown was indexed wrong.

**Comment by artistro08** [comment]
Awesomenss. Thank you!
