### ISSUE TITLE
after instalation parse error

### ISSUE THREAD

**Issue by SpurnyMarek** [OFFLINE-GmbH/oc-mall-plugin#156]
Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)
![image](https://user-images.githubusercontent.com/43445347/53842442-c6d97200-3f9f-11e9-9fad-61281fed0166.png)

**Comment by Eoler** [comment]
PHP7.1+ is required...

**Comment by tobias-kuendig** [comment]
See Eoler's comment and https://offline-gmbh.github.io/oc-mall-plugin/#requirements
