### ISSUE TITLE
Rewrite product name if product uses Additional properties

### ISSUE THREAD

**Issue by romanseki** [OFFLINE-GmbH/oc-mall-plugin#159]
I have product with product variants an If I add Addditional properties product name is rewrited by last of Additional property name

**Comment by tobias-kuendig** [comment]
Thanks for your bug report! I'll see if I can re-produce the issue.

**Comment by papppeter** [comment]
same happening to me.

steps:
create a product
add Additional properties
save

last one name will overwrite product name.

**Comment by tobias-kuendig** [comment]
I'm currently unable to reproduce this issue. What do you mean by `add additional properties`? Are you creating a new Variant? Are you adding new properties to a category?

**Comment by romanseki** [comment]
> I'm currently unable to reproduce this issue. What do you mean by `add additional properties`? Are you creating a new Variant? Are you adding new properties to a category?

Under product tab "Details" is "Additional properties" repeater

**Comment by tobias-kuendig** [comment]
Now I've got it, thank you for the quick response! :+1:

**Comment by tobias-kuendig** [comment]
This problem is related to RainLab.Translate. See https://github.com/rainlab/translate-plugin/issues/459 for further updates.

**Comment by tobias-kuendig** [comment]
This problem was solved upstream. Once the new October Builds are available this problem will be fixed with the mall plugin as well.

Thank you for the bug report, @romanseki and @papppeter!

https://github.com/rainlab/translate-plugin/issues/459
