### ISSUE TITLE
[Enhancement] Product upload from excel (xlsx or csv file)

### ISSUE THREAD

**Issue by bozsokidaniel** [OFFLINE-GmbH/oc-mall-plugin#169]

**Comment by bozsokidaniel** [comment]
Hi guys!

First, thank you for this great plugin! 👍 

What do you think about uploading products from excel table like xlsx or csv file? It would be much easier to upload multiple products.

**Comment by tobias-kuendig** [comment]
Hi @bozsokidaniel 

Thank you for your input. I'm closing this issue as a duplicate of https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/98

See #98 for further infos.
