### ISSUE TITLE
sort = manual?

### ISSUE THREAD

**Issue by Apoculos** [OFFLINE-GmbH/oc-mall-plugin#173]
Hi I'm not sure if this is an issue.. or me overlooking where to manually order products. I need to be able to manually order products and it seems its already built in somehow? The documentation doesn't really go into detail. Thanks!

**Comment by tobias-kuendig** [comment]
You can sort products in the `Products` tab on the edit category page:

https://mall.offline.swiss/backend/offline/mall/categories/update/2

I'll update the docs, thanks!

**Comment by Apoculos** [comment]
Thanks tobias! This did in fact work for products under a single category. 

I can not get the manual sort to work when a category has sub categories (and both subs have products). The reorder products option is available under the main category.. but doesn't seem to have an effect.

**Comment by tobias-kuendig** [comment]
This is unexpected behaviour. Nested products should be sortable as well. I'll look into this, thank you for the feedback :+1:

**Comment by tobias-kuendig** [comment]
Probably fixed by e8829f006a7bac9495c73a9dbe2b50e8182c194c
