### ISSUE TITLE
product category id reference

### ISSUE THREAD

**Issue by ajsaces** [OFFLINE-GmbH/oc-mall-plugin#174]
Hi,
on the product overview page I was previously checking the products category using 
{% if item.category_id == 8 %}
then doing some dynamic fetching.

Has this referencing changed since update?

**Comment by tobias-kuendig** [comment]
Yes, an item can now have multiple categories (it's been like this for a couple of versions now).

You'll have to rewrite this check to

```twig
{% if item.categories.pluck('id').contains(8) %}
``` 

Let me know if you need further assistance.

**Comment by ajsaces** [comment]
that's what I needed thanks.
