### ISSUE TITLE
color customfield input data is not added to the cart

### ISSUE THREAD

**Issue by ajsaces** [OFFLINE-GmbH/oc-mall-plugin#175]
I have verified this on your offline demo mall as well.

If I add a cart color customfield to a product line when you build the cart on the frontend this color field does not get passed to addcart and hangs on the field

Example online now not sure when you refresh the data though.
https://mall.offline.swiss/en/product/stormrider-jersey/3AqLOdWK

![image](https://user-images.githubusercontent.com/46471237/55552391-f27b8380-5728-11e9-9175-6a50f0181bf0.png)

![image](https://user-images.githubusercontent.com/46471237/55552610-8d745d80-5729-11e9-9f6d-7a96116a3ed1.png)

**Comment by ajsaces** [comment]
any help/advice?

**Comment by tobias-kuendig** [comment]
Thank you for this report, the bug has been fixed in 1.2.2.

Please report back if you experience any further problems!
