### ISSUE TITLE
where is route.php file is located?

### ISSUE THREAD

**Issue by alitaleghani** [OFFLINE-GmbH/oc-mall-plugin#176]
I'm looking to change or add some features. however i can't find **routes** which plugin is using.
where the routes are located?
thanks

**Comment by tobias-kuendig** [comment]
October plugins do not provide a routes file per default. All routes this plugin uses are controlled via the cms pages.

https://offline-gmbh.github.io/oc-mall-plugin/getting-started/theme-setup.html#pages

What exactly do you need to know?

**Comment by alitaleghani** [comment]
Thanks so much for reply. 
I want add a bidding feature to plugin. 
How could I add it without getting conflicting with orginal plugin files and not losing future updates?

**Comment by tobias-kuendig** [comment]
It's hard to tell without more details. I suggest you read https://octobercms.com/docs/plugin/extending 

You can create your own plugin that extends the models and components of oc-mall. This should already bring you a long way.
