### ISSUE TITLE
Page errors

### ISSUE THREAD

**Issue by exaline-ru** [OFFLINE-GmbH/oc-mall-plugin#179]
After installation and configuration as in the instructions, errors appear on the pages: Product and Category:

![5srlfjtLd9](https://user-images.githubusercontent.com/46493161/55911623-ada09280-5be9-11e9-9e9f-2005ec1cb09d.png)
![4HMPhRuXab](https://user-images.githubusercontent.com/46493161/55911624-ada09280-5be9-11e9-9f52-90d872adc7d6.png)

The remaining pages work.

**Comment by tobias-kuendig** [comment]
Thank you for this report. Could you post the whole stack trace of the error message, please?

**Comment by exaline-ru** [comment]
Pruduct page error:

`

154155156157158159160161162163164165166 | if ($this->initialized) {            throw new LogicException(sprintf('Unable to register extension "%s" as extensions have already been initialized.', $class));        }          if (isset($this->extensions[$class])) {            throw new LogicException(sprintf('Unable to register extension "%s" as it is already registered.', $class));        }          // For BC/FC with namespaced aliases        $class = (new ReflectionClass($class))->name;        $this->extensions[$class] = $extension;    }
-- | --


# | Called Code | Document | Line
-- | -- | -- | --
65 | Twig_ExtensionSet->addExtension(…) | ~/vendor/twig/twig/lib/Twig/Environment.php | 672
64 | Twig_Environment->addExtension(…) | ~/plugins/jorgeandrade/events/Plugin.php | 22
63 | JorgeAndrade\Events\Plugin->JorgeAndrade\Events\{closure}(…) |   |  
62 | call_user_func_array(…) | ~/vendor/october/rain/src/Events/Dispatcher.php | 233
61 | October\Rain\Events\Dispatcher->dispatch(…) | ~/vendor/october/rain/src/Events/Dispatcher.php | 197
60 | October\Rain\Events\Dispatcher->fire(…) | ~/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php | 221
59 | Illuminate\Support\Facades\Facade::__callStatic(…) | ~/modules/system/traits/EventEmitter.php | 58
58 | Cms\Classes\Controller->fireSystemEvent(…) | ~/modules/cms/classes/Controller.php | 194
57 | Cms\Classes\Controller->run(…) | ~/plugins/offline/mall/components/Product.php | 153
56 | OFFLINE\Mall\Components\Product->onRun() | ~/modules/cms/classes/CmsCompoundObject.php | 172
55 | Cms\Classes\CmsCompoundObject->runComponents() | ~/modules/cms/classes/Controller.php | 500
54 | Cms\Classes\Controller->execPageCycle() | ~/modules/cms/classes/Controller.php | 393
53 | Cms\Classes\Controller->runPage(…) | ~/modules/cms/classes/Controller.php | 224
52 | Cms\Classes\Controller->run(…) | ~/modules/cms/classes/CmsController.php | 50
51 | Cms\Classes\CmsController->run(…) |   |  
50 | call_user_func_array(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Controller.php | 54
49 | Illuminate\Routing\Controller->callAction(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php | 45
48 | Illuminate\Routing\ControllerDispatcher->dispatch(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Route.php | 212
47 | Illuminate\Routing\Route->runController() | ~/vendor/laravel/framework/src/Illuminate/Routing/Route.php | 169
46 | Illuminate\Routing\Route->run() | ~/vendor/laravel/framework/src/Illuminate/Routing/Router.php | 658
45 | Illuminate\Routing\Router->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 30
44 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/plugins/rainlab/translate/classes/LocaleMiddleware.php | 29
43 | RainLab\Translate\Classes\LocaleMiddleware->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
42 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
41 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php | 41
40 | Illuminate\Routing\Middleware\SubstituteBindings->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
39 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
38 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php | 49
37 | Illuminate\View\Middleware\ShareErrorsFromSession->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
36 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
35 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php | 63
34 | Illuminate\Session\Middleware\StartSession->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
33 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
32 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php | 37
31 | Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
30 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
29 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php | 66
28 | Illuminate\Cookie\Middleware\EncryptCookies->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
27 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
26 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 102
25 | Illuminate\Pipeline\Pipeline->then(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Router.php | 660
24 | Illuminate\Routing\Router->runRouteWithinStack(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Router.php | 635
23 | Illuminate\Routing\Router->runRoute(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Router.php | 601
22 | Illuminate\Routing\Router->dispatchToRoute(…) | ~/vendor/october/rain/src/Router/CoreRouter.php | 20
21 | October\Rain\Router\CoreRouter->dispatch(…) | ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php | 176
20 | Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 30
19 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/plugins/offline/speedy/classes/middleware/CDNMiddleware.php | 40
18 | OFFLINE\Speedy\Classes\Middleware\CDNMiddleware->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
17 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
16 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/plugins/offline/speedy/classes/middleware/Http2Middleware.php | 38
15 | OFFLINE\Speedy\Classes\Middleware\Http2Middleware->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
14 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
13 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/plugins/offline/responsiveimages/classes/ResponsiveImagesMiddleware.php | 30
12 | OFFLINE\ResponsiveImages\Classes\ResponsiveImagesMiddleware->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
11 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
10 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php | 46
9 | Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
8 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
7 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/plugins/vdlp/redirect/classes/RedirectMiddleware.php | 63
6 | Vdlp\Redirect\Classes\RedirectMiddleware->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
5 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
4 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 102
3 | Illuminate\Pipeline\Pipeline->then(…) | ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php | 151
2 | Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(…) | ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php | 116
1 | Illuminate\Foundation\Http\Kernel->handle(…) | ~/index.php | 43

`

**Comment by exaline-ru** [comment]
Category page error:

`

# | Called Code | Document | Line
-- | -- | -- | --
64 | Illuminate\Database\Eloquent\Builder->findOrFail(…) | ~/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php | 1477
63 | Illuminate\Database\Eloquent\Model->__call(…) | ~/vendor/october/rain/src/Extension/ExtendableTrait.php | 423
62 | October\Rain\Database\Model->extendableCall(…) | ~/vendor/october/rain/src/Database/Model.php | 635
61 | October\Rain\Database\Model->__call(…) | ~/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php | 1489
60 | Illuminate\Database\Eloquent\Model::__callStatic(…) | ~/plugins/offline/mall/classes/traits/category/Slug.php | 70
59 | OFFLINE\Mall\Models\Category::bySlugOrId(…) | ~/plugins/offline/mall/components/ProductsFilter.php | 452
58 | OFFLINE\Mall\Components\ProductsFilter->getCategory() | ~/plugins/offline/mall/components/ProductsFilter.php | 268
57 | OFFLINE\Mall\Components\ProductsFilter->setData() | ~/plugins/offline/mall/components/ProductsFilter.php | 300
56 | OFFLINE\Mall\Components\ProductsFilter->onRun() | ~/modules/cms/classes/CmsCompoundObject.php | 172
55 | Cms\Classes\CmsCompoundObject->runComponents() | ~/modules/cms/classes/Controller.php | 500
54 | Cms\Classes\Controller->execPageCycle() | ~/modules/cms/classes/Controller.php | 393
53 | Cms\Classes\Controller->runPage(…) | ~/modules/cms/classes/Controller.php | 224
52 | Cms\Classes\Controller->run(…) | ~/modules/cms/classes/CmsController.php | 50
51 | Cms\Classes\CmsController->run(…) |   |  
50 | call_user_func_array(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Controller.php | 54
49 | Illuminate\Routing\Controller->callAction(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php | 45
48 | Illuminate\Routing\ControllerDispatcher->dispatch(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Route.php | 212
47 | Illuminate\Routing\Route->runController() | ~/vendor/laravel/framework/src/Illuminate/Routing/Route.php | 169
46 | Illuminate\Routing\Route->run() | ~/vendor/laravel/framework/src/Illuminate/Routing/Router.php | 658
45 | Illuminate\Routing\Router->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 30
44 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/plugins/rainlab/translate/classes/LocaleMiddleware.php | 29
43 | RainLab\Translate\Classes\LocaleMiddleware->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
42 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
41 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php | 41
40 | Illuminate\Routing\Middleware\SubstituteBindings->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
39 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
38 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php | 49
37 | Illuminate\View\Middleware\ShareErrorsFromSession->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
36 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
35 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php | 63
34 | Illuminate\Session\Middleware\StartSession->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
33 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
32 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php | 37
31 | Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
30 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
29 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php | 66
28 | Illuminate\Cookie\Middleware\EncryptCookies->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
27 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
26 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 102
25 | Illuminate\Pipeline\Pipeline->then(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Router.php | 660
24 | Illuminate\Routing\Router->runRouteWithinStack(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Router.php | 635
23 | Illuminate\Routing\Router->runRoute(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Router.php | 601
22 | Illuminate\Routing\Router->dispatchToRoute(…) | ~/vendor/october/rain/src/Router/CoreRouter.php | 20
21 | October\Rain\Router\CoreRouter->dispatch(…) | ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php | 176
20 | Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 30
19 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/plugins/offline/speedy/classes/middleware/CDNMiddleware.php | 40
18 | OFFLINE\Speedy\Classes\Middleware\CDNMiddleware->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
17 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
16 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/plugins/offline/speedy/classes/middleware/Http2Middleware.php | 38
15 | OFFLINE\Speedy\Classes\Middleware\Http2Middleware->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
14 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
13 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/plugins/offline/responsiveimages/classes/ResponsiveImagesMiddleware.php | 30
12 | OFFLINE\ResponsiveImages\Classes\ResponsiveImagesMiddleware->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
11 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
10 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php | 46
9 | Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
8 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
7 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/plugins/vdlp/redirect/classes/RedirectMiddleware.php | 63
6 | Vdlp\Redirect\Classes\RedirectMiddleware->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
5 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
4 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 102
3 | Illuminate\Pipeline\Pipeline->then(…) | ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php | 151
2 | Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(…) | ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php | 116
1 | Illuminate\Foundation\Http\Kernel->handle(…) | ~/index.php | 43


`

**Comment by tobias-kuendig** [comment]
Did you enter any data yet? Both errors indicate that your store is completely empty.

Try to run `php artisan mall:seed` to get some demo data.

**Comment by tobias-kuendig** [comment]
The product page error actually comes from `jorgeandrade/events/Plugin.php` line 22 and has nothing to do with the mall plugin.

**Comment by exaline-ru** [comment]
Disable jorgeandrade/events/Plugin.php + run php artisan mall:seed to get some demo data. Category page error:

`

# | Called Code | Document | Line
-- | -- | -- | --
64 | Illuminate\Database\Eloquent\Builder->findOrFail(…) | ~/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php | 1477
63 | Illuminate\Database\Eloquent\Model->__call(…) | ~/vendor/october/rain/src/Extension/ExtendableTrait.php | 423
62 | October\Rain\Database\Model->extendableCall(…) | ~/vendor/october/rain/src/Database/Model.php | 635
61 | October\Rain\Database\Model->__call(…) | ~/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php | 1489
60 | Illuminate\Database\Eloquent\Model::__callStatic(…) | ~/plugins/offline/mall/classes/traits/category/Slug.php | 70
59 | OFFLINE\Mall\Models\Category::bySlugOrId(…) | ~/plugins/offline/mall/components/ProductsFilter.php | 452
58 | OFFLINE\Mall\Components\ProductsFilter->getCategory() | ~/plugins/offline/mall/components/ProductsFilter.php | 268
57 | OFFLINE\Mall\Components\ProductsFilter->setData() | ~/plugins/offline/mall/components/ProductsFilter.php | 300
56 | OFFLINE\Mall\Components\ProductsFilter->onRun() | ~/modules/cms/classes/CmsCompoundObject.php | 172
55 | Cms\Classes\CmsCompoundObject->runComponents() | ~/modules/cms/classes/Controller.php | 500
54 | Cms\Classes\Controller->execPageCycle() | ~/modules/cms/classes/Controller.php | 393
53 | Cms\Classes\Controller->runPage(…) | ~/modules/cms/classes/Controller.php | 224
52 | Cms\Classes\Controller->run(…) | ~/modules/cms/classes/CmsController.php | 50
51 | Cms\Classes\CmsController->run(…) |   |  
50 | call_user_func_array(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Controller.php | 54
49 | Illuminate\Routing\Controller->callAction(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php | 45
48 | Illuminate\Routing\ControllerDispatcher->dispatch(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Route.php | 212
47 | Illuminate\Routing\Route->runController() | ~/vendor/laravel/framework/src/Illuminate/Routing/Route.php | 169
46 | Illuminate\Routing\Route->run() | ~/vendor/laravel/framework/src/Illuminate/Routing/Router.php | 658
45 | Illuminate\Routing\Router->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 30
44 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/plugins/rainlab/translate/classes/LocaleMiddleware.php | 29
43 | RainLab\Translate\Classes\LocaleMiddleware->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
42 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
41 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php | 41
40 | Illuminate\Routing\Middleware\SubstituteBindings->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
39 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
38 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php | 49
37 | Illuminate\View\Middleware\ShareErrorsFromSession->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
36 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
35 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php | 63
34 | Illuminate\Session\Middleware\StartSession->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
33 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
32 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php | 37
31 | Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
30 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
29 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php | 66
28 | Illuminate\Cookie\Middleware\EncryptCookies->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
27 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
26 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 102
25 | Illuminate\Pipeline\Pipeline->then(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Router.php | 660
24 | Illuminate\Routing\Router->runRouteWithinStack(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Router.php | 635
23 | Illuminate\Routing\Router->runRoute(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Router.php | 601
22 | Illuminate\Routing\Router->dispatchToRoute(…) | ~/vendor/october/rain/src/Router/CoreRouter.php | 20
21 | October\Rain\Router\CoreRouter->dispatch(…) | ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php | 176
20 | Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 30
19 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/plugins/offline/speedy/classes/middleware/CDNMiddleware.php | 40
18 | OFFLINE\Speedy\Classes\Middleware\CDNMiddleware->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
17 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
16 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/plugins/offline/speedy/classes/middleware/Http2Middleware.php | 38
15 | OFFLINE\Speedy\Classes\Middleware\Http2Middleware->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
14 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
13 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/plugins/offline/responsiveimages/classes/ResponsiveImagesMiddleware.php | 30
12 | OFFLINE\ResponsiveImages\Classes\ResponsiveImagesMiddleware->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
11 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
10 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php | 46
9 | Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
8 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
7 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/plugins/vdlp/redirect/classes/RedirectMiddleware.php | 63
6 | Vdlp\Redirect\Classes\RedirectMiddleware->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
5 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
4 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 102
3 | Illuminate\Pipeline\Pipeline->then(…) | ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php | 151
2 | Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(…) | ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php | 116
1 | Illuminate\Foundation\Http\Kernel->handle(…) | ~/index.php | 43

`

**Comment by tobias-kuendig** [comment]
How did you set up your category page? Are you passing the `:slug` along to the component?

https://offline-gmbh.github.io/oc-mall-plugin/getting-started/theme-setup.html#pages

Please post the content of your category cms page.

**Comment by exaline-ru** [comment]
![hTE35TZcr4](https://user-images.githubusercontent.com/46493161/55948005-479f2400-5c58-11e9-9b67-b34971f78352.png)
![LueslfHBR8](https://user-images.githubusercontent.com/46493161/55948007-4837ba80-5c58-11e9-9cd8-7edfd5146f5b.png)
![ZYlahF5A33](https://user-images.githubusercontent.com/46493161/55948008-4837ba80-5c58-11e9-8412-70ea2d6c7098.png)

**Comment by tobias-kuendig** [comment]
And are you visiting `/booking/category/bikes`?

**Comment by exaline-ru** [comment]
The same error on the visit /booking/category/bikes. All categories and products in order:
![1p4XA1WNQ5](https://user-images.githubusercontent.com/46493161/55949057-70c0b400-5c5a-11e9-962e-6b81a328140d.png)
![OKdPQ1TKtI](https://user-images.githubusercontent.com/46493161/55949062-74543b00-5c5a-11e9-8c37-bb3a764daec8.png)

**Comment by tobias-kuendig** [comment]
Try to debug the error from this line on backwards:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/ProductsFilter.php#L452

First of all check if `$this->param('slug')` and `$this->property('category')` contain the values you expect.

**Comment by tobias-kuendig** [comment]
Were you able to debug this issue any further?

Thank you for your feedback!

**Comment by exaline-ru** [comment]
It does not work yet. All the same mistake.

**Comment by exaline-ru** [comment]
Everything worked out! Made ported settings from the offline-oc-mall-theme template. Thank you for your help!

**Comment by tobias-kuendig** [comment]
Great! Feel free to reply if you need any further assistance.
