### ISSUE TITLE
possibility to overwrite short description on variant update page

### ISSUE THREAD

**Issue by papppeter** [OFFLINE-GmbH/oc-mall-plugin#184]
it would be nice, if i could update short description, or even description on variant page.

name would be nice if it would be not required, if we have at least one required property.

**Comment by papppeter** [comment]
Hi,

if you accept this feature request, i will try to write the code for it. what do you think?

**Comment by tobias-kuendig** [comment]
Yes, why not. This should be possible by adding a new column to the variants and a new field to the variant form.

**Comment by tobias-kuendig** [comment]
Have you already started with this? I'm currently making changes to the variants and could implement it in one go.

**Comment by papppeter** [comment]
Hi, I planed it for the weekend. It would be nice if you do it!

Tobias Kündig <notifications@github.com> ezt írta (időpont: 2019. máj. 3.,
P 14:05):

**Comment by papppeter** [comment]
Hi,

did you had a time to do it?

**Comment by tobias-kuendig** [comment]
Yes, it's available on the [merchant branch](https://github.com/OFFLINE-GmbH/oc-mall-plugin/commits/merchant). This is currently a work in progress. I'll try to merge this today.

**Comment by tobias-kuendig** [comment]
This is now available in `v1.3.0`. Currently only via edge updates.
