### ISSUE TITLE
Documentation review

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#185]
in the theme setup doc, inside the section pages, the address.htm is showing the wrong content example.

**Comment by tobias-kuendig** [comment]
Good catch, thank you! Fixed in ac09ca9

**Comment by chrisvidal** [comment]
I might be the only one still reading the doc haha
thanks for your awesome plugin and way of coding it, inspiring!

**Comment by chrisvidal** [comment]
How can I use and see the docs provided with the plugin after install on my localhost please?

**Comment by tobias-kuendig** [comment]
See https://github.com/OFFLINE-GmbH/oc-mall-plugin#documentation-1

```
npm i -g vuepress
cd docs
vuepress dev
```

**Comment by chrisvidal** [comment]
great, thanks

apparently, the plugin is also depending on Static Page and Translation plugins. I didnt see it in the doc.

**Comment by tobias-kuendig** [comment]
The plugin isn't but the demo theme is, I will update the docs to make this more apparent :+1:

**Comment by tobias-kuendig** [comment]
This was added in 8d80a2e, thanks again! :ok_hand:
