### ISSUE TITLE
Feature Request: Product Review/Ratings System

### ISSUE THREAD

**Issue by ajsaces** [OFFLINE-GmbH/oc-mall-plugin#186]
Just wondering if there is any short term plan for releasing a per product Client review functionality? People would pay for it as a separate addon like other carts I am sure.

**Comment by tobias-kuendig** [comment]
Yes, this will be the next big addition to the plugin. I cannot tell you a release date yet, though since I currently don't have too much time to work on this plugin. I'm mostly busy fixing bugs and making minor improvements.

**Comment by danielbidala** [comment]
A big +1 for this request. It's very important feature for an online store.

**Comment by tobias-kuendig** [comment]
This feature is now available via edge upates:
https://offline-gmbh.github.io/oc-mall-plugin/changelog/1.6.0.html

**Comment by damsfx** [comment]
As it stands, I can post any comments without moderation from the administrators and anonymously.  

I think this possibility should only be left to users who are authenticate on the site and have purchased the product at least once.

**Comment by tobias-kuendig** [comment]
Thanks for testing, there are a few settings for reviews:
https://offline-gmbh.github.io/oc-mall-plugin/digging-deeper/reviews.html#settings

**Comment by damsfx** [comment]
Damned ... you rock's !

**Comment by damsfx** [comment]
An outstanding question anyway...

It is possible to comment on an article that you have not bought!  
I have looked at the demo site but I think the reviews settings are not available for testing.

**Comment by tobias-kuendig** [comment]
Yes, this feature was left for a future update to the review system. I am tracking progress for this here: https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/328

This feature currently has low priority for us but it could be easily implemented by someone in the community.

I'm closing this issue since the Review feature is generally available since yesterday. 

Thanks for your feedback, @damsfx!
