### ISSUE TITLE
Bad price if product uses variants and custom fields with price

### ISSUE THREAD

**Issue by romanseki** [OFFLINE-GmbH/oc-mall-plugin#188]
If product have variants and custom field (in my case checkbox). Price from custom field count on cheapest variant not for currently selected

<img width="288" alt="Screenshot 2019-04-18 at 23 45 58" src="https://user-images.githubusercontent.com/4614305/56394918-0b138f80-6239-11e9-8f8b-75fd1042c991.png">
<img width="360" alt="Screenshot 2019-04-18 at 23 45 42" src="https://user-images.githubusercontent.com/4614305/56394919-0b138f80-6239-11e9-8a50-2379ac9ad4ac.png">
<img width="349" alt="Screenshot 2019-04-18 at 23 45 29" src="https://user-images.githubusercontent.com/4614305/56394920-0b138f80-6239-11e9-9cf9-d89300b06ec6.png">
<img width="338" alt="Screenshot 2019-04-18 at 23 45 20" src="https://user-images.githubusercontent.com/4614305/56394921-0b138f80-6239-11e9-8f94-7e4f1839d962.png">

**Comment by tobias-kuendig** [comment]
Thank you for this bug report! This issue has been fixed in 778fc99. 

The calculated price when the product was added to the cart was correct, it wasn't displayed correctly in the product component though.
