### ISSUE TITLE
Error when downloading image to product

### ISSUE THREAD

**Issue by skobb** [OFFLINE-GmbH/oc-mall-plugin#189]
Have this problem:
![image](https://user-images.githubusercontent.com/46927994/56423983-0db4ca00-62b7-11e9-8c2c-27adbdd56372.png)
Its only when I'm updating the image, first dowload going without any problems
If I push button"update" after this message, I get 4(four!) copies of my image ;)

**Comment by tobias-kuendig** [comment]
I'll need some more information. Can you post the whole stack trace from your `system.log`?

**Comment by skobb** [comment]
[2019-04-22 05:50:44] development.ERROR: ErrorException: get_class() expects parameter 1 to be object, null given in /home/sko6/pultok/modules/backend/behaviors/RelationController.php:833
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'get_class() exp...', '/home/sko6/pult...', 833, Array)
#1 /home/sko6/pultok/modules/backend/behaviors/RelationController.php(833): get_class(NULL)
#2 /home/sko6/pultok/modules/backend/behaviors/RelationController.php(373): Backend\Behaviors\RelationController->makeManageWidget()
#3 /home/sko6/pultok/modules/backend/behaviors/RelationController.php(230): Backend\Behaviors\RelationController->initRelation(Object(OFFLINE\Mall\Models\Product), 'brand')
#4 /home/sko6/pultok/modules/backend/behaviors/RelationController.php(417): Backend\Behaviors\RelationController->validateField('brand')
#5 [internal function]: Backend\Behaviors\RelationController->relationRender('brand')
#6 /home/sko6/pultok/vendor/october/rain/src/Extension/ExtendableTrait.php(409): call_user_func_array(Array, Array)
#7 /home/sko6/pultok/modules/backend/classes/Controller.php(192): Backend\Classes\Controller->extendableCall('relationRender', Array)
#8 /home/sko6/pultok/plugins/offline/mall/controllers/products/_brand.htm(1): Backend\Classes\Controller->__call('relationRender', Array)
#9 /home/sko6/pultok/modules/system/traits/ViewMaker.php(247): include('/home/sko6/pult...')
#10 /home/sko6/pultok/modules/system/traits/ViewMaker.php(97): Backend\Classes\Controller->makeFileContents('/home/sko6/pult...', Array)
#11 /home/sko6/pultok/modules/backend/widgets/form/partials/_field_partial.htm(7): Backend\Classes\Controller->makePartial('_brand.htm', Array)
#12 /home/sko6/pultok/modules/system/traits/ViewMaker.php(247): include('/home/sko6/pult...')
#13 /home/sko6/pultok/modules/system/traits/ViewMaker.php(97): Backend\Classes\WidgetBase->makeFileContents('/home/sko6/pult...', Array)
#14 /home/sko6/pultok/modules/backend/widgets/Form.php(274): Backend\Classes\WidgetBase->makePartial('_field_partial....', Array)
#15 /home/sko6/pultok/modules/backend/widgets/form/partials/_field.htm(22): Backend\Widgets\Form->renderFieldElement(Object(Backend\Classes\FormField))
#16 /home/sko6/pultok/modules/system/traits/ViewMaker.php(247): include('/home/sko6/pult...')
#17 /home/sko6/pultok/modules/system/traits/ViewMaker.php(97): Backend\Classes\WidgetBase->makeFileContents('/home/sko6/pult...', Array)
#18 /home/sko6/pultok/modules/backend/widgets/form/partials/_field-container.htm(8): Backend\Classes\WidgetBase->makePartial('_field.htm', Array)
#19 /home/sko6/pultok/modules/system/traits/ViewMaker.php(247): include('/home/sko6/pult...')
#20 /home/sko6/pultok/modules/system/traits/ViewMaker.php(97): Backend\Classes\WidgetBase->makeFileContents('/home/sko6/pult...', Array)
#21 /home/sko6/pultok/modules/backend/widgets/form/partials/_form_fields.htm(2): Backend\Classes\WidgetBase->makePartial('_field-containe...', Array)
#22 /home/sko6/pultok/modules/system/traits/ViewMaker.php(247): include('/home/sko6/pult...')
#23 /home/sko6/pultok/modules/system/traits/ViewMaker.php(97): Backend\Classes\WidgetBase->makeFileContents('/home/sko6/pult...', Array)
#24 /home/sko6/pultok/modules/backend/widgets/form/partials/_form_tabs.htm(29): Backend\Classes\WidgetBase->makePartial('_form_fields.ht...', Array)
#25 /home/sko6/pultok/modules/system/traits/ViewMaker.php(247): include('/home/sko6/pult...')
#26 /home/sko6/pultok/modules/system/traits/ViewMaker.php(97): Backend\Classes\WidgetBase->makeFileContents('/home/sko6/pult...', Array)
#27 /home/sko6/pultok/modules/backend/widgets/form/partials/_section.htm(27): Backend\Classes\WidgetBase->makePartial('_form_tabs.htm', Array)
#28 /home/sko6/pultok/modules/system/traits/ViewMaker.php(247): include('/home/sko6/pult...')
#29 /home/sko6/pultok/modules/system/traits/ViewMaker.php(97): Backend\Classes\WidgetBase->makeFileContents('/home/sko6/pult...', Array)
#30 /home/sko6/pultok/modules/backend/widgets/form/partials/_form.htm(7): Backend\Classes\WidgetBase->makePartial('_section.htm', Array)
#31 /home/sko6/pultok/modules/system/traits/ViewMaker.php(247): include('/home/sko6/pult...')
#32 /home/sko6/pultok/modules/system/traits/ViewMaker.php(97): Backend\Classes\WidgetBase->makeFileContents('/home/sko6/pult...', Array)
#33 /home/sko6/pultok/modules/backend/widgets/form/partials/_form-container.htm(8): Backend\Classes\WidgetBase->makePartial('_form.htm')
#34 /home/sko6/pultok/modules/system/traits/ViewMaker.php(247): include('/home/sko6/pult...')
#35 /home/sko6/pultok/modules/system/traits/ViewMaker.php(97): Backend\Classes\WidgetBase->makeFileContents('/home/sko6/pult...', Array)
#36 /home/sko6/pultok/modules/backend/widgets/Form.php(227): Backend\Classes\WidgetBase->makePartial('_form-container...', Array)
#37 /home/sko6/pultok/modules/backend/behaviors/FormController.php(409): Backend\Widgets\Form->render(Array)
#38 [internal function]: Backend\Behaviors\FormController->formRender()
#39 /home/sko6/pultok/vendor/october/rain/src/Extension/ExtendableTrait.php(409): call_user_func_array(Array, Array)
#40 /home/sko6/pultok/modules/backend/classes/Controller.php(192): Backend\Classes\Controller->extendableCall('formRender', Array)
#41 /home/sko6/pultok/plugins/offline/mall/controllers/products/update.htm(17): Backend\Classes\Controller->__call('formRender', Array)
#42 /home/sko6/pultok/modules/system/traits/ViewMaker.php(247): include('/home/sko6/pult...')
#43 /home/sko6/pultok/modules/system/traits/ViewMaker.php(109): Backend\Classes\Controller->makeFileContents('/home/sko6/pult...')
#44 /home/sko6/pultok/modules/backend/classes/Controller.php(412): Backend\Classes\Controller->makeView('update')
#45 /home/sko6/pultok/modules/backend/classes/Controller.php(286): Backend\Classes\Controller->execPageAction('update', Array)
#46 /home/sko6/pultok/modules/backend/classes/BackendController.php(161): Backend\Classes\Controller->run('update', Array)
#47 [internal function]: Backend\Classes\BackendController->run('offline/mall/pr...')
#48 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#49 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)
#50 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Backend\Classes\BackendController), 'run')
#51 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#52 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()
#53 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 /home/sko6/pultok/modules/backend/classes/BackendController.php(68): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#55 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(131): Backend\Classes\BackendController->Backend\Classes\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#56 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#58 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#61 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#64 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#67 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#70 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#71 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#73 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#74 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#75 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#76 /home/sko6/pultok/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#77 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#78 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#79 /home/sko6/pultok/plugins/bedard/debugbar/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#80 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#81 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#82 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#83 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#84 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#85 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#86 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#87 /home/sko6/pultok/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#88 /home/sko6/pultok/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#89 /home/sko6/pultok/server.php(18): require_once('/home/sko6/pult...')
#90 {main}

**Comment by tobias-kuendig** [comment]
What form is it in the screenshot? Are you editing a Variant? Could you please provide me with the exact steps you do to trigger this error? I'm having a hard time replicating the issue.

**Comment by skobb** [comment]
So, i ll ty (ssory for bad english and bad knowledge :) ). If i create a new product, I'm downloading image in standard form and all ok. But if i want to change image after that - 
![image](https://user-images.githubusercontent.com/46927994/56557966-b7d96e00-65a5-11e9-89fe-6f5aeeda807f.png)
![image](https://user-images.githubusercontent.com/46927994/56557991-d63f6980-65a5-11e9-85c5-b4cc73cd9bd1.png)
I've got an error - 
![image](https://user-images.githubusercontent.com/46927994/56558020-eb1bfd00-65a5-11e9-8135-d09ed21a6f54.png)
if i click on new image - 
![image](https://user-images.githubusercontent.com/46927994/56558028-f707bf00-65a5-11e9-9bef-d31f89a348d1.png)
If I just close the error - all ok, image changes, but I want to remove the error. If You need more information, just tell me what I should post here, Thanks!

**Comment by tobias-kuendig** [comment]
I have opened an issue to track this bug upstream:

https://github.com/octobercms/october/issues/4300

**Comment by tobias-kuendig** [comment]
The issue has been resolved upstream. Please let me know if you still experience problems after upgrading October to build 455.

https://github.com/octobercms/october/issues/4300#issuecomment-492880444
