### ISSUE TITLE
Bad prices in variants 

### ISSUE THREAD

**Issue by yevgenatlanov** [OFFLINE-GmbH/oc-mall-plugin#191]
Hi, 

i've moved prices from the product to variants, cause i need prices only in variants - and now when i create a new variant and call >>>Edit stock and price values>>> - the form popups with prices from the previous variant. So seems i made something wrong. 

Can you please help me understand what is the correct way to get prices modal table (yep, with custom price groups) works on variants model correct? Thanks a lot

**Comment by yevgenatlanov** [comment]
hey, is there a way to resolve it? thanks

**Comment by tobias-kuendig** [comment]
I'm having a hard time understanding what the problem is. What do you mean by `the form popups with prices from the previous variant.`? When you change the values and safe, are they persisted to the database corretly?

**Comment by yevgenatlanov** [comment]
Hi @tobias-kuendig, 

Let me try describe it again. I moved to the trigger "Edit stock and price values" from the product form to the variant form. I was thinking that i will be able to set this custom prices to the variants. 
Here's the screenshot of the trigger button and form itself (with group prices) 
[](url)

You are right, form writes to the db, but it rewrites the prices of all another variants. In this case i have one price groups for all variants of the product. 

What i can do to make it work? (Price groups on variants page model)

**Comment by tobias-kuendig** [comment]
Did I get this right: You just moved the "edit stock and price values" button to the variant form? This won't work ‒ you'd have to adjust the whole rest of the backend logic as well.

Also, why do you need this exactly? When you hit the edit price button on the main form you can edit all prices ‒ including the variant values. Only the first row is the product, the other rows are variants:

![image](https://user-images.githubusercontent.com/8600029/56819720-a238a280-684a-11e9-939f-561e01d651c9.png)

**Comment by yevgenatlanov** [comment]
@tobias-kuendig, oh well, seems like i need to update my mall plugin version. It wasn't working on my version - but works good on the clean setup. Thank's. You and team made a great work, it's super hard to implement something to it, but on the other hand it's stable and cool :) Thank you!

**Comment by tobias-kuendig** [comment]
Great, feel free to respond if you need any further assistance :+1:

**Comment by yevgenatlanov** [comment]
@tobias-kuendig hello:) is it possible to make my product always have variants? i can't get prices as you have them on the screenshot :( I need to cut off product somehow to be use only variants feature

**Comment by tobias-kuendig** [comment]
Maybe you can describe your use-case in detail. I feel like you're trying to shoehorn the plugin into a special use-case that might be better solved differently.

**Comment by yevgenatlanov** [comment]
Hi Tobias! 

Sorry I missed your message somehow .. I’m trying to use you product variant scheme because it looks super perfect for me .. but I made a lot custom code ontop and it’s not the right way, I’m trying to make tours and tours variants .. like for example you are heading to Paris and I recommend you 5 different ways to do it. Actually I made this work without offline/mall but I’ve stack on the checkout and currency switching (you did it perfect) so I decided to implement  mall plugin to make it work with mine 

Now it seems to work nice. Just small thing here and there that I don’t understand. I’m getting this error. It appears when I’m trying to edit created variant. I made few extra fields translatable and now getting this error. It works good on first create. 

Thanks for any advice.

**Comment by tobias-kuendig** [comment]
>  I made few extra fields translatable and now getting this error. It works good on first create.

What error? :man_shrugging: :grin:

**Comment by yevgenatlanov** [comment]
Hmm, screenshot attached

**Comment by tobias-kuendig** [comment]
You are replying to a GitHub issue, attachements won't be shown on the website.

**Comment by yevgenatlanov** [comment]
I'm dumb, lol

1)error itself https://www.dropbox.com/s/qlysn6c5tlzq89j/Screen%20Shot%202019-05-10%20at%205.38.50%20PM.png?dl=0
2) controller part https://www.dropbox.com/s/s8d9d6f6n7w11zj/Screen%20Shot%202019-05-10%20at%205.56.31%20PM.png?dl=0

**Comment by tobias-kuendig** [comment]
This looks like an error that is there because of changes you made. `post('MallPrice')` does not return any values, these are expected. What did you do to the price field? If you don't need the price field change the call to `post('MallPrice', [])` and the code should execute. This was added in 697b51b.

If you need the price field inspect the request to the backend and see if the `MallPrice` array is present.
