### ISSUE TITLE
product default redirect to a variant

### ISSUE THREAD

**Issue by papppeter** [OFFLINE-GmbH/oc-mall-plugin#193]
HI,

i have a product with variants. But still would like to send out the product url, which will redirect me to one of the variant. my problem is that redirect does not care if the variant is published or not. Is there a solution how i can solve this problem? Or need to fixed it?

**Comment by tobias-kuendig** [comment]
The bug will be around here, you can patch it until I get around fixing it.
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/Product.php#L160

PRs are always welcome :+1:

**Comment by tobias-kuendig** [comment]
This has been fixed in 8fcde28. Thanks for reporting the issue!

**Comment by papppeter** [comment]
Thanks!
