### ISSUE TITLE
Flash::success not working in French

### ISSUE THREAD

**Issue by willouch** [OFFLINE-GmbH/oc-mall-plugin#195]
Hi,

I think I have an error in file /components/Product.php in line 246 with :
Flash::success(trans('offline.mall::lang.frontend.cart.added'));

it's not working for me, i need change this line to
Flash::success(trans('offline.mall::frontend.cart.added'));

Regards

**Comment by tobias-kuendig** [comment]
Thank you! This has been fixed.
