### ISSUE TITLE
Register a PaymentProvider problem

### ISSUE THREAD

**Issue by sozonovalexey** [OFFLINE-GmbH/oc-mall-plugin#198]
Hello!

I have problem with registration

```
public function boot()
    {
        $gateway = $this->app->get(PaymentGateway::class);
        $gateway->registerProvider(new ExampleProvider());
    }
```

![Снимок экрана 2019-04-30 в 9 59 41](https://user-images.githubusercontent.com/1676060/56945153-bb816d80-6b2e-11e9-80cd-f7f99397b307.png)

**Comment by sozonovalexey** [comment]
![Снимок экрана 2019-04-30 в 10 00 58](https://user-images.githubusercontent.com/1676060/56945182-dfdd4a00-6b2e-11e9-81b5-6d52a1e1a5a5.png)

If I add code here - everything is ok

**Comment by tobias-kuendig** [comment]
Could you try adding the code to the `register` method instead of boot? May I ask what your plugin name is? (vendor.plugin)

**Comment by sozonovalexey** [comment]
![Снимок экрана 2019-04-30 в 12 18 37](https://user-images.githubusercontent.com/1676060/56952096-1d979e00-6b42-11e9-85f1-2b9ac575b373.png)

> May I ask what your plugin name is? (vendor.plugin)

xeor.tinkoffmall

You can download the plugin here

https://github.com/octocart/tinkoffmall-plugin

**Comment by tobias-kuendig** [comment]
Can you try again with this change applied?

https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/0135f22cbd34a4ed9d5226f1270c027308fc464b

**Comment by sozonovalexey** [comment]
Yes. Not it's ok.

**Comment by tobias-kuendig** [comment]
Great! Thank you for the feedback. I will release this change with the next version later today.
