### ISSUE TITLE
How to change notifications to a language other than English?

### ISSUE THREAD

**Issue by exaline-ru** [OFFLINE-GmbH/oc-mall-plugin#199]
Why is that notifications only in English !? Is this the default?

**Comment by tobias-kuendig** [comment]
Feel free to submit a PR with the frontend translations in your language:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/lang/en/frontend.php

You can override the strings locally as well:

https://octobercms.com/docs/plugin/localization#overriding

**Comment by exaline-ru** [comment]
Frontend (Russian) works. Only messages in the mail, for some reason only in English!?

**Comment by exaline-ru** [comment]
The issue is resolved by manually translating all the mail templates into backend.

**Comment by tobias-kuendig** [comment]
Unfortunately, October does not yet provide a native way to translate mail partials. Translating them manually is the only solution at the moment :+1:
