### ISSUE TITLE
Cart totals and grand totals not updated after current currency format change

### ISSUE THREAD

**Issue by marcomessa** [OFFLINE-GmbH/oc-mall-plugin#201]
After updating in Settings/Currencies the current currency format, changes are not reflected in cart page. Product prices are formatted using new format, but cart totals, grand total and discount keep old format. (look at column labelled "Prezzo", that is working).

Working
```twig
{{ product.price() | raw }}
```
Not Working
```twig
{{ product.totalPreTaxes | money }}
```
<img width="983" alt="Schermata 2019-05-02 alle 11 23 08" src="https://user-images.githubusercontent.com/4236142/57066526-b1957100-6ccc-11e9-8054-7fd9cafdf833.png">

**Comment by tobias-kuendig** [comment]
Thank you, this is fixed in f5a2bf5. The issue only persists for the current session. New visitors should already see the new format. You can alternatively log out and back in to refresh your session and therefore the currency format.
