### ISSUE TITLE
Sort products by alphabet

### ISSUE THREAD

**Issue by MartinZboril** [OFFLINE-GmbH/oc-mall-plugin#203]
Hello, please how can I order products by alphabet. I couldn't find any option for this. I would be grateful if you could help me ASAP...

**Comment by tobias-kuendig** [comment]
This is currently not possible and will need an addition to the index table since the names are not indexed. 

I can try to release an update by tomorrow that includes a fix to this.

**Comment by tobias-kuendig** [comment]
This has been implemented in 5556971eff218cdecbca863ceb612e50730b8091 and is available in v1.2.8. 

You need to run `php artisan mall:reindex` for this new feature to work. You can add `sort = "name"` to your `Products` component to sort alphabetically by name.
