### ISSUE TITLE
Order without products

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-mall-plugin#204]
Hello,

I wonder if it would be possible to use your mall plugin just for the order part of the ecommerce (cart + checkout + order management).

I would like to be able to create my own product model with my own fields, and being able to add them to your cart (as long as I respect your requirement like having a price in the format your orders needs etc....)

It would be really interesting to be able to create our own models for products, with the fields our clients needs (and not more). Do you think it's actually possible or it would bring many problems to many different parts of the backoffice ?

Thank you,

**Comment by tobias-kuendig** [comment]
This will not be possible without making many changes to the current plugin architecture.

You definitely can re-use the Cart and Order models and extend them to use your own related models. But you will most likely run into complications pretty soon.

I guess for your use-case you are better off using a "Cart" plugin that is only that - a cart.
