### ISSUE TITLE
After langugage change in cart, cart is empty. 

### ISSUE THREAD

**Issue by romanseki** [OFFLINE-GmbH/oc-mall-plugin#205]
After langugage change via rainlab translation plugin in cart, cart become empty

**Comment by tobias-kuendig** [comment]
I cannot reproduce this issue.

Can you see if the issue exists on [mall.offline.swiss](https://mall.offline.swiss)?

**Comment by romanseki** [comment]
on mall.offline.swiss is everythink ok, probabbly somethink wrong in my code
