### ISSUE TITLE
Error when sorting Variant properties

### ISSUE THREAD

**Issue by Eoler** [OFFLINE-GmbH/oc-mall-plugin#207]
MySQL 5.6, plugin version: 1.2.8

Properties column in Product Variants relation allows sorting in backend controller, but gives error when clicked:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'properties_description' in 'order clause'`

The problem is that grid widget already remembered sort column, so opening Product form always throws exception after that until deleting October session cookie.

**Comment by tobias-kuendig** [comment]
Thank you for this bug report! The issue has been fixed in 9018783.
