### ISSUE TITLE
Column not found: name

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#209]
Whilst saving a simple product item from the backend, I am facing this error:

<img width="681" alt="Screenshot 2019-05-08 15 11 04" src="https://user-images.githubusercontent.com/2263496/57356806-fffeb000-71a3-11e9-8a30-1b9eb791013d.png">

**Comment by tobias-kuendig** [comment]
This is fixed in `v1.3.0`
