### ISSUE TITLE
Make State/Province validation for addresses optional

### ISSUE THREAD

**Issue by Eoler** [OFFLINE-GmbH/oc-mall-plugin#210]
MySQL 5.6, plugin version: 1.2.8

RainLab.Location does not provide States/Provinces for many countries, and in some cases it's irrelevant data (shipping companies don't care).

Proposing to make it optional (or at least check if any states/provinces are available) to reduce signup friction.

**Comment by tobias-kuendig** [comment]
Yes, this definitely makes sense. Thank you for this suggestion.

I'm leaving the issue open to track progress.

**Comment by Eoler** [comment]
> I'm leaving the issue open to track progress.

I will try it, now that I saw you're accepting pull requests.

**Comment by tobias-kuendig** [comment]
There is now a `Use state` option in the backend settings that lets you disable the state field completely.

Added in 8d0ae50.
