### ISSUE TITLE
Error Msg : The URL has to be unique

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#212]
I really dont understand why I am facing this validation error `The URL has to be unique` when saving a new category with this code:

// $slug is equal to 'guitars' in my demo data

```php
            $name = array_get($item, 'Name', "Untitled");
            $slug = Str::slug(array_get($item, 'Name', "Untitled"));

// $slug is equal to 'guitars' in my demo data

$category = Category::firstOrCreate( [
                    'code' => array_get($item,'ID',1)
                ],[
                    'name'                      => $name,
                    'slug'                      => $slug,
                    'code'                      => array_get($item, 'ID', 1),
                    'sort_order'                => array_get($item, 'SortOrder', 1),
                    'meta_title'                => $name,
                    'description'               => array_get($item, 'Description', null),
                    'meta_description'          => array_get($item, 'Description', null)
                ]
            );
```

**Comment by chrisvidal** [comment]
it looks like the responsible of my problems is hidden in the trait slug.php

```php
/**
     * Returns a cached map of category_ids and slug pairs.
     */
    public function getSlugMap($locale = null)
    {
        $locale = $this->getLocale($locale);

        return \Cache::rememberForever($this->mapCacheKey($locale), function () use ($locale) {
            $map = [];

```


it looks like there is a forever cache.

My scenario is that I am pulling data product from an external API. So as right now, I am constantly pulling the data and test.
Would that be the problem?

**Comment by tobias-kuendig** [comment]
You can always `Cache::forget($this->mapCacheKey($locale))` before importing the data. Would that work for you?

The slugs are cached since it's very expensive to re-generate the whole category tree for all installed locales.

**Comment by chrisvidal** [comment]
I am doing this in my command code but it does not solve the problem:

```php
 $locale = Category::DEFAULT_LOCALE;
Cache::forget(Category::MAP_CACHE_KEY . '.' . $locale);
```

**Comment by chrisvidal** [comment]
Oh i changed OC cache driver to database and now the cache seems to be flushed.

`
CACHE_DRIVER=database
`

**Comment by tobias-kuendig** [comment]
Hmm, another cache driver results in a "blank" cache for sure. 

Does it work from now on with the DB driver?

**Comment by chrisvidal** [comment]
nope, it worked once but now it does not anymore

**Comment by chrisvidal** [comment]
I have to seed the demo data, and then my data import is working again.

What is done in the demo data seeding?

**Comment by tobias-kuendig** [comment]
How does your data import work? Are you wiping all data before the import? 

I see you are relying on `firstOrCreate`, this might be where the problem lies.

**Comment by tobias-kuendig** [comment]
In the trait, you can see what is in these variables to check what data is blocking:

```php
// Around line 48
// ID of existing model, ID of current model
dd($map[$slug], $model->id);
```

**Comment by chrisvidal** [comment]
I thought about this as well and now I am using `::create` => same result

yes I am truncating all the data. Maybe I miss some tables, i need to check further

**Comment by chrisvidal** [comment]
the `dd` return
```
1
null
```

**Comment by tobias-kuendig** [comment]
What does `Cache::get(Category::MAP_CACHE_KEY . '.' . $locale);` return before you create the product? This should be empty.

**Comment by chrisvidal** [comment]
It happens before creating the category, not the product.

the `cache:get` returns `null`

**Comment by chrisvidal** [comment]
I copy/paste the existing `function cleanup()` from the demo data seeder, and it seems to do the job.

i think this is `Artisan::call('cache:clear');` who makes thing happens

thanks for your support @tobias-kuendig

**Comment by tobias-kuendig** [comment]
Alright, I'll close this for now since it's a special use-case. If anybody has similar problems we can further investigate the issue.
