### ISSUE TITLE
Creating product variants price by code

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#215]
When I run the seed-demo, I am supposed to see a product variant price for the variant `Cruiser 5000 27.5" S`
However, we cant see any price in the backend product form for the variant.
In DB, the prices are saved, but nothing is displayed in the variant.
I wonder what is happening.

I am trying to save price for my variants product through code, but cant seem to be able to achieve it following the existing code seed-demo.

`in DemoProduct.php`

```php
 $v = Variant::create([
                'product_id'   => $this->product->id,
                'image_set_id' => $variant['image_set_id'] ?? null,
                'stock'        => $variant['stock'],
                'name'         => $variant['name'],
                'price'        => $variant['price'] ?? null,
                'old_price'    => $variant['old_price'] ?? null,
                'published'    => true,
            ]);

            if (isset($variant['prices'])) {
                $variant['prices'] = collect($variant['prices'])->map(function ($price) {
                    $price['product_id'] = $this->product->id;

                    return $price;
                });
                $v->prices()->saveMany($variant['prices']);
            
```

```php
protected function variants(): array
    {
        return [
            [
                'name'       => 'Cruiser 5000 27.5" S',
                'stock'      => 4,
                'price'      => $this->prices(),
                'properties' => [
                    'frame-size' => 'S (38cm / 15")',
                    'wheel-size' => '27.5"',
                ],
            ],
```

**Comment by tobias-kuendig** [comment]
There was an error in the demo seeder where it references `price` instead of `prices`. This comes from an older version where a Product only had one price value.

This is fixed in 71acfae.

After this fix I'm seeing the Variant prices in the backend. 

What does your `offline_mall_product_prices` table look like? Do you have the price entries for your `product_id` and `variant_id` values?

**Comment by chrisvidal** [comment]
OK, let me try with this.
I didnt receive any updates on the plugin side, but I will update manually the code and test.

**Comment by chrisvidal** [comment]
ok now it works fine, i can see the different price based on the currency.
Thanks again @tobias-kuendig 

FYI, I am in the midst of developing an extension plugin for Mall, that will handle the concept of Marketplace. I am not sure if this is in your future plan?
We can talk about it if you want on Slack, I saw that you were on the OctoberCMS channel as well.

**Comment by tobias-kuendig** [comment]
Great! Feel free to contact me on Slack. I will close this issue, simply reply if furhter problems arise.
