### ISSUE TITLE
Add the possibility of being able to buy a product for a specific date

### ISSUE THREAD

**Issue by zimudec** [OFFLINE-GmbH/oc-mall-plugin#216]
I am adapting your plugin to do something more personalized, making it possible to buy, indicating for what date I want the order.

For that, I am making specific adaptations for my requirements:
- I am using variants to control product associated with a day of the week
- Show the shopping cart with each product associated with your chosen day (variant), ordered from today onwards (same could be a specific date instead of a day of the week)
- Adapting the order_product table, so that a delivery date for that specific product is saved
- Adapting the detail of an order, so that date can be seen
- Creating a list in backend, to show the list of products that must be delivered on a specific date (by default, today)

I know it's not the standard way to do this. But I ask: Will there be a standard way to do this?

If so, I propose to implement a functionality as it is, that is configurable and optional for the system administrator, that is adapted for all cases like the rest of the existing functionalities.

**Comment by tobias-kuendig** [comment]
Wouldn't a custom "date picker" field that you can add to a product be sufficient in this case? Like you can already with checkboxes etc (see «Include bike assembly guide» from the demo data).

If yes, you can watch https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/161

**Comment by exaline-ru** [comment]
Previously, I also asked a similar question: how to do so that customers can only order (pre-order) this product, and not buy it immediately.

The question remained unanswered.

**Comment by tobias-kuendig** [comment]
Pre-orders are currently not supported. You are, however, welcome to submit a PR that adds this feature.

**Comment by tobias-kuendig** [comment]
I'm closing this issue for the time being since this use-case is very specific. 

You may want to look at our MicroCart plugin that provides you with the checkout flow of Mall but doesn't confine you with the product structure in any way:

https://github.com/OFFLINE-GmbH/oc-microcart-plugin

Let me know if you need any more support.
