### ISSUE TITLE
Error in the order payment process

### ISSUE THREAD

**Issue by exaline-ru** [OFFLINE-GmbH/oc-mall-plugin#217]
Error in the order payment process: (When choosing any payment method. The base demo is installed and works fine)

`"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'brand' in 'field list' (SQL: insert into `offline_mall_order_products` (`order_id`, `product_id`, `variant_id`, `item`, `name`, `variant_name`, `quantity`, `taxes`, `tax_factor`, `price_post_taxes`, `price_taxes`, `price_pre_taxes`, `total_pre_taxes`, `total_taxes`, `total_post_taxes`, `weight`, `total_weight`, `width`, `length`, `height`, `stackable`, `shippable`, `brand`, `properties_description`, `property_values`, `custom_field_values`, `updated_at`, `created_at`) values (5, 6, 31, {"id":31,"product_id":6,"user_defined_id":null,"image_set_id":null,"stock":1,"name":"Red Shirt ...
on line 664 of /public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php`

**Comment by tobias-kuendig** [comment]
Your db isn't up to date. Make sure to run the latest migrations. What
version are you on?

exaline-ru <notifications@github.com> schrieb am Sa., 11. Mai 2019, 21:32:

**Comment by exaline-ru** [comment]
> Your db isn't up to date. Make sure to run the latest migrations. What version are you on?

Ver. 1.2.8.

**Comment by tobias-kuendig** [comment]
You are running newer code. The `brand` column was added in 1.3.0. 

Try running `php artisan october:up` and see if this fixed the problems. Version after 1.2.8 are not released to the stable channel yet.

**Comment by exaline-ru** [comment]
After upgrading to version 1.3.2, the issue is resolved. You can close this issue.
