### ISSUE TITLE
Request: component productFilter

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#219]
In the `productFilter.php` line 272 we have this piece of code:
```php
if ($this->includeChildren) {
            $categories = $this->category->getChildrenIds();
        }
        $this->setVar('categories', $categories);
```

I am not sure why we are returning only the childrenIds of the category?

In my design, I would need to be able to display the sub-categories of a category, hence I would need their name, total number of products inside, id and slug to create a UI.

Did I miss something that would help me to achieve that?

**Comment by tobias-kuendig** [comment]
Currently, we only need the ids inside the component. I'm not against changing this so that all category data is available.

**Comment by chrisvidal** [comment]
I believe it will be great for frontend dev

**Comment by tobias-kuendig** [comment]
This has been added in 1d7d93b.
