### ISSUE TITLE
Possibility to delete orders

### ISSUE THREAD

**Issue by alxy** [OFFLINE-GmbH/oc-mall-plugin#22]
I'm unsure of this is a good idea, as orders can also be set to "cancelled" in case they are canceled. But sometimes you may wish to entirely remove an order from your system, so I think it can be considered puttin that little trash icon on the bottom right of the order page.

What do you think?

**Comment by tobias-kuendig** [comment]
Closed via https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/23
