### ISSUE TITLE
Category tree

### ISSUE THREAD

**Issue by juliCy** [OFFLINE-GmbH/oc-mall-plugin#221]
Ther is a way to get the category tree in a page instead of a menu? My template works without the staticPages plugin.

Thanks in advance.

**Comment by tobias-kuendig** [comment]
The Category model uses the NestedTree trait. You can use all the methods it provides like `getAll()` or `getNested()` etc.

https://octobercms.com/docs/database/traits#nested-tree

**Comment by juliCy** [comment]
Solved. Just used the pages pluging to do it. Thanks.
