### ISSUE TITLE
Incorrect display of the mall installation in backend

### ISSUE THREAD

**Issue by exaline-ru** [OFFLINE-GmbH/oc-mall-plugin#222]
It was observed in backend. I don't know if there are any hidden problems!? The version is updated to 1.3.3 and everything seems to work fine.
![image](https://user-images.githubusercontent.com/46493161/57649457-f1affa00-75d0-11e9-8903-59c74cd82cce.png)

![image](https://user-images.githubusercontent.com/46493161/57649422-da710c80-75d0-11e9-8aab-dc17abafb1b8.png)

**Comment by tobias-kuendig** [comment]
Do you have any custom plugins that `$require` the mall plugin? IIRC October's dependency check is case-sensitive. Search your project for `Offline.Mall` with matching case and see where it is referenced. Changing it to `OFFLINE.Mall` should fix this. 

I might create a PR to October's core to fix this issue for good.

**Comment by exaline-ru** [comment]
No plugin in bundles with Mall, except only one payment provider.

**Comment by tobias-kuendig** [comment]
I have sumitted a PR to solve this issue:
https://github.com/octobercms/october/pull/4337

**Comment by tobias-kuendig** [comment]
A fix has been merged upstream: https://github.com/octobercms/october/pull/4337
