### ISSUE TITLE
Theme Overriding issue of component product

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#223]
I think this is a OC limitation more than a bug. It's worth mentioning here, as maybe you know a trick to come around that issue:

```twig
{% partial __SELF__ ~ '::properties/default' item=item propertyValue=propertyValue %}
```

this won't work in a theme, OC will still get the original component folder and get the partial `components/product/properties/default.htm` and not the one in the theme folder `themes/my_awesome_theme_name/partials/product/properties/default.htm`

**Comment by tobias-kuendig** [comment]
Have you tried moving the partial to `themes/my_awesome_theme_name/partials/product/properties/default.htm`

The component alias has be be included in the partial path.

**Comment by chrisvidal** [comment]
yes I did, I am overriding the entire product component, and the rest of the partials are properly included

**Comment by tobias-kuendig** [comment]
I just tried it and indeed it does not work. I raised an issue upstream: https://github.com/octobercms/october/issues/4347

**Comment by tobias-kuendig** [comment]
A fix for this problem has been merged into October and will be available with a future release:

https://github.com/octobercms/october/pull/4652
