### ISSUE TITLE
Question regarding the variants grouping options

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#224]
I am playing the demo data to better understand the relationship between properties, categories, variants, variant grouping.

For the Bike Cruiser 5000 if I set the Attribute for variant grouping to -none-, I was expecting to see all the properties 'frame size' and 'wheel size' displayed on the product page in the frontend. And this is how it works. good good.

Now, I was expecting to be redirected to the variant page after I choose a frame/wheel size, but it seems that only the price/stock/cart section is getting refreshed. 

Would that be possible to be redirected to the variant page in that conditions? 
Because the product name for example does not change and it should, maybe the image are different, maybe the description is different as well.

**Comment by tobias-kuendig** [comment]
I see the use-case for this. It currently isn't possible. We could add a `redirectToVariant` property on the component that takes care of this though.

**Comment by chrisvidal** [comment]
I need this feature for my current project. 
Let me see if I can implement it and share the code with you.

**Comment by tobias-kuendig** [comment]
The new `redirectOnPropertyChange` property was added in 0e9153a.

see https://offline-gmbh.github.io/oc-mall-plugin/components/product.html
