### ISSUE TITLE
json_decode()  error on offline Payment

### ISSUE THREAD

**Issue by Mabudigital** [OFFLINE-GmbH/oc-mall-plugin#225]
I found this error while placing an order using the offline payment method. How can I fix it?

"json_decode() expects parameter 1 to be string, array given" on line 1115 of /home/*****/public_html/vendor/october/rain/src/Database/Model.php

**Comment by Mabudigital** [comment]
I found it was an error on my side.

**Comment by Mabudigital** [comment]
I thinks it was solved but it shows again. How I can solve it?

**Comment by tobias-kuendig** [comment]
You'll have to post the complete stack trace of the error

**Comment by Mabudigital** [comment]
It occurs on the checkout page. When I select offline payment method and try to place order with this method it shown the error alert. And is just when the alternate language. Main language(English) works well on alternate language(Spanish) shown the alert.

![D48E5328-7FF9-4DF9-87B0-34756AB7994C](https://user-images.githubusercontent.com/6021373/58019300-30631a00-7ad3-11e9-874a-4fe8885a3f2e.png)

**Comment by tobias-kuendig** [comment]
In your `storage/logs/system.log`, there is the error with the complete stack trace. Please post that otherwise it's hard to help you.

**Comment by Mabudigital** [comment]
First of all thanks for answer. This is what I have on my system.log file

[2019-05-20 12:40:09] development.ERROR: ErrorException: json_decode() expects parameter 1 to be string, array given in /home/qualityhemp/public_html/vendor/october/rain/src/Database/Model.php:1115
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'json_decode() e...', '/home/qualityhe...', 1115, Array)
#1 /home/qualityhemp/public_html/vendor/october/rain/src/Database/Model.php(1115): json_decode(Array, true)
#2 /home/qualityhemp/public_html/plugins/offline/mall/models/CartProduct.php(151): October\Rain\Database\Model->attributesToArray()
#3 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(438): OFFLINE\Mall\Models\CartProduct->getItemDataAttribute(NULL)
#4 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(340): Illuminate\Database\Eloquent\Model->mutateAttribute('item_data', NULL)
#5 /home/qualityhemp/public_html/vendor/october/rain/src/Database/Model.php(993): Illuminate\Database\Eloquent\Model->getAttributeValue('item_data')
#6 /home/qualityhemp/public_html/vendor/october/rain/src/Database/Model.php(957): October\Rain\Database\Model->getAttributeValue('item_data')
#7 /home/qualityhemp/public_html/plugins/offline/mall/classes/traits/JsonPrice.php(72): October\Rain\Database\Model->getAttribute('item_data')
#8 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1382): OFFLINE\Mall\Models\CartProduct->getAttribute('item_data')
#9 /home/qualityhemp/public_html/vendor/october/rain/src/Extension/ExtendableTrait.php(360): Illuminate\Database\Eloquent\Model->__get('item_data')
#10 /home/qualityhemp/public_html/vendor/october/rain/src/Database/Model.php(617): October\Rain\Database\Model->extendableGet('item_data')
#11 /home/qualityhemp/public_html/plugins/offline/mall/models/CartProduct.php(65): October\Rain\Database\Model->__get('item_data')
#12 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): OFFLINE\Mall\Models\CartProduct->OFFLINE\Mall\Models\{closure}(Object(October\Rain\Database\Connections\MySqlConnection))
#13 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(327): Illuminate\Database\Connection->transaction(Object(Closure))
#14 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#15 /home/qualityhemp/public_html/plugins/offline/mall/models/CartProduct.php(99): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#16 /home/qualityhemp/public_html/plugins/offline/mall/models/Order.php(177): OFFLINE\Mall\Models\CartProduct->moveToOrder(Object(OFFLINE\Mall\Models\Order))
#17 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): OFFLINE\Mall\Models\Order::OFFLINE\Mall\Models\{closure}(Object(OFFLINE\Mall\Models\CartProduct), 0)
#18 /home/qualityhemp/public_html/plugins/offline/mall/models/Order.php(178): Illuminate\Support\Collection->each(Object(Closure))
#19 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): OFFLINE\Mall\Models\Order::OFFLINE\Mall\Models\{closure}(Object(October\Rain\Database\Connections\MySqlConnection))
#20 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(327): Illuminate\Database\Connection->transaction(Object(Closure))
#21 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#22 /home/qualityhemp/public_html/plugins/offline/mall/models/Order.php(185): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#23 /home/qualityhemp/public_html/plugins/offline/mall/components/Checkout.php(217): OFFLINE\Mall\Models\Order::fromCart(Object(OFFLINE\Mall\Models\Cart))
#24 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): OFFLINE\Mall\Components\Checkout->OFFLINE\Mall\Components\{closure}(Object(October\Rain\Database\Connections\MySqlConnection))
#25 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(327): Illuminate\Database\Connection->transaction(Object(Closure))
#26 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#27 /home/qualityhemp/public_html/plugins/offline/mall/components/Checkout.php(218): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#28 /home/qualityhemp/public_html/modules/cms/classes/ComponentBase.php(187): OFFLINE\Mall\Components\Checkout->onCheckout()
#29 /home/qualityhemp/public_html/modules/cms/classes/Controller.php(850): Cms\Classes\ComponentBase->runAjaxHandler('onCheckout')
#30 /home/qualityhemp/public_html/modules/cms/classes/Controller.php(740): Cms\Classes\Controller->runAjaxHandler('checkout::onChe...')
#31 /home/qualityhemp/public_html/modules/cms/classes/Controller.php(373): Cms\Classes\Controller->execAjaxHandlers()
#32 /home/qualityhemp/public_html/modules/cms/classes/Controller.php(224): Cms\Classes\Controller->runPage(Object(Cms\Classes\Page))
#33 /home/qualityhemp/public_html/modules/cms/classes/CmsController.php(50): Cms\Classes\Controller->run('checkout/confir...')
#34 [internal function]: Cms\Classes\CmsController->run('checkout/confir...')
#35 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#36 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)
#37 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Cms\Classes\CmsController), 'run')
#38 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#39 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()
#40 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /home/qualityhemp/public_html/plugins/rainlab/translate/classes/LocaleMiddleware.php(29): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): RainLab\Translate\Classes\LocaleMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#61 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#62 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#63 /home/qualityhemp/public_html/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#64 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#65 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#66 /home/qualityhemp/public_html/plugins/offline/speedy/classes/middleware/CDNMiddleware.php(40): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#67 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): OFFLINE\Speedy\Classes\Middleware\CDNMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 /home/qualityhemp/public_html/plugins/offline/speedy/classes/middleware/Http2Middleware.php(38): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#70 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): OFFLINE\Speedy\Classes\Middleware\Http2Middleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#71 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#73 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#74 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 /home/qualityhemp/public_html/plugins/vdlp/redirect/classes/RedirectMiddleware.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#76 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Vdlp\Redirect\Classes\RedirectMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#77 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#78 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#79 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#80 /home/qualityhemp/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#81 /home/qualityhemp/public_html/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#82 {main}

**Comment by tobias-kuendig** [comment]
Thank you for providing the information!

I was able to reproduce this issue. It looks like an upstream problem with RainLab.Translate. I'll further investigate it tomorrow.

**Comment by tobias-kuendig** [comment]
You can track progress here: https://github.com/rainlab/translate-plugin/issues/485

**Comment by tobias-kuendig** [comment]
This issue was fixed upstream.
