### ISSUE TITLE
Menu item url

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#227]
Not sure what is happening but since the 2 last versions, the menu item url is always a `#` when using the 'OFFLINE: All shop categories"

**Comment by tobias-kuendig** [comment]
In the backend settings, under Mall General -> Configuration, do you have a category page selected?

**Comment by chrisvidal** [comment]
you are right. thanks @tobias-kuendig 
How come did these settings disappear? As I set them up before.
I must have refresh the Mall plugin maybe and so this settings would have been reset as well?
