### ISSUE TITLE
Checkout without shipping

### ISSUE THREAD

**Issue by papppeter** [OFFLINE-GmbH/oc-mall-plugin#228]
Hi, i would like to have a checkoutprocess where i can disable the shipping. We are selling online ticket, so i don't need this feature.

the best would be to decide it on category, or product basis, if it needs shipping or not.

now if i am deleting the shipping method cart gives me an error.

what do you think about this feature request?

**Comment by tobias-kuendig** [comment]
Yes, this definitely makes sense. Great idea!

For the time being you can create a `Without Shipping` shipping method. If it's the only available method the method selector will be skipped during the checkout.

**Comment by tobias-kuendig** [comment]
This feature is now available in v1.7.0.

https://offline-gmbh.github.io/oc-mall-plugin/changelog/1.7.0.html

https://mall.offline.swiss/en/category/gift-cards
