### ISSUE TITLE
Email show order button doesn't work. URL 

### ISSUE THREAD

**Issue by borjadevelop** [OFFLINE-GmbH/oc-mall-plugin#230]
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/d02ed503022913053f1c701dcaff34e8edbae499/classes/events/MailingEventHandler.php#L282

It doesn't work, show missing. 

    protected function getBackendOrderUrl($order): string
    {
        return Backend::url('offline/mall/orders/show/' . $order->id);
    }

Thanks

**Comment by tobias-kuendig** [comment]
Thank you! Fixed in 24cb9ab
