### ISSUE TITLE
Price of variant does not change when choosing an variant

### ISSUE THREAD

**Issue by exaline-ru** [OFFLINE-GmbH/oc-mall-plugin#231]
When choosing the option of the variants to display in frontend, like here 
![image](https://user-images.githubusercontent.com/46493161/57853971-bfc8ae80-77ef-11e9-8a17-45aa10edcaaa.png)
Price variant does not change when choosing an variant. The variants have different prices.
If attribute for variant grouping selected - Everything works fine.

**Comment by artistro08** [comment]
Can you replicate this on https://mall.offline.swiss ?

**Comment by exaline-ru** [comment]
I tested the feature on your site and the prices are displayed correctly. On my site why that feature so does not work.
![image](https://user-images.githubusercontent.com/46493161/57981490-c6019980-7a40-11e9-9ae2-a3703168f069.png)
![image](https://user-images.githubusercontent.com/46493161/57981491-cb5ee400-7a40-11e9-87fd-58f756f8daf0.png)
![image](https://user-images.githubusercontent.com/46493161/57981493-d31e8880-7a40-11e9-91e9-99a2d207df42.png)

**Comment by exaline-ru** [comment]
It is necessary to refine the function: when adding an option with different prices, prices will be saved automatically. Now it is necessary to add manually.

**Comment by artistro08** [comment]
Do you have `{% framework %}` and `{% framework extras %}` somewhere in your layout?

**Comment by exaline-ru** [comment]
I use the default template (as on https://mall.offline.swiss). My template has {% framework extras %}.

**Comment by artistro08** [comment]
What does your template look like on your website? Mind if I take a look?

**Comment by exaline-ru** [comment]
With the setting (as in the screenshot), the price switch works.
![AAfuFHiCEp](https://user-images.githubusercontent.com/46493161/58166103-c775d080-7c91-11e9-8da7-50851890e3ad.png)

If enabled, the price switch does not work.

**Comment by tobias-kuendig** [comment]
Yes, depending on this option there is a request made to the backend once the properties are changed or not.

I'll have to look into this :+1:

**Comment by tobias-kuendig** [comment]
This has been fixed in 45de4f5.
