### ISSUE TITLE
Brand filter not working

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#239]
the brand filter works well with the demo data.
When I used my data, it does not work anymore.

Where could that be coming from?

**Comment by tobias-kuendig** [comment]
Does your `offline_mall_index` table include the brand data? If not you can run `php artisan mall:reindex` to populate it. The brand filter was added in later versions so if you have older data it might not be indexed yet.

**Comment by chrisvidal** [comment]
same issue even if I force a `reindex`

**Comment by tobias-kuendig** [comment]
To debug the issue you can start from here and work backwards: 

> plugins/offline/mall/classes/index/mysql/MySQL.php:193

Check where the brand key gets missing.

**Comment by chrisvidal** [comment]
All good, my issue was coming from the fact that i removed the `div class="mall-products"` in my theme.

Which make me think of how could know which `ID's` and `css classes` are important to keep in out theme?
