### ISSUE TITLE
Add links to the blog post (news) in the product description

### ISSUE THREAD

**Issue by exaline-ru** [OFFLINE-GmbH/oc-mall-plugin#240]
It is advisable to add links to the blog post (news) in the product description. Or integrate a blog post (news) that writes (advertises) about this product. Is it possible to implement?

If this is possible, you can also add a function (button) to purchase goods directly from the page of the blog post (news).

**Comment by tobias-kuendig** [comment]
Sorry, I'm not sure what you mean.

**Comment by exaline-ru** [comment]
I mean: the ability to use the blog post (plugin Blog) by product to describe the product in the Mall, or attach the link desired blog post to the description of the product.

**Comment by tobias-kuendig** [comment]
You can add relations to the blog post as you wish by using October's extend functionality:

https://octobercms.com/docs/plugin/extending#usage-examples

This won't be part of the main plugin though since it is a very specific use-case.
