### ISSUE TITLE
Available from/to for products and variants

### ISSUE THREAD

**Issue by papppeter** [OFFLINE-GmbH/oc-mall-plugin#242]
Hi,

we would need to have an availability from to on products, and variants. our products are only available in a time frame. could you maybe include this in next updates?

**Comment by tobias-kuendig** [comment]
This is a good idea, I'll leave this issue open to track progress.

**Comment by tobias-kuendig** [comment]
If someone needs this feature PRs are welcome. For the time being we won't implement this ourselves.
