### ISSUE TITLE
Paypal error

### ISSUE THREAD

**Issue by borjadevelop** [OFFLINE-GmbH/oc-mall-plugin#243]
When i try to use paypal get that error. 
![image](https://user-images.githubusercontent.com/22686755/58315698-4f82e400-7e12-11e9-962e-7e7a284f0f47.png)

I have the web online and set up the client id and secret key on settings.

**Comment by papppeter** [comment]
Hi, maybe you did not switched to live version of the paypal. and your are still in sandbox mode.

**Comment by borjadevelop** [comment]
Same error on live and test mode :/

**Comment by tobias-kuendig** [comment]
Do you see any more details in your payment log (it's in the backend -> orders)? 

Did you double check that you are using the right credentials? Did you double check that you did not swap the client id and secret by accident?

**Comment by bilalpk99** [comment]
Hello guys,

i am facing a strange error "Call to undefined method Omnipay\Common\Http\Client::getEventDispatcher()" when Proceed to the Payment.

i am using PayPal-Rest and have setup the "PayPal Client ID" and "PayPal Secret" properly.
![Paypal-Error](https://user-images.githubusercontent.com/92153/58639052-105f0200-82ee-11e9-9a5d-163c3a1cf501.jpg)

Thanks

**Comment by tobias-kuendig** [comment]
Make sure you have omnipay v3 installed.

bilalpk99 <notifications@github.com> schrieb am Do., 30. Mai 2019, 16:17:

**Comment by bilalpk99** [comment]
Thanks "tobias-kuendig" for your reply i have sorted out the issue. The simplest solution is to install another plugin called "Omnipay Lite" which i believe installs omnipay v3 and everything started working as expected and after that i tried to disable the "Omnipay Lite" plugin and and got the same error as i posted so the fix is to install and enable the "Omnipay Lite" plugin if someone else is facing the same issue.

**Comment by tobias-kuendig** [comment]
Mall already ships Omnipay. You just have to make sure that no other Version is installed. Usually removing the vendor directory and re-installing the dependencies oslves this issue (as long as you don't have a conflicting plugin that requires v2 of Omnipay).
