### ISSUE TITLE
create a discount code if buys a certain product - feature request

### ISSUE THREAD

**Issue by papppeter** [OFFLINE-GmbH/oc-mall-plugin#244]
hi,

would it be usefull if we could have this feature. So i could sell a coupon product, which creates a discount code if it is sold, and paid. than i don't need to do this manually.

**Comment by tobias-kuendig** [comment]
You should be able to do this already by listening to the `mall.checkout.succeeded` event. You'd have to filter the products and check if the product exists but this should already be enough to implement this feature.

https://offline-gmbh.github.io/oc-mall-plugin/development/events.html#mall-checkout-succeeded

**Comment by tobias-kuendig** [comment]
Closing as duplicate of #375
