### ISSUE TITLE
orders sort order maybe not good

### ISSUE THREAD

**Issue by papppeter** [OFFLINE-GmbH/oc-mall-plugin#245]
Hi,

i just recognised if i try to sort by ORDER column, it gives a wrong result. please check the picture.

![Screenshot_17](https://user-images.githubusercontent.com/3380880/58403069-1c369400-8062-11e9-9084-f98c329f30f8.png)

**Comment by tobias-kuendig** [comment]
Thank you! 05424f8 that should fix it.
