### ISSUE TITLE
Fatal error on category list

### ISSUE THREAD

**Issue by papppeter** [OFFLINE-GmbH/oc-mall-plugin#247]
![Screenshot_18](https://user-images.githubusercontent.com/3380880/58415933-4e56ee80-8080-11e9-86a9-a8aba21ca799.png)

i hope it is not only because i use my own forked version.

**Comment by tobias-kuendig** [comment]
On line 250, do you have a call to `getAllChildrenAndSelf()`?

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/Products.php#L250

**Comment by papppeter** [comment]
my code looks like the same 

https://github.com/papppeter/oc-mall-plugin/blob/develop/components/Products.php#L250

**Comment by tobias-kuendig** [comment]
Found the issue, the problem only occured when you did not use the `includeChildren` option.

Thank you for reporting this bug :+1: 

Fixed in ce630c5 released as v1.3.7.
