### ISSUE TITLE
Ordering of menu items

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#251]
I noticed that the menu items from `All shop categories`  are not ordered by any specific order, not alphabetical at least.
Is it easy to fix and make them alphabetical ordered please?

**Comment by tobias-kuendig** [comment]
It should return the Categories in the order you sorted them in the backend. 

Can you try and run `php artisan cache:clear` and see if this updates the sort order? It might be that the cache is not busted correctly on re-order.

**Comment by tobias-kuendig** [comment]
Infact it looks like the re-order did not trigger the `saved` model event. I have added a fix in 11646d4. Let me know if the order is not right after you have cleared the cache.

**Comment by chrisvidal** [comment]
ok, it is fixed, thanks Tobias
