### ISSUE TITLE
Cart events

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#252]
There are 2 existing events for the cart `mall.cart.product.added` and `mall.cart.product.removed`

could we have another one `mall.cart.product.updated` for any update action, like the quantity updates for example in there `onUpdateQuantity()` in `cart.php` component

thanks so much

**Comment by chrisvidal** [comment]
Apparently the 2 existing events are not fired, I cant manage to listen and catch them

**Comment by tobias-kuendig** [comment]
Great suggestion! You can use either the `mall.cart.product.updated` or `mall.cart.product.quantityChanged` events added in v1.3.8.

https://offline-gmbh.github.io/oc-mall-plugin/development/events.html#mall-cart-product-updated

**Comment by chrisvidal** [comment]
thanks @tobias-kuendig

**Comment by chrisvidal** [comment]
The ordering of firing the events is somehow weird.
the 'cart updated' event is fired before the 'cart added' event.

It is because the updated event is fired upon the model cartProduct eloquent updated event and that the cart added event is fired by the cart component, so independently of the Eloquent events.

**Comment by tobias-kuendig** [comment]
Good point, I have moved the events to re-use the Eloquent event methods:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/783bb237a4a4280cadb1aead978a8e4ca1b8782e

This should work better. I'll release this change in the next version, make sure to change the event arguments. Each event now only receives the CartProduct model from where you can access all properties.

**Comment by chrisvidal** [comment]
awesome! Thanks @tobias-kuendig 

I was needing another event this other day but I can't remember which one now :D
