### ISSUE TITLE
Exception on edit address

### ISSUE THREAD

**Issue by m49n** [OFFLINE-GmbH/oc-mall-plugin#254]
On demo site if change address and change url, we get exceporion
1.Edit
![image](https://user-images.githubusercontent.com/15114737/58536241-97ca4980-81f8-11e9-8acd-fd9acad1d714.png)
2.Change
![image](https://user-images.githubusercontent.com/15114737/58536310-cd6f3280-81f8-11e9-8233-7cc55f06a9ab.png)
3.Exception
![image](https://user-images.githubusercontent.com/15114737/58536371-027b8500-81f9-11e9-9e8d-95d742da95fc.png)

**Comment by tobias-kuendig** [comment]
Thank you! Fixed in 518361c.
