### ISSUE TITLE
forgotten password is not wokring

### ISSUE THREAD

**Issue by papppeter** [OFFLINE-GmbH/oc-mall-plugin#259]
after reset password process, i still could not log in with the newly set password.

second problem: i could reset the password to a password less than 8 chars. than on login page i get a validation warning.

i could not reset the password from backend either.

could the problem be that i used guest checkout?

**Comment by tobias-kuendig** [comment]
This problem was resolved by the latest changes to the RainLab.User plugin. Thank you for reporting it, @papppeter!

**Comment by maartenmachiels** [comment]
Hi guys, has something changed? I'm unable to change a users password via the password reset function on the front-end and via the back-end aswel. I'm on October CMS build 473 and Mall 1.14.2. Does anyone else have this issue?

**Comment by chocolata** [comment]
Hi @tobias-kuendig,
I've done some more research and I've found that the client previously checked out as a guest. He had the expectation that an account would be created when he did the password reset steps. This seemingly works, but then the e-mail doesn't arrive.

Can we think about the optimal way of converting a guest to a user with an account? Now I just set his particular is_guest column directly in the database to 0 and he was able to perform the password reset.

I might oversee some things... but can't we just set the flag is_guest to 0 when a user resets a password on a previously guest account?

Thanks for your insights.

**Comment by tobias-kuendig** [comment]
Looking at the [DefaultSignupHandler](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/customer/DefaultSignUpHandler.php) it looks like this is the way to go. Also, the User is assigned a "Guest" role, that should be removed as well.
