### ISSUE TITLE
Matomo integration

### ISSUE THREAD

**Issue by markusobi0** [OFFLINE-GmbH/oc-mall-plugin#260]
Are there twig-Variables for a checkout-tracking with Matomo?

I already implemented SiteSearch in my Matomo-Analytics now I am wondering if it's also possible with the checkout.

Example for my SiteSearch integration
`  _paq.push(['trackSiteSearch',"{{ query }}",false,false]);`

Required parameters are:
- Order-ID
- Order Grand Total
and optional parameters are:
- subtotal amount
- Tax amount
- shipping amount
- discount amount

**Comment by tobias-kuendig** [comment]
Where would you have to access these parameters? Once the checkout is done? In this case you should be able to access the order in the partial via the `order` variable (it sits on the `Checkout` component). 

Once you've got the model at hand you can reffer to the docs to see how to get the order amounts:

https://offline-gmbh.github.io/oc-mall-plugin/development/order-model.html#access-pricing-information

    {{ order.totalPaymentPostTaxes().decimal }}

**Comment by markusobi0** [comment]
Please tell me, if I understood this right:

Order Grand Total: `{{ order.totalPaymentPostTaxes().decimal }}`
Tax amount: `{{ order.totalTaxes().decimal }}`
shipping amount: `{{ order.totalShippingPreTaxes().decimal }}`
... 

but how do I get the Order-ID?

**Comment by tobias-kuendig** [comment]
For the grand total use `{{ order.totalPostTaxes().decimal }}`. Also use `totalShippingPostTaxes` (note: Post instead of Pre) if you have any taxes on the shipping itself.

The order ID is available as `{{ order.id }}`. `order` in this case is a reference to the Order Eloquent model.

**Comment by markusobi0** [comment]
Thanks so far. Now I can try to integrate Matomo
