### ISSUE TITLE
empty order object in checkout

### ISSUE THREAD

**Issue by romanseki** [OFFLINE-GmbH/oc-mall-plugin#261]
I set Bankwire as offline payment method and in payment instructions try to use {{order}} to get some data but order objedct didnt exist also try dd(request()->get(); in checkout.php and it get null

**Comment by romanseki** [comment]
in payment method selection

**Comment by tobias-kuendig** [comment]
Hm, okay. It makes sense that you don't have any order data there since the order obviously hasn't been created yet. Let me check if we can make the cart available instead.

What order data would you need specifically in your payment instructions?

**Comment by tobias-kuendig** [comment]
You can apply the following changes to get access to your `cart` during checkout: 34ab3a4

```twig
{% if order %}
	The order exists: {{ order.totalPostTaxes() | raw }}
{% else if cart %}
	No order exists, but a cart: {{ cart.totals.totalPostTaxes | money }}
{% endif %}

**Comment by tobias-kuendig** [comment]
I'm closing this issue due to inactiviy. Please report back if you still experience any issues.
