### ISSUE TITLE
Duplicate orders

### ISSUE THREAD

**Issue by onesoco** [OFFLINE-GmbH/oc-mall-plugin#264]
Hello,

My problem is that when placing an order, with any method of payment, the entries in the order table are doubled.

Any solution why this happens? 
Does it happen the same problem to someone?

**Comment by tobias-kuendig** [comment]
Just to be clear: You've got two rows in your offline_mall_orders table for an actual order?

Do both orders contain all products in the backend or is one "empty"? Are the totals correct? Are you on the latest mall version? Did you do any custom modifications to the checkout process? What specific payment method did you use to test this?

**Comment by onesoco** [comment]
It was a problem when updating, now it's already solved.
