### ISSUE TITLE
omnipay/omnipay is abandoned

### ISSUE THREAD

**Issue by Flynsarmy** [OFFLINE-GmbH/oc-mall-plugin#267]
You're currently using omnipay/* in your [composer.json](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/composer.json#L26) which is [abandonware](https://packagist.org/packages/omnipay/omnipay). The project has moved to [league/omnipay](https://packagist.org/packages/league/omnipay).

**Comment by tobias-kuendig** [comment]
Thank you for the heads up. We are importing `league/omnipay` as the main package and  use `omnipay/stripe` and `omnipay/paypal`. As per the [Community Gateways page](https://omnipay.thephpleague.com/gateways/community/) it looks like these are the correct packages.

Is this correct?

**Comment by Flynsarmy** [comment]
Yep all good! Thanks for the response!
