### ISSUE TITLE
Make PropertyValue translatable

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#271]
Is this possible to make PropertyValue translatable?

For example, a property Color value for a variant product will have a value `Red` in English and `Rouge` in French.

**Comment by tobias-kuendig** [comment]
From the top of my head I cannot remember if there are any problems. Have you tried simply adding the Translatable traits to the PropertyValue model and see if it works? 

We can integrate it into the plugin once we know what's missing to get the values translatable.

**Comment by chrisvidal** [comment]
I did give a try and it does not work, because the PropertyValue are rendered through a specific formWidget that uses php, and render the input in a 'hardcoded' way.
Do you see what I mean?

**Comment by tobias-kuendig** [comment]
This will be fixed in https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/417 and released as 1.9.0 later this week.
