### ISSUE TITLE
Problem with repaeter field

### ISSUE THREAD

**Issue by MartinZboril** [OFFLINE-GmbH/oc-mall-plugin#275]
Hi, I have a problem with repeater field in backend for product form. I added some new fields via plugin by extending fields in my plugin. This everything works good but when I clicked on the new repeater fields value (Additional descriptions and Additional properties) I have there fields that I added by extending by my plugin.

This is example of field that I added.

`// Add an extra field
            $widget->addTabFields([
                'recomended' => [
                    'name'   => 'recomended',
                    'label'   => 'Recomended',
                    'type'    => 'switch',
                    'tab' => 'offline.mall::lang.product.general',
                    'span' => 'auto'
                ],
]);`

**Comment by tobias-kuendig** [comment]
Do I understand your problem correctly: You have added additional fields to the product form and these fields do show up in the wrong repeater?

**Comment by MartinZboril** [comment]
Yes, the fields that I added are showing up in every repeater fields in the product form. I wanted them only in the general tab like a normal fields.

**Comment by tobias-kuendig** [comment]
This looks like an issue with October itself. I suggest you create a code example that makes this issue reproducible using the test plugin:

https://github.com/octoberrain/test-plugin

Then create an issue in October's main repo.
