### ISSUE TITLE
Exclude Variants from search results

### ISSUE THREAD

**Issue by artistro08** [OFFLINE-GmbH/oc-mall-plugin#276]
Not entirely sure if I should post it here or on the sitesearch plugin, but there should be an ability to search through the main products and not the variants associated with the main product.

**Comment by tobias-kuendig** [comment]
So you mean like "Exclude Variants from search results"?

**Comment by artistro08** [comment]
Yes that's what I meant

**Comment by tobias-kuendig** [comment]
Added in 9f021a9, thanks @artistr08!
