### ISSUE TITLE
Migration of the index table

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#281]
I am experiencing this error message when I am trying to update columns of the offline_index table.
first of all, I am not sure why the index, name and brand columns have a size of 191 and not a size of 255?

This is what I am trying to update, my product variants are reaching the 255 characters in some case.

```
                $table->json('category_id');
                $table->json('property_values');
                $table->json('sort_orders');
                $table->json('prices');
                $table->json('parent_prices');
                $table->json('customer_group_prices');
```

It is not advised to use the `->json()` function because it is depending on the mySQL level of implementation as explained here https://github.com/octobercms/october/issues/3231

which is the issue I am facing when trying to increase the size of the 3 previous columns.

```
[Doctrine\DBAL\DBALException]
  Unknown database type json requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.
```

**Comment by tobias-kuendig** [comment]
> first of all, I am not sure why the index, name and brand columns have a size of 191 and not a size of 255?

See here: https://stackoverflow.com/a/43833633, but I've just seen that the `products` table has a forced length of `255` characters. We should make them the same. The safe option here would be to go for 191 for everything.

Just out of interest, what are your products called to be more than 190 characters long? 

What version of MySQL are you running? 5.7 with proper json support is a requirement for the database based index.

**Comment by chrisvidal** [comment]
> See here: https://stackoverflow.com/a/43833633, but I've just seen that the products table has a forced length of 255 characters. We should make them the same. The safe option here would be to go for 191 for everything.

> Just out of interest, what are your products called to be more than 190 characters long?
in my client products, I didn't find yet the exact product that is causing the problem,
I found stuff like this: 
product name would be: 12103 FIT ME MATTE & PORELESS POWDER
and the variant name (for a color) would be 12103 FIT ME MATTE & PORELESS POWDER 120 CLASSIC IVORY 8.5G

At first, I was concatenating the product name and the variant name, which seems to cause the error.
I am doing more tests with their data, that I synchronised from an external API.

> What version of MySQL are you running?
v5.7.25

**Comment by tobias-kuendig** [comment]
Looks like it is safe to increase the varchar length as long as we don't exceed 65,535 bytes per row:

http://sforsuresh.in/mysql_varchar_max_length/

**Comment by chrisvidal** [comment]
> http://sforsuresh.in/mysql_varchar_max_length/

interesting ~ but the migration does not run because of the `->json` error despite using mysql 5.7.25.

**Comment by tobias-kuendig** [comment]
:thinking:  But as I understand the comments in octobercms/october#3231, the usage of `->json()` should not be a problem with MySQL 5.7, right?

**Comment by chrisvidal** [comment]
what seems to be happening.

the first execution of the migration is working.

but, now I am trying a 
```php  
Schema::table('offline_mall_index', function($table) {   
   $table->string('name', 255)->change();
});
```

which provokes the error

**Comment by tobias-kuendig** [comment]
This problem has been adressed in 44fb36556934eb11b068918c5d248a99880c4def. 

Let me know if you need any further support.
