### ISSUE TITLE
What is product property and what is the purpose of it ?

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-mall-plugin#287]
Hello,

I'm trying Mall plugin (nice job to the author) but there is a concept that I don't understand.

I can't see the purpose of product property (when you create property for product but not define them as variant).

I created some properties, I can see a property tab on product page, but I can't see any difference with a product that don't have any properties on frontend.

Could you please explain me the purpose of it ?

Thank you

Alex

**Comment by tobias-kuendig** [comment]
The property values can be used to add specific datapoints to a product (Size, Color, Material etc.) 

The demo theme does not show all property values to keep everything simple. It only shows those that differ between variants.

You can, however, display them if you want: You can access them using the `$product->all_property_values` relation [as documented](https://offline-gmbh.github.io/oc-mall-plugin/development/product-model.html#property-values) and display the labels and values.

**Comment by PubliAlex** [comment]
Ok I understand, thank you for this clarification
