### ISSUE TITLE
Batch creation of variants

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-mall-plugin#288]
Hello,

I have a very specific product that is highly configurable. It has : 
- 7 different materials available
- 3 different zone where you can customize colors
- 250 colors available for each zone
- Can customize dimensions (width, length, height)

If I want to make each option available, I reach several thousands of variants. That's why I wonder what could be the best way to create variants in batch. Or maybe do you see a better option here ? (I don't have stock management need as products are handcrafted when order is received).

Thank you for your help

Alex

**Comment by tobias-kuendig** [comment]
Since you don't need stock management, you could create the product without any variants and provide the customization options as custom fields:
https://offline-gmbh.github.io/oc-mall-plugin/development/product-model.html#custom-fields

**Comment by PubliAlex** [comment]
Thank you for your answer. I gave a try to custom fields and I think it can do the Job. Thank you
