### ISSUE TITLE
cart_product vs cart_products

### ISSUE THREAD

**Issue by alxy** [OFFLINE-GmbH/oc-mall-plugin#29]
I have no idea why this worked, but there is an ambiguity between the table definition and the relationd efinition here:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/updates/builder_table_create_offline_mall_cart_products.php#L10  => `offline_mall_cart_products`
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/models/Product.php#L114 => `offline_mall_cart_product`

The easy fix is to replace it in the relation definition, but I am not sure if it has side effects.

**Comment by tobias-kuendig** [comment]
Good catch. This worked because this relation has not been used so far.

**Comment by alxy** [comment]
If you delete a product, that will lead to an error, as it tries to delete carts as well. This is how I catched it.
