### ISSUE TITLE
add to cart leading to login page

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#292]
Would that be possible to have this option 'add to cart leading to login page' ?

**Comment by tobias-kuendig** [comment]
Great input :+1:

I think it would be best to change the current "redirect_to_cart" option into a "redirect_to_page" and let the user choose the page.

**Comment by chrisvidal** [comment]
ok so I just create a PR in that regard.

My implemented flow is as following:
guest user is adding item to cart.
let the add to cart happens
but force to go login page
after login page, redirect to cart

**Comment by chrisvidal** [comment]
so in the cart page I added this code:

```
<?php
function onStart() {
    if (!Auth::check()) {
        Flash::error(post('flash', trans('Please register or log in to continue.')));
        return \Redirect::guest('/login?redirect=eshop/cart');
    }
}
?>
==
``

**Comment by chrisvidal** [comment]
in the signIn form component I added this to override the redirect options

```twig
==
<?php
function onStart() {
    $this['local_redirect'] = request()->get('redirect');
}
?>
==
```

and 

```twig
<form
    data-request="onSignin"
    {% if local_redirect %}
    data-request-data="redirect: '{{ local_redirect}}'"
    {% endif %}
    data-request-validate
    data-request-flash
    id="userForm"
    class="">
```

**Comment by chrisvidal** [comment]
and all works perfectly with the PR added in the component `signup.php`, function redirect()

**Comment by tobias-kuendig** [comment]
Thank you for these inputs, @chrisvidal! The PR has been merged.
