### ISSUE TITLE
Wishlist extension

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-mall-plugin#298]
Hello,

First, congratulation about your module and support. I'm played with it the last few days and it's a really well done plugin.

My project will need a wishlist feature, nothing crazy here, it's a kind of shopping cart you can save and load as desired.

My question is, do you plan to add that kind of feature soon ? If not, how would you implement it ? If I you don't develop this feature, I will, but I want to do it with your validation and advices.

Best regards,

Alex

**Comment by tobias-kuendig** [comment]
> My project will need a wishlist feature, nothing crazy here, it's a kind of shopping cart you can save and load as desired.

We will implement this feature in the comming days for a customer. I'll report back once there is something to test!

**Comment by PubliAlex** [comment]
Wow, awesome. Do you have a donation plateform in place ? We planed to invoice our customer for that addition, if your feature can save us some development time, I would like to give you something to support the project.

Best regards,

Alex

**Comment by tobias-kuendig** [comment]
@PubliAlex thank you for your offer! Feel free to make a donation to the October project here: https://octobercms.com/fundraising Just 40% to go! :wink: 

The wishlists feature can be tested in version 1.4.0 that is currently available as an edge update or on our demo website: https://mall.offline.swiss/en/product/cruiser-1500/OVaXoq8n

Please feel free to respond with any feedback regarding the feature in this issue.

**Comment by tobias-kuendig** [comment]
The feature is now available via the default update channel. Let me know if you have any feedback.
