### ISSUE TITLE
Having a brand page

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#299]
Having a brand page displaying all the product from the brands would be a must.

**Comment by tobias-kuendig** [comment]
You could already do this yourself using the filter strings:

https://mall.offline.swiss/en/category/bikes/mountainbikes?brand=cruiser-bikes&sort=bestseller

https://offline-gmbh.github.io/oc-mall-plugin/components/products.html#properties

**Comment by chrisvidal** [comment]
Good idea ~ just did it actually

**Comment by damsfx** [comment]
@tobias-kuendig  
Using the URL way don't allow us to show the entire brand's products, only those of a specific category.

Imagine your demo shop with "Cruiser bikes" having some sports clothes, then you can't get all "Cruiser bikes" products (bikes and clothes) on the same result page.

Only solution to do it this way is to create an single top category "all".

**Comment by tobias-kuendig** [comment]
That is true, @damsfx. While we don't ship any pre-made components, a brand page is still a relatively easy thing to do yourself. All you have to do is to register your own component that fetches a Brand based on a slug. You can then fetch all the related products and even re-use the partials from the `Products` component to display the data.
