### ISSUE TITLE
Auto generate discount code

### ISSUE THREAD

**Issue by faselunare** [OFFLINE-GmbH/oc-mall-plugin#305]
Add a random generated discount code with possibility to modify it by hand
In the plugin configuration add settings:
- Code lenght
Charset to use
- Uppercase
- Lowercase
- Digits
- Special chars

Like this
https://www.randomcodegenerator.com/en/generate-codes

**Comment by tobias-kuendig** [comment]
Automatic generation was added in c68c7d1. The other options won't be added for the time being since Dicsounts will be reworked some time in the future anyways.
