### ISSUE TITLE
Visiting the page checkout payment method logouts the user

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#310]
I am using a plugin to offer the possibility to login with FB.
the plugin creates a Rainlab user from the FB accout. No issue here.
and it login the user.

After adding items to the cart, I go to the checkout page and place the order. Reaching the page payment method at that stage logs out the user. I also noticed that the payment methods are not listed, as they should be, I have 2 methods.

Any idea around what could be the problem?
Just starting to investigate what could happen here.

**Comment by tobias-kuendig** [comment]
Were you able to find the issue here?

**Comment by chrisvidal** [comment]
yes, I think so but I can't remember :)
we can close
