### ISSUE TITLE
Total amount in the backend show wrong total amount (on order overview scoreboard)

### ISSUE THREAD

**Issue by faselunare** [OFFLINE-GmbH/oc-mall-plugin#317]
I have a user that didn't complete the order (or the order failed)
then he make another order and it was fine.

The result is an order in the list that failed and wrong total amount (because the total is the sum of all orders event the one that filed.

**Comment by tobias-kuendig** [comment]
> The result is an order in the list that failed

In the backend?

> wrong total amount

Is it a completely wrong amount that does not match the products listed below?

**Comment by faselunare** [comment]
the TOTAL AMOUNT at the top of the ORDERS page (/backend/offline/mall/orders), sum all the orders even those whose payment has not been successful or have been canceled

**Comment by tobias-kuendig** [comment]
Alright, thanks for clearing things up. Now I now what you mean and can implement a fix for that. :+1:

**Comment by tobias-kuendig** [comment]
This is fixed in 3e56c8c, thanks @faselunare!
