### ISSUE TITLE
Add digital download

### ISSUE THREAD

**Issue by faselunare** [OFFLINE-GmbH/oc-mall-plugin#318]
Add digital download for tickets (event tickets)
with a (customizable) pdf in confirmation email to print and show at the event to exchange with real tickets

**Comment by tobias-kuendig** [comment]
Thank you for the suggestion!

I'm closing this since there is already PR #316 and https://github.com/OFFLINE-GmbH/oc-mall-plugin/projects/2 that track this feature.
