### ISSUE TITLE
Additional services modal

### ISSUE THREAD

**Issue by alxy** [OFFLINE-GmbH/oc-mall-plugin#321]
I just tested out the new additional services feature on the demo theme. If I just hit add to cart on [this page](https://mall.offline.swiss/en/product/cruiser-1000/g3dxMq6L), everything works as expected (A modal opens with the available services). However, if I select the "Include bike assembyl guide" checkbox, the modal content opens in a raw form within an error modal popup.

**Comment by tobias-kuendig** [comment]
Good catch! I'll release af ix for this tomorrow.

**Comment by tobias-kuendig** [comment]
This is fixed in b43a97d and will be released later today.
