### ISSUE TITLE
Error thrown on product varaints

### ISSUE THREAD

**Issue by StanleyBonhomme** [OFFLINE-GmbH/oc-mall-plugin#322]
After updating I continue to get this error when i click on a product that has variants. I can't figure out why anyone have an idea how i can resolve this error

![image](https://user-images.githubusercontent.com/30869347/64638093-20997980-d3d3-11e9-88f1-a691435847d3.png)

**Comment by tobias-kuendig** [comment]
Does this fix work for you? a557438

**Comment by StanleyBonhomme** [comment]
@tobias-kuendig Yes this does fix the issue not it is working again. Thanks. Anyway this fix can be committed to the main repo?

**Comment by tobias-kuendig** [comment]
Just keep your installation patched manually, this change will be available with the next update (probably released by tomorrow).

Thank you for the bug report, @StanleyBonhomme!

**Comment by StanleyBonhomme** [comment]
@tobias-kuendig Ok thanks for your help!

**Comment by StanleyBonhomme** [comment]
@tobias-kuendig Ok Thanks for your help
