### ISSUE TITLE
Page Not Found when redirectOnPropertyChange is used

### ISSUE THREAD

**Issue by gpluess** [OFFLINE-GmbH/oc-mall-plugin#323]
I just discovered that the redirect (triggered by the select box) is no longer working when `redirectOnPropertyChange = 1` is set on the product page.

Instead of a hash, there is the variant ID (?) in the URL. For example:

`/en/product/cruiser-1000/1`
instead of
`/en/product/cruiser-1000/DZ15j43Q`

I just verified this using a clean install of OctoberCMS and the Mall plugin using the Demo theme with demo data.

Are you able to reproduce this?

**Comment by tobias-kuendig** [comment]
Thank you for this bug report, @gpluess. 

This is fixed in 78b60c1 and will be released later today with an official update.

**Comment by gpluess** [comment]
Thanks for the fix! And thanks a lot for making this great plugin free and open source!
