### ISSUE TITLE
New European payments law PSD2 - Stripe 

### ISSUE THREAD

**Issue by haralake** [OFFLINE-GmbH/oc-mall-plugin#326]
Hello! 

Will this new law affect the operation of our store? Do you need to upgrade stripe payments to support PSD2?

https://stripe.com/en-se/connect/eu-guide

Thank you

**Comment by tobias-kuendig** [comment]
No idea! As a swiss company we are in the grey area regarding EU regulations (we currently do not do international business). 

We will definitely have to look into this. If in the meantime someone with more experience regarding the PSD2 regulations and Stripe Elements reads this issue feel free to post.

**Comment by tobias-kuendig** [comment]
We are using Stripe's new API for a while now which should take care of PSD2 regulations.
