### ISSUE TITLE
"Missing BC Math or GMP extension" on product view

### ISSUE THREAD

**Issue by haralake** [OFFLINE-GmbH/oc-mall-plugin#331]
On clean octobercms install to local environment i get this error on product view. I'm using mall demo theme and when i click on product , product page opens and then i get this message:

"An exception has been thrown during the rendering of a template ("Missing BC Math or GMP extension.") in ".../plugins/offline/mall/components/wishlistbutton/item.htm" at line 11." on line 421 of .../vendor/twig/twig/src/Template.php

This message came from components/product/scripts.htm

**Comment by tobias-kuendig** [comment]
As the message says, your php installation is missing the bc math extension required by Laravel.

Run

> sudo apt install php7.3-bcmath

or whatever your system's equivalent is.
