### ISSUE TITLE
Change calculation in totalPostTaxes

### ISSUE THREAD

**Issue by itplusvn** [OFFLINE-GmbH/oc-mall-plugin#332]
Please help me the following problem

Currently I want to adjust the calculation in totalPostTaxes.

TotalsCalculator.php file: 

> protected function calculateProductPreTaxes(): float
{
    $total = $this->input->products->sum('totalPreTaxes');
    return $total > 0 ? $total : 0;
}

So which file can I edit?
Why does it understand 'totalPreTaxes' ?

**Comment by tobias-kuendig** [comment]
The totalPreTaxes value comes from here:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/traits/cart/CartItemPriceAccessors.php#L22

What are you trying to achieve, though? By editing these internal files you won't be able to update to newer versions of the plugin.

Make sure to extend or wrap the classes correctly.

**Comment by itplusvn** [comment]
@tobias-kuendig 
Thanks for your feedback,
Let me ask one more question:
In CartItemPriceAccessors.php # L22, then:
Why did the value of '$ this-> totalProductTaxes' be generated?

> public function getTotalPreTaxesAttribute(): float
    {
        return **$this->totalProductPreTaxes** + **$this->totalServicePreTaxes**;
    }

**Comment by tobias-kuendig** [comment]
These are all Laravel accessors:

https://laravel.com/docs/6.x/eloquent-mutators#accessors-and-mutators

**Comment by tobias-kuendig** [comment]
Reply if you need further assistance. I will close this issue for now.
