### ISSUE TITLE
Digital delivery and auto update shipment status

### ISSUE THREAD

**Issue by faselunare** [OFFLINE-GmbH/oc-mall-plugin#333]
Add a Digital Delivery method for digital content (files, tickets, code)
that automatically updates the shipment status in 'sent' after sending a confirmation email to the customer but ONLY if the payment is with PayPal or with other ONLINE platforms and ONLY if it has been successful. NOT valid for OFFLINE payments.

**Comment by pvullioud** [comment]
Looks in progress here https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/316

**Comment by tobias-kuendig** [comment]
This feature is now available in v1.7.0.

https://offline-gmbh.github.io/oc-mall-plugin/changelog/1.7.0.html

https://mall.offline.swiss/en/category/gift-cards
