### ISSUE TITLE
Customize product fields

### ISSUE THREAD

**Issue by Zmove** [OFFLINE-GmbH/oc-mall-plugin#340]
Hello,

Would it be possible to add a feature that would allow developpers to customize fields that appears in the product backend ?

I mean something quite simple, maybe add an option in settings that allow to load a different filename than fields.yaml for product form (and why not the same option for columns.yaml).

Like that we could copy it and hide fields we don't need, without resetting changes on each updates.

What do you think about it ?

**Comment by amdad** [comment]
Hi, look here: https://octobercms.com/docs/plugin/extending

**Comment by tobias-kuendig** [comment]
Yes, as @amdad pointed out, this is a feature that October already provides. There is no need for this to be implemented in the plugin.
