### ISSUE TITLE
How to implement Payment by Redirecting to bank with required info

### ISSUE THREAD

**Issue by shahnawab** [OFFLINE-GmbH/oc-mall-plugin#342]
Thank you for such a great plugin and keeping it free.
I dont know if its an issue or require a new feature to be developed.

We are implementing the CCAvenue Indian Payment Gateway (PG) and have stuck with a point, where we need to redirect to their website with 
1. Customer Personal Info
2. Order Details - Amount, Currency
3. API Keys
4. URLs - Payment Success, Payment Cancel

We have created a Custom Payment Provider class. 

But I am not getting which Page/Function we will use to send all above details and while on return process the Status from response.

Please help.

**Comment by tobias-kuendig** [comment]
Take a look at the PayPal Rest provider. It redirects to paypal here:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/payments/PayPalRest.php#L68

Return is handled here:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/payments/PayPalRest.php#L78

The only think you have to care about is to set your class as callback like this, Mall will take care of the rest.
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/payments/PayPalRest.php#L78

**Comment by shahnawab** [comment]
I was looking at that.

A bit confused about this code:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/d688138b224686340593922ffbef534936aa82db/classes/payments/PayPalRest.php#L55

What its is doing?

**Comment by tobias-kuendig** [comment]
This is just Omnipay's api to send a http request:
https://omnipay.thephpleague.com/

Maybe there is a Omnipay library for your provider as well? If not use Guzzle to create and send a request.

**Comment by shahnawab** [comment]
Still not able to resolve.

Actually what I am looking is:
1. On my website User is shown with Order Details
2. Click Submit Button to go to the Payment Processor Website with POST Data having Order Details, Customer Details and URLs info (Return URL on Success, or Cancel URL)
3. And back on Website process the Info sent back by Payment Processor

I am unable to figure out where to write code for redirecting user to Payment Gateway Website.

Please suggest how to do it.

**Comment by tobias-kuendig** [comment]
Googling around for five minutes I found next to nothing about CCAvenue's payment gateway API. No docs and no usable php libraries. 

I really can't help you in this case since I'm not familier with that provider.

**Comment by shahnawab** [comment]
Here is link to their integration guide:
https://jemds.com/data_pdf/1_CCAvenue%20Integration%20-%20Ver%202.0.pdf

**Comment by shahnawab** [comment]
And its nothing related to CCAvenue. I am not getting how to redirect to the CCAvenue with Post parameters and on return how to process the return data.

**Comment by tobias-kuendig** [comment]
It looks like CCAvenue requires a POST request to a URL that then takes over the payment flow. This is not ideal since this kind of redirect + POST requests essentially require a standard HTML form to be submitted.

To do this using mall you can try this:

1. Create a custom plugin [that registers a new route](https://octobercms.com/docs/plugin/registration#routing-initialization) in its route.php file like `/your-custom/ccavenue/route`
2. From that route, return the required HTML form as specified in the CCAvenue documentation, add a `<script> document.getElementById("myForm").submit(); </script>` to the page that immediately submits the form when the page is visited.
3. Use the code below in your PaymentProvider class. Here all required data is stored in the session, then the user is redirected to your HTML form. Use the session data to populate the form. The form is submitted and the user is redirected to CCAvenue. Once this process is done, the user will be redirected back to your store and the `complete` method is triggered automatically.

```php


use OFFLINE\Mall\Models\PaymentGatewaySettings;
use Omnipay\Omnipay;
use Request;
use Session;
use Throwable;
use Validator;

class CCAvenue extends PaymentProvider
{
    /**
     * {@inheritdoc}
     */
    public function name(): string
    {
        return 'CCAvenue';
    }

    /**
     * {@inheritdoc}
     */
    public function identifier(): string
    {
        return 'ccavenue';
    }

    /**
     * {@inheritdoc}
     */
    public function validate(): bool
    {
        return true;
    }

    public function process(PaymentResult $result): PaymentResult
    {
		// $settingValue = PaymentGatewaySettings::get('whatever_you_need');

        $url = 'https://test.ccavenue.com/transaction/transaction.do';
		$data = [
            'merchant_id' => '1234',
            // Whatever else is needed as per the CCavenue docs...
            'amount'       => $this->order->total_in_currency,
            'currency'     => $this->order->currency['code'],
            'redirect_url' => $this->returnUrl(),
            'cancel_url'   => $this->cancelUrl(),
        ];
		
        Session::put('mall.payment.callback', self::class);
        Session::put('mall.ccavenue.data', $data);

        // Redirect to a page that contains only the required CCavenue form. 
        // Submit that form immediately via JS when the user visits the page.
        // You can use the data from Session::get('mall.ccavenue.data') to 
        // populate the form fields.
        return $result->redirect(url()->to('/your-custom/ccavenue/route'));
    }

    /**
     * The request returned.
     *
     * @param PaymentResult $result
     *
     * @return PaymentResult
     */
    public function complete(PaymentResult $result): PaymentResult
    {
        $data = Request::all();

        // Do some error checking here!
        // if ($data['x'] == 'y') {
        //     return $result->fail([
        //         'msg'   => 'Error',
        //         'data'   => $data,
        //     ], null);
        // }

        // Everything is good.
        return $result->success($data, 'All good!');
    }


    /**
     * {@inheritdoc}
     */
    public function settings(): array
    {
        return [
            'whatever_you_need' => [
                'label'   => 'label',
                'comment' => 'comment',
                'span'    => 'left',
                'type'    => 'switch',
            ],
        ];
    }
}
```

**Comment by shahnawab** [comment]
Thank you so much for your response, I think it will help in completing
this implementation.

Only one query:

'redirect_url' => $this->returnUrl(),
'cancel_url'   => $this->cancelUrl(),


Where are these urls defined?

**Comment by tobias-kuendig** [comment]
On the parent class:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/593fe7149fb4b75383d1f94446142f4a058928de/classes/payments/PaymentProvider.php#L165

**Comment by tobias-kuendig** [comment]
Are you still working on this? You can checkout the [postfinance](https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/422) branch where we added support for POST requests to external payment providers. You might have better support now for ccavenue.

I'm closing this issue as I did not hear back from you. If you still need further assistance please feel free to reply.
