### ISSUE TITLE
Additional custom informations for virtual products

### ISSUE THREAD

**Issue by faselunare** [OFFLINE-GmbH/oc-mall-plugin#343]
In the case of a user who, for example, purchases a ticket for an event for himself and for 3 other people, it would be useful to be able to insert for each ticket the name of the associated person (in a mandatory way).

In this way, when they arrive at the event they will have their name on a list and they will not necessarily have to come all together.

In addition, the nominative ticket is an anti-scalper guarantee.
And it is useful information to generate tickets in pdf with all the data.

It would also be useful to enter the email address together with the name to send a confirmation and the digital download ... but maybe there are GDPR problems because the email address come from a third party ...

Then you should send an email to the ticket owner with a confirmation request to process the data and then subsequently deliver the virtual ticket.

**Comment by tobias-kuendig** [comment]
> it would be useful to be able to insert for each ticket the name of the associated person (in a mandatory way).

This should be doable using custom fields on the product.

> It would also be useful to enter the email address together with the name to send a confirmation and the digital download

You can disable the default email in the "notificaton settings" and handle all the email sending yourself using the event system.

We cannot handle every use-case with the plugin but using the event system you should be able to do much of it yourself.

**Comment by faselunare** [comment]
Thank you @tobias-kuendig!
however your answer helped me!
