### ISSUE TITLE
How to handle weight property

### ISSUE THREAD

**Issue by alxy** [OFFLINE-GmbH/oc-mall-plugin#35]
Currently, if the weight property is not set properly on a product, the checkout fails as the total cannot be computed correctly.

I see two options to solve this:
1.) Make the weight required
2.) Set a default value (0), as there might be products of no physical nature, that have no weight

Tell me which one you prefer (or what you think about it), and I will create a PR.

Side note: Maybe the weight property needs also to be propagated to the variants, as different variants might have different weights.

**Comment by tobias-kuendig** [comment]
I have added a new weight property to variants.

The checkout should not fail if no weight is specified. The weight is saved as `null` but should be converted to `0` while calculating the total.

Do you have any more specifics about the error?

**Comment by tobias-kuendig** [comment]
This has been tested with the latest version and everything seems to work as expected.

Null values are counted as 0g weight and go through checkout without any problems.

Thank you for reporting the issue!
