### ISSUE TITLE
Mail "Your downloads are ready" is sent for non-virtual goods.

### ISSUE THREAD

**Issue by igor-tv** [OFFLINE-GmbH/oc-mall-plugin#350]
If an order that does not contain virtual goods is marked on the backend as paid and completed, the buyer receives a letter “Your downloads are ready” in which there are no download links. Tested on the invoice payment method.

**Comment by tobias-kuendig** [comment]
Thank you for reporting this! This is fixed in 59b2b09 and will be released as a new version today.
