### ISSUE TITLE
Problems with the wish list after removing the product

### ISSUE THREAD

**Issue by igor-tv** [OFFLINE-GmbH/oc-mall-plugin#351]
If the manager removes the product from the catalog, the user will have problems if this product was on his wish list.
1) When switching to the card of any product, an error appears: 
`An exception has been thrown during the rendering of a template (" Trying to get property 'price_includes_tax' of non-object ") in" C: \ xampp \ htdocs \ october / plugins /offline/mall/components/wishlistbutton/list.htm "at line 5`
2) The user can no longer access his wish list page. The debugger returns: 
`
An exception has been thrown during the rendering of a template ("Trying to get property 'price_includes_tax' of non-object").
C: \ xampp \ htdocs \ october / plugins / offline / mall / components / wishlists / list.htm line 5
`

**Comment by tobias-kuendig** [comment]
Thank you very much for reporting this issue. This has been fixed in c9a397e.
