### ISSUE TITLE
List subcategories only for active parent category

### ISSUE THREAD

**Issue by bozsokidaniel** [OFFLINE-GmbH/oc-mall-plugin#352]
Hello!

I have created the categories and my question is how can I list only subcategories for that active parent category?

For example:
Parent category
    - Sub category 1
    - Sub category 2
    - Sub category 3

I know that I can list it with Static Pages plugin but there I can list all categories but this is not good solution in my case.

I have left sidebar with parent categories and when click on parent category the site need to load only that sub categories which are under active parent category.

I have tried to get this but I have only half solution, here is my code:

```
function onStart(){
         // Save the slug
	$this['slug'] = $this->param('slug');
        // List parent category id
        $this['categories'] = Category::where('slug', $this->param('slug'))->value('id');
        // List subcategories data only for that parent category
	$this['subcategories'] = Category::where('parent_id', $this['categories'])->get();
         // List subcategories id
	$this['subcategories_id'] = Category::where('parent_id', $this['categories'])->select('id')->get();
	// Try to get the image for subcategory but there is no path in the query result
        $this['subcategoriesImage'] = Db::table('system_files')
    ->join('offline_mall_categories', 'attachment_id', '=', 'offline_mall_categories.id')
    ->whereIn('attachment_id', $this['subcategories_id'])
    ->where('attachment_type', 'like', 'OFFLINE\\\\Mall\\\\Models\\\\Category')
    ->get();
	
	dd($this['subcategoriesImage']);
}
```
As you can see, I can list subcategories but I can't get the images for each subcategories. I have tried to find the solution with October "System\Models\Files" but something I do wrong.

Thanks for help in advance!

**Comment by tobias-kuendig** [comment]
You are doing too much yourself. Use Laravel's relationships to get what you need:

```php
==
function onStart()
{
    $this['category'] = Category::where('slug', $this->param('slug'))->first();
    $this['children'] = $this['category']->getChildren();
}
==
{% for child in children %}
    {{ child.image.path }}
{% endfor %}
```

**Comment by bozsokidaniel** [comment]
@tobias-kuendig Thanks for quick reply and help, it works!
