### ISSUE TITLE
Error translating wishlistbutton component

### ISSUE THREAD

**Issue by igor-tv** [OFFLINE-GmbH/oc-mall-plugin#354]
If you add the Russian language for the frontend (using the Translate RainLab plugin), then switch to Russian on the frontend and go to the product page, you get this error:

`"An exception has been thrown during the rendering of a template ("Unable to choose a translation for "One product|:count products" with locale "ru" for value "0". Double check that this translation has the correct plural options (e.g. "There is one apple|There are %count% apples").") in "C:\xampp\htdocs\october/plugins/offline/mall/components/wishlistbutton/item.htm" at line 19." on line 421 of C:\xampp\htdocs\october\vendor\twig\twig\src\Template.php`

By the way the `transchoice `filter is deprecated since Symfony 4.2 and will be removed in 5.0. I don't know if this is important for OctoberCMS or not.

**Comment by tobias-kuendig** [comment]
It looks like October is complaining since this translation string is missing:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/lang/en/frontend.php#L139

Do you think you can provide a PR that adds the missing russian translations for the `frontend.php`?

**Comment by igor-tv** [comment]
I did it (https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/356)

> Do you think you can provide a PR that adds the missing russian translations for the frontend.php?

**Comment by tobias-kuendig** [comment]
This is great, thank you very much!

**Comment by igor-tv** [comment]
You are welcome!
