### ISSUE TITLE
orders reverse list feature request

### ISSUE THREAD

**Issue by papppeter** [OFFLINE-GmbH/oc-mall-plugin#366]
Hi Tobias,

we are using your cart system as a booking page. So basically we have events, where you can buy tickets. I added some small features to achieve this. Check my for if you are interested: https://github.com/papppeter/oc-mall-plugin (telephone with validation, datetime, time properties, order by a property)

but now i need to list all my active variants, and get back all the orders to it where people buyed that variant. So basically i can see an event with all the participants in it.

Do you have any suggestion where to start? or maybe it would be a good feature for all, which you could develop more easily than me. This is basically an analytics feature.

**Comment by tobias-kuendig** [comment]
A simple whereHas query wouldn't be enough in this case?

```php
OFFLINE\Mall\Models\Variant::whereHas('order_products')->with('order_products.order')->get();
```

(make sure to include these changes: 062fb9c)

**Comment by papppeter** [comment]
Hi, thanks for the help, i will try to solve it.

**Comment by tobias-kuendig** [comment]
Feel free to reply to this issue if you have any further questions.
