### ISSUE TITLE
Error during OctoberCMS installation using Project ID with Offline.Mall plugin

### ISSUE THREAD

**Issue by igor-tv** [OFFLINE-GmbH/oc-mall-plugin#371]
I create a new account at https://octobercms.com/, create a new project in which I add the Mall by OFFLINE plugin and the Mall Demo Theme by OFFLINE, then I install octobercms and use my Project ID in installation settings. 
<img width="1212" alt="Снимок экрана 2019-11-09 в 18 41 29" src="https://user-images.githubusercontent.com/6777469/68531455-471c5800-0323-11ea-9905-dfdf8c5b86d8.png">
I get an error during the installation process:
`"Class 'RainLab\Location\Models\Country' not found" on line 27 of /Applications/MAMP/htdocs/shop/plugins/offline/mall/classes/registration/BootExtensions.php`

<img width="1177" alt="Снимок экрана 2019-11-09 в 18 44 26" src="https://user-images.githubusercontent.com/6777469/68531388-dffea380-0322-11ea-8185-39bfca38557d.png">

It seems that with this installation method, your plugin does not install the necessary dependencies. If you first install octobercms, and then bind Project ID in the updates and update the plugins, this does not happen.

**Comment by tobias-kuendig** [comment]
AFAIK there is no way for a plugin to install a required plugin. You have to add the RainLab.Location and RainLab.User plugins to your project as well. There are hard required dependencies: 
https://offline-gmbh.github.io/oc-mall-plugin/getting-started/installation.html#installation

**Comment by tobias-kuendig** [comment]
Feel free to reply if you need any further support.
