### ISSUE TITLE
Delivery notes?

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#372]
Is it possible to leave some sort of delivery notes during the checkout?

**Comment by tobias-kuendig** [comment]
Currently not out-of-the-box. You might be able to achieve this by adding a textarea to this partial (or any other partial on the checkout component):
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/checkout/confirminfo.htm

Then you can hook into the [`mall.order.created`](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/models/Order.php#L214) event and update it accordingly. (`$order->your_custom_note_colum = input('note')`)

**Comment by chrisvidal** [comment]
thanks Tobias,
I came out with the same idea indeed.
I noticed there is a 'customer_notes' and 'admin_notes' column in the 'orders' table.
can I use them?

**Comment by tobias-kuendig** [comment]
Looks like I had that feature already in mind :grin: 

Yes, you can use them, that's what they are intended for. Just watch out for when this feature is officialy implemented, you might need to change your version of it.

**Comment by chrisvidal** [comment]
hehe it looks like it :)

I implemented it, it works fine, just that the location of this delivery notes textarea is quite tricky to place haha

**Comment by RobertCh2** [comment]
I would like to ask for little explanation of the topic. The »textarea« should be a form? How the »hook« on  mall.order.created event should look? Where to put the code?

**Comment by tobias-kuendig** [comment]
In this partial, you can add whatever form fields you want: 
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/checkout/confirminfo.htm

```html
<textarea name="notes"></textarea>
```

You then can register an event listener in a custom Plugin's boot method (or even in the code section of the checkout page) and register some action that needs to be done, once the order is created:

```php

\Event::listen('mall.order.afterCreate', function($order, $cart) {
    // Fetch the `notes` from the request and store it with the order.
    $order->customer_notes = input('notes');
    $order->save();
});

**Comment by RobertCh2** [comment]
I cannot make it to work, I am stuck.
My confirminfo.htm file is exactly only this:
`<form>
	<textarea name="notes"></textarea>
</form>`
And php part of my checkout.htm page is:
`<?php
function onStart()
{    
    // test if notes field is passed
    echo(input('notes'));
    \Event::listen('mall.order.afterCreate', function($order, $cart) {
            // test if mall.order.afterCreate is fired
            echo ('!');
            // Fetch the `notes` from the request and store it with the order.
            $order->customer_notes = input('notes');
            $order->save();
        });
}
?>`
Any of echo testing points is showing output.
What I am missing / what is wrong?

**Comment by tobias-kuendig** [comment]
> Any of echo testing points is showing output.

Are all visible or none? Also, it is better to use the `info('xyz')`  function to log to the `system.log` file since echo statements in wrong places might interfere with the HTTP response.

If this does not work, try to register the event in a plugin's boot method.

**Comment by chrisvidal** [comment]
I am trying to display this `customer_notes` in the order in the backend, I was planning to extend the form controller of the Orders controller, but it does not use any form controller :) but a custom `show` method.
How could we display this customer_notes in the backend? any idea?

**Comment by chrisvidal** [comment]
@RobertCh2 

create a file `init.php` at the root of your plugin with this code and that's it:

```php
<?php

namespace auther\plugin;

use Event;

Event::listen('mall.order.created', function($order) {
    $order->customer_notes = post('customer_notes');
    $order->save();
});

```

**Comment by tobias-kuendig** [comment]
>  How could we display this customer_notes in the backend? any idea?

We could add an event to the custom `show` method that allows you to specify custom fields to be rendered. Then use the event's returns to display a form somewhere one the page.

**Comment by chrisvidal** [comment]
> > How could we display this customer_notes in the backend? any idea?
> 
> We could add an event to the custom `show` method that allows you to specify custom fields to be rendered. Then use the event's returns to display a form somewhere one the page.

that would be cool indeed

**Comment by RobertCh2** [comment]
The method with init.php in plugin folder is working. It is catching the event of creating the order and writing in offline_mall_table. What I cannot still achieve is passing the variable from cornfirminfo.htm to event handler, nothing seems to work for me. What are the possible ideas there?

**Comment by tobias-kuendig** [comment]
Don't you see the data in your request? `dd(input())`?

**Comment by markandmedia** [comment]
I ran into the same problem and found a solution. Maybe this can help someone else. 
The "problem" is that the button to place the order makes a Ajax call to continue to the checkout and does not do a "post" with the data. But you can easily add the value from the customer_notes field to the Ajax call. 

My steps:
Use init.php as mentioned by @chrisvidal in your own plugin

Place the following code in confirminfo.htm (don't forget the ID if you use my solution) also no need for adding a form:
```html
<textarea id="customer_notes" name="customer_notes" class="form-control"></textarea>
```

Edit the partial "scripts.htm", add the line with "data" to the script. This adds the value from the field customer_notes to the call and makes it available for the Init event:

```javascript
on('click', '.js-mall-checkout', function (e) {
    e.preventDefault()
    $overlay.prependTo($body).show()
    $.request('{{ __SELF__ }}::onCheckout', {
        data: {customer_notes: $("#customer_notes").val()}, // New line to add the value from customer_notes
        error: function (jqXHR) {
            $overlay.hide();
            if (jqXHR.status === 406) {
                var platform = data.hasOwnProperty('X_OCTOBER_ERROR_MESSAGE') ? 'OCTOBER' : 'WINTER'
                return this.options.handleValidationMessage(
                    jqXHR.responseJSON['X_' + platform + '_ERROR_MESSAGE'],
                    jqXHR.responseJSON['X_' + platform + '_ERROR_FIELDS']
                )
            }
            this.error(jqXHR)
            document.location.href = '{{ __SELF__.accountPage | page }}'
        },
        handleValidationMessage: function (message, fields) {
            alert("There was an error while processing your order: " + message)
            document.location.href = '{{ __SELF__.accountPage | page }}'
        }
    })
});
```

**Comment by chocolata** [comment]
Thanks @markandmedia - this was the solution to the issue. Much appreciated!
