### ISSUE TITLE
_field_dropdown.htm Not Found

### ISSUE THREAD

**Issue by Ta2Ta2** [OFFLINE-GmbH/oc-mall-plugin#380]
Hi,

I installed fresh copy with seeded demo. on my freshly installed 459. I have public folder enabled.

Whenever I open any product with a property of "dropdown" (like size,,,etc.), I receive below error:
Even after clearing cache, re-mirror the public folder - same issue.

`The partial 'modules/backend/widgets/form/partials/_field_dropdown.htm' is not found.`

`/var/www/html/test/modules/system/traits/ViewMaker.php line 91`

**Comment by tobias-kuendig** [comment]
Do you have a complete stack trace for the error from your system.log?

**Comment by Ta2Ta2** [comment]
[log.txt](https://github.com/OFFLINE-GmbH/oc-mall-plugin/files/3862392/log.txt)

**Comment by tobias-kuendig** [comment]
Does the file `modules/backend/widgets/form/partials/field_dropdown.htm` exist in your installation? Are you using symlinks to redirect a folder or something?

I cannot reproduce the issue locally and I'd be surprised if the dropdown property wouldn't have worked for the past few months.

**Comment by Ta2Ta2** [comment]
Good catch!

Actually inside my public folder `modules/backend/widgets/form/` there is no symlinks to `/partials/` directory. doesn't matter how many times I re-mirrored.

Now I manually created symlinks for the `/partials/` and all is ok for now.

**Comment by tobias-kuendig** [comment]
Great, glad this is working then! :+1:

**Comment by jeffreydevreede** [comment]
We actually also had this issue, the solution was indeed to create the symlink manually.
So I believe as long as you don't use a dedicated public folder it works without any issues, but if you do use a public folder you need to create the symlink yourself.

I am not sure if it is possible, but wouldn't it be a good idea to make this symlink automatically when running the october:mirror command? Not sure if we can extend this functionality though. @tobias-kuendig

**Comment by tobias-kuendig** [comment]
Thanks everyone, this has been fixed in 08e85a7
