### ISSUE TITLE
SEO for inactive variants

### ISSUE THREAD

**Issue by papppeter** [OFFLINE-GmbH/oc-mall-plugin#381]
Hi,

almost all our products have variants inside. There is a time frame how long they are online for selling.  If i am searching my site on google i got many "dead" links because a variant was crawled, but it is not online any more. 

1. Is there a way to redirect them to another variant if it could not be found? I know there is a redirect plugin, but i would like to be able to turn on of variant, and i think to push remove all the redirects would be overkill for this. So how can we do this in within the mall plugin?
2. If all the variants gets offline, it would be nice to have an not sellable product page, where the product still exist, tells now there is no variant to sell, but google is not leading us to a 404 page. (if product it self is inactive as well than of course 404 is ok) How can i solve this?

thanks for your answers.

**Comment by tobias-kuendig** [comment]
This is a very specific feature that the cms itself is responsible for, not the mall plugin.

You can easily solve the problem by adding a custom script section to your product page. 

This is untested code, but you should get something like this working:

```php
title = "product"

[product]
==
function onStart()
{
    // If no variant is present, redirect.
    if ( ! $this['product']->variant) {
        return redirect('/other-page', 302);
    }
}
==
{% component 'product' %}

**Comment by papppeter** [comment]
HI, thanks i will try it out.

**Comment by tobias-kuendig** [comment]
Feel free to reply to this issue if you have any further questions.
