### ISSUE TITLE
discount can produce negative totals

### ISSUE THREAD

**Issue by papppeter** [OFFLINE-GmbH/oc-mall-plugin#383]
Hi,

i have a question again. if we have a discount fixed amount 7000, my cart is 6000 total. then this will produce -1000. which i think is incorrect. total should never go below 0. we could add some hints that not all the coupon was used. Maybe mark the order itself or something.

my another question is if i have a discount which is equal with the total, than we should skip the payment part. this makes customers confused why they still need to pay trough paypal.

Or is there a solution which i did oversee?

thanks

**Comment by tobias-kuendig** [comment]
This was fixed in 376538b, thanks @papppeter
