### ISSUE TITLE
Prices are stored in the cart

### ISSUE THREAD

**Issue by rubenvanerk** [OFFLINE-GmbH/oc-mall-plugin#388]
I just discovered that prices are stored in the cart. If someone has a product in their cart and I change price in the backend, the cart totals don't change. This is not desired behavior for us. 

Is this intended or is this a big? Or is there a setting to control this?

**Comment by tobias-kuendig** [comment]
This is done on purpose. Once the product is added to a cart, no changes to the original product will affect it. 

You can hook into the Product's afterSave model event and update all the connected CartProducts yourself.

**Comment by tobias-kuendig** [comment]
If you only require the latest prices before checking out, you could also use the [`mall.order.beforeCreate`](https://offline-gmbh.github.io/oc-mall-plugin/development/events.html#order) event to update the cart.

**Comment by rubenvanerk** [comment]
@tobias-kuendig would it be okay if we would add an option in the settings to always use price from the product? We were thinking of adding a check here: https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/f5109e9d1ef722957084034f40988d3a535b8cbf/classes/traits/JsonPrice.php#L95

**Comment by tobias-kuendig** [comment]
Sure, just make sure that it doesn't end in N+1 query problems! I'm not sure the price relation is always properly eager loaded on the cart model.
