### ISSUE TITLE
Add Offline payment

### ISSUE THREAD

**Issue by pvullioud** [OFFLINE-GmbH/oc-mall-plugin#39]
Like "Pay on Delivery", "Bank transfer"
This kind of payment need to display extra info on the bill and the email : 
- Bank info
- Address

Work in progress
https://github.com/OFFLINE-GmbH/oc-mall-plugin/compare/develop...inetis-ch:offline_pay?expand=1

**Comment by tobias-kuendig** [comment]
I guess this information should be added to the `PaymentMethod` model. Maybe via a repeater field?

This way I could create a Payment method `Pay on Delivery` with the new Offline gateway (maybe without additional fields). I could also add a method `Bank transfer` with the Offline gateway and enter info like `Bank info` etc.

**Comment by pvullioud** [comment]
Most of the time the description could have those info.
We could in a first time add a 2 checkbox below the description : 
- "Add the description in the email"
- "Add the description in the invoice"
And see later if we need something more flexible.

```html
<div class="mall-cart-summary__method-logo">
    {% if __SELF__.cart.payment_method.logo %}
        <img src="{{ __SELF__.cart.payment_method.logo.thumb(150, 'auto') }}" alt=""/>
    {% else %}
        {{ __SELF__.cart.payment_method.name }}
    {% endif %}
    
    {% if __SELF__.cart.payment_method.show_description %}
        {{ __SELF__.cart.payment_method.description | raw}}
    {% endif %}
</div>
```

PS: not happy with the name "show_description", but you got the idea

**Comment by tobias-kuendig** [comment]
It is true that the `description` field could be used for that. Maybe a comment like `Enter any further information or payment instructions here` would clear things up a bit. Or even changing the label to `Description and payment instructions` altogether.

I'm not sure we need the checkboxes though. What if (for whatever reason) a user has some other outputs than email and invoice? What about a unique `code` field (via the Sluggable trait) than can be queried in the email template/partial?

```twig
<div class="mall-cart-summary__method-logo">
    {% if __SELF__.cart.payment_method.logo %}
        <img src="{{ __SELF__.cart.payment_method.logo.thumb(150, 'auto') }}" alt=""/>
    {% else %}
        {{ __SELF__.cart.payment_method.name }}
    {% endif %}
    
    {% if __SELF__.cart.payment_method.code == "bank" %}
        {{ __SELF__.cart.payment_method.description | raw}}
    {% endif %}
</div>
```

**Comment by pvullioud** [comment]
`Description and payment instructions` 👍 

I don't understand the idea behind the unique code field. Could you explain it?

No all description need to be on other document. Exemple :
"Pay by credit card": "We Accept Visa and Mastercard" -> only on the screen to choose the payment methode
"Bank transfer": "Our IBAN is xxxxxxxxxxx" -> need to be on other communication

**Comment by tobias-kuendig** [comment]
Let's say I have to following two payment methods:

| Method        | Code        |
|---------------|-------------|
| Credit Card   | credit-card |
| Invoice       | invoice     |
| Bank transfer | bank        |

This way I can use `payment_method.code` in all partials to check whether or not to display the description. This is a decision the developer makes when implementing the shop plugin. This feature can be used in frontend partials, email partials or even in something like Telegram/Whatsapp notifications.

```twig
{# Invoice partial, only show description for bank #}
{% if payment_method.code == "bank" %}
    {{ payment_method.description | raw}}
{% endif %}


{# Cart partial, only show description for credit-card #}
{% if payment_method.code == "credit-card" %}
    {{ payment_method.description | raw}}
{% endif %}
```

The implementation of the `code` field can be done via the `Sluggable` trait:

```php
<?php namespace OFFLINE\Mall\Models;

class PaymentMethod extends Model
{
    use Sluggable;

    public $slugs = [
        'code' => 'name',
    ];
```
