### ISSUE TITLE
Make it possible to configure the required fields for user registration

### ISSUE THREAD

**Issue by igor-tv** [OFFLINE-GmbH/oc-mall-plugin#390]
If a user buys a digital product or just wants to register on the site without a purchase, he has to fill in his address. It would be great if it were possible to configure the required registration fields in the plugin settings.

**Comment by igorpank** [comment]
> 
> 
> If a user buys a digital product or just wants to register on the site without a purchase, he has to fill in his address. It would be great if it were possible to configure the required registration fields in the plugin settings.

Это реальный минингит. Покупатель не хочет заполнять кучу полей при регистрации. Мне пришлось закомментировать исходный код и добавить форму при оформлении заказа

**Comment by chrisvidal** [comment]
you can override the `DefaultSignup' class with your own, and then decide of the validation process. check the doc. for the overriding of the class, it is well explained

**Comment by igor-tv** [comment]
> you can override the `DefaultSignup' class with your own, and then decide of the validation process. check the doc. for the overriding of the class, it is well explained

Thanks, I already did. But I think this functionality is better to make the plugin settings.

**Comment by tobias-kuendig** [comment]
Closing this in favour of #172
