### ISSUE TITLE
Search for accessories in product. DONE

### ISSUE THREAD

**Issue by m49n** [OFFLINE-GmbH/oc-mall-plugin#393]
For example we have 1k+ pruducts and it becomes difficult to find the right products.
May be add search field in this relation ?
![image](https://user-images.githubusercontent.com/15114737/70078408-af551580-1613-11ea-96bd-040cf2ec0e5d.png)

**Comment by tobias-kuendig** [comment]
Definitely! Good point! :+1:

**Comment by m49n** [comment]
> Definitely! Good point! 👍
Hi, just enough to add "showSearch: true" to 
/controllers/products/config_relation.yaml here 
![image](https://user-images.githubusercontent.com/15114737/70148226-d0227700-16b6-11ea-9f6c-d9f3fde285b0.png)

**Comment by tobias-kuendig** [comment]
This was added a while back, thank you for the input!
