### ISSUE TITLE
Sorting by price does not work

### ISSUE THREAD

**Issue by igorpank** [OFFLINE-GmbH/oc-mall-plugin#396]
Sorting by price does not work!
Can you help solve this problem?
MySQL  5.7.28
PHP 7.1.33
![bug](https://user-images.githubusercontent.com/34834916/70470788-81b91200-1ad4-11ea-89c5-cb88d2298a93.jpg)

**Comment by tobias-kuendig** [comment]
Can you try to run the displayed query directly on your database but change the `ORDER BY` part to:

> ORDER BY JSON_EXTRACT(prices, $."EUR") ASC

**Comment by igorpank** [comment]
only this query is executed without errors (correct syntax):
select `variant_id` as `id`, `product_id` as `other_id`, `is_ghost` from `offline_mall_index` where `index` = 'variants' and `published` = 1 and (JSON_CONTAINS(category_id, '[53]') or JSON_CONTAINS(category_id, '[55]') or JSON_CONTAINS(category_id, '[54]') or JSON_CONTAINS(category_id, '[67]')) order by JSON_EXTRACT(prices, '$."EUR"') desc

**Comment by tobias-kuendig** [comment]
Thank you! This bug has been fixed in 77de78b and is released as v1.8.3 to the marketplace.
