### ISSUE TITLE
Virtual products Variants

### ISSUE THREAD

**Issue by error-maker** [OFFLINE-GmbH/oc-mall-plugin#400]
Hello, I am trying to use your plugin for a music selling website. When adding a product to the shopping cart, it should be possible to select a license. Total cost will be equal to the cost of the selected license.  What features of the plugin should I use? I wanted to do this through Variants, but the Virtual products disabled Variants. I'm trying to set a product price $0.00, and adding a required selection of services from which I made licenses. It's the right way?

**Comment by tobias-kuendig** [comment]
You can use [Custom Fields](https://offline-gmbh.github.io/oc-mall-plugin/development/product-model.html#custom-fields) or [Services](https://offline-gmbh.github.io/oc-mall-plugin/digging-deeper/services.html) to achieve this. Both features can be found on the "Cart" tab on the Product form. Custom fields as well as services add additional cost to a product when it is added to the cart.

**Comment by error-maker** [comment]
Thanks, you helped me a lot.
