### ISSUE TITLE
Shipping Methods conditions

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#402]
Could we add easily, on top of the country, the state in the shipping conditions tab?

**Comment by tobias-kuendig** [comment]
I'm closing this as duplicate of https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/364

It's as "easy" as adding another relationship to the conditions model and checking it in the totals calculator class.

I would have to look into it myself to give you a proper answer. PRs welcome!
