### ISSUE TITLE
Get active menu item

### ISSUE THREAD

**Issue by igorpank** [OFFLINE-GmbH/oc-mall-plugin#409]
Is any possibility to get or set active menu item from product page?
Thanks

**Comment by tobias-kuendig** [comment]
This is more of a `RainLab.Pages` question, if you are talking about that plugin.

See their official documentation: https://octobercms.com/plugin/rainlab-pages (see "Setting the active menu item explicitly")

```php
function onInit()
{
    $this['activeMenuItem'] = 'blog';
}
```

**Comment by tobias-kuendig** [comment]
Feel free to reply to this issue if you have any further questions.
