### ISSUE TITLE
Adding payment method : Can't have several encrypted fields ?

### ISSUE THREAD

**Issue by Zmove** [OFFLINE-GmbH/oc-mall-plugin#412]
Hello,

I'm writing a custom payment method for mall. (PostFinance, you may be interested as in Switzerland).

I have several fields I want to see encrypted : pspid, sha_in, sha_out.

So, wrote the encryptedSettings() method like that : 

    public function encryptedSettings(): array
       {
            return ['pspid', 'sha_in', 'sha_out'];
       }

If I only put pspid, it seems to work, but as soon as I add more fields, I get the following error when I go to Settings > Payment gateways, I get the following error : 

> "The payload is invalid." on line 191 of /vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php

Did I miss something ?

**Comment by tobias-kuendig** [comment]
Make sure your field values are empty (remove all plugin settings). It looks like the framework is trying to decrypt an already existing (unecrypted) value.

**Comment by Zmove** [comment]
Hello,

Wow, what a fast answer. Yes, I added encryption after adding some values to fields, cleaning them solved it. Thank you !
