### ISSUE TITLE
Don't empty user cart if order fail

### ISSUE THREAD

**Issue by Zmove** [OFFLINE-GmbH/oc-mall-plugin#413]
Hello,

I noticed that when an order fail, the user cart is emptied. Would it be possible to keep the cart active ? It sounds more logical to me to empty the cart only if the order is a success.

Best regards,

Alex

**Comment by tobias-kuendig** [comment]
The order should be created even if the payment fails. In fact, it is created before the payment is even initiated. If the payment flow exits without any fatal errors you should end up with a complete paid order. 

Did you have a situation where the order vanished?

**Comment by Zmove** [comment]
Nothing related to your code. I'm developping a new payment gateway so I'm actually redirected to the checkout/failed page quite often.

I didn't check where the cart is emptied when an order is complete (success or fail), but if the result of an order is a fail (for whatever reason), I think it would be better for the user to keep it's cart, to be able to try to checkout again without recomposing the whole cart.

**Comment by tobias-kuendig** [comment]
You don't have to re-create your cart. Since the order is created, you will be redirected to your "my account" page after a failed payment where you can re-try to pay for your order.

**Comment by Zmove** [comment]
Hi,

Ah ok, didn't know that. I heavily customized the display so I rewrote most of the components code in my own partials. I will look into your code to see how you generate the payment link to retry

**Comment by tobias-kuendig** [comment]
Please feel free to reply to this issue if you have any further questions.
