### ISSUE TITLE
fedex, EU Vat api integration?..

### ISSUE THREAD

**Issue by shiftaltd** [OFFLINE-GmbH/oc-mall-plugin#415]
Hi,

Thanks for this great work. 
I think to extend the plugin with third party api like the EU vat number checker api or the fedex api.
Is one already managed that? 
What's wiould be the best way ?

thanks

**Comment by tobias-kuendig** [comment]
I think the best solution for this would be to create a separate plugin that extends the Mall plugin. 

You can add events to the plugin if you need to extend something that currently cannot be extended.

**Comment by tobias-kuendig** [comment]
Please feel free to reply to this issue if you have any further questions.
