### ISSUE TITLE
How to display product property's and custom fields on product page one by one?

### ISSUE THREAD

**Issue by haralake** [OFFLINE-GmbH/oc-mall-plugin#426]
I'm trying to find a way to display product property's and custom fields on product page. Currently i'm using successfully this:
```
{{ product.variant.properties_description | raw }}
{{ product.custom_field_value_description | raw }}
```
But i need to display property's and custom fields one by one to be able to better customize them. How can i make this happen?

**Comment by tobias-kuendig** [comment]
Thank you for your feedback! Starting from `1.10.0` you can access property values like so:

```php
$productOrVariant->grouped_properties;

[
   [ 
    'group' => PropertyGroup::class,           // Group model
    'values' => Collection([PropertyValues])   // All values in this group
   ]
];
```

Does this help you in this case?

see https://offline-gmbh.github.io/oc-mall-plugin/development/product-model.html#grouped-values

**Comment by haralake** [comment]
Thank you for the suggestion. I try this code:
```
{% for entry in product.grouped_properties %}
    <h2>{{ entry.group.name }}</h2>
    {% for value in entry.values %}
        <strong>{{ value.property.name }}</strong><br>
        {{ value.display_value | raw }} {{ value.property.unit }}
    {% endfor %}
{% endfor %}
```
inside product component to be able to display properties but with no luck. Nothing is displayed in frontend. I guess something i'm missing.

**Comment by tobias-kuendig** [comment]
Use `item.grouped_properties` in the component. Also, if you have version 1.10 installed, you already have a working example in there:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/product/propertyvalues.htm

**Comment by haralake** [comment]
Yes you have right, i missed that! Thank you is working perfect now.
