### ISSUE TITLE
Stripe Payment Error when not using State

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#429]
if the settings are not using the State field or our country does not have State (my case), the Strip payment does not go through and raises an exception.

in file 'OFFLINE\Mall\Classes\Payments/Stripe.php` line 254

```php
                'state'       => $customer->shipping_address->state->name,
```

**Comment by tobias-kuendig** [comment]
Fixed in b034aa2, thanks!
