### ISSUE TITLE
Should product variants have a product id?

### ISSUE THREAD

**Issue by Fl0Cri** [OFFLINE-GmbH/oc-mall-plugin#43]
Currently a variant can have a stock, so I assume that it's a physical item in the inventory.

But variants doesn't have a product id (`user_defined_id`) like products.
IMO variants should also have a `user_defined_id` that would override the one of the parent product if provided, exactly like stock does.

If you're ok with this, I can do a PR.

**Comment by tobias-kuendig** [comment]
This sounds reasonable :+1:

**Comment by tobias-kuendig** [comment]
Closed by #44
