### ISSUE TITLE
Product translations no longer work since v1.9.x

### ISSUE THREAD

**Issue by gpluess** [OFFLINE-GmbH/oc-mall-plugin#431]
Not sure if I missed anything, but my translated products (names, descriptions, etc.) always fall back to the default language instead of displaying the correct language.

In the backend, I can add names and descriptions in all languages, save it and it's correctly updated in the DB. However, when I open the same product again, all translations are gone.

To verify my assumption I checked out a previous version (1.8) and all of a sudden all translation appear again (backend and in the shop).

Maybe this has something to do with the "Optimized loading of translated attributes" feature in release 1.9?

**Comment by tobias-kuendig** [comment]
Thank you for this report! This seems to be an issue with RainLab.Translate. You can track progress here:
https://github.com/rainlab/translate-plugin/issues/539

**Comment by tobias-kuendig** [comment]
This problem has been fixed upstream. Thank you for the report!
