### ISSUE TITLE
Display category list on home page

### ISSUE THREAD

**Issue by haralake** [OFFLINE-GmbH/oc-mall-plugin#436]
I'm trying to display category's with image, title and description on home page but i didn't find a way on documentation. Is there a way?

**Comment by tobias-kuendig** [comment]
You can simply query the model:

```php
Category::with('image')->getAll();
```

Either do this in the php section of a page or build a component that runs the query.

The Category model uses the [NestedTree Trait](https://octobercms.com/docs/database/traits#nested-tree) so you can use its method to query the category tree as you require.

Also, there is a pending PR you can take some inspiration from:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/389

**Comment by haralake** [comment]
This is very interesting component! I also try your function but i get error:
`An exception has been thrown during the rendering of a template ("Call to undefined method October\Rain\Database\QueryBuilder::getAll()")`

**Comment by chrisvidal** [comment]
```php
Category::with('image')->get();
```

will do

**Comment by haralake** [comment]
Is working now, thank you.
