### ISSUE TITLE
Would love a subscription/recurring model

### ISSUE THREAD

**Issue by Thomo120** [OFFLINE-GmbH/oc-mall-plugin#438]
After looking at other issues, I do understand the presure and the lack of time you may have, however, I would love to know if you are going to implement a subscription-based product type (users to pay monthly fees, etc) in the near future?

**Comment by tobias-kuendig** [comment]
This is not a high priority right now... until a paying customer requests it!

**Comment by chrisvidal** [comment]
@Thomo120  you can probably interconnect with Responsiv.Pay and Responsiv.Subscribe plugins

**Comment by tobias-kuendig** [comment]
Subscriptions are currently not in the scope of this plugin, this is why I close this issue.
