### ISSUE TITLE
Wishlist button on product items (products component)

### ISSUE THREAD

**Issue by haralake** [OFFLINE-GmbH/oc-mall-plugin#442]
I try to implement a wishlist button for every product item on products component. I use this code:

```
{% set items=wishlistButton.items %}
{% for wishlist in items %}
{% set list_id=wishlist.hash_id %}
{% set product_id=wishlistButton.property('product') %}
{% set variant_id=wishlistButton.property('variant') %}
<a href="javascript:;"
   class="mall-wishlist-item"
   data-request="onAdd"
   data-request-flash
   data-request-success="
    $.publish('mall.wishlist.productAdded', data);
    document.querySelector('.mall-wishlist-button__popup').classList.remove('mall-wishlist-button__popup--visible');
   "
   data-request-data="
         wishlist_id: '{{ list_id }}',
         product_id: '{{ item.productHashId }}',
         variant_id: '{{ item.variantHashId }}'
    ">
    Button
</a>
{% endfor %}
```

When i click on button i get flash message "product added" and the product successfully added το wishlist but i also get an error:
`Uncaught TypeError: Cannot read property 'classList' of null
`

The weird thing is that i get wishlist_id properly on my code page.

**Comment by tobias-kuendig** [comment]
The error comes from this code:

```
document.querySelector('.mall-wishlist-button__popup').classList.remove('mall-wishlist-button__popup--visible')
```

Do you have the `.mall-wishlist-button__popup` element somewhere on your page? Maybe it has a different class? Maybe you don't need this call?

**Comment by haralake** [comment]
You have right @tobias-kuendig. I missed that code, is unnecessary for me. Thank you.
