### ISSUE TITLE
Mass update of essential values

### ISSUE THREAD

**Issue by Zmove** [OFFLINE-GmbH/oc-mall-plugin#449]
Hello,

I'm developping a website for a business that regulary need to update prices and stock for large number of products.

It seems that this plugin don't actually propose this feature, I wonder what would be the best way to achieve this.

I use both type of products (with and without variants)

Best regards,

Alex

**Comment by tobias-kuendig** [comment]
I feel like mass updates is something October should provide in the future, and not be implemented by each plugin separately. 

That being said, nothing stops you from writing some custom UI to update the pricing information. You can simply change the `Price` models attached to each Product/Variant, there's nothing special about it.

There is the Datatable widget October provides that could help here, but it is poorly documented.

What is the specific use-case? Are the price updates like 10% off on the whole store or are we talking about very specific changes to certain products?

**Comment by Zmove** [comment]
Thank you for the feedback, I agree that it would be better to see mass model editing handled by october core itself to avoid to reinvent the wheel each time.

I suppose it will not for tomorrow, so I will work on a quick code to do what I need. Thank you
