### ISSUE TITLE
Search in accessories

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-mall-plugin#451]
Hello,

I have a large set of products and I heavily use the "accessories" tab to add related products to the current product page.

Actually, there is no search functionnality for this relation manager, which quickly become a nightmare to manage for shop owner.

I believe that the core relation manager provided by octobercms allow to add a search field just by adding an option, it would be great to activate it in a next commit to make our life easier.

Thank you ;)

**Comment by tobias-kuendig** [comment]
Thank you for this feedback! Added in 3386b7a, released as v1.11.5
