### ISSUE TITLE
Errors approving and creating feedback from the backend

### ISSUE THREAD

**Issue by igor-tv** [OFFLINE-GmbH/oc-mall-plugin#460]
If I get to approve a review from the product management section, I get an `AJAX handler 'onApprove' error was not found`.
<img width="1099" alt="Снимок экрана 2020-03-04 в 14 27 00" src="https://user-images.githubusercontent.com/6777469/75876830-7a7d7800-5e27-11ea-8775-488c2054753e.png">

If I try to create a review in the reviews section, I get the error `The product id field is required`.
<img width="1212" alt="Снимок экрана 2020-03-04 в 14 27 49" src="https://user-images.githubusercontent.com/6777469/75876848-8406e000-5e27-11ea-8784-968f810dd4c3.png">

CURRENT BUILD 464
Mall  1.11.6

**Comment by tobias-kuendig** [comment]
Thank you for this report! This bug has been fixed in 219d63a. I will release a new version tomorrow.

You can still edit the reviews from the "Reviews" submenu. This bug only occurs if you edit reviews from the Product form.

**Comment by igor-tv** [comment]
Maybe you should remove the +Crete button from the Reviews section. Since adding reviews in this view does not work. Or you need to expand the form and add a selection field for the product for which the review is intended.

Now it does not work.
<img width="557" alt="Снимок экрана 2020-03-06 в 18 39 33" src="https://user-images.githubusercontent.com/6777469/76098530-b3118300-5fda-11ea-8221-889d987a1534.png">

**Comment by tobias-kuendig** [comment]
This is a good point, thanks. Will fix this in a upcomming version.
