### ISSUE TITLE
Question: integration of shipping method "pick up at parcelshop"

### ISSUE THREAD

**Issue by maartenmachiels** [OFFLINE-GmbH/oc-mall-plugin#475]
Hi, I'm loving the Mall Plugin. It is very complete, and it does look like it's exactly what I've been looking for. In Belgium parcelshops are very popular. Users can select a parcelshop near them and the parcel would be delivered there instead of at their home address.

This would imply showing something like this [https://www.dpdwebparcel.be/en/ParcelShop#/parcelShopFinder/](url) embedded in a pop-up and saving the returned value into the order.

I'd just like to know the feasability of this. Could you let me know? Thanks!

**Comment by tobias-kuendig** [comment]
If they provide an API where you can select a shop and get an ID or something in return this is definitely possible. You can include any custom partial in the payment method selector and do whatever you want.

The Stripe payment method generates a token during checkout in the frontend. It is then sent along in the `payment_data` array ‒ you can do the same thing for your shop id:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/paymentmethodselector/gateways/stripe.htm#L8

All values in the `payment_data` array will then be accessible in your payment provider class as `$this->data`:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/payments/Stripe.php#L178

You can even validate it to prevent tinkering/errors:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/payments/Stripe.php#L45

**Comment by maartenmachiels** [comment]
Thank you very much, Tobias! I'll investigate this!
