### ISSUE TITLE
Problem with variant properties, displayed twice.

### ISSUE THREAD

**Issue by haralake** [OFFLINE-GmbH/oc-mall-plugin#477]
Seems that there is a bug on property display on variants. 
Steps:
1.Create a product and then change Inventory management method to article variants
2.Choose Attribute for variant grouping
3.Create variant product and fill properties
4.Save variant product

On frontend variant product page you will see that properties you choose for variant are saved twice. I also test it in mall demo site and i get the same issue. I guess the properties saved once when you first create the product, and then when you change Inventory management to article variants doesn't deleted. And the main problem is that there is no way to delete those properties.

**Comment by haralake** [comment]
This seems to only happen if you create a product as article and save it and then you decide to change it to article variants. The solution is to remove property group from category, open product and save it, and then re enable property groups on category.

**Comment by tobias-kuendig** [comment]
Thank you for this bug report! This issue has been fixed in 69fe679.
