### ISSUE TITLE
Improve speed for Category and CategoryFilter

### ISSUE THREAD

**Issue by pvullioud** [OFFLINE-GmbH/oc-mall-plugin#48]
It's the getProduct function that take too much time
<img src="https://monosnap.com/image/K5LDGuJCWQJvJ3EtUocxIWdgNoN6Y5.png">
on my test site with 180 products, it take 5s

31 queries take only 150ms

**Comment by pvullioud** [comment]
I guess this  is due to the intensive usage of `flatten` in `getProducts`

**Comment by tobias-kuendig** [comment]
Yes, this doesn't scale well. I'm on a refactor of all the queries the Category and CategoryFilter components use.

**Comment by pvullioud** [comment]
Thanks for the refactoring. Looks great so far.
We will test it with our large products DB and do some feedback

**Comment by tobias-kuendig** [comment]
You'll have to migrate you property_values table manually and enable "show_variants" in your category component. The query to display products only has not been refactored yet. This branch is highly work in progress.

**Comment by Fl0Cri** [comment]
Tried to pull branch `optimize-category-component` on our dev server but it has some JSON fields for the prices and JSON are only available from MySQL 5.7 or MariaDB 10.2

Unfortunately we have no server matching these requirements (the best we have is MySQL 5.6 or MariaDB 10.0).
For most project we use mutualized or managed servers, and it seems that next to all hosing providers have not deployed these versions yet (even for MySQL that is stable for 3 years now...)

Cloudways told a few month ago that MySQL 5.7 was now available, but they seems to have silently rolled back now.

From what I could see JSON fields are currently only used for pricing filtering. I don't know how much perfs it can give, but it would be nice to have the plugin compatible with older (at least MySQL 5.6) DBMS.

**Comment by tobias-kuendig** [comment]
I thought that it's a bit too early to require MySQL 5.7.

The json column is used to select a single currency out of the `price` column and filter by this value. I don't know of any other solution without json functionality that enables us to do this without having to fall back to in memory filtering in PHP.

Do you have any suggestions?

**Comment by Fl0Cri** [comment]
With the prices stored in json format, I'm almost sure there's no clean SQL way to do it. I've looked at `REGEX` but it seems to only be usable to match a patern, not to extract data (apparently there are more functionnalities in MySQL 8 but it would be worse than now ;) ).

I think the best we can do with the current table schema is to use Eloquent's `chunk()` and hope it will not fill all the available memory. And if we could query the prices separately (fetch only id and price, and bypass all Eloquent initializations and accessors) and then do the full query with only the products we want, we may have decent performances for medium/large datasets.

In an other fashion, maybe we could store prices in a separate table with multiple rows by product (one for each currency).
I don't realy know how polymorphic relations perform when looking at performances (does Eloquent realy use sql for this? - even if it was, it never uses joins so it would end up fetching a big set of EAV records).
Instead of using a polymorphic relation, maybe we could make some pivot tables between the products/variants and prices tables.

**Comment by pvullioud** [comment]
For the price, we could store it in the main currency only and have a currency exchange rate table. I'm not sure to understand in which situation multi currency prices are relevant.

**Comment by tobias-kuendig** [comment]
If you only store a rate you cannot set prices like 19.99 or 15.95 in different currencies. You'll end up with prices like 15.87 and 14.23.

**Comment by pvullioud** [comment]
For me, having the possibility to set a price per currency have more cons (performance, complexity, update) than pros.
We can imaging having it as an addon/plugin. The vast majority of the stores will not need it.

**Comment by tobias-kuendig** [comment]
I'm the whole month off for my civilian service so the plugin development will slow down a bit. 

I thought about a solution for all these problems and came up with the idea of a index/search service. This is how it is done in other ecommerce solutions.

We can have some kind of indexing service that listens for CRUD operations on products and variants. This service then can have multiple adapters. For a simple setup we can provide a MySQL adapter that denormalizes the whole catalog and stores it as an easy to query datastructure. For more complex setups we can then provide an ElasticSearch adapter that pushes all the updates into an ElasticSearch index. It would also be possible to provide adapters for hosted services like Algoia.

What are your thoughts on this?

**Comment by Fl0Cri** [comment]
Yes, in very large shops it could be great to be able to externalize the search workload.

This sounds a bit like [Laravel Scout](https://laravel.com/docs/5.6/scout) (I never used it in practice). It is based by default on Algolia and I don't know if it can be easily integrated with October, but maybe we can reuse a similar interface (and maybe simplify it).

**Comment by w20k** [comment]
Our you could skip Algolia, and use it with TNTSearch ([Tnt Scout Search for Laravel](https://github.com/teamtnt/laravel-scout-tntsearch-driver) or [TnTSearch](https://github.com/teamtnt/tntsearch) ).

**Comment by tobias-kuendig** [comment]
@w20k TnTSearch support is a must, good suggestion! I'm not an Algolia user myself but I guess if we add support for different search providers we should think about Algolia as well.

**Comment by w20k** [comment]
@tobias-kuendig I think if you work toward Laravel Scout integration, Algolia should be like a different config parameter  ;) 

But I'm personally trying not to use externals services as much as I can, only if really needed.

**Comment by tobias-kuendig** [comment]
It needed a few changes to pretty much everything but I think I've got a good solution now.

I have added an indexer that denormalizes all product data into flat json files (by default). These files are then searched when viewing the category. With this system it's easy to add elasticsearch or any other datastore for searching.

The performance looks good to me. This is the category page on first load (31 queries) and on page navigation (13 queries) on my machine with PHP 7.2 and XDebug enabled:

```
70 Variants
-> First page load: 600ms
-> Page navigation: 371ms

500 Variants
-> First page load: 761ms 
-> Page navigation: 464ms

5000 Variants (I'd swich to a "product only display" here ;-)
-> First page load: 2.2s
-> Page navigation: 1.6s
```

**Comment by Fl0Cri** [comment]
Nice! The performances are fine now. I did a similar page load with the same data as @pvullioud did.
The page is showing products (without variants) from a category. There is 1 property per product, 2 properties per variant, each product have at least 1 variant.
There is 1073 products and 3056 variants in the DB.

I have a lot of variability on this server but overall the generation time measured by DebugBar is between 1.2 and 1.6 seconds (with some rare spikes at ~2.2s).

I have no visible difference between my biggest category (128 products, 353 variants) and others with only 1 or 2 articles.
