### ISSUE TITLE
Wishlist problem with partial

### ISSUE THREAD

**Issue by MateThemes** [OFFLINE-GmbH/oc-mall-plugin#480]
Hello!

I am using Mall for my digital goods shop. So far every works fine. I have to customize a lot of markup, since I am using UIkit 3 Framework not TailwindCSS.

So I run into problems with the wishlist component. If I add the wishlist with {% component 'wishlists' %} everything works fine, but the markup lacks. If I add it with {% partial 'wishlists/default' %} no product will be added to a wishlist. It is always empty.

Did somebody so far, run into the same problem?

**Comment by igor-tv** [comment]
Everything works. I added `{% component 'wishlists'%}` to the cms page `wishlists.htm` and redefined the markup. To do this, I copied the `plugins/offline/mall/components/wishlists` folder in `themes/my-theme/partials` and made my markup in included htm files.

The `[wishlistButton]` and `[mallDependencies]` components must be connected on the product page.

**Comment by MateThemes** [comment]
Hello!

You are right. I made a mistake. I copied the folder from components/wishlists and added it instead of {% component 'wishlists' %} with {% partial 'wishlists/default ' %}. And this won't work.

Many thanks for your help!!
