### ISSUE TITLE
Currency Selector Component

### ISSUE THREAD

**Issue by az-vm** [OFFLINE-GmbH/oc-mall-plugin#481]
Hello,

First of all, thank you all, for this Great Plugin!!!

I´m doing a responsive theme for this, and i need some help to, how i can passe the Currency Selector Component to Partial, like the LocalePicker, so i can to some customization on it, so it can go with the theme i´m working on.

**Comment by tobias-kuendig** [comment]
You can override the component partials like any other partials in your theme:

https://octobercms.com/docs/cms/components#overriding-partials

**Comment by az-vm** [comment]
Hello!

So simple..... Thank you! Done!

Regard´s
Vitor
