### ISSUE TITLE
Question: set currency before value

### ISSUE THREAD

**Issue by NoDev1991** [OFFLINE-GmbH/oc-mall-plugin#487]
Hi, I can't find where to change
`<div class="mall-product__current-price">1.00€</div>`

to 
`<div class="mall-product__current-price">€1.00</div>`

the offline/mall/components/product/currentprice.htm only shows {{ price | raw }}.

Can you help me out?

**Comment by igor-tv** [comment]
<img width="1440" alt="Снимок экрана 2020-04-15 в 23 35 18" src="https://user-images.githubusercontent.com/6777469/79385924-067bd700-7f72-11ea-84d2-54d5aaf102c8.png">
Currencies settings in the general section of Mall plugin's settings.
