### ISSUE TITLE
Product Variants - Show only the main product on category

### ISSUE THREAD

**Issue by az-vm** [OFFLINE-GmbH/oc-mall-plugin#492]
Hello,

I´m testing mall on an fashion store, and there is a lot of colors and sizes per product, and this is turning a big mess, because the products only have one photo (in only one color) and in category its shows a lot of itens of the same... is there away to on product page select:

- Color 
- Size

Thank you,
Vitor

**Comment by tobias-kuendig** [comment]
You might want to set the `includeVariants` property of the `products` component to `false` so only Products are listed in your Category view, but not all the individual Variants.

https://offline-gmbh.github.io/oc-mall-plugin/components/products.html#properties

**Comment by az-vm** [comment]
Hello Tobias,

Thank you, it worked!

But there is no way to show in product the sizes and colors, wihtout going to variants?

Regard´s
Vitor

**Comment by tobias-kuendig** [comment]
What exactly do you mean by `in product`? On the overview page of the category?

You have access to all product data there as well. You can override the partials you need and add more information if you want.

A few examples on how to access the property values can be found in the docs:
https://offline-gmbh.github.io/oc-mall-plugin/development/product-model.html#property-values

**Comment by az-vm** [comment]
I mean this:
![variant](https://user-images.githubusercontent.com/2712273/80212540-3177c200-8627-11ea-949d-300c0031cd7b.jpg)

**Comment by tobias-kuendig** [comment]
The properties should be listed on the product page. You can check out our demo and log in to the backend as well to check the configuration (demo / demo):

https://mall.offline.swiss/en/product/cruiser-3000/zDpK3pj4

The theme can be found here, so you can check against the component configuration as well.

https://github.com/OFFLINE-GmbH/oc-mall-theme

**Comment by az-vm** [comment]
@tobias-kuendig Thank you!

It worked, but, only with dropdown option, it was good to have this by using the other filters options to, as you can see on the image i send after.

Regard´s
Vitor
