### ISSUE TITLE
CartProduct Updated event not fired

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#495]
the user scenario is the following:
user login, select a product and add a quantity of 2.
he goes have a coffee and come back to the same product page and add a quantity of 3.
Cart is containing a quantity of 5 as expected but my issue is that the event `'mall.cart.product.updated'` is not being fired up. And I need to do an external API call with the second quantity value. Any idea of how to achieve that please?

CartAction.php
```php
public function addProduct()
{
  ...
      CartProduct::where('id', $cartEntry->id)->update(['quantity' => $newQuantity]);
   ...
}
```

CartProduct.php
```php
public static function boot()
{
...
      static::updated(function (self $cartProduct) {
            Event::fire('mall.cart.product.updated', [$cartProduct]);
        });
...
}
```

**Comment by tobias-kuendig** [comment]
That `update` call never actually loads the Eloquent model, I guess this is why the event is not triggered.

Could you try and replace the line in the `addProduct` method with this version:

```php
CartProduct::find($cartEntry->id)->update(['quantity' => $newQuantity]);
```

**Comment by chrisvidal** [comment]
with this line we have a `Illuminate\Database\Eloquent\MassAssignmentException: quantity`

**Comment by tobias-kuendig** [comment]
You will have to add a `$fillable` property to the `CartProduct` model.

```php
public $fillable = ['quantity'];
```

**Comment by chrisvidal** [comment]
yes it solves the exception.

now my requirement is to get the new added quantity and can't find a way with this event as the CartProduct instance is already updated, and can't get the original value. any idea?

**Comment by tobias-kuendig** [comment]
We could introduce a new `mall.cart.product.updating` event:

```php
        static::updating(function (self $cartProduct) {
            Event::fire('mall.cart.product.updating', [$cartProduct]);
        });
```

In this, you should be able to get the quantities:

```php
$product->getOriginal('quantity'); // Before
$product->quantity; // After
```

Keep in mind that the CartProduct model has not been saved to the database yet in this case.

Does this work for you?

**Comment by chrisvidal** [comment]
I think it could work and I would use this new event `mall.cart.product.updating` for the 2 possible scenarios: 
- quantityModified from the cart, 
- and quantity added (in existing CartProduct or not) from the product page.

> Keep in mind that the CartProduct model has not been saved to the database yet in this case.

Thanks. 
Any case where the CartProduct could not be saved at the stage?

**Comment by tobias-kuendig** [comment]
>  Any case where the CartProduct could not be saved at the stage?

Sure, there can always be a problem saving the data. But in theory, all data should already be validated at this point so as long as your DB connection works you should be fine.

**Comment by tobias-kuendig** [comment]
This event has been added in 7e9d98a. 

Please respond if you need any further help.

**Comment by chrisvidal** [comment]
I think you forgot to update the CartActions.php file
updating `CartProduct::where('id', $cartEntry->id)->update(['quantity' => $newQuantity]);` to `CartProduct::find($cartEntry->id)->update(['quantity' => $newQuantity]);`

because none of the events `updated` and `updating` are fired.

with the code `CartProduct::find($cartEntry->id)->update(['quantity' => $newQuantity]);`, the event `updating` is fired but the mode does not contain the original value, meaning `$cartProduct->getOriginal('quantity')` is equal to `$cartProduct->quantity;`

if I replace this code line with this lines, the `updating` event is fired with the proper original values in the model.

```php
                $cartEntry = CartProduct::find($cartEntry->id);
                $cartEntry->quantity = $newQuantity;
                $cartEntry->save();
```
