### ISSUE TITLE
Product grouped properties with shared properties

### ISSUE THREAD

**Issue by damsfx** [OFFLINE-GmbH/oc-mall-plugin#497]
Hi,  
When setting up and testing groups/properties/variants I found myself with groups of properties sharing some properties.

So I created a property 'fence height' which is common between two groups, posts and panels.  
But when viewing the product (or a variant), `item.grouped_properties` returns both groups even if they don't belong to the product category.

Checking on the demo site, I noticed that you use a `$color` variable [SeedDemoData.php#L249](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/b61fd8cd814f86dba117867fdeba90ddba5fc342/console/SeedDemoData.php#L249) that you use in two different groups `$specs` and `$specsGroup` and the result is exactly the same.

![image](https://user-images.githubusercontent.com/282242/81029961-4c4c0100-8e87-11ea-9cf9-3a42d368cfc3.png)

Apparently you shouldn't share properties between different groups.

**Comment by tobias-kuendig** [comment]
Thanks! I'll have to look into this. Sharing the property shouldn't be a problem.

**Comment by tobias-kuendig** [comment]
Fixed in 5a7e070
