### ISSUE TITLE
Properties of a variant's parent are not saved in an order

### ISSUE THREAD

**Issue by Fl0Cri** [OFFLINE-GmbH/oc-mall-plugin#50]
When making an order with a product variant in the cart, all properties of the variant are serialized to the `property_values` and `property_description` columns of the `offline_mall_order_products` table.

But if we use a mix of product and variant properties, properties from the parent product won't be written.

IMO it would make sense to merge parent and variant properties in `offline_mall_order_products`.
I even suggest to do it directly in the `getAttribute()` of the variant because it may be useful in some other places.

Are you ok with this? If yes I can do a PR.

**Comment by tobias-kuendig** [comment]
Sounds good! :+1:
