### ISSUE TITLE
Install mall plugin on my shared server ,all other required plugins are shown but mall plugin is not shown

### ISSUE THREAD

**Issue by amjadniazi48** [OFFLINE-GmbH/oc-mall-plugin#507]
I have installed mall plugin , all other required plugin like translate,sitesearch are shown but mall plugin not shown

**Comment by tobias-kuendig** [comment]
How did you install the plugin? Are the permissions on the plugin folder the same as on the other plugins? Did you create any symlinks by hand?

**Comment by amjadniazi48** [comment]
I have solved the problem, basically Mall plugin not compatible with PHP 7.3, its work with 7.2.

**Comment by amjadniazi48** [comment]
Sorry test it again with 7.3, its working, it was just a problem with 7.1, no issue
