### ISSUE TITLE
Delete multiple language

### ISSUE THREAD

**Issue by altoca86** [OFFLINE-GmbH/oc-mall-plugin#509]
I don't need a store with many languages, I only need one but I am forced to have "/en" in my URL, is it possible to remove this annoying from the URL? Thank you very much for this great project.

**Comment by tobias-kuendig** [comment]
You have to disable it in the RainLab.Translate plugin. It takes care of all translation stuff. (probably [the forceUrl property on the localePicker component](https://github.com/rainlab/translate-plugin/blob/master/components/LocalePicker.php#L50))
