### ISSUE TITLE
How to display Additional descriptions and properties on frontend

### ISSUE THREAD

**Issue by LaxusMcfury** [OFFLINE-GmbH/oc-mall-plugin#510]
I need **additional descriptions and properties** tags to display them in product page. 
Also instead of creating another post i want to ask here if you are planning to add the ability to show **Related Products** in product page.

Thank you!

**Comment by tobias-kuendig** [comment]
> I need additional descriptions and properties tags to display them in product page.


You can override the default component partials and display whatever you want! You can access them via `{{ product.additional_properties }}` and `{{ product.additional_descriptions }}`.

> Also instead of creating another post i want to ask here if you are planning to add the ability to show Related Products in product page.


These are available via `{{ product.accessories }}` (in case you added them as an accessory). If you want to display "related products" from the same category, you can use this example from the docs:

https://offline-gmbh.github.io/oc-mall-plugin/components/products.html#example-implementations

**Comment by LaxusMcfury** [comment]
Hi and thank you for responding

I placed tags you gave me in the overridden component partial (product/info.htm) but the additional descriptions and properties didn't appear in product page, do you have any idea what could prevent it from appearing?

![Annotation 2020-05-21 154300](https://user-images.githubusercontent.com/60826570/82587790-50fffd00-9b89-11ea-9da4-956e3585e7c7.jpg)

**Comment by tobias-kuendig** [comment]
The variable is actually called `item` in the `Product` component (see other partials from that component):

```
{{ item.additional_properties }}
```

**Comment by LaxusMcfury** [comment]
You're right i didn't pay attention to that, just like `{{ item.name }}` or `{{ item.description }}` variables... but unfortunately `{{ item.additional_properties }}` triggered an error that says:

> An exception has been thrown during the rendering of a template ("Array to string conversion").

i'm still learning so i don't know what that means, something about **Cms\Classes\CmsException**
is looks like things are getting a bit complicated and i don't want to waste your time, if the solution is simpler than it appears to be i would appreciate your help, if not then i think i can move on without additional descriptions and properties, at least i managed to get **Related Products** to work, the documentation was very informative, thank you for that

**Comment by tobias-kuendig** [comment]
You cannot output an array in twig, you have to iterate over it. My code examples were not meant literally. You'll have to adjust them to your setup.

This should work:

```twig
{% for property in item.additional_properties %}
    {{ property.name }}: {{ property.value }}
{% endfor %}
```

The same will work for the descriptions.

Let me know if you need any more help.

**Comment by LaxusMcfury** [comment]
i see you thought i knew what i was doing lol, it's working now, thank you!
