### ISSUE TITLE
Changing brand slug makes productfilter brand selector useless

### ISSUE THREAD

**Issue by xariketi** [OFFLINE-GmbH/oc-mall-plugin#513]
Steps to reproduce issue:
1. Go to demo site and open "Cruiser Bikes" brand
2. Change brand slug and save it
3. Go to frontend category page
4. On product filter brand selector choose brand "Cruiser Bikes"
5. You get no results

**Comment by tobias-kuendig** [comment]
Thank you! This is fixed in 0064d28. You can run `php artisan mall:reindex` if you have a installation with inconsistent data. Your index will be re-created and the filter should be working again.
