### ISSUE TITLE
"Trying to get property 'id' of non-object" after adding top-level category

### ISSUE THREAD

**Issue by RobertCh2** [OFFLINE-GmbH/oc-mall-plugin#531]
I have added top-level category and included all existing categories (two levels) into this new one. After this all items which have this new category selected are throwing "Trying to get property 'id' of non-object" exception (on product pages). 

Items which I have added after creating this new top-level category are OK.

![Screenshot 2020-06-29 at 10 09 06 (2)](https://user-images.githubusercontent.com/18311946/85993241-50fbe400-b9f6-11ea-8950-733c2a23035d.png)

**Comment by tobias-kuendig** [comment]
How did you set the "Inherit properties" option on the 

- top level category
- the second level categories

?

**Comment by hauzmann** [comment]
It happens when child category doesn't inherit properties of its parent category.

**Comment by RobertCh2** [comment]
This is it. Setting »Inherit properties of parent category« to »ON« removes the error.
