### ISSUE TITLE
Color type custom fields does not update product price

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-mall-plugin#536]
Hello,

I noticed a bug related to the custom fields. When it's defined as a "color" type, when you click on the different color square on the product page, it does not dynamically update the product price.

Tested with simple dropdown, it works as expected, it seems to be related to the color type exclusively.

Best regards,

Alex

**Comment by tobias-kuendig** [comment]
Thank you for this report! This is fixed in 7691f9d. Let me know if you still experience any issues.
