### ISSUE TITLE
Add anonymous checkout or quick checkout without login/registration

### ISSUE THREAD

**Issue by w20k** [OFFLINE-GmbH/oc-mall-plugin#54]
Checkout page fields: [First_Name, Last_Name, Phone_Number, Notes, Delivery_Address, EMAIL]

When user prepared an order: 
He should define mandatory fields -> First_Name, Last_Name, Phone_Number - mandatory.
Address is mandatory, only if delivery options is not selected as pickup from the store, which is free.

**Comment by tobias-kuendig** [comment]
Closing this in favour of https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/172
