### ISSUE TITLE
Exception: Discount applicable to user belonging to a customer group

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#542]
when the user does not belong to any particular customer group, the exception is raised:

`Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function where() on null in /var/www/html/plugins/offline/mall/classes/cart/DiscountApplier.php:131`

```php
#0
/var/www/html/plugins/offline/mall/classes/cart/DiscountApplier.php(117):
OFFLINE\Mall\Classes\Cart\DiscountApplier->userBelongsToCustomerGroup(1)
#1
/var/www/html/plugins/offline/mall/classes/cart/DiscountApplier.php(49):
OFFLINE\Mall\Classes\Cart\DiscountApplier->discountCanBeApplied(Object(OFFLINE\Mall\Models\Discount))
```

**Comment by tobias-kuendig** [comment]
Thank you for this report! This should be fixed in 6623599, can you confirm that this is working for you (also available in version 1.11.22)

**Comment by chrisvidal** [comment]
yes this should fixed it, you beat me to the release of a PR haha

**Comment by tobias-kuendig** [comment]
:grin: Thanks, @chrisvidal, as always :+1:

**Comment by chrisvidal** [comment]
did you push the fix?

**Comment by tobias-kuendig** [comment]
It is out now, yes
