### ISSUE TITLE
Error in controllers/orders/_address.htm line 12

### ISSUE THREAD

**Issue by Hessel91** [OFFLINE-GmbH/oc-mall-plugin#543]
Sorry I don't know what I changed but suddenly I get this error when I try to view an excisting order in backend/offline/mall/orders. 
Changing settings: " Use State/County/Province field" on or of has no effect. 
Can you tell me what could couse this error?

[orders state error.pdf](https://github.com/OFFLINE-GmbH/oc-mall-plugin/files/4988285/orders.state.error.pdf)

**Comment by tobias-kuendig** [comment]
Can you try and change the offending line to the following and see if this works for you?

```php
<?= e(optional($address['state'])['name']) ?>
```

**Comment by Hessel91** [comment]
> Can you try and change the offending line to the following and see if this works for you?
> 
> ```
> <?= e(optional($address['state'])['name']) ?>
> ```

issue solved. Thank you Tobias =)

**Comment by Eoler** [comment]
This is incompatibility with PHP 7.4+ (probably).

**Comment by tobias-kuendig** [comment]
Fixed in ac74e14, thank you @Hessel91.
