### ISSUE TITLE
Feature request: Multi-vendor (Marketplace)

### ISSUE THREAD

**Issue by skacco** [OFFLINE-GmbH/oc-mall-plugin#546]
Hi everyone!

I want to understand if it is planned the implementation of multi-vendor functionality. It could be a killer feature.

**Comment by tobias-kuendig** [comment]
Unfortunately, there is nothing like that planned at this time.

**Comment by skacco** [comment]
I think the most important task is to integrate paypal ecommerce platform to allow payment from the customer and automatic payout to the vendor.
Other useful feature could be:
-    Sale stats for each vendor per product/category/month/year
 -   Different percentage commission for each vendor/group
 -    Separated media folder for each vendor to manage his eshop media content
-    If possible, maybe at later stage, ability for design customisations/templating for each vendor to give a different look for his shop

**Comment by tobias-kuendig** [comment]
Multi-vendor stores feature will most likely not be implemented
