### ISSUE TITLE
Edit products remove brand doesn't work on a first click

### ISSUE THREAD

**Issue by w20k** [OFFLINE-GmbH/oc-mall-plugin#55]
When trying to remove a brand from a product (tested -> https://mall.offline.swiss/backend/offline/mall/products/update/1), needs two clicks to remove a brand from the readonly input.

![sep-09-2018 14-00-06](https://user-images.githubusercontent.com/1053320/45263786-054f0380-b439-11e8-8a36-f0dc110f40d5.gif)

**Comment by chrisvidal** [comment]
same issue here when removing a brand
