### ISSUE TITLE
loggedin user not able to give the review from frontend

### ISSUE THREAD

**Issue by amjadniazi48** [OFFLINE-GmbH/oc-mall-plugin#550]
![FireShot Capture 079 - toogoodguyz - Coffee Travel Mug - toogoodguyz com](https://user-images.githubusercontent.com/2420029/89222074-d3775500-d5ed-11ea-8b5d-05ad22559750.png)

![FireShot Capture 082 - toogoodguyz - Coffee Travel Mug - toogoodguyz com](https://user-images.githubusercontent.com/2420029/89222177-04578a00-d5ee-11ea-894a-dc7b0d2c8de2.png)

**Comment by tobias-kuendig** [comment]
Thank you for this report! See https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/548#issuecomment-667833357 for a temporary workaround. I'll try to release a proper fix today. Please track #548 for progress on this.
