### ISSUE TITLE
Reviews cannot be added from the frontend. 

### ISSUE THREAD

**Issue by dizakids** [OFFLINE-GmbH/oc-mall-plugin#554]
Thanks for the great plugin. There are small flaws with reviews.
The form for adding reviews does not appear when you click on the asterisks (in your demo it work, but on my test site https://js-studio.site/en/product/produkt-1 it does not work for me) Why?

**Comment by tobias-kuendig** [comment]
Thank you @dizakids. This is fixed in 14d1d54.
