### ISSUE TITLE
Brands

### ISSUE THREAD

**Issue by dizakids** [OFFLINE-GmbH/oc-mall-plugin#558]
1. How to display all brands on a separate page?
2. There is no brand name, description or logo on the page that shows brand products. How to display its logo, description, name on the page of a specific brand?

**Comment by tobias-kuendig** [comment]
There's nothing stopping you from creating a custom component:

```php
public function onRun()
{
    $this->brands = Brand::get();
}
```

**Comment by dizakids** [comment]
Unfortunately I don't know how to create my own components yet. How to implement it in a little more detail. What code to write and where. Thanks you

**Comment by tobias-kuendig** [comment]
Then I suggest you start here:
https://octobercms.com/docs/plugin/components

**Comment by dizakids** [comment]
Thank you, I figured out the creation of my component, I created the brands page and successfully brought the name and description of the brand there. But I can't figure out how to show the brand logo (because it is not in the Brands table). Here is my brands / default.htm
`<ul>
  {% for brand in __SELF__.brands %}
  <li>
{{ brand.name }}
{{ brand.description | raw }}
{{ brand.website }}
{% if images %}
        {% for image in images %}
                <img src="{{ image.thumb(240, auto) }}" alt=""/>
        {% endfor %}
{% endif %}
  </li>
{% endfor %}
</ul>`

Here is my Brands.php
`<?php namespace OFFLINE\Mall\Components;

use OFFLINE\Mall\Classes\Traits\CustomFields;
use OFFLINE\Mall\Models\Brand;

class Brands extends MallComponent
{

public $brands;

public function componentDetails()
    {
        return [
            'name' => 'Brands',
            'description' => 'Displays brands.'
        ];
    }

public function onRun()
{
    $this->brands = Brand::get();
}
`
What you need to add to show the brand logo?

**Comment by tobias-kuendig** [comment]
Looking great! :clap:

Images in October are usually solved via attachments: https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/models/Brand.php#L39

You can access them using `brand.image.thumb(240, auto)`. 

```twig
<img src="{{ brand.image.thumb(240, auto) }}" alt=""/>
```

Note: Make sure to eager-load these images if you loop over all brands. Otherwise each loop will trigger a new query that fetches the image from the database:

```php
$this->brands = Brand::with('image')->get();
```

**Comment by dizakids** [comment]
Thanks for the help, but I am doing something wrong and I get a PAGE ERROR

Here is my brands/default.htm
```
<ul>
{% for brand in __SELF__.brands %}
  <li>
    <a href="brand/{{ brand.slug }}">{{ brand.name }}</a>
    {{ brand.description | raw }}
    {{ brand.website }}
    <img src="{{ brand.image.thumb(240, auto) }}" alt=""/>
  </li>
{% endfor %}
</ul>
```
Here is my Brands.php
```
<?php namespace OFFLINE\Mall\Components;

use OFFLINE\Mall\Classes\Traits\CustomFields;
use OFFLINE\Mall\Models\ImageSet;
use OFFLINE\Mall\Models\Brand;
use System\Models\File;

class Brands extends MallComponent
{
use CustomFields;

public $brands;

public function componentDetails()
    {
        return [
            'name' => 'Brands',
            'description' => 'Displays brands.'
        ];
    }

public function onRun()
{
  $this->brands = Brand::with('image')->get();
}

}
```

**Comment by tobias-kuendig** [comment]
Check the storage/logs/sytem.log file for more details on the error. 

Also, you don't need the `use CustomFields`  part.

**Comment by tobias-kuendig** [comment]
I just noted, the relation on the Brand model is not called `image` but `logo`, so make sure to use the right name. I guess this is the problem you see here.

**Comment by dizakids** [comment]
Thanks for the help, I replaced image on logo and it  worked super, the last question was left by brands. Made a component of a single brand it only works when:
```
$this->brand = Brand::with('logo')->find(1); 
```
(naturally shows 1 record in the Brand table, but I need a transition by slug) I need that when you click on a specific brand to see the page with this brand
I'm trying to
```
$this->brand=Brand::with('logo')->find($slug); 
``` 
and got mistake
Here is my link from component Brands.php
```
<a href="brand/ {{brand.slug} }"> {{brand.name}} </a>
```
How to correctly implement the transition with the parameter in Oktober cms ? 
Thank you for your understanding

**Comment by tobias-kuendig** [comment]
This is out of the scope of this plugin. Translations are handled by the RainLab.Translate plugin. Check their documentation on how to do this. IIRC you need to use `transWhere`, it is documented with the plugin.

Also, to find a Brand by slug, you need to use `Brand::where('slug', $slug')->first()`.

**Comment by dizakids** [comment]
I don't need translations. I meant to pass a parameter ($slug ????). I am trying to implement showing brands of your plugin Mall.
 In the logs, I get an error that the variable slug is undefined
Here is my Brand1.php 
```
<?php namespace OFFLINE\Mall\Components;

use OFFLINE\Mall\Classes\Traits\CustomFields;
use OFFLINE\Mall\Models\Brand;

class Brand1 extends MallComponent
{

public $brand;
public $slug;

public function componentDetails()
    {
        return [
            'name' => 'BrandComponent',
            'description' => 'Displays 1 brand.'
        ];
    }

public function onRun()

{
    $this->slug = $this->param('slug');
    $this->brand = Brand::where('slug', $slug)->first();
}
}
```
Here is my Brands.htm 

```
<ul>
{% for brand in __SELF__.brands %}
  <li>
    <a href="brand/{{ brand.slug }}">{{ brand.name }}</a>
    {{ brand.description | raw }}
    {{ brand.website }}
    <img src="{{ brand.logo.thumb(240, auto) }}" alt=""/>
  </li>
{% endfor %}
</ul>
``` 
Here is my Brand1.htm 
```
{{ __SELF__.brand.name }}
<img src="{{ __SELF__.brand.logo.thumb(240, auto) }}" alt=""/>
{{ __SELF__.brand.description | raw }}
{{ __SELF__.brand.website }}
```
I do not understand how to transfer the slug correctly. Help me please

**Comment by tobias-kuendig** [comment]
Please check out October's Discord or Slack servers for support.

You probably are looking for this: https://octobertricks.com/tricks/generate-link-cms-page

```twig
<a href="{{ 'your-brand-detail-page-filename' | page({slug: brand.slug}) }}"> ... </a>
```
