### ISSUE TITLE
Product categories to be single select

### ISSUE THREAD

**Issue by panakour** [OFFLINE-GmbH/oc-mall-plugin#559]
I have a use case where I want the product to belongs to only one category at each time.

**Possible solution:**
I think it will be better and more flexible for a product to have one main category and optional secondary categories.

**Comment by tobias-kuendig** [comment]
You can use the [`backend.form.extendFields
`](https://octobercms.com/docs/api/backend/form/extendfields) event and turn the relation picker into a simple selectbox so only one category is selectable.

**Comment by panakour** [comment]
> You can use the [`backend.form.extendFields `](https://octobercms.com/docs/api/backend/form/extendfields) event and turn the relation picker into a simple selectbox so only one category is selectable.

yes but with this way you will lose the functionality of categories and you have to create your own

**Comment by tobias-kuendig** [comment]
> What do you think about having one main category in the core of the plugin?

We had this at the start but soon noticed, that many users require more categories to be set. It won't matter what category structure we choose, there is always someone that needs it the other way around.

What would be the benefit of having one main category?

**Comment by panakour** [comment]
> What would be the benefit of having one main category?

the benefit would be to prevent the admin who manage the products to accidentally select two categories that it does not make any sense

**Comment by tobias-kuendig** [comment]
Alright, I guess for the time being the solution via `backend.form.extendFields` is sufficient for that. We might add a backend setting in the future that offers this as a core feature.
