### ISSUE TITLE
How to change price format

### ISSUE THREAD

**Issue by amjadniazi48** [OFFLINE-GmbH/oc-mall-plugin#560]
I am using   {{ currency.symbol}} {{ price|number_format(2, '.', '\'') }}  and if i put 30 it will be shown as  30,00.
How should i change it so that it  looks like 30.00 instead of 30,00

**Comment by tobias-kuendig** [comment]
What does `{{ 30|number_format(2, '.', "'") }}` print?

**Comment by amjadniazi48** [comment]
i just want dot instead of comma in my prices

**Comment by tobias-kuendig** [comment]
This has nothing to with this plugin. `number_format` is a Twig function. I understand your question but you have to do some work and check the output of the code I posted above otherwise I cannot help you.

**Comment by amjadniazi48** [comment]
the above code has no change on the prices

**Comment by tobias-kuendig** [comment]
Try a `php artisan cache:clear`.

**Comment by amjadniazi48** [comment]
no change even after this command

**Comment by tobias-kuendig** [comment]
Please show me some code, give me some info. Are you using the `|money` filter? If not this is not a problem of this plugin. 

What is the output of `{{ 10000|number_format(2, '.', "'") }}`, are the separators correct this way?

**Comment by amjadniazi48** [comment]
![FireShot Capture 111 - Edit Currencies - Toogoodguyz - toogoodguyz com](https://user-images.githubusercontent.com/2420029/90615354-72729280-e225-11ea-9e22-8eb79ba02ebe.png)
![Screenshot(7)](https://user-images.githubusercontent.com/2420029/90615458-96ce6f00-e225-11ea-8a25-99eb8b21de6e.png)
no change in price format and i m not using any |money filter as well

**Comment by tobias-kuendig** [comment]
Can you check in a incognito tab? IIRC the currency format is bound to your session so it might be cached in there. Either log out and back in or open the page in a incognito tab and see if this reloads the config.

**Comment by amjadniazi48** [comment]
test it in incognito tab as well but no change

**Comment by amjadniazi48** [comment]
On my local machine its working correct but on my shared server if i change the currency format it is not working, any idea?

**Comment by tobias-kuendig** [comment]
The currency is cached on your server and the selected currency is stored in your session:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/models/Currency.php#L64

If you save the currency in the backend, everything should get wiped clean.

You can also check what the `defaultCurrency` or `activeCurrency` methods return:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/models/Currency.php#L100

```
dd(Currency::activeCurrency()->format);
```

Here you should see the format you have entered in the backend.

**Comment by amjadniazi48** [comment]
dd(Currency::activeCurrency()->format) shows me the result which is written in the currency config file, I have no idea how to get rid of this comma, just want to publish my site but due to this comma I am stuck

**Comment by tobias-kuendig** [comment]
Dive into the code, see where it behaves wrong. You are a dev, you should be able to find this out! :wink: 

It's hard to give you any further assistance here as it seems like a cache problem, especially if it only happens on your server.

Just a last thought I had: If you have direct access to the server, try restarting php-fpm to make sure there's nothing in PHP's opcache that is not reloaded.
