### ISSUE TITLE
Gift cards

### ISSUE THREAD

**Issue by gpluess** [OFFLINE-GmbH/oc-mall-plugin#561]
Looking for advice: I'm in the process of implementing gift cards in my shop and am thinking about which approach might be the best.

The two approaches I'm thinking of are:

- use the currently available discount feature
- add a new payment provider for "gift cards"

One requirement for me is that the "remaining amount" of a gift card does not lapse, meaning that if someone has a 100$ gift card and buys something for 60$, the remaining 40$ should be available for a later purchase. I'm not sure if this is currently possible with the existing discount feature...?

Any advice on this? Much appreciated!

**Comment by tobias-kuendig** [comment]
The gift cards themselves I would implement using virtual products:
https://offline-gmbh.github.io/oc-mall-plugin/digging-deeper/virtual-products.html (see our demo website for an example)

There also an example on how to create a discount code during checkout:
https://offline-gmbh.github.io/oc-mall-plugin/digging-deeper/virtual-products.html#generate-user-specific-product-files

Using any of the order events, you should be able to update the discount code after the order has been created. You can then manually update the discount to have "less value":
https://offline-gmbh.github.io/oc-mall-plugin/development/events.html#order

This is not an ideal solution but it should work.

**Comment by gpluess** [comment]
Thanks for your advice! We intended to physically ship the gift cards, but I'll try the virtual products approach.

**Comment by gpluess** [comment]
While implementing the above solution I stumbled upon a case where the cart total could be 0.

Selecting the offline payment method would be a workaround, but I think from a customer's point of view, I wouldn't expect to have to choose a payment method if the total amount due is 0.

Is there an easy way to bypass the payment entirely in such a case?

**Comment by tobias-kuendig** [comment]
I didn't look into this in detail, but my best guess would be to extend the `PaymentMethodSelector` component and check the cart's total in the `onRun` method. If the total is 0, set the "payment method" you want and redirect to the next step. 

I believe an order currently needs a payment method, it cannot be created without it.

**Comment by tobias-kuendig** [comment]
Gift cards (virtual products) are supported out-of-the-box for some time now. Closing this issue.
