### ISSUE TITLE
Rainlab user menu and permissions

### ISSUE THREAD

**Issue by panakour** [OFFLINE-GmbH/oc-mall-plugin#562]
I have created a backend user with new custom role who has access to manage users only
![image](https://user-images.githubusercontent.com/12927166/91202806-01dae280-e70b-11ea-864b-f7adee10f121.png)

But this user can see the menus for also customer groups and addresses 
![image](https://user-images.githubusercontent.com/12927166/91202952-2fc02700-e70b-11ea-9178-ea29c5b0db90.png)

because of: https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/27b1e238cc575a0b07afeda52a15cded27eeef6d/classes/registration/BootExtensions.php#L93

Is there any reason to have the permission to `rainlab.users.*`. I think is unnecessary and also caused issue when the user try to navigate to this items:
![image](https://user-images.githubusercontent.com/12927166/91203194-84fc3880-e70b-11ea-8b2a-037028529b4b.png)

Also I think the code for the users menu is not needed here because is defined to the origin plugin.  https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/27b1e238cc575a0b07afeda52a15cded27eeef6d/classes/registration/BootExtensions.php#L80
```
            $manager->addSideMenuItems('RainLab.User', 'user', [
                'users' => [
                    'label'       => 'rainlab.user::lang.users.menu_label',
                    'url'         => \Backend::url('rainlab/user/users'),
                    'icon'        => 'icon-user',
                    'permissions' => ['rainlab.users.*'],
                ],
            ]);
```
If you agree with the above issues I can open a PR.

**Comment by tobias-kuendig** [comment]
Very good points, @panakour!

If you could provide a PR with fixed permissions and any dead code removed that would be great.
