### ISSUE TITLE
PaymentResult:: success ()  returns error at http-foundation/Response::setContent

### ISSUE THREAD

**Issue by epikoder** [OFFLINE-GmbH/oc-mall-plugin#563]
I'm trying to build a payment method plug-in. I followed the documentation and can make payment on the gateway website, on callback.. 
`$order = Order::find($response->order_id);`
`$result = new PaymentResult($provider, $order);`
`$result->success((array) $reponse->data, $response);`
This is the error message.. 
![Screenshot_20200826-023519](https://user-images.githubusercontent.com/39457512/91244667-d248cc00-e744-11ea-9cda-9fe0eda42f35.png)

I run a test on setContent using the response and it worked, without error.
How is setContent called from PaymentResult as i can't seem to find it.. 
Methods implemented in $response 

`isSuccessful()` return status : bool
`__toString()` returns status text
`getCode()` returns response code
`getMessage()`  return message

The order is updated on the store and throws the this error. 
Please tell me if the information provided isn't enough

**Comment by tobias-kuendig** [comment]
Take a look at the stack trace. This looks like a internal call of some library. I'd say it happens before it reaches Mall's code.

What payment provider are you using? Can you share some code?

**Comment by epikoder** [comment]
Looking at PaymentResult I got lost 😐, after it called `tap` 
https://github.com/epikoder/oc-paystack this is the current state of the code

**Comment by tobias-kuendig** [comment]
Try to add a few `traceLog('reached method x')` calls in your code. Can you find out where it crashes?

For example, is the `PaystackResponse` ever properly created?
https://github.com/epikoder/oc-paystack/blob/master/controllers/PaystackController.php#L42

Can the order be resolved from you reference?
https://github.com/epikoder/oc-paystack/blob/master/controllers/PaystackController.php#L48

etc.

**Comment by epikoder** [comment]
I'll use the `tracelog` now and see

What other way can I get resolve the order?
https://github.com/epikoder/oc-paystack/blob/master/controllers/PaystackController.php#L48

This is where I included the order_id
https://github.com/epikoder/oc-paystack/blob/32b8bf3523ddcd05e1fa4980e024dd4f4b1107bc/classes/Paystack.php#L126

**Comment by tobias-kuendig** [comment]
Do you have any control over the return URL? If so, you can put it as a GET parameter in there, like

    http://site.tld/callback_url?order_id=2

Another solution is to store the value in the user's session as we did with PayPal:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/payments/PayPalRest.php#L66 (Line 66 and Line 80)

**Comment by epikoder** [comment]
`$tranx->data->metadata->id` is not empty. The order is been completed in the store. Either the value of 
`Order::find($id)`
Is the issue.
I can't use the url parameters as it's handled by the gateway, I'll use the session and give feedback.. Thanks for the time

**Comment by epikoder** [comment]
I've been able to make it work, seems the problem began from creating an instance of PaymentResult.

the gateway has webhook support, how  do add the support in case there's a network failure, the order can be processed from
the webhook and also not processed twice. This's the state of the code.
https://github.com/epikoder/oc-paystack
