### ISSUE TITLE
Add mobile number to customer account.

### ISSUE THREAD

**Issue by epikoder** [OFFLINE-GmbH/oc-mall-plugin#564]
I'd like to add mobile number to customer account.
How do I go about it using plugin.

Tip please

**Comment by tobias-kuendig** [comment]
1. Create your own plugin (MallExtensions)
1. Add the additional database fields via migrations
1. Add the additional form fields to your component partials
1. Register an event listener (in your Plugin.php's boot method) for the [`mall.customer.afterSignup`](https://offline-gmbh.github.io/oc-mall-plugin/development/events.html#customer) event. There you can access the created customer model via `$user->customer` and set the additional form data via the normal form input methods (`request()`, `input()`, etc.).
1. Extend any backend forms as described in October's docs: https://octobercms.com/docs/plugin/extending

We are trying to make this easier in future releases.

**Comment by epikoder** [comment]
Okay.. I'll try it. I'm leaving this issue closed for now
