### ISSUE TITLE
display customer address and # order ..? on pdf

### ISSUE THREAD

**Issue by Hessel91** [OFFLINE-GmbH/oc-mall-plugin#568]
Hi, 

what is the correct syntax to display the customer address and to display the generated ordernr? (# ORDER) on the pfd invoice?

{{ order.customer.address }} and {{ order.customer.order}  is not correct. 

thanks in advange.
Hessel

**Comment by Hessel91** [comment]
thank you, Tobias.  however, I cannot output an array in twig, I am struggling with how to iterate it. 
{% for ... in .. %}
{{ order.number }}
{{ order.billing_address }}
{% endfor %}

**Comment by tobias-kuendig** [comment]
Try this:

```twig
Order #{{ order.number }}

Address:

{{ order.shipping_address.company }}
{{ order.shipping_address.name }}
{{ order.shipping_address.lines }}
{{ order.shipping_address.zip }} {{ order.shipping_address.city }}
{{ order.shipping_address.state.name }}
{{ order.shipping_address.country.name }}
```

You should not have to iterate over the array in this case.
