### ISSUE TITLE
Additional descriptions value shows a <p> tag in front-end

### ISSUE THREAD

**Issue by Dione-stack** [OFFLINE-GmbH/oc-mall-plugin#569]
Hello!

Do you have any clue why `<p>` tag is showing around the text in front-end, and only in additional descriptions value, while additional properties appears normally as you can see in the screenshots...

Please spare some of your time on this weird issue and thank you

![Screenshot (105)](https://user-images.githubusercontent.com/67985418/92291074-c4e2cd00-ef0e-11ea-99bd-a14780b2e94e.png)
![Screenshot (106)](https://user-images.githubusercontent.com/67985418/92291075-c613fa00-ef0e-11ea-852e-eeee53d47e24.png)
![Screenshot (110)](https://user-images.githubusercontent.com/67985418/92291077-c6ac9080-ef0e-11ea-94be-0e53a32ed2b2.png)

**Comment by panakour** [comment]
@Dione-stack because its a richeditor field. If you want to remove html tags you can use the striptags filter https://twig.symfony.com/doc/3.x/filters/striptags.html

**Comment by Dione-stack** [comment]
> @Dione-stack because its a richeditor field. If you want to remove html tags you can use the striptags filter https://twig.symfony.com/doc/3.x/filters/striptags.html

ok i think it's time for me to learn more about twig, thank you for the help
