### ISSUE TITLE
Promoted products in category

### ISSUE THREAD

**Issue by tobias-kuendig** [OFFLINE-GmbH/oc-mall-plugin#57]
* [ ] Add "promoted products" to category, make them sortable
* [ ] By default, display them at the top of the product listing
* [ ] Add a "featured" option to the CategoryFilter sorting dropdown

**Comment by amdad** [comment]
Filter by Brand would also be nice, Don't you think?

**Comment by tobias-kuendig** [comment]
[Done!](366bdd0782e7911abd168f16bc51df809c3f2e18)

**Comment by amdad** [comment]
Brands and sorting works :) Very thanks. 
Promoted products and Featured can be not only for sorting but for filtering. As checkbox, to show only products on sale or featured ones.

**Comment by amdad** [comment]
So like with brands. Option to filter out only "On Sale" in frontend filters checkbox.

**Comment by tobias-kuendig** [comment]
This was shipped in 1.0.8
