### ISSUE TITLE
Sort by price issue

### ISSUE THREAD

**Issue by bozsokidaniel** [OFFLINE-GmbH/oc-mall-plugin#571]
Hi,

I see there is a slight error in sorting by price but I can't decide exactly what this might be.

<img width="1664" alt="sort_by_price_issue" src="https://user-images.githubusercontent.com/13118726/92418873-4a15ee00-f16a-11ea-8268-55b2b1f63a6b.png">

When sorting by price ascending or descending, it seems to me that the algorithm does not sort the products properly

I also attach a picture of exactly what i mean.

In the database, I found that the system automatically adds two zeros to the price in offline_mall_product_prices table.

<img width="673" alt="db_table" src="https://user-images.githubusercontent.com/13118726/92419052-67978780-f16b-11ea-9153-05fd984b532b.png">

Mall version: 1.3.9

**Comment by tobias-kuendig** [comment]
The zeroes are expected. We store the prices in cents, to work around floating point errors.

The data is sorted according to the returned values from the `offline_mall_index` table. Could it be possible, that this is out of sync? You can rebuild it by running `php artisan mall:reindex`. 

If you change the filter to `price_high` do the producs show up in the reverse (but still wrong) order?

**Comment by bozsokidaniel** [comment]
The reindex solved the problem.

I don't know how the sync stopped, my question would be, can the sync be restored after the reindex?

**Comment by tobias-kuendig** [comment]
The "sync" happens automatically every time you update a product. So in theory, the index should never get out of sync. It can happen though, if there was an error while saving a product or if you manually change the data in the database (either by hand or by importing data from an external system). Of course, there's also the possibility of a bug in the code that lead to a broken index. 

Since you are the first one to report this problem, I'd like to way for more reports before we dive in deeper. The index code hasn't been touched in months, so any bug should have been around for a while.

**Comment by bozsokidaniel** [comment]
I reviewed the functionality. After deleting the index table and then editing the products, the data is written to the index table, so the data update works for a change. However, reindexing does not always work. I don't know if it has to do with the type of database. It runs fine on Mysql version 8 but not on mariadb 10.5 and 10.4. Is it possible to know why if I move the database from one repository to another, why does the sort go wrong?

**Comment by tobias-kuendig** [comment]
Do you have any error messages in your `system.log` table? Are you using the `sync` queue driver? The indexing happens in the queue if you don't use the `sync` driver, so errors might happen in the background.

**Comment by bozsokidaniel** [comment]
Okay, I think this issue can be closed. I have update the code to the latest release and now everything is working. I don't know exactly what happened there were lot of strange thing because I have test it on variable environments with different release versions.

After update this get fixed.

Thank you for your support and help!
