### ISSUE TITLE
Error while installing plugin

### ISSUE THREAD

**Issue by osakalevin** [OFFLINE-GmbH/oc-mall-plugin#573]
Hey,

After following the instructions on [link](https://offline-gmbh.github.io/oc-mall-plugin/getting-started/installation.html#installation), the installation fails while attempting to install offline.mall plugin, with the following message:

![Screenshot from 2020-09-09 12-25-24](https://user-images.githubusercontent.com/10699626/92592808-0caf7e80-f298-11ea-885a-7c3681b762fd.jpg)

Any clue on why this is happening?

Thanks

**Comment by tobias-kuendig** [comment]
This is related: https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/572/files

It looks like the parsing of the version information changed. What version of October and PHP are you running?

The marketplace does not allow me to edit old update messages, I'll have to see what we can do here.

**Comment by bomja** [comment]
Run into the same problem.

469 october
Tested on 7.3 and 7.2 php same issue.

**Comment by osakalevin** [comment]
> This is related: https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/572/files
> 
> It looks like the parsing of the version information changed. What version of October and PHP are you running?
> 
> The marketplace does not allow me to edit old update messages, I'll have to see what we can do here.

Yeah, sorry about that. October 469 and php 7.2.

Thanks

**Comment by tobias-kuendig** [comment]
Can you give it another try with the latest version? If a `php artisan october:update` still triggers the error, patch the versions.yaml manually first: 

https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/572/files

**Comment by osakalevin** [comment]
> Can you give it another try with the latest version? If a `php artisan october:update` still triggers the error, patch the versions.yaml manually first:
> 
> https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/572/files

Yep. Fixed.

Thanks for the speedy solution.

**Comment by bomja** [comment]
> Can you give it another try with the latest version? If a `php artisan october:update` still triggers the error, patch the versions.yaml manually first:
> 
> https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/572/files

Same for me! Thank you! 
Best regards!
