### ISSUE TITLE
Exception (unkown column valid_from) after fresh install

### ISSUE THREAD

**Issue by osakalevin** [OFFLINE-GmbH/oc-mall-plugin#574]
Hey,

After freshly installing October with the OFFLINE Mall plugin, the following message appears on every page:

![Screenshot from 2020-09-09 19-58-12](https://user-images.githubusercontent.com/10699626/92641734-13a9b180-f2d7-11ea-9d9a-a3d8721e2c6a.png)

Describing the table offline_mall_discounts, we can check that the column doesn't exist:
![Screenshot from 2020-09-09 19-58-23](https://user-images.githubusercontent.com/10699626/92641794-2b813580-f2d7-11ea-9aee-014432659b12.png)

Please note that I followed the instructions as stated on the documentation, with the seed-demo information.

October 469. Not sure if this is related to issue #573 

Thanks

**Comment by osakalevin** [comment]
Hey again,

Looks like the installation was not completed at some point. I manually added the valid_from column to the offline_mall_discounts table, and now the error is the following:

![Screenshot from 2020-09-09 20-15-38](https://user-images.githubusercontent.com/10699626/92643255-5e2c2d80-f2d9-11ea-937e-8fe31b68b081.png)

Thanks

**Comment by tobias-kuendig** [comment]
If this is a fresh installation, try to completely remove the plugin and then install it again. If the migrations failed at an arbritrary point it can be very cumbersome to get it fixed without a reinstall.

```
rm -rf plugins/offline/mall
```

In MySQL, drop all `offline_mall_*` tables. Also remove the plugin from October's tables:

```
DELETE FROM system_plugin_versions WHERE code = 'OFFLINE.Mall';
DELETE FROM system_plugin_history WHERE code = 'OFFLINE.Mall';
```

Then install the plugin again:

```
php artisan plugin:install offline.mall
```

**Comment by osakalevin** [comment]
> ```
> php artisan plugin:install offline.mall
> ```

Working now :]

If someone stumbles on this issue, after the steps provided by tobias, you will also need to ALTER the 'users' table and DROP the column 'offline_mall_customer_group_id' or the installation will fail.

Thanks
