### ISSUE TITLE
Question: Creating multiple PaymentMethods with one provider

### ISSUE THREAD

**Issue by snakemastr** [OFFLINE-GmbH/oc-mall-plugin#576]
First, hats off for such a cool and very complete plugin! I am loving it.

I am creating a Mollie PaymentGateway using Omnipay and was wondering if I could use one gateway to implement multiple methods. My goal would be to have a single Mollie Gateway and a PaymentMethod per method (1 for iDeal, 1 for Bancontact, etc) that uses the Mollie Gateway with an extra parameter (ie 'ideal' or bancontact). This would make it possible to add a new method without having to create a separate provider.

My inital setup was to create separate providers inheriting from a Mollie Base (which handles the requests), adding the necessary request data per provider. But then I would have to write a (small) provider for each payment method in Mollie.

Is it possible to simply add a parameter in PaymentMethod that can be read in the Gateway or am I better of with my initial setup?

**Comment by tobias-kuendig** [comment]
You could create a single:

- Mollie Payment Provider

Then add some payment methods that use this provider:

- ideal
- bancontact

In your provider's `process` method you can get the selected payment method via `$this->order->payment_method`. You can then do a switch on this and handle the payment in whatever way you want:

```php
    public function process(PaymentResult $result): PaymentResult
    {
        switch ($this->order->payment_method->code)
		{
		    case "ideal":
		        return $this->handleIdeal($result);
		    case "bancontact":
		        return $this->handleBancontact($result);
            default:
                throw new Exception('Invalid payment method');
		}
    }
```

**Comment by snakemastr** [comment]
Oh yeah that's a great idea! I don't know why I thought about that.. Thank you so much for also providing an example.
