### ISSUE TITLE
Sql error with mall:seed-demo command

### ISSUE THREAD

**Issue by damsfx** [OFFLINE-GmbH/oc-mall-plugin#577]
After updating to lastest OctberCMS build (469), using the `php artisan mall:seed-demo` command result in an error : 

>   SQLSTATE[HY000]: General error: 1364 Field 'disk_name' doesn't have a default value (SQL: insert into `system_files` (`is_public`, `field`, `attachment_id`   
  , `attachment_type`, `updated_at`, `created_at`) values (1, images, 1, mall.imageset, 2020-09-10 15:39:59, 2020-09-10 15:39:59))

May it can be linked to the lastest OctoberCMS build?

See: https://github.com/octobercms/october/issues/5270

**Comment by tobias-kuendig** [comment]
Thank you for the report. This has been fixed upstream:
https://github.com/octobercms/library/pull/521
