### ISSUE TITLE
mallPDF Error  

### ISSUE THREAD

**Issue by damanic** [OFFLINE-GmbH/oc-mall-plugin#579]
PDF templates (eg. wishlist) use CSS partial includes.

A recent OctoberCMS  update has seen this error occur (System build 469):

`An exception has been thrown during the rendering of a template ("The specified file extension [css] is invalid.").`

Looks like you cannot include .css partials anymore.  

```
    <style>
        {% partial 'mallPDF/wishlist/styles.css' %}
    </style>
```

**Comment by tobias-kuendig** [comment]
Thank you for the heads up. We will change that to a .htm extension.

**Comment by tobias-kuendig** [comment]
Fixed in https://github.com/OFFLINE-GmbH/oc-mall-theme/commit/841b22181e38ef74e34a85929e4a76e005545df5
