### ISSUE TITLE
Sold product by weight (like vegetables)

### ISSUE THREAD

**Issue by PrestaSafe** [OFFLINE-GmbH/oc-mall-plugin#580]
Hi,

I want to sell vegetables products, there is a way to sold product by weight ? 
ex: 1.0 kg = $2.99 the customer choose to put 1.5 kg in the cart ? 

Thanks.

**Comment by tobias-kuendig** [comment]
There is nothing specific like this built in but maybe you could simply re-use the quantity input?

Product price = 2.99
Quantity = 2 (kg)

We don't support floating point quantities though, but maybe you can get this to work without too many changes.

**Comment by PrestaSafe** [comment]
ok thanks, i'll do that in a first time. It's could be a good idea to create a product type like that.

Thanks for you answer.
