### ISSUE TITLE
Property checkboxes not saving  (build 469)

### ISSUE THREAD

**Issue by damanic** [OFFLINE-GmbH/oc-mall-plugin#581]
Checkbox properties are being saved to the database, but the saved property values are not being returned.  

Steps to recreate :

- Create a property group
- Assign more than one checkbox property
- Assign the property group to a category
- Update a product in that category
    - Tick a property checkbox , save and then CTRL + F5 the form

Expected result:

- Checkbox value saved to database
- Checkbox ticked state persists on form reload
- Checkbox property is output on  {% for entry in item.grouped_properties %} loop

Actual Result:

- Checkbox value saved to database (pass)
- Checkbox ticked state does not persist on form reload (fail)
- A checked value is not being returned in the  {% for entry in item.grouped_properties %} loop  (fail)

I have this on two sites/environments (both 469 build)

![Capture](https://user-images.githubusercontent.com/5227303/93099576-8063e800-f6eb-11ea-9879-58c367581212.PNG)

---------------

As a side note, I am also getting the same error screen as previously reported issue:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/531
That issue was closed with a potential work around, or at least a pointer to the cause. But nothing done to prevent the error from repeating - as far as I can tell.

**Comment by Tciferblatt** [comment]
I have the same problem. Property checkboxes not saving. Any solution?

**Comment by tobias-kuendig** [comment]
This bug is likely somewhere in this method (and in the same method on the Variant model):
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/c91f05ab2779369d4caf779dbd95213d73567ae4/models/Product.php#L327

**Comment by damanic** [comment]
The issue is here:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/c91f05ab2779369d4caf779dbd95213d73567ae4/models/PropertyValue.php#L85

OctoberCMS checkbox field expects value to be 1 or 0

Mall is returning a string value of `Checked` or `Unchecked`. Or equivalent translated string.

Why?!


The OctoberCMS checkbox field/widget evaluates if the checkbox field is selected here:

https://github.com/octobercms/october/blob/develop/modules/backend/widgets/form/partials/_field_checkbox.htm#L14

With function isSelected() 
https://github.com/octobercms/october/blob/develop/modules/backend/classes/FormField.php#L367

Mall returning a field value of `Checked` as a string does not qualify as `isSelected()`  .

**Comment by chrisvidal** [comment]
@damanic thanks
where do you return `returning (bool)$value` to fix this issue?

**Comment by chrisvidal** [comment]
yes, I am using the checkbox type in properties as well, and noticed this issue. returning ` (bool)$value;` in the `PropertyValue::class` fix the problem indeed.

**Comment by tobias-kuendig** [comment]
Thank you @damanic and @chrisvidal! I have fixed the handling of checkbox values in e9b8334.
