### ISSUE TITLE
Question: creating a product comparison / creating a custom view of products based on specific criteria

### ISSUE THREAD

**Issue by maartenmachiels** [OFFLINE-GmbH/oc-mall-plugin#582]
Hi,

First of - thanks for your fantastic work. The Mall-plugin is very impressive and I am very much enjoying working with it.
I've got a specific question. A client of mine wants to have a sort of wizard on his website, asking a bunch of questions, that would ultimately lead to a selection of products in a comparison view. The products he sells are a bit too technical for lay people, so that's where the wizard would help out.

On the demo theme, I see that we can do something like https://mall.offline.swiss/en/category/bikes?brand=cruiser-bikes&price=795.00-1284.47&color=think-pink&sort=bestseller to have a subselection. I think I can get the wizard to add those parameters to the url based on the answers of the client and have a subselection that way (by hiding the filters and product-overview untill all relevant questions have been filled out) - but I'm now wondering if that would be the best way to go about it:

- Is there any way to query products by their specifications via a model query? Something like: show all products with (custom) property `Lorem = ipsum`? Or is my thinking too simplistic?
- Would it be difficult to create a product comparison table then? 

Sorry if my question is a bit unclear. I'd be happy to provide more details. And thanks again for your great work.

**Comment by tobias-kuendig** [comment]
If you have a reasonable amount for products/variants there's nothing stopping you from simply querying the models using Eloquent's query builder. 

For larger installations, the plugin keeps a `offline_mall_indexes` table that contains all products and variants in a denormalized form. You can also run queries against this table and use the returned product/variant IDs to query the real models. This is essentially how the Products component works.

This is where this query is built, but you can easily build it with the fields you need:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/c91f05ab2779369d4caf779dbd95213d73567ae4/classes/index/mysql/MySQL.php#L176

I would suggest you build a custom component for this wizard feature. This way you are independent of the Products component which may change in the future.

**Comment by maartenmachiels** [comment]
Thank you for your advice, tobias. I will definitely try it as you suggested. Have a nice day!
