### ISSUE TITLE
Error after placing order on the demo site

### ISSUE THREAD

**Issue by maartenmachiels** [OFFLINE-GmbH/oc-mall-plugin#583]
Hi @tobias-kuendig ,

I was just trying to test out the invoice functionality on the demo platform. I first selected the Stripe payment method and used the provided test card number on the homepage.

This led to an error - and I received an email stating that there was an issue with the payment gateway. I then tried to select the "invoice" payment gateway. Unfortunately now the site throws the following error:

```
Type error: Argument 2 passed to Clockwork\DataSource\EloquentDataSource::__construct() must be an instance of Illuminate\Events\Dispatcher, instance of October\Rain\Events\Dispatcher given, called in /home/offlineg/public_html/_domains/mall.offline.swiss/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkServiceProvider.php on line 74
/home/offlineg/public_html/_domains/mall.offline.swiss/vendor/itsgoingd/clockwork/Clockwork/DataSource/EloquentDataSource.php line 35
```
![image](https://user-images.githubusercontent.com/3584586/93614516-87804400-f9d2-11ea-946e-f261ef2ab759.png)

Do you have an idea what might have gone wrong?

**Comment by maartenmachiels** [comment]
By the way, this is the error that is thrown right after purchasing with the test card details:

```
Failed to process your payment
Your order has been processed but the payment failed.

Please try again to pay this order.

The following error occurred:
Call to undefined method Omnipay\Common\Http\Client::getConfig()

Go to your order overview
```

![image](https://user-images.githubusercontent.com/3584586/93622228-0c705b00-f9dd-11ea-9b24-5ad157946084.png)

**Comment by tobias-kuendig** [comment]
Thank you for reporting this issue! It looks like some dependencies got messed up. I'll take a look at this.

**Comment by tobias-kuendig** [comment]
This was a problem with the demo website setup. The problem has been fixed.

**Comment by maartenmachiels** [comment]
Thank you @tobias-kuendig !
