### ISSUE TITLE
Custom items to index

### ISSUE THREAD

**Issue by panakour** [OFFLINE-GmbH/oc-mall-plugin#584]
I have some custom data that I want to use them in the index functionality of the mall plugin, Specifically using the mysql index https://github.com/OFFLINE-GmbH/oc-mall-plugin/tree/develop/classes/index/mysql 

For example I have a destination entity that is interact like categories in the product: 
![image](https://user-images.githubusercontent.com/12927166/93665661-ebf9dc80-fa80-11ea-9ad2-4fceb4acf144.png)

Is there any way to extend this without overwriting the plugin ?

**Comment by tobias-kuendig** [comment]
It is currently not possible to add additional data to the index table. There are two solutions:

1. You implement your own custom MySQL index (by extending the existing one) and [register it in the service container](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/registration/BootServiceContainer.php#L58).
1. We could add an event that allows you to hook into the indexing process and add your custom data. Adding more columns to the index table should be done by your extension plugin. The event calls could be added [here](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/index/ProductEntry.php#L38) and [here](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/index/VariantEntry.php#L46) (simply listen for an event and then merge all returned data into the `$data` variable. The event itself should receive the Product and/or Variant models. A possible event name could be `mall.index.extend`.

PRs welcome! That would be a great addition!

**Comment by tobias-kuendig** [comment]
Resolved by #585
