### ISSUE TITLE
Single Article (non-variants) do not show up [CRUCIAL]

### ISSUE THREAD

**Issue by amdad** [OFFLINE-GmbH/oc-mall-plugin#59]
When you add Article it didn't display on frontend at all. Only products with variants works.

**Comment by tobias-kuendig** [comment]
This was fixed in f0cfc16. You will have to reindex your data.

> php artisan mall:reindex

**Comment by amdad** [comment]
hurray! REINDEX? Isn't it new one? :) Shiny and chrome!

**Comment by amdad** [comment]
When you update Properties of Variant, frontend Filters reflects that right away. 
When you change Single Article properties.. nothing changes. 
Can you confirm it as bug?

**Comment by tobias-kuendig** [comment]
Thanks for pointing this out. It should be fixed in 0f07832.

Can you try again?

**Comment by amdad** [comment]
Issue continued in #62
