### ISSUE TITLE
Problem with adding/editing product "array_merge() expects at least 1 parameter, 0 given"

### ISSUE THREAD

**Issue by Tciferblatt** [OFFLINE-GmbH/oc-mall-plugin#592]
Hello, i have a problem with adding new or editing existing product. 

Build: 469. 
MALL version: 1.11.29

After the existing product editing or a new product adding on save i get an error:

"array_merge() expects at least 1 parameter, 0 given" on line 42 of /xxx/public_html/plugins/offline/mall/classes/index/ProductEntry.php

I haven't made any global changes in the code. Only in templates.

Thanks in advice for any help!

**Comment by tobias-kuendig** [comment]
Thank you for this bug report. It looks like this PR is the culprit: #585 

Are you using the `mall.index.extendProduct` event? If not, could you check what the `$result` and `$data` variables contain here:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/index/ProductEntry.php#L39

```php
dd($result, $data);
```

**Comment by Tciferblatt** [comment]
Thank you for fast response!
Sorry, I'm an entry-level user and I did not add any events myself.

dd($result, $data); dump attached to this message... 

[dump.txt](https://github.com/OFFLINE-GmbH/oc-mall-plugin/files/5328668/dump.txt)

I didn't understand anything there :(

**Comment by tobias-kuendig** [comment]
Thank you! Could you try the following changes in your `ProductEntry.php` and see if this fixes things?

Fix: https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/f07371d533bf07c6d3a022be307a8d7fb38832f0

**Comment by Tciferblatt** [comment]
> 
> 
> Thank you! Could you try the following changes in your `ProductEntry.php` and see if this fixes things?
> 
> Fix: [f07371d](https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/f07371d533bf07c6d3a022be307a8d7fb38832f0)

Thank you very much, this solution helped me! Everything is OK!

**Comment by tobias-kuendig** [comment]
Great, thank you!
