### ISSUE TITLE
How to restrict discounts

### ISSUE THREAD

**Issue by mogozay-zawmyintoo** [OFFLINE-GmbH/oc-mall-plugin#596]
I want user use only one discount at an order. Can someone instruct me how i should do

**Comment by tobias-kuendig** [comment]
You could extend the `DiscountApplier` component with your own, then override the `onApplyDiscount` method and check if there already is a discount applied to the cart:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/DiscountApplier.php#L43

**Comment by mogozay-zawmyintoo** [comment]
Thanks @tobias-kuendig

**Comment by tobias-kuendig** [comment]
Closing this as dupliceate of #375
