### ISSUE TITLE
mall:seed-demo generate empty images

### ISSUE THREAD

**Issue by PrestaSafe** [OFFLINE-GmbH/oc-mall-plugin#599]
hi, on a fresh install `php artisan mall:seed-demo`
generated empty images. 

<img width="1108" alt="Capture d’écran 2020-10-09 à 19 57 09" src="https://user-images.githubusercontent.com/4788787/95616167-aae65e00-0a69-11eb-9508-061a12341c38.png">

I'm the only one to have this issue ? 
Im on build 469.

Thanks.

**Comment by tobias-kuendig** [comment]
Can you confirm that you are on 1.0.469 for the library package?

    composer show october/rain | grep versions

October did change the handling of file attachments some days ago and there was a broken library version floating around. This might be connected to this.

I cannot reproduce the issue on build 469 myself. The File model gets created here:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/demo/products/DemoProduct.php#L75

This would be a good place to debug the issue.

**Comment by PrestaSafe** [comment]
Hello,
i've installed it with the installation wizard. I'll make it again with composer and i'll tell you the version. 

Thanks

**Comment by PrestaSafe** [comment]
Ok so i've installed it with composer, and i've the same issue.
`composer show october/rain | grep versions`
show me: 
`versions : * v1.0.469`
<img width="1358" alt="Capture d’écran 2020-10-13 à 09 50 28" src="https://user-images.githubusercontent.com/4788787/95831612-89bb9100-0d39-11eb-9abf-32277f790b07.png">

**Comment by tobias-kuendig** [comment]
Were you able to find out more about this problem? If not, I'll try to reproduce the issue tomorrow.

**Comment by PrestaSafe** [comment]
Nope, i've tried locally and remotely, same problem. But i didn't found why.

**Comment by tobias-kuendig** [comment]
Does this problem still exist? I'm pretty sure it is related to this change:
https://github.com/octobercms/library/commit/6cd6af6940ca15598ad1bab64e2db4a005d9d38f

**Comment by PrestaSafe** [comment]
i'll try it again i'll let you know. Thanks for the feedback.

**Comment by PrestaSafe** [comment]
Hi, 
it works with the latest october version and php 7.4

Thanks
