### ISSUE TITLE
Price field do not store data, on create new Product form

### ISSUE THREAD

**Issue by amdad** [OFFLINE-GmbH/oc-mall-plugin#60]
When creating new product, we have direct field to enter price value. After last changes of how prices are stored (separate tables) it do not save it's data. 

Only 'Edit stock and price values' save data correctly.

**Comment by tobias-kuendig** [comment]
I cannot reproduce this issue. The pricing info is stored correctly.

Is your db schema up to date? Can you try to run `php artisan mall:seed-demo` and see if the problem still exists?

**Comment by amdad** [comment]
I mean to catch the issue, do not update existing products. Because there is no problem on **products/update/X** form. But just on **products/create/X** form. So Create new product to see that.

**Comment by amdad** [comment]
I bet this Price field here, trying to store it's value in old **price** column in _products table. Which was moved from there to prices table, in last DB structure changes.
![image](https://user-images.githubusercontent.com/10062429/46127229-55e3a080-c230-11e8-83c0-6e81d419e651.png)

**Comment by tobias-kuendig** [comment]
See https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/controllers/Products.php#L63 to further debug the issue.

**Comment by amdad** [comment]
But you can confirm bug?

**Comment by tobias-kuendig** [comment]
No, not yet. It works on my local installation.

**Comment by amdad** [comment]
Ahh, false alarm. It was something with my localhost env. On server, no problem.  Sorry :)
