### ISSUE TITLE
General settings - CMS Pages List

### ISSUE THREAD

**Issue by panakour** [OFFLINE-GmbH/oc-mall-plugin#601]
In General settings the CMS Pages are taken from the current theme page that has a specific component name
If for example have a Cart page with a custom cart component called different than [cart] the page setting will not retrieve any page to connect the cart.

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/a59cce2bdbf7c056f5829d027438efd689ddc904/models/GeneralSettings.php#L66

wouldn't be better to just load all of the pages and just select what you want?

**Comment by tobias-kuendig** [comment]
Good point, thank you! I have fixed this issue in fa44732.
