### ISSUE TITLE
Proper way to create "Popular" products

### ISSUE THREAD

**Issue by Blinks44** [OFFLINE-GmbH/oc-mall-plugin#606]
Greetings! Excuse me if there was a question like this, but i could't find it. What is proper way to add "Popular" functionality to products. Maybe client wants to add popular products on frontpage, how to implement this?
I think checkbox in admin panel with Popular label would be enough. And on frontpage render only products with "Popular" checkbox, but i don't understand how to implement new field in Product and check it in frontpage loop.

Thank you very much!

**Comment by tobias-kuendig** [comment]
Popular by what measure? Sale number, page views, custom?

**Comment by Blinks44** [comment]
> Popular by what measure? Sale number, page views, custom?

Sorry, forget to add it.

I think checkbox in admin panel with Popular label would be enough. And on frontpage render only products with "Popular" checkbox, but i don't understand how to implement new field in Product and check it in frontpage loop.

**Comment by Blinks44** [comment]
However by page views is very interesting too, just for my education :)

**Comment by tobias-kuendig** [comment]
The easiest way to implement such a feature is to use October's plugin extension features:

1. Create a custom plugin, like `Blinks44.MallExtensions`
1. Add a `is_featured` column to the `offline_mall_products` table via a migration
1. [Use the `backend.form.extendFields` event](https://octobercms.com/docs/plugin/extending#extending-backend-form) to place a new checkbox on Mall's product form

Not sure if required:

1. [Extend the Product model](https://octobercms.com/docs/plugin/extending#extending-user-model) to include your `is_featured` column in the `$fillable` property

Now you can get all featured products on your homepage simply by running a query like `Product::where('is_featured', true)->get();`.

The same goes for page views (you'd have to count them yourself). If you want to show the best selling products you can use the already existing [`sales_count`](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/updates/create_offline_mall_products.php#L38) column on the product model.

https://octobercms.com/docs/plugin/extending

**Comment by Blinks44** [comment]
Thank you very much! I will try it.

**Comment by Blinks44** [comment]
I have some problem, when implementing this to products. When i add extra field "Popular" to product, on backend it appears not only in main editable section, but also in every modal window. How to keep this new field only once in main section?
![2020-11-03_11-55-25](https://user-images.githubusercontent.com/8570193/97965790-f7ecf400-1dcb-11eb-85bc-b6b902221de3.png)

**Comment by Blinks44** [comment]
Sorry, i forgot to check model, when creating new field. Now everything works fine!
