### ISSUE TITLE
Checkbox properties are not handled correctly when displaying the product

### ISSUE THREAD

**Issue by tobias-kuendig** [OFFLINE-GmbH/oc-mall-plugin#61]
With checkbox values there are not multiple `PropertyValues` as with every other type. In this case there is only one value that is either 0 or 1. 

Also, an additional label would be great so the user doesn't only see "Checked" or "Unchecked" but rather "With feature XY".

The easiest solution would be to remove the support for checkbox values since they can be emulated with dropdowns.

**Comment by amdad** [comment]
Dropdowns are not checkboxes. Checkboxes are not dropdowns. :) 
So I would rather suggest to improve how to handle checkbox rather get rid of it. 
But I'm not exactly understand from your description how it's look like. So can't propose possible solution yet.

**Comment by tobias-kuendig** [comment]
If you create a checkbox property for a product like `Is the special one` it gets rendered like this to the customer:

![image](https://user-images.githubusercontent.com/8600029/46095258-622e1600-c1bc-11e8-8a83-eb84647d0df1.png)

The customer should be able to choose via a dropdown even if this is a simple "Checked/Unchecked" property. But if this will be supported we need two more attributes to define a "checked label" (Special one) and "unchecked label" (Not the special one).

So I'm wondering if it woudn't make more sense to define this as a dropdown property and simply add two options "Speical one" and "Not special one". This would solve the problem in the fronend. In the backend you could no longer just tick a checkbox but you have to use the dropdown when editing the product.

**Comment by amdad** [comment]
Ok, I will think about it and test it then reply tomorrow about this. 
For now, can you check out issue #59? It's important one.

**Comment by tobias-kuendig** [comment]
Checkbox properties will not be part of the feature set of the initial release. This feature has been disabled in 6de7a65 to bring the plugin towards 1.0. 

We might include it in a later version if a valid use case is present.
