### ISSUE TITLE
sort = "manual" on more then one category

### ISSUE THREAD

**Issue by bmiskoski** [OFFLINE-GmbH/oc-mall-plugin#610]
Greetings,
The sort = "manual" functionality is great when working with a single category, is there a possibility to use that functionality but on more then one category. 
What i try to achieve is to have a slider with products which will allow me to sort the order of the products manually. The main problem is that i want to show products from all categories. The sort order works as expected when i use latest, or bestseller etc.
I can probably make a custom solution but i wanted to use the products component for showing the products.

**Comment by tobias-kuendig** [comment]
There is currently no way to specify a custom sort order that spans multiple categories. The `offline_mall_category_product_sort_order` table is there to store the order of each product inside a category. You would have to create another custom table, that is capable of handling the sort order for whatever scope you need.

**Comment by bmiskoski** [comment]
Thank you for the detailed answer.
