### ISSUE TITLE
Event not triggered on Customer registration

### ISSUE THREAD

**Issue by PrestaSafe** [OFFLINE-GmbH/oc-mall-plugin#611]
Hi, 

i've made a plugin who listening this event: 
``` php 
Event::listen('rainlab.user.register', function($user) {
            \trace_log('register USER');
            \trace_log($user);
        });
```
but, when i'm register a new customer on the front end, it's not working, 

if a trigger this event manually (with tinkerwell for exemple)
it works. 
```php
use Event;
$user = RainLab\User\Models\User::find(1);
Event::fire('rainlab.user.register',$user);

```
![Capture d’écran 2020-10-22 à 09 08 16](https://user-images.githubusercontent.com/4788787/96837121-32f33d00-1446-11eb-9528-d71582c9940a.png)

I'm missing something ?

**Comment by tobias-kuendig** [comment]
If you want to listen for customer signups, you can use the `mall.customer.afterSignup` event. The `rainlab.user.register` event is only triggered in the Account component of the RainLab.User plugin, we do not use this code.

https://offline-gmbh.github.io/oc-mall-plugin/development/events.html#customer

**Comment by PrestaSafe** [comment]
It works perfectly as always. 

Thanks ! You rock !
