### ISSUE TITLE
Quick question about checkout process order

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#619]
Right now, there is a predefined order in the process of checkout, it seems to be: 

when a user is logged-in:
- payment method, 
- then shipping method
- final check and place order

when user is not logged-in
- login or sign up
- payment method, 
- then shipping method
- final check and place order

how could I modify simply this order? I'd like to put the `shipping choice` before the `payment method`?

**Comment by Eoler** [comment]
> how could I modify simply this order? I'd like to put the `shipping choice` before the `payment method`?

Yeah, everyone orders it that way (except perhaps those nice Swiss people :) so it was added in 1.12.1: #303

**Comment by chrisvidal** [comment]
> Yeah, everyone orders it that way (except perhaps those nice Swiss people :) so it was added in 1.12.1: #303

Looks awesome! thanks
