### ISSUE TITLE
"dataLayer is not defined" after started from scratch

### ISSUE THREAD

**Issue by Blinks44** [OFFLINE-GmbH/oc-mall-plugin#621]
Hello! I've started dev project with mall plugin from scratch, after "Getting started" section in "Theme setup" section i ran into a problem. After creating category.htm with suggested code, ajax filters works only once and the page always show this error in console:

![2020-10-30_23-08-20](https://user-images.githubusercontent.com/8570193/97752964-0acea280-1b06-11eb-8fea-d3b6ceb95e0c.png)

![2020-10-30_23-16-44](https://user-images.githubusercontent.com/8570193/97752958-099d7580-1b06-11eb-8ab8-bc916e585407.png)

What am i doing wrong? It is 5 minutes after installation, very sad that i can't figure it out :(

**Comment by Eoler** [comment]
`dataLayer` Javascript variable comes from Google Analytics (Tag Manager, Merchant...?) so you can try disabling Google Merchant Center Feed in Mall's backend settings, or install GoogleAnalytics plugin and put `Google Analytics tracker` component somewhere close to start of the page (after title/canonical meta tags).

**Comment by Blinks44** [comment]
Thank you very much!
