### ISSUE TITLE
Need advice to understand shop functionality.

### ISSUE THREAD

**Issue by Blinks44** [OFFLINE-GmbH/oc-mall-plugin#624]
Greetings! Can anyone help me to understand how to implement common feature:

I want to create test magazine with clothes and i need to categorise each item (men, women), customers can click in menu on frontpage and go to all catalog for men, women or for everyone. 

So each cloth will be for men or for women. What best practice to do this task? Do i need to create 2 parent categories Men and Women and create child categories for them, for example Coats-men, Coats-Women or what? Thank you!

**Comment by chrisvidal** [comment]
I would start with the official theme for the plugin here: https://github.com/OFFLINE-GmbH/oc-mall-theme

**Comment by tobias-kuendig** [comment]
You can also check out the demo page: https://mall.offline.swiss/

You can log in to https://mall.offline.swiss/backend using the password an username `demo`.

There is also the `php artisan mall:seed` command that creates some demo content for you to tinker around with. 

Last but not least, there are a few tips on how to structure your show in the official docs:

* https://offline-gmbh.github.io/oc-mall-plugin/digging-deeper/properties.html
* https://offline-gmbh.github.io/oc-mall-plugin/digging-deeper/categories.html
* https://offline-gmbh.github.io/oc-mall-plugin/digging-deeper/products.html


Without knowing the details, from what you described, you might want to create a structure like this:

* Clothing
  * Men
    * Coats
    * ...
  * Women
    * Coats
    * ...
