### ISSUE TITLE
array_key_exists() error in pages/category if category has property group with property of type "Color"

### ISSUE THREAD

**Issue by lieszkol** [OFFLINE-GmbH/oc-mall-plugin#633]
How to reproduce: create a property group with one property with field type "Color". Set "Use for variants" to ON (although I'm not sure if this matters). Create a category and assign this one property group to it. Add a product to this category. Now navigate to the `/category/category-slug` page of your site to view all products in this category.

Error:
`array_key_exists(): The first argument should be either a string or an integer
/var/www/hungraszept.hu/public_html/themes/hungraszept-emarket/pages/category.htm line 1691`

Trace:

55 | array_key_exists(…) | ~/vendor/laravel/framework/src/Illuminate/Support/Collection.php | 1695
-- | -- | -- | --
54 | Illuminate\Support\Collection->offsetExists(…) | ~/plugins/offline/mall/models/Property.php | 110
53 | OFFLINE\Mall\Models\Property::OFFLINE\Mall\Models\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Support/Collection.php | 1400
52 | Illuminate\Support\Collection->sortBy(…) | ~/plugins/offline/mall/models/Property.php | 111
51 | OFFLINE\Mall\Models\Property::OFFLINE\Mall\Models\{closure}(…) |   |  
50 | array_map(…) | ~/vendor/laravel/framework/src/Illuminate/Support/Collection.php | 861
49 | Illuminate\Support\Collection->map(…) | ~/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php | 139
48 | Illuminate\Database\Eloquent\Collection->map(…) | ~/plugins/offline/mall/models/Property.php | 112
47 | OFFLINE\Mall\Models\Property::getValuesForCategory(…) | ~/plugins/offline/mall/components/ProductsFilter.php | 428
46 | OFFLINE\Mall\Components\ProductsFilter->setProps() | ~/plugins/offline/mall/components/ProductsFilter.php | 284
45 | OFFLINE\Mall\Components\ProductsFilter->setData() | ~/plugins/offline/mall/components/ProductsFilter.php | 301

Cause: see line 109 in models/Property.php, under `public static function getValuesForCategory($categories)`:

`return $order[$value->value] ?? 0;`

In case of colors, $value->value is itself an array, for example: ['name'=>'White', 'hex'=>'#ffffff'], thus the above line will fail. 

I'm creating a pull request to address this.

**Comment by tobias-kuendig** [comment]
Fixed via #634, thank you @lieszkol!
