### ISSUE TITLE
Group products by variant color

### ISSUE THREAD

**Issue by mskraban** [OFFLINE-GmbH/oc-mall-plugin#635]
Is possible to group products by variants property color only?

For example I made 6 products with 3 colors.
1 Red
3 Blue
2 Green

Instead of displaying all of 6 products, I would like to display only 3 of them (one per different color).

**Comment by chrisvidal** [comment]
I think this is prebuilt in the plugin using the properties:
check this out: https://mall.offline.swiss/en/category/clothing?color=red&sort=bestseller

**Comment by mskraban** [comment]
Not exacly what I'm trying searching for.
### **This is only filtering by specific color:**
![GitHub Logo](https://i.ibb.co/pRr1Qp9/001.jpg)


### **And I'm searching for something like this: (Group by variant color)**
![GitHub Logo](https://i.ibb.co/j8QX6KQ/002.jpg)

**Comment by chrisvidal** [comment]
it is quite the same, you just need to set `false` to the param `includeVariants` in the component `Products`

**Comment by mskraban** [comment]
`false` parameter only hides variants. But I want to group variants by color.
### Here is another example:
One product with 6 different variants. They have 3 different colors.
![Drag Racing](https://i.ibb.co/1ZW2TKc/0001.jpg)
### And I want only one of single color to be visible (products grouped by color property)
![Drag Racing](https://i.ibb.co/D9r9GGp/0002.jpg)
Is this possible?

**Comment by chrisvidal** [comment]
I don't understand your case, what is your product to illustrate?

**Comment by mskraban** [comment]
@chrisvidal Yes this images are only to illustrate my problem and question.

**Comment by tobias-kuendig** [comment]
:thinking: I don't think this is currently possible. You would have to create three products (Shirt Green, Shirt Blue and Shirt Red) in this case, then group the variants. Obviously, this is not ideal. You can currently only show all variants or just the product (grouped variants).

Another option is to extend the built-in `Products` component and override the `getItems` method with your own implementation:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/Products.php#L338

If there is an event we can add to help with this use-case let me know. I'd have to dig into the code myself to find out how to implement it best.

**Comment by mskraban** [comment]
Thanks @tobias-kuendig for explanation. This was only a curious question for this use-case scenario. There is also no need for implementation.
