### ISSUE TITLE
custom payment fields at checkout plus validation

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#637]
Hello again. I've created a custom payment gateway for Sagepay Direct, based on what you did for Stripe.
For testing I hard-coded the credit card, expiry date and cvv into the Sagepay class. All works OK.
I now need to include a partial at checkout to collect this data.
Examining `\classes\payments\PaymentProvider.php`, the code on line 131 expects the custom file in `/public_html/themes/partials/mall/payments/sagepay/form.htm`. This works: https://prnt.sc/vlhf1m .
However, is this intended? I would expect the file to be located in my theme, e.g.  `/public_html/themes/my_theme/partials/mall/payments/sagepay/form.htm`.

I've also added validation in the Sagepay class for the credit card number...
`public function validate(): bool
    {
        $rules = [
                 'sagepayCardNumber' => 'required|size:16',
        ];
        $validation = Validator::make(post(), $rules);
        if ($validation->fails()) {
            throw new ValidationException($validation);
        }
        return true;
    }`

if it fails, this throws an exception, but the overlay is hanging. see https://prnt.sc/vli6vd
Would you have any ideas how to cancel the overlay? Is this even the best approach for data collection and validation?

Thank-you.

**Comment by dathwa** [comment]
Testing on clean install with mall theme, going through checkout, if i edit validation rules in `plugins/offline/mall/classes/payments/Stripe.php`, changin "28" to "99"
`$rules = [
            'token' => 'required|size:99|regex:/tok_[0-9a-zA-z]{24}/',
        ];`
this forces validation to fail, we stay on the page, but the "proceed" button is disabled - https://prnt.sc/vllev3 - and unable to proceed without refreshing page. 
Can this be fixed? 
Thank-you.

**Comment by tobias-kuendig** [comment]
> However, is this intended? I would expect the file to be located in my theme, e.g. /public_html/themes/my_theme/partials/mall/payments/sagepay/form.htm.


Good find! This is fixed in df45fc2.

> if it fails, this throws an exception, but the overlay is hanging. see prnt.sc/vli6vd

Make sure to call `$overlay.hide();` in the error handler of your request:
2216d0f

> this forces validation to fail, we stay on the page, but the "proceed" button is disabled 

This has been fixed in bbaf0e3

Thank you for this feedback!
