### ISSUE TITLE
ProductFilters issue

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#638]
any changes have been made to the productFilters component recently?

I can't seem to be able to filter anymore on my current project,
not only the filtering is not happening (all products are rendered) but I received this AJAX error `AJAX handler 'products::onRun' was not found.` noticing that the URL has been updated/replaced from `mydomain.com/shop` to `mydomain.com/?on_sale=✓&sort=price_low`. The URL segment `shop` disappeared, and I have no idea why that.

Any idea what could happen here please?

![image](https://user-images.githubusercontent.com/2263496/99757785-1290ce00-2b2b-11eb-9b58-976dec647923.png)

**Comment by tobias-kuendig** [comment]
I'm not sure what could have caused this error. Maybe check the git history of the related files, but I don't think we made any changes to these components in the last few releases.

Let me know if you find the issue.

**Comment by chrisvidal** [comment]
i am trying to trace back the problem, but so far I didn't find much.
What I identified so far is that it works fine if I comment this js line in the `scripts.htm` from the `productFilters` component:


```javascript
if (response.responseJSON.hasOwnProperty('queryString')) {
                            history.replaceState(null, '', '?' + response.responseJSON.queryString)
                        }
```

**Comment by Blinks44** [comment]
I have problems too. Fresh install (2 weeks ago), all original markup saved, filters work 2-3 times out of 10... I've recorded a small video fragment, you can view it online - https://yadi.sk/i/9D_ks2ONvcTdGA

**Comment by tobias-kuendig** [comment]
That is very strange. It could be a race condition between the different response handlers in the JS code. By @Blinks44 video it looks very much like that because the URL does not get updated after every request.

**Comment by Blinks44** [comment]
I didn’t add any js, except default mall scripts. And very strange, that even when url changes, partial with products sometimes doesn’t update

**Comment by chrisvidal** [comment]
ok after quite a long research, i found my error;
I had a HTML `base url` tag in the meta of my layouts, something like ```twig<base url="{{ URL(') "/>``` 
but apparently this is rerouting the `html.replaceState()` to this base URL as well. good to know
