### ISSUE TITLE
List subcategories for active category

### ISSUE THREAD

**Issue by Blinks44** [OFFLINE-GmbH/oc-mall-plugin#645]
I have same issue as this - https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/352

But the code in the solution only works for grand parent, because i have this structure for categories:
- For Men (slug: catalog-men)
-- Bags
-- Shoes (slug: shoes, in frontend this is catalog-men/shoes)
- For Women (slug: catalog-women)
-- Bags
-- Shoes (slug: shoes, in frontend this is catalog-women/shoes)

And for category "For Men" the code
```
Category::where('slug', $this->param('slug'))->first();
```
works fine, but for "For Men - Shoes" it returns null, because param('slug') returns "catalog-men/shoes" and there is not category with this slug.

When i try to get category only by slug "shoes", mall doesn't understand what category "For Men" or "For Women" to get, because of same url and gets the first one...

So the question is: how to get child categories based on current category that knows who is her parent (Men or Women)?

I can change same urls and it works fine, but i want to understand, is this posible with same url based on parent or not.

Thank you!

**Comment by tobias-kuendig** [comment]
There is a `getByNestedSlug` helper method you can use:

```php
$category = Category::getByNestedSlug('catalog-men/shoes');
```

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/traits/category/Slug.php#L73

**Comment by Blinks44** [comment]
Thank you very much!
