### ISSUE TITLE
Min Password for Login is hard-wired

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#646]
My use case is I have inherited users with small passwords.
I see the min password length is hard coded [here](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/c5262e645dc5559902c58e07caa79af9f37022a6/classes/customer/DefaultSignInHandler.php#L93).
Rainlab User has a config file with a setting [here](https://github.com/rainlab/user-plugin/blob/a7b42f2e15cb410e906c9ba40db9e4a28103af48/config/config.php#L10) which can be over-ridden.

Can we update DefaultSignInHandler.php to use this setting instead?

**Comment by tobias-kuendig** [comment]
Great idea! Added in 143715d

**Comment by dathwa** [comment]
Hi Tobias.
Almost :(
It's the `DefaultSignInHandler.php` that is giving me grief. 
Agreed, we need it in the `DefaultSignUpHandler.php` too.
Specifically, I need this for users who registered before the Mall plugin was installed.
Can you apply the same changes to `DefaultSignInHandler.php`?

Thank-you

**Comment by tobias-kuendig** [comment]
Ah, I didn't see it is used there as well. You can use the same code. I added it here:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/2dc4ad3a0a4136dadb64e99a87f8fcab7a28ce44
