### ISSUE TITLE
How to include important customer info in the admin order notification?

### ISSUE THREAD

**Issue by zlobec** [OFFLINE-GmbH/oc-mall-plugin#648]
I see much need for the customer's email to be included in the admin order notification. And also even the phone number.

Now the process to get the email as stands, the person who processed emails has to login to the backend, find the order and then copy the email address of the customer in order to reply to the customers order for any additional information, like the phone number.

I checked #172, and got to the point where the phone number could be added after the user has created its account or even the order ... But in the e-commerce sense, this option is not viable. To collect the phone number is a crucial information regarding any order (shipping, CRM, marketing, etc.).

My knowlede of laravel and octobercms is not sufficient to understand how the Customer and User models interact, but I am willing to learn. Could somebody help me with this problem?

I currently have 3 websites that have the need to add this information to the sales process. I held of my clients as much as I could, but I need to come back with a fix for this. Switching to any new e-commerce platform will cost too much.

**Comment by tobias-kuendig** [comment]
> I see much need for the customer's email to be included in the admin order notification. And also even the phone number.

You can change the e-mail contents via October's backend: For example, see Settings -> Mail templates -> Partials (Tab) -> mall.customer.address

**Comment by tobias-kuendig** [comment]
I have added the email address to the default mail partials in 1b6d008.

**Comment by tobias-kuendig** [comment]
Feel free to reply to this issue if you have any further questions.
