### ISSUE TITLE
Broken validation If extend Rainlab.User plugin, and add validation rule

### ISSUE THREAD

**Issue by ref** [OFFLINE-GmbH/oc-mall-plugin#654]
I add new field `phone` to RainLab User model.

And if i add new validation rule (phone), i always got validation error when i try create new user from frontend.

```php
public function boot()
{
    ...

    User::extend(function ($model) {
        $model->addFillable(['phone']);
        $model->rules['phone'] = 'required'; // if i add this rule, i got validation error
    });
}
```

Send my form:
<img width="603" alt="Screenshot 2020-12-02 at 14 37 02" src="https://user-images.githubusercontent.com/505388/100842750-e28ee680-34ab-11eb-806f-94a353af9518.png">

Validation error:
<img width="691" alt="Screenshot 2020-12-02 at 14 37 09" src="https://user-images.githubusercontent.com/505388/100842787-ecb0e500-34ab-11eb-8c3a-9b6afbfe6db3.png">

**Comment by ref** [comment]
I find problem. It's method [onSubmit](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/CustomerProfile.php#L65) in `OFFLINE\Mall\Components\CustomerProfile`

It's save only name, email and password, and other fields will be ignored. `phone` field transmitted but ignored, and i get validation error.

To extend model User and add field without validation error:
```php
User::extend(function ($model) {
    $model->addFillable(['phone']);
    $model->rules['phone'] = 'required';

    $model->bindEvent('model.beforeSave', function() use ($model) {
        if (Input::has('phone')) {
            $phone = Input::get('phone');
            $model->phone = $phone;
        }
    });
});
```

**Comment by tobias-kuendig** [comment]
Great code example, thank you! Also see #172 for related info and progress.

**Comment by maartenmachiels** [comment]
Hi @ref , thank you for your code. Did you do anything else to get this working? Your code is very clear and useful, but the only thing I'm running into is the same issue when signing up or changing the user profile field. The input field phone just keeps saying that the field is required, even with your code. Thanks in advance for any additional insights.

**Comment by ref** [comment]
> Hi @ref , thank you for your code. Did you do anything else to get this working? Your code is very clear and useful, but the only thing I'm running into is the same issue when signing up or changing the user profile field. The input field phone just keeps saying that the field is required, even with your code. Thanks in advance for any additional insights.

Hi! You need change event from 'model.beforeSave' to 'model.beforeValidate' and it work again.
I don't know why my sample stop working, but change event will work :)

**Comment by maartenmachiels** [comment]
Hi @ref, `model.beforeValidate` works like a charm. Thank you!
