### ISSUE TITLE
Registering new user via register form on login page

### ISSUE THREAD

**Issue by bmiskoski** [OFFLINE-GmbH/oc-mall-plugin#660]
Greetings,

I am experiencing problems with the sign up form on the login/register page.

The problem is that the form on submit loads indefinitely and doesn't show any confirmation, but the user is added in the User plugin and can be logged in. No error is shown.

I've tried to implement the plugin on a different website also built on OctoberCMS, there i do the same setup and get this error:

Flash message:
![image](https://user-images.githubusercontent.com/58108005/100996793-c77ab000-3559-11eb-819b-2a4964b48964.png)

User is still being added in the User plugin, and can be logged in.

Thanks in advance.

**Comment by tobias-kuendig** [comment]
You can find the full stack trace in your `system.log` file and see where the error comes from. With just this message it's hard to help you as it could come from literally everywhere.

**Comment by bmiskoski** [comment]
From the logs:

[2020-12-03 12:13:33] development.ERROR: Swift_TransportException: Expected response code 250 but got code "421", with message "421 4.4.2 s615.loopia.se Error: timeout exceeded
" in /www/webvol19/7f/pfgykmms599cjhd/holiyaytravel.com/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:457

Hope this helps ...

**Comment by bmiskoski** [comment]
I didn't set up my mail configuration as i should have.

I'm sorry for wasting your time, thanks for the fast response.

All the best.
