### ISSUE TITLE
Virtual Product link error if not logged in

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#661]
Here's the scenario.
Log in, purchase a virtual product (e.g. MP3), log out.
Check emails.
"Hi Billy
Your downloads are ready! Please use the links below to download your purchases:
Download Good Tune
valid until 2020-12-08
max. 1 downloads"

Clicking on the link we get a page error...
`Symfony\Component\Debug\Exception\FatalThrowableError: Class 'OFFLINE\Mall\Classes\Downloads\Session' not found in /public_html/plugins/offline/mall/classes/downloads/VirtualProductFileDownload.php:94`

All works fine if the user is logged in.

Can you please help? Thank-you

**Comment by tobias-kuendig** [comment]
That was a missing import, thank you!

Fix: https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/f62f4f096889f11d34c4e45ebe0ea8bbc2d678a1
