### ISSUE TITLE
How to remove products in cart when logged out

### ISSUE THREAD

**Issue by MariusGi** [OFFLINE-GmbH/oc-mall-plugin#662]
Hello,
I would like to remove cart products when user logs off.

This is confusing because when person who is not logged in adds a product and logs in he has his previous basket plus added product which I believe user rarely wants.

**Comment by tobias-kuendig** [comment]
If you use the stock RainLab.User `Session` component, you can listen for the `rainlab.user.logout` event and access the cart via `$user->customer->cart`:

https://github.com/rainlab/user-plugin/blob/9105ef11182bd46046e542ba5617c777661f4db1/components/Session.php#L145

**Comment by MariusGi** [comment]
@tobias-kuendig Hmm i get **null** when I dump $user->customer->cart. I also dumped $user->customer and there seems no cart model.

``class Plugin extends PluginBase
{
    public function registerComponents()
    {
    }

    public function registerSettings()
    {
    }

    public function boot()
    {
        Event::listen('rainlab.user.logout', function($user) {
            dd($user->customer->cart);
        });
    }
}``

I also tried pasting Event::listen directly into session component, same result. What could be wrong here?

**Comment by chrisvidal** [comment]
I usually insert my listener into a `'init.php` file at the root of my plugin

**Comment by MariusGi** [comment]
Thanks, this could be cleaner way. However I still get null.
Am I doing something wrong?

**Comment by MariusGi** [comment]
Solved using this code in init.php

```
<?php

use OFFLINE\Mall\Models\Cart;

Event::listen('rainlab.user.logout', function($user) {
    $cart = Cart::byUser($user);
    $cart->delete();
});
```
