### ISSUE TITLE
Quantity step

### ISSUE THREAD

**Issue by damsfx** [OFFLINE-GmbH/oc-mall-plugin#669]
Expected behavior : 
Add product to cart by 2 (or more) rather one by one.

It could be interesting to be able to adjust the quantity step when adding to the basket.  
A product is available in a minimum quantity and when I add it to the cart I can specify the quantity added.

For example:  
Product's "cart properties"
 - `quantity_default` = 2
 - `quantity_step` = 2
So my product quantities will be 2, 4, 6 ...

The input field used could take advantage of the `step` attribute. (ref: [MDN Input/number](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/number#step))
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/0c2bab4355458f448b7d0e4c50fa7ff277f6b852/components/product/addtocart.htm#L16

Has anyone experienced a similar situation before?

**Comment by tobias-kuendig** [comment]
This is a rather specific requirement. Have you tried implementing this as a plugin extension?

You could

1. Add a new `quantity_step` column to the products tabe
2. Add a new form field using [October's backend form extension](https://octobercms.com/docs/plugin/extending#extending-backend-form)
3. Use the new `quantity_step` value  in the partial you have linked above (overritten in your theme)

**Comment by damsfx** [comment]
Thank you for the answer.

I am going to direct my thoughts in this direction.
