### ISSUE TITLE
Optimize component naming

### ISSUE THREAD

**Issue by tobias-kuendig** [OFFLINE-GmbH/oc-mall-plugin#67]
New proposed names:

* `Category` -> `ProductList`
* `Product` -> `ProductDetail`
* `CategoryFilter` -> `ProductFilter`

**Comment by amdad** [comment]
That's right! I'll do this simple changes. But.. promoted products are a little bit more complicated.

**Comment by tobias-kuendig** [comment]
If you can do this and #40 together that would be great and prevent some nasty merge conflicts!

Leave promoted products for later.

**Comment by amdad** [comment]
Alright, sorry for delay but serve issues stole the night :)

**Comment by amdad** [comment]
I'm was about to change this, but I want to propose first this. Why not like this:

Category -> **Products** 
Product -> **Product** (keep the name)
CategoryFilter -> **ProductsFilter**

Especially changing Product to ProductDetail I see as unnecessary complication. Or you have any real reason for that?
**Products** and **Product**, like Rainlab.Blog **Posts** and **Post** components. Simple as that.

I'm not sure about English here, but it seems both  ProductFilter and **ProductsFilter** are correct. But in our case this one is tightly connect to **Products** component, works as it's extension. So to naming can reflect that. What do you think?

**Comment by tobias-kuendig** [comment]
Good points, let's go with your suggestions :+1:
