### ISSUE TITLE
[quickCheckout] payment working?

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#674]
Does anyone manage to make the payment work with the quickCheckout component?

I am trying with Stripe and with my own payment provider but I am facing some error, which was working fine with the normal checkout previously.

error in javascript:

```javascript
VM5230:75 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null
    at stripeTokenHandler (<anonymous>:75:35)
    at <anonymous>:65:29
```

which come from this line I guess from `classes/payment/stripe/form.htm`

```javascript
var submit = form.querySelector('.oc-loading')
```

the form is never submitted.

also when I inspect the HTML code of the quickCheckout page, I do not find any `#mall-payment-form`, is that normal?

somehow it works fine on the online demo `https://mall.offline.swiss/`
hence I wonder what did change with the new `quickCheckout` component that I might have overide before?

**Comment by chrisvidal** [comment]
I found my error, I didnt resolve the Promise properly in my payment method HTML form and javascript code.

**Comment by PubliAlex** [comment]
Could make stripe working, but I also noticed that #mall-payment-form selector that doesn't exists in quickcheckout form. It's probably a rest of the old checkout system, but my payments works so I didn't touch anything ^^
