### ISSUE TITLE
How to customize stripe form ?

### ISSUE THREAD

**Issue by Zmove** [OFFLINE-GmbH/oc-mall-plugin#676]
Hello,

What is the way to customize the default stripe form ? (for example remove zip code, or put form in several separate fields instead of one "multi-field" that is not always the most understandable for non-tech users)

Thank you

**Comment by chrisvidal** [comment]
you need to add your own partial in your theme here:

`partials/paymentSelectorMethod/gateways/stripe.htm` => for the card form

`partials/paymentSelectorMethod/paymentmethods/stripe.htm` => for the existing saved card

**Comment by Zmove** [comment]
I found another solution, creating partial under /partials/mall/payments/stripe/form.htm

**Comment by tobias-kuendig** [comment]
@Zmove that is the suggested method :+1:
