### ISSUE TITLE
Multiple checkbox property type ?

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-mall-plugin#679]
Hello,

I have some products that would need a multiple checkbox widget to select properties. It's for beauty products, that can be for several skin type. So, I would think that I could create multiple checkbox property to select different skin types by products, and then, use filters depending on the checked skin types.

But it seems that I only have single checkbox option for each property, do you have some tips to give to handle that problematic ?

Thank you

**Comment by chrisvidal** [comment]
I had the same type of needs for food products.
What I did, from the top of my head:
- one property per filter, not a checkbox but a switch I think (one of these twos, cant remember for sure)
- I override in my theme the `property.htm` that render this type of property in the filter, instead of display 2 checkbox (for true and false) which is the default behavior of Mall, I display only one checkbox

hope that helps

**Comment by PubliAlex** [comment]
I came to the same conclusion, created X single checkbox property instead of one property with multiple checkbox.

In the backoffice, the render is quite the same, and I have to adapt the display of the filters to group them in a single list.

**Comment by tobias-kuendig** [comment]
This sounds like a good solution. Having multiple values in a single property is a pretty complicated addition and nothing I can see in the near scope of this plugin. If someone comes up with a PR we can implement it, but given there are other solutions, I don't think it's worth it!

**Comment by PubliAlex** [comment]
The biggest problem when you handle multiple single checkboxes to manage several options that all can be checked is the display of filters on the frontend.

It display a title per checkbox, with a yes / no value for each.

To avoid managing multiple choice per property that change way property are managed deeply, it would be great to add an option called "filter group" or something like that, that appears when you use the checkbox field type, and that allow to put a name of the group.

All checkbox that belongs to the same group would be displayed that way : 
Group name
- checkbox 1
- checkbox 2
- checkbox 3

It could be a quite simple solution to manage multiple checkboxes without changing deep behaviors
