### ISSUE TITLE
[critical bug] wrong tax calculation when vat rate applied on product is different than vat rate applied on shipping

### ISSUE THREAD

**Issue by Zmove** [OFFLINE-GmbH/oc-mall-plugin#684]
Hello,

I have a VAT setup like this : 

![vat-settings](https://user-images.githubusercontent.com/1314678/102527284-29303380-409d-11eb-8dae-1267a11fb9e8.jpg)

I have a product setting like this : 

![vat-on-product](https://user-images.githubusercontent.com/1314678/102527326-38af7c80-409d-11eb-9b6e-3feff1791712.jpg)

I have a shipping setting like this : 

![vat-on-shipping](https://user-images.githubusercontent.com/1314678/102527346-406f2100-409d-11eb-91d9-4fc8e44422b0.jpg)

Here is an exemple of my shopping cart subtotal for 2 products of 55€ applied to the cart : 

![vat-bug](https://user-images.githubusercontent.com/1314678/102527373-4b29b600-409d-11eb-9356-40e973c217a4.jpg)

The calculation is completely bugged : 

- The 5.5% VAT amount should be 5.73€ (extracted from 110€)
- The 20% VAT amount should be : 2.50 (extracted from 15€)
So, the total of the tax should be : 8.23 (5.73 + 2.50)

So the calculation is completely wrong, I even couldn't explain what the system try to do, values are just nonsense

**Comment by Zmove** [comment]
I update that issue with the latest infos I could get.

It seems the default option for tax is for small shops that only one tax for everything (correct me if I'm wrong). If I set "default" to off to both tax, and assocate the right tax to the right element, I have a correct tax calculation on my backend orders.

But the system is unable to display any taxes before the order creation (cart, checkout, etc...)

I can understand that the system needs to know the shipping country in order to display the right tax for the right country, but : 
- It should display the tax in the checkout as soon as you selected a country, which is not the case
- When your tax have no country restriction (so apply worldwide), it should be able to display tax on the cart

Best regards

**Comment by SamBrishes** [comment]
Hello,

short update to this issue, as far as I could test, this problem should be fully solved with the upcoming 3.2.0 release and the new PriceBag handling. (#1082)

~ Sam.

**Comment by SamBrishes** [comment]
This issue has been fixed and released with v3.2.0 / v3.2.1.
