### ISSUE TITLE
Add more return infos in the addToCart() method of product component.

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-mall-plugin#692]
Hello,

I would like to display a nice confirmation popup when you successfully add a product to the cart instead of the default flash message.

the function return the following array : 

        return [
            'item' => $this->dataLayerArray($product, $variant),
            'currency' => optional(Currency::activeCurrency())->only('symbol', 'code', 'rate', 'decimals'),
            'quantity' => $quantity,
            'new_items_count' => optional($cart->products)->count() ?? 0,
            'new_items_quantity' => optional($cart->products)->sum('quantity') ?? 0,
            'added' => true,
        ];

and the item subarray contain the following fields : 

        return [
            'id' => $item->prefixedId,
            'name' => $product->name,
            'price' => $item->price()->decimal,
            'brand' => optional($item->brand)->name,
            'category' => optional(optional($item->categories)->first())->name,
            'variant' => optional($variant)->name,
        ];

I think the returned array is too much limited. For example, if you want to display the just added product or variant images in the confirmation popup, which is a quite regular need. I would add a reference to the full object in the returned array.

What do you think about this ?

Best regards,

**Comment by tobias-kuendig** [comment]
That makes sense, we could add a `product` key that returns the Product or Variant model and leave the rest as is.

Would you mind creating a PR for this?

**Comment by tobias-kuendig** [comment]
Nevermind, I just added this in c91129f, thank you for your input @PubliAlex!

**Comment by tobias-kuendig** [comment]
Addition in 6b89c48

**Comment by PubliAlex** [comment]
Hello,

I think you have to check for the existence of $variant before return it in the following line of your commit :

`'variant' => $variant->only($this->getPublicAttributes()),`

Because, when I try to add a product without variant to the cart (for example a gift card created with the mall:seed-demo command), I get an error : 

> "Call to a member function only() on null" on line 570 of /plugins/offline/mall/components/Product.php

If I comment that line, it works.

**Comment by tobias-kuendig** [comment]
That's true, thank yor for pointing this out! Fixed in 5998e99.
