### ISSUE TITLE
Make customer_id for Address model fillable

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-mall-plugin#695]
Hello,

I want to customize the addressbook and the way addresses are added. To do that, I don't use the addressForm component but created my own onUpdateAddress and onCreateAddress methods.

Globally, it works well except that the address model require a 'customer_id' relation (which is comprehensible) but the 'customer_id' attribute is not $fillable. That prevent me to manually create address.

Fortunately, there is an easy fix, just add the 'customer_id' attribute to the $fillable array in the Address model.

Best regards,

**Comment by tobias-kuendig** [comment]
We can make the field fillable, no problem! Would you mind creating a quick PR with this change?

**Comment by Zmove** [comment]
Sure, here is it #699

**Comment by tobias-kuendig** [comment]
Awesome, thank you very much @Zmove :+1:
