### ISSUE TITLE
Language switching is broken

### ISSUE THREAD

**Issue by amdad** [OFFLINE-GmbH/oc-mall-plugin#70]
It seems like almost-permanent cache issue. 

1. When you change language by frontend lang switcher categories in do not change itself to match new lang, stays on en versions. Sometimes it does switch, but then switch back doesn't work. So it seems like it cannot refresh lang/translation page/cache like it should. But this can be other reason it didn't work. 

2. Even if you type whole url with translated slugs, it gives error.

![image](https://user-images.githubusercontent.com/10062429/46452333-8a5cdc80-c79b-11e8-8c32-6a2b252d0454.png)
![image](https://user-images.githubusercontent.com/10062429/46452251-1c181a00-c79b-11e8-9c05-d2d125c7bc59.png)

**BUT, not every time**. When site somehow switch itself to Deutsch, then category will open from this link. Those two are critical to access translated content. 
But also, one feature are missing to full translations support:

3. URLs, are not translated on lang switch. Only prefix are changed.
So in this case:
https://mall.offline.swiss/en/category/bikes/mountainbikes
should be switched to:
https://mall.offline.swiss/de/category/translation-test/bekleidung

**Comment by tobias-kuendig** [comment]
Thank you for the detailed bug report. This is fixed in f2e02de1d74b14d06348e66560c7d3933d6f987f

Make sure to run `php artisan cache:clear` before testing.
