### ISSUE TITLE
Composer & repo

### ISSUE THREAD

**Issue by Apache46** [OFFLINE-GmbH/oc-mall-plugin#702]
Hi everyone,
I use composer for install your plugin and I noticed that the tags and master are still at version 1.12.2 while on the octobercms marketplace there is version 1.13.1 (Develop branch). Why use develop as a stable branch and not the master? Why don't you create tags for each release?

Thanks for the replies.

**Comment by tobias-kuendig** [comment]
The `develop` branch is used for edge updates (you can get them by setting the `cms.edgeUpdates` config setting to true). The master branch is actually stable.

I just forgot to tag the 1.13 release after testing it for a few days via the edge update channel.

Thanks for bringing this up, I have now tagged the 1.13 release properly. :+1:
