### ISSUE TITLE
Quick Checkout Error

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#703]
Hi. Updated to Mall 1.13.1 today and starting to see these errors in the log. Coincidence?
Can anyone throw any light on this?

Thanks.

[2021-01-08 10:03:16] production.INFO:   
[2021-01-08 10:03:39] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to OFFLINE\Mall\Models\Order::byCustomer() must be an instance of OFFLINE\Mall\Models\Customer, null given, called in /home/sites/5a/7/71ca1669c4/public_html/plugins/offline/mall/components/QuickCheckout.php on line 413 in /home/sites/5a/7/71ca1669c4/public_html/plugins/offline/mall/models/Order.php:134
Stack trace:
#0 /home/sites/5a/7/71ca1669c4/public_html/plugins/offline/mall/components/QuickCheckout.php(413): OFFLINE\Mall\Models\Order::byCustomer(NULL)
#1 /home/sites/5a/7/71ca1669c4/public_html/plugins/offline/mall/components/QuickCheckout.php(178): OFFLINE\Mall\Components\QuickCheckout->setData()
#2 /home/sites/5a/7/71ca1669c4/public_html/modules/cms/classes/Controller.php(1456): OFFLINE\Mall\Components\QuickCheckout->init()
#3 /home/sites/5a/7/71ca1669c4/public_html/modules/cms/classes/Controller.php(662): Cms\Classes\Controller->addComponent('quickCheckout', 'quickCheckout', Array)
#4 /home/sites/5a/7/71ca1669c4/public_html/modules/cms/classes/Controller.php(334): Cms\Classes\Controller->initComponents()
#5 /home/sites/5a/7/71ca1669c4/public_html/modules/cms/classes/Controller.php(225): Cms\Classes\Controller->runPage(Object(Cms\Classes\Page))
#6 /home/sites/5a/7/71ca1669c4/public_html/modules/cms/classes/CmsController.php(50): Cms\Classes\Controller->run('checkout/done')
#7 [internal function]: Cms\Classes\CmsController->run('checkout/done')
#8 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#9 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)
#10 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Cms\Classes\CmsController), 'run')
#11 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#12 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()
#13 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /home/sites/5a/7/71ca1669c4/public_html/plugins/rainlab/translate/classes/LocaleMiddleware.php(29): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): RainLab\Translate\Classes\LocaleMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(68): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#35 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#36 /home/sites/5a/7/71ca1669c4/public_html/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#37 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#38 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#39 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /home/sites/5a/7/71ca1669c4/public_html/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(25): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /home/sites/5a/7/71ca1669c4/public_html/plugins/vdlp/redirect/classes/RedirectMiddleware.php(111): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Vdlp\Redirect\Classes\RedirectMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#48 /home/sites/5a/7/71ca1669c4/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#49 /home/sites/5a/7/71ca1669c4/public_html/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#50 {main}

**Comment by dathwa** [comment]
I see this has now been addressed. #https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/5998e993db31c9bcd44c52b645dd9fa35ee797c5

**Comment by dathwa** [comment]
Ahh. still seeing this. https://www.larabug.com/exception/0zoH46tOCJ4TX3F

**Comment by dathwa** [comment]
Bump. no-one else experiencing this?
I think it may have something to do with us selling virtual products (tickets) with no shipping.
Seems that the line 413 in `\offline\mall\components\QuickCheckout.php`
`$this->setVar('order', Order::byCustomer(optional($this->user)->customer)->find($orderId));` is causing this.

So i change  line 134 in `\offline\mall\models\Order.php` from
`public static function byCustomer(Customer $customer)
    {
        return static::where('customer_id', $customer->id);
    }`
to 
`
    public static function byCustomer($customer)
    {
        if (empty($customer))
        {
            return null;
        }else{
            return static::where('customer_id', $customer->id);
        }
    }`

is this the correct approach?

**Comment by tobias-kuendig** [comment]
I have added a fix in fc72aac3e50d109d13750d14c2f5873ac246d82b. The `byCustomer` method should always return a query, so we try to not have a `null` return. 

Rather than changing it in the Order model, we can fix the problem by only fetching the order if a user is logged in in the QuickCheckout component.
