### ISSUE TITLE
Use categories as filter

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-mall-plugin#710]
Hello (again),

A common use case on ecommerce website is to filter product by subcategories. 

Concretely, if I'm on a category and that category have subcategories, I would like to display a list of checkbox on the filter sidebar, where the user can check one or more subcategory to filter products.

Actually, it seems it's not possible with Mall

Best regards,

**Comment by tobias-kuendig** [comment]
As #709, this should already be working in the backend. The MySQL index supports multiple category IDs in one go: 
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/ad21c55e1000a6e997f67e51c06feaa8287b59db/classes/index/mysql/MySQL.php#L198

You would have to check where the filter value is fetched from. You might be able to inject your selected checkboxes there.

**Comment by PubliAlex** [comment]
Hum, you mean that I can add my categories checkboxes on frontend as I want, and use a `category_id[]` name on my checkboxes and it will do the job ?

**Comment by tobias-kuendig** [comment]
Just test it! I would have to dive into the inner workings of this component myself. The Filter accepts multiple values. So in theory, all you have to do is make sure that you send an array to the backend instead of a single value.

**Comment by PubliAlex** [comment]
I've investigate this and the category_id cannot be used as filters because of this condition in getFilters() method of products component.

        if ($this->categories) {
            $filters->put('category_id', new SetFilter('category_id', $this->categories->pluck('id')->toArray()));
        }

even if you put some category_ids in your filters, it's overriden by the list of all categories.

A solution is to check for the existence of category_id in filters before define default logic.

        if ($this->categories && !isset($filters['category_id'])) {
            $filters->put('category_id', new SetFilter('category_id', $this->categories->pluck('id')->toArray()));
        }

I will create a PR if this addition seems correct to you

**Comment by tobias-kuendig** [comment]
Closed via #738

**Comment by PubliAlex** [comment]
I reopen this issue because it does not work with the recent october 2 and latest Mall

Don't know the reason it stopped working (seems my small PR still do the job) but it seems it's not possible to filter by categories using category_id as get parameter

**Comment by PubliAlex** [comment]
I found why it worked in one case and not the other.

The difference between the 2 websites was the product index system. The category_id filter works with FileSystem index, but not with the MySQL one (others filters works as expected with MySQL, only the category filter doesn't work).

Index system are quite obscure to me so I think I will not be able to go further. Things I noticed is that, on the getItems() method, the line : `$index  = app(Index::class);` return a full object with filesystem, but return nothing with mysql when I filter by category.

**Comment by vdomah** [comment]
Can filter accept multiple categories ids from url get params? Something like this:
/products?category_id=[1,2]

or at least to have ability to pass categories ids to component property

**Comment by tobias-kuendig** [comment]
Try if ` /products?category_id=1.2` works (delimited by `.`)

Parsed here:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/3e10c11ea89e9c79838c4ceff6e0cda7c9c83cf6/classes/categoryfilter/QueryString.php#L40

Applied here:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/3e10c11ea89e9c79838c4ceff6e0cda7c9c83cf6/classes/index/mysql/MySQL.php#L213
