### ISSUE TITLE
Shipping method not translated (bug)

### ISSUE THREAD

**Issue by maartenmachiels** [OFFLINE-GmbH/oc-mall-plugin#714]
Hi,

I noticed a small bug. If you provide a translation for the shipping method, it is not shown on the front-end.
For example, on the demo site, provide "Standard" as the German translation of the default shipping method:

![image](https://user-images.githubusercontent.com/3584586/106459249-dd411e80-6491-11eb-9f20-0ead90114817.png)

The English translation will persist everywhere:
![image](https://user-images.githubusercontent.com/3584586/106459339-ffd33780-6491-11eb-98bd-c050aec2fd0a.png)

The problem appears everywhere the shipping method is shown on the site, but also in the email notifications.

This in contrast to the payment method, which does seem to be translated correctly everywhere.

Just to let you know.

**Comment by Eoler** [comment]
Still there in 1.13.1
Direct call to `attributes['name']` should be probably replaced with `getAttributeTranslated('name')` here:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/models/ShippingMethod.php#L123

I can do the PR, but don't know if TranslatableModel behavior is still optional @tobias-kuendig ?

**Comment by tobias-kuendig** [comment]
PR welcome! The dependency on RainLab.Translate is no longer optional, no. So the TranslatableModel should be available in any case.

**Comment by tobias-kuendig** [comment]
Fixed in #733
