### ISSUE TITLE
Missing locale in generated sitemap

### ISSUE THREAD

**Issue by gpluess** [OFFLINE-GmbH/oc-mall-plugin#717]
I'm using Malls sitemap generation feature. However, "All shop products" and "All shop variants" return a URL without the locale part.

Current: `example.com/shop/product-slug`
Expected: `example.com/de/shop/product-slug`

Is there an easy way to fix this?

I tried this without luck: https://octobertricks.com/tricks/generate-page-url-specific-locale

Thank you!

**Comment by tobias-kuendig** [comment]
This is where the URL is generated:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/models/Product.php#L557

If you want to generate the URL for each registered locale this code won't work anyways. Do you actually provide all locale URLs in a single sitemap? I'm not sure what best pracices are in this case.

Using the `urlFromPattern` method from the linked October Trick should work in theory, as it simply adds the language prefix manually.

> I tried this without luck

What didn't work?

Also, you can always regsiter your own page type and let it return the sitemap results in the format you need.

**Comment by gpluess** [comment]
Thanks for the quick feedback!

> Do you actually provide all locale URLs in a single sitemap?

It's complicated :) We started out having multiple locales, but now realized it's too much of an effort to keep everything up to date in all languages, so now we only use the 'de' locale but don't want to drop it from the URLs.

> What didn't work?

Finally I got it to work the way I wanted using this code after you posted your comment:
```
$localeUrl = $router->urlFromPattern(sprintf("/%s%s", 'de', $cmsPage->url), ['slug' => $product->slug]);

return [
    'title'    => $product->name,
    'url'      => config('app.url') . $localeUrl,
    'mtime'    => $product->updated_at,
    'isActive' => $pageUrl === $url,
];
```

Thank you!
