### ISSUE TITLE
Multiple colors per product variation

### ISSUE THREAD

**Issue by bmiskoski** [OFFLINE-GmbH/oc-mall-plugin#721]
Hello,

Is there a possibility to add multiple colors for a product variants?

For example i have a product that has multiple dimensions, also that product has 5 colors per dimension. 

Is there a possibility to add all five colors to a single dimension, and not to create that dimension five times with all color variants?

Is there a workaround for this?

Thanks in advance.

**Comment by tobias-kuendig** [comment]
With the current setup, it is required to create each color for each dimension. After all, these are five separate products that might have five different stock values or prices.

If you don't need the stock managment, you could add the color/dimensions options as a custom dropdown field to the product directly and not use variants at all. This has some disadvantages, but depending on your use case it won't matter.
