### ISSUE TITLE
$.request destroys previous addEventListeners

### ISSUE THREAD

**Issue by zlobec** [OFFLINE-GmbH/oc-mall-plugin#722]
Hey,

I've added Additional descriptions to a product and they are displayed on the info.htm partial in the Product component. I've arranged them to display as tabs which switch from "Product Description" to all Additional descriptions as each element of the array.

The JS code is added in the footer and listenes for document loaded event. It took me a while to understand why the Event listener for "click" was not working... The mall-product__info HTML is recreated when the $.request from https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/fc72aac3e50d109d13750d14c2f5873ac246d82b/components/product/scripts.htm#L36 completes.

I've added some extra code to work around it:

```
                $.request('onCheckProductStock', {
                    data: {slug: '{{ item.slug }}'},
                    loading: null,
                    success: function (data) {
                        this.success(data)
                        initTabs()
                    },
                })
```

Would there be a better way of doing this... not have to edit the scripts.htm file from the component (in a partial) ?

Regard,
Darjan

**Comment by tobias-kuendig** [comment]
You can add permantent event listeners in jQuery using `$('body', '.your-selector').on('click', ...)` that will "survive" DOM updates (as the listener is on the body, not the element itself).
