### ISSUE TITLE
Continual page refresh on product and registration pages

### ISSUE THREAD

**Issue by ja-gallagher** [OFFLINE-GmbH/oc-mall-plugin#725]
Hi,

The plugin looks excellent, but I'm experiencing a couple of issues on some pages as follows:

1. The product pages continually reload themselves without any user interaction a couple of seconds after they have loaded.
2. The user login/registration page reloads itself when a country is selected from the dropdown menu. On reload, all previously filled fields are empty.

I'm running a completely fresh install of OctoberCMS and plugins, on Wampserver, using the Mall Starter theme and the provided demo data.

Any idea what might be happening here?

Thanks in advance,

ja

**Comment by tobias-kuendig** [comment]
It sounds like you did not include jQuery/October Framework assets correctly. Can you reproduce the issue on our demo site? https://mall.offline.swiss/en

Also, check your JS console if this happens.

**Comment by ja-gallagher** [comment]
Hi, thanks for the response.

No, I haven't seen the same behaviour on the demo site. 

Apologies if I'm missing something obvious (long-term Wordpress developer, first time using October), but since I'm using the demo theme unmodified (I do plan on building another theme, but I'd like to get this one working first), wouldn't the appropriate assets already be included in the theme files?

JQuery is definitely loaded, and  the app.js, framework.js, framework.extras.js and pubsub.js files are all present at the bottom of the page. Also, the console is not displaying any errors.

Thanks in advance!

**Comment by tobias-kuendig** [comment]
> The product pages continually reload themselves without any user interaction a couple of seconds after they have loaded.

Having the reload happen automatically is definitely strange. Can you check the request that is being sent? Is it a POST/GET request? What headers and data does it have?

In the network tab of your browser's dev tool, you shout also be able to see the stacktrace/initiator of the request. That might show you where the request comes from. Here's a screenshot from Chrome's dev tools:

![image](https://user-images.githubusercontent.com/8600029/114051110-1b413100-988d-11eb-9b0d-0a414166a7d7.png)

**Comment by ja-gallagher** [comment]
All GET requests. This is what Chrome DevTools is saying:

![screen1](https://user-images.githubusercontent.com/78157539/114054355-b59e7600-9887-11eb-85e5-612d4566239b.jpg)

![screen2](https://user-images.githubusercontent.com/78157539/114054379-b9ca9380-9887-11eb-8548-8847fc0a2acc.jpg)

**Comment by ja-gallagher** [comment]
![screen3](https://user-images.githubusercontent.com/78157539/114054983-3e1d1680-9888-11eb-9aeb-c573d3400cb5.jpg)

**Comment by tobias-kuendig** [comment]
Can you show the initiator of a request to the /en/product/cruiser-1000 page (not the JS files)? This is the request that actually reloads the page.

**Comment by ja-gallagher** [comment]
Hi,

I figured it out - at some point I had installed the Vdlp.CSRF protection plugin and that's what was causing the reload loop.

Thanks again for your help!
