### ISSUE TITLE
How to get the categories list?

### ISSUE THREAD

**Issue by quildcrest** [OFFLINE-GmbH/oc-mall-plugin#728]
Just tried to put categories to the mega menu but I don't know how to get the list (not static menu). Anyone could help? Thanks a lot.

**Comment by tobias-kuendig** [comment]
It is a simple Laravel model:

```php
Category::get()
```

Also see https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/436 for more examples.

**Comment by quildcrest** [comment]
Thank you very much.
