### ISSUE TITLE
Why is need compare count with less to one?

### ISSUE THREAD

**Issue by dimti** [OFFLINE-GmbH/oc-mall-plugin#730]
I think is not normal: Result from count method of the collection compare with "less one"
What is history reason for the that style?
`if ($data->count() < 1) {`

Because, count is not possible returned value less than null or negative null, or negative one.

Why is not make that:
`if ($data->count() == 0) {` or `if (!$data->count()) {`

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/fc72aac3e50d109d13750d14c2f5873ac246d82b/components/ProductsFilter.php#L317

**Comment by tobias-kuendig** [comment]
Not specific reason why it is that way. After all, it's just preference. All of the provided methods evaluate the same way, so I don't see a reason to change it.
