### ISSUE TITLE
Stripe - allow Bancontact and other payment methods

### ISSUE THREAD

**Issue by maartenmachiels** [OFFLINE-GmbH/oc-mall-plugin#742]
Hi, 

This might be a stupid question, but is it possible to allow "Bancontact" in the Stripe Payment Gateway? If so, how would we go about this? This is a very popular payment method in Belgium - credit cards are less popular here.

In the documentation of Stripe, I notice that this is something that should be implemented in the code. I was expecting just to be able to allow it via the Stripe dashboard, but this isn't the case. Here you can see the documentation that Stripe shows:
[https://stripe.com/docs/payments/bancontact/accept-a-payment?platform=web](https://stripe.com/docs/payments/bancontact/accept-a-payment?platform=web)

Thanks in advance for your answer.

**Comment by tobias-kuendig** [comment]
I do not know about "Bancontact" or the related Stripe feature, so I cannot help you here. 

If this is a Stripe feature that can be added either do this via a custom payment provider or submit a PR to add the feature to the built in one.

Thanks!
