### ISSUE TITLE
How can I setup several products components with different properties on one page? 

### ISSUE THREAD

**Issue by niksen2** [OFFLINE-GmbH/oc-mall-plugin#748]
I've not found any information about that in the documentation

**Comment by tobias-kuendig** [comment]
Does this work for your use-case?

```ini
[product prodA]
your = properties

[product prodB]
your = other-properties
==

{% component 'prodA' %}
{% component 'prodB' %}
```

**Comment by niksen2** [comment]
> Does this work for your use-case?
> 
> ```ini
> [product prodA]
> your = properties
> 
> [product prodB]
> your = other-properties
> ==
> 
> {% component 'prodA' %}
> {% component 'prodB' %}
> ```



> Does this work for your use-case?
> 
> ```ini
> [product prodA]
> your = properties
> 
> [product prodB]
> your = other-properties
> ==
> 
> {% component 'prodA' %}
> {% component 'prodB' %}
> ```

I guess it is! Thank you very much!
