### ISSUE TITLE
Not updating entries

### ISSUE THREAD

**Issue by niksen2** [OFFLINE-GmbH/oc-mall-plugin#750]
I've changed structure of products component for my needs and added some new partials, but now updating entries is not working, it just goes into ifinite loading. I didn't touch any scripts, so i guess there is some necessary classes to be. What can i do?

**Comment by tobias-kuendig** [comment]
> What can i do?

Share what you changed, and if you see any errors in your console. Also, what goes into infinite loading? The whole page? What request is triggered?

**Comment by niksen2** [comment]
First;y, I've changed the default layout by deleting this class:
![image](https://user-images.githubusercontent.com/67999886/115576056-928ab200-a2dc-11eb-81cb-1ac7ca31ec19.png)
Then there are a lot of changes in inner partials:

Items partial:
![image](https://user-images.githubusercontent.com/67999886/115576311-d2ea3000-a2dc-11eb-9532-a22ccc01b8b4.png)

Item itself:
![image](https://user-images.githubusercontent.com/67999886/115576423-ea291d80-a2dc-11eb-94b9-6f5635a76056.png)

Added my own script but i didn't change the original one:
![image](https://user-images.githubusercontent.com/67999886/115576680-2c525f00-a2dd-11eb-94ca-5ebf9f9e2f04.png)

Indexitems:
![image](https://user-images.githubusercontent.com/67999886/115576758-3d02d500-a2dd-11eb-997b-2aa22ce85e52.png)

**Comment by niksen2** [comment]
>  Also, what goes into infinite loading? The whole page? 

Only products component

> and if you see any errors in your console

No decent errors, just some ui slider one

![image](https://user-images.githubusercontent.com/67999886/115577066-881ce800-a2dd-11eb-8d9a-818a56750f45.png)

**Comment by tobias-kuendig** [comment]
The `.mall-products` class is needed here:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/products/scripts.htm#L10

You have to set a custom class in the default.htm and the script.htm if you don't want the default styles to be applied.

**Comment by niksen2** [comment]
Ok, thanks a lot!
