### ISSUE TITLE
Is language setting of this plugin is tied with October's backend language list?

### ISSUE THREAD

**Issue by ahmcho** [OFFLINE-GmbH/oc-mall-plugin#753]
Hello!
I am trying to translate some UI components to my native language - Azerbaijani. The work is almost done, but I can not figure out how to switch the language of the plugin? The frontend part displays the strings correctly - translated. But plugin submenus, menus, dropdowns, labels and etc. ( for example, Catalogue menu item and anything that is inside it) do not update yet. I changed the locale setting in  `config/app.php` section of the October CMS.  Do I missing something else?  Because when I changed the language in `Backend preferences` to Russian, everything got translated. 

EDIT:
I must also state, that Azerbaijani language is not an option in `Backend preferences`. I just changed the locale to match it with new language inside the plugin folder.

**Comment by tobias-kuendig** [comment]
The plugin uses the default langauge setting of October, yes. So if you change it in your backend preferences, the translations should be loaded. Just make sure there is a language folder for your language available:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/tree/develop/lang

If your language is not in the available translations, english will be used as a fallback.
Changeing the config/app.php locale only sets the default locale. If you have selected a locale in your backend preferences, the config/app.php setting will be ignored.

**Comment by ahmcho** [comment]
Thank you for explanation!
