### ISSUE TITLE
Extending the sorting mechanism to include specific properties per category

### ISSUE THREAD

**Issue by maartenmachiels** [OFFLINE-GmbH/oc-mall-plugin#759]
Hi, 

I was wondering if you could shed some light on the following:
Would it be possible to include one or more specific custom properties in the sorting mechanism?

For example, I've created a "start date" datetime property, because the application I'm building sells tickets for events that happen at specific dates. It would be ideal if I could have the products sorted on the basis of the "start_date" (so we would have an ordered list of upcoming events) but still allow the visitor to change the sorting via the dropdown:

![sorting](https://user-images.githubusercontent.com/3584586/117949473-71811400-b312-11eb-95b6-848ea19d4f7b.png)

These custom properties make the system so incredibly flexible, so it would be great if I could use them to attain the goal of this application.

Thanks for looking into this.

**Comment by tobias-kuendig** [comment]
You can specify the sort order via the `sort` property in the component:
https://offline-gmbh.github.io/oc-mall-plugin/components/products.html#properties

If you add an Event to extend this array, you can provide your custom SortOrder implementation:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/31400f852106e3e0bd2db56d7e27cbf1d7ba30cc/classes/categoryfilter/sortorder/SortOrder.php#L68

Would this work for your use-case?

**Comment by maartenmachiels** [comment]
Hi Tobias,

Thanks very much for your answer. It's still a bit unclear to me how to do this exactly.
Could you please let me know what to listen for in the event exactly? Would it be something like this?

    public function boot()
    {
        Event::listen('offline.mall.xxx', function ($user) {
            
        });
    }

**Comment by tobias-kuendig** [comment]
This method: 
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/categoryfilter/sortorder/SortOrder.php#L68

Change it to be something like that (untested!):

```php
    public static function options($excludeInternal = false)
    {
        $options = [
            'manual'     => new Manual(),
            'bestseller' => new Bestseller(),
            'ratings'    => new Rating(),
            'latest'     => new Latest(),
            'price_low'  => new PriceLow(),
            'price_high' => new PriceHigh(),
            'oldest'     => new Oldest(),
            'random'     => new Random(),
            'name'       => new Name(),
        ];
 
 
		$extensions = \Event::fire('offline.mall.extendSortOrder');
        if (count($extensions) > 0) {
            foreach ($extensions as $extension) {
                $options = array_merge($options, $extension);
            }
        }


        if ($excludeInternal) {
            unset($options['manual'], $options['random'], $options['name']);
        }

        return $options;
    }
```

Then in your plugin's boot method:

```php
\Event::listen('offline.mall.extendSortOrder', function() {
    return [
        'my-custom-sorter' => new MyCustomSorter(); // Extends and implements \OFFLINE\Mall\Classes\CategoryFilter\SortOrder
	];
});
```

If this is working for you, we can then add the changes made to the options method above to the plugin properly.

Sorting is done on the data of the `offline_mall_index` table. The sort classes are applied here:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/cdf7a3240c25a12d42823348f1e3488350e429ab/classes/index/mysql/MySQL.php#L261

I suggest you work backwards from the `handleOrder` method and see what needs to be added for your use-case.

**Comment by maartenmachiels** [comment]
Hi Tobias,

Thanks so much. This works like a charm. I got it working by creating a separate column `start_date` in the `offline_mall_products` table. **Could you please check out the two final questions below?**

Below is my code:

![image](https://user-images.githubusercontent.com/3584586/118401225-22661680-b665-11eb-9705-e5b36c47152e.png)

```
<?php

namespace Chocolata\Chocotools\Classes\StartDate;
use OFFLINE\Mall\Classes\CategoryFilter\SortOrder\SortOrder;

class StartDate extends SortOrder
{
    public function key(): string
    {
        return 'start_date';
    }

    public function property(): string
    {
        return 'start_date';
    }

    public function direction(): string
    {
        return 'asc';
    }
}
```
![image](https://user-images.githubusercontent.com/3584586/118401255-445f9900-b665-11eb-8dfe-b73b29aac7d7.png)

```
public function boot()
    {


        \Event::listen('offline.mall.extendSortOrder', function() {
            return [
                'start_date' => new Classes\StartDate\StartDate
            ];
        });
}
```
Then you can test it by going to a category page and appending `?sort=start_date` which should just sort everything without issue.

Two final questions remain:

1. Could you please add the code for the extensions to the core? 
2. Could you please let me know if and how it would be possible to use this mechanism to sort by a specific property instead of a newly created table column. The former seems to be the most flexible option and would allow us not to taint the database with superfuous columns.

Thank you so much again! You are a programming rockstar.

**Comment by tobias-kuendig** [comment]
> Could you please add the code for the extensions to the SortOrder class to the core?

Did the code from my previous comment work? If so, I can add it (or you can PR it!)

> Could you please let me know if and how it would be possible to use this mechanism to sort by a specific property instead of a newly created table column.

Are you sure that this custom column is required? You should find your custom property in the `offline_mall_index` table without any modifications. The sort order that gets applied [in the MySQL index class](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/index/mysql/MySQL.php#L273) is applied to the query that queries `offline_mall_index`, so you should not need to add a custom column.

**Comment by maartenmachiels** [comment]
Hi Tobias,

Yes, your code works like a charm. Thank you so much! I've created a pull request here:
[https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/763](https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/763)

Regarding sorting by properties: I do see the sorting options show up in the index. In my case the index is present as a file and not in the database. I've no clue what to enter then below. Could you have a final look?

```
class StartDate extends SortOrder
{
    public function key(): string
    {
        return 'property_values[15]';
    }

    public function property(): string
    {
        return 'property_values[15]';
    }

    public function direction(): string
    {
        return 'asc';
    }
}
```

Here is the entry in the index:
```
{
   "__created_at":1620758042,
   "__updated_at":1621256796,
   "data":{
      "id":11,
      "brand_id":null,
      "user_defined_id":"",
      "name":"Nog een event",
      "slug":"nog-een-event",
      "description_short":"",
      "description":"",
      "meta_title":"Nog een event",
      "meta_description":"",
      "meta_keywords":"",
      "additional_descriptions":null,
      "additional_properties":null,
      "weight":null,
      "length":null,
      "width":null,
      "height":null,
      "quantity_default":null,
      "quantity_min":null,
      "quantity_max":null,
      "stock":5,
      "reviews_rating":"0.00",
      "links":"",
      "inventory_management_method":"single",
      "allow_out_of_stock_purchases":false,
      "stackable":true,
      "shippable":true,
      "price_includes_tax":true,
      "group_by_property_id":null,
      "published":true,
      "sales_count":0,
      "created_at":"2021-05-11 20:34:02",
      "updated_at":"2021-05-17 15:06:35",
      "deleted_at":null,
      "mpn":"",
      "gtin":"",
      "embeds":"",
      "is_virtual":false,
      "file_expires_after_days":null,
      "file_max_download_count":null,
      "file_session_required":false,
      "start_date":"2021-05-09 15:06:34",
      "end_date":null,
      "published_at":null,
      "expired_at":null,
      "index":"products",
      "on_sale":false,
      "category_id":[
         3,
         4
      ],
      "property_values":{
         "13":[
            "moeilijk"
         ],
         "14":[
            "12-15"
         ],
         "15":[
            "2021-05-09-080600"
         ]
      },
      "prices":{
         "EUR":1999
      },
      "customer_group_prices":[
         
      ],
      "sort_orders":{
         "3":null,
         "4":null
      }
   }
}
```

**Comment by maartenmachiels** [comment]
Scratch that last bit :-) I got it! Below is my working code.
Thanks for the support!
```
class StartDate extends SortOrder
{
    public function key(): string
    {
        return 'property_values.15';
    }

    public function property(): string
    {
        return 'property_values.15';
    }

    public function direction(): string
    {
        return 'asc';
    }
}
```
