### ISSUE TITLE
There is no column with name 'length' on table 'offline_mall_products'.

### ISSUE THREAD

**Issue by aminusmin** [OFFLINE-GmbH/oc-mall-plugin#768]
October 2.0.16, Mall 1.13.6, DB SQlite

I get the error when importing the demo data. 

`SQLSTATE[HY000]: General error: 1 no such column: length`

**Comment by tobias-kuendig** [comment]
Do you have a stack trace to that error? Otherwise it is not possible to say where the error is generated.

**Comment by tobias-kuendig** [comment]
Do either of your `offline_mall_products` or `offline_mall_product_variants` tables have a `length` column?

Either your schema is messed up (the length column is actually missing) or this is a SQLite issue in the down migration: https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/updates/add_width_and_length_to_product_model.php#L24

As a quick workaround, you can uncomment all the lines in the down migration as they are not really required (the whole table will be dropped later anyways).

**Comment by aminusmin** [comment]
offline_mall_products does not have a length column. offline_mall_products_variants does.

**Comment by tobias-kuendig** [comment]
That sounds more like a messed um DB then. You should be able to fix this by either

1. adding the `length` column back to the `offline_mall_products` table
2. or as described in the comment above, just uncomment the lines in the `down()` method of the migration

After that, the error should no longer appear

**Comment by aminusmin** [comment]
that's strange. It's a fresh installation of october. After installation the column is there in both tables. After the command "php artisan mall:seed-demo" the column disappears in offline_mall_products.
I'll keep testing. thanks anyway

**Comment by tobias-kuendig** [comment]
Thank you for this bug report @aminusmin. I have fixed the compatibility issues with SQLite here: 3a4db6419c3a4e82d54771504b6b39abd0c60244

This fix will be released as a new version later today.
