### ISSUE TITLE
How to upgrade from version 1.13.5 to 1.13.6 in October CMS v.2?

### ISSUE THREAD

**Issue by exaline-ru** [OFFLINE-GmbH/oc-mall-plugin#773]
When upgrade from version 1.13.5 to 1.13.6 in October CMS v.2 as indicated below:

A line "offline/mall-plugin": "^1.1", has been added into composer.json 
After that, run the command: php artisan october:update
Error: 

- Root composer.json requires offline/mall-plugin, it could not be found in any version, there may be a typo in the package name.

In a different way: composer update offline/mall-plugin

Error: 

Loading composer repositories with package information
Package "offline/mall-plugin" listed for update is not locked.
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Generating autoload files
> System\Console\ComposerScript::postAutoloadDump
78 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> System\Console\ComposerScript::postUpdateCmd

* You are using October CMS version: v2.0.17

**Comment by tobias-kuendig** [comment]
The package name is `offline/oc-mall-plugin` (note the `oc-` prefix). Newer October versions fix this automatically, you might have installed it before the fix went live.

You can use `composer require offline/oc-mall-plugin` to install the plugin. You might have to remove the old composer.json entry before this works.

**Comment by exaline-ru** [comment]
The update was successful! Thank you very much!
