### ISSUE TITLE
Discounts on Shipping and Click & Collect

### ISSUE THREAD

**Issue by inalto** [OFFLINE-GmbH/oc-mall-plugin#774]
I want to set a discount when people choose to pick up the goods in store.
The idea is to add a "pickup in store" shipping method with the ability to add discounts just like it is now for the taxes.
Other frameworks like bagisto or aimeos achieve this allowing negative taxes percents, but mall has discounts already!

The second part is the "Click & Collect" which propose to the customer to pay a part (percent) of the price in advance to actually book the goods.

I plan to add these features to a project I am working on, and maybe this enhancement make sense for other people too.
Let me know :)

**Comment by tobias-kuendig** [comment]
Implemented in #775
