### ISSUE TITLE
Custom field color issue display in the email

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#783]
the color displays well in the backend order screen but the HTML code is appearing in the confirmation email sent to customer and admin.

![WhatsApp Image 2021-06-22 at 12 18 28 PM](https://user-images.githubusercontent.com/2263496/123058893-d49ab600-d43b-11eb-849a-cecbbe6dad46.jpeg)

**Comment by tobias-kuendig** [comment]
I guess here we need a change:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/views/mail/_partials/order/table.htm#L39

```twig
{% for field in item.custom_field_values %}
	{% if field.custom_field.type === 'color' %}
		{{ field.custom_field.name }}: {{ field.display_value | raw }}<br />
    {% else %}
		{{ field.custom_field.name }}: {{ field.display_value }}<br />
    {% endif %}
{% endfor %}
```

Could you test that?

**Comment by tobias-kuendig** [comment]
Added in 6268b07
