### ISSUE TITLE
OCMS 1 can't upgrade to 1.14.1

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#785]
Every time I click the update button, it goes through the process of upgrading from 1.14.0 to 1.14.1 (downloads, unpacks, etc, message is "Updates processed OK", but it does not actually update. This has now been happening for several days.
No changes in the version.yaml file.
This happens on 2 live sites and 2 dev sites.
Anyone else?

**Comment by damsfx** [comment]
I think it's because `oc-mall-plugin` requirements are in conflict with other plugins requirement.
With the last update I got many error resolving dependencies with other plugins like `rainlab/googleanalytics-plugin`  
see: https://github.com/rainlab/googleanalytics-plugin/blob/5b50e9ea709d182c196db637105eec0084286d98/composer.json#L20.

As a temporary workaround, removing `rainlab/googleanalytics-plugin` solved my issues.

**Comment by dathwa** [comment]
Alas, I removed `rainlab/googleanalytics-plugin` (plus settings) but it made no difference. still can't update Mall. Thanks anyway :(

**Comment by guus-frenken** [comment]
Hey guys, I think the update is not installing because there's no [release](https://github.com/OFFLINE-GmbH/oc-mall-plugin/releases) for v1.14.1 (yet). I can't update on October CMS build 2.0.24 either.

I suppose you could clone the development branch and update Mall manually if you really need the latest version.

**Comment by MateThemes** [comment]
Same problem here.

I cannot update to 1.14.1 although everything is uptodate and i use oc 2.

If I deinstall and reinstall mall I also have version 1.14.0

**Comment by MateThemes** [comment]
I am unable to run composer update offline/mall

**Comment by damsfx** [comment]
> 
> 
> I am unable to run composer update offline/mall

Is there a problem with the dependencies in the error message?

**Comment by MateThemes** [comment]
this is the message i got 

`Package "offline.mall" listed for update is not locked`

**Comment by tobias-kuendig** [comment]
Please try to upgrade using `composer update offline/oc-mall-plugins`, if this does not work, provide the full output from the command. Thanks!

**Comment by MateThemes** [comment]
If I use composer update offline/oc-mall-plugins, I got this output:
`composer update offline/oc-mall-plugins
Loading composer repositories with package information
Package "offline/oc-mall-plugins" listed for update is not locked.
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Generating autoload files
> System\Console\ComposerScript::postAutoloadDump
83 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> System\Console\ComposerScript::postUpdateCmd

* You are using October CMS version: v2.0.26`

The Mall version still remains 1.14.0, although there is now 1.14.2

**Comment by tobias-kuendig** [comment]
Alright, there is no error, so it seems like composer just resolves to 1.14.0 as the last supported version for your setup.

Could you try to explicitly require 1.14.2? This way we should see what dependencies are conflicting:

```
composer require offline/oc-mall-plugin 1.14.2
```

**Comment by MateThemes** [comment]
I solved the problem with the artisan command:

`php artisan october:update OFFLINE.Mall`

The next time I have problems I will try it with explicitly require the version number.

Thanks for helping me

**Comment by tobias-kuendig** [comment]
Great! Glad that did the trick.

**Comment by dathwa** [comment]
**tried all these with no success and no errors...**
I guess I'll wait for next update and see if it finally kicks in.

λ composer require offline/oc-mall-plugin 1.14.2
./composer.json has been updated
Running composer update offline/oc-mall-plugin
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Downgrading offline/oc-mall-plugin (v1.14.3 => v1.14.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downgrading offline/oc-mall-plugin (v1.14.3 => v1.14.2): Extracting archive
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Generating autoload files
> System\Console\ComposerScript::postAutoloadDump
85 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> System\Console\ComposerScript::postUpdateCmd

* You are using October CMS version: v2.1.6

**manually changed back to "offline/oc-mall-plugin": "^1.14",**

λ composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Upgrading offline/oc-mall-plugin (v1.14.2 => v1.14.3)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Upgrading offline/oc-mall-plugin (v1.14.2 => v1.14.3): Extracting archive
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Generating autoload files
> System\Console\ComposerScript::postAutoloadDump
85 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> System\Console\ComposerScript::postUpdateCmd

* You are using October CMS version: v2.1.6

**And finally...**

λ php artisan october:update OFFLINE.Mall
  **Too many arguments, expected arguments "command".**

**Tried this too...**
composer require offline/oc-mall-plugin

**Comment by PubliAlex** [comment]
Same here, I update my october 2 website, everything seems to works, but when I return to the module page it says mall is still on 1.14.2 whereas he detect that a version 1.14.3 is available... strange...
