### ISSUE TITLE
Availability of price category code in additional_prices

### ISSUE THREAD

**Issue by inalto** [OFFLINE-GmbH/oc-mall-plugin#786]
The additional prices array of the product is missing the information of what category the price in the array is belonging to.
Not a bug, but il great to know in the frontend what price you are referring to.

**Comment by inalto** [comment]
Ok, i have made available that price information with [this](https://github.com/inalto/oc-mall-plugin/commit/0d784f27b42282ada2b54447567e3b13a67fe651#diff-fb7754d055204ce0110de018bbe8c9b8c5c8ccc9097cec8d5c9e071d36439b2f)

**Comment by tobias-kuendig** [comment]
Thank you for this input @inalto! I have implemented this change in 2504aeb.
