### ISSUE TITLE
Undefined index: pricetable

### ISSUE THREAD

**Issue by PrestaSafe** [OFFLINE-GmbH/oc-mall-plugin#788]
Hello, 

I'm working on WinterCMS, and i've virtual products, if i want to change the prices, 
i've this issue: 
<img width="556" alt="Capture d’écran 2021-07-06 à 10 32 52" src="https://user-images.githubusercontent.com/4788787/124568819-a22e8700-de45-11eb-852b-0caa0d3971ce.png">

Do you khnow why ?

Thanks

**Comment by tobias-kuendig** [comment]
Fixed by #788

**Comment by Hambern** [comment]
I still have this problem...
