### ISSUE TITLE
Product bundles

### ISSUE THREAD

**Issue by kikobalco** [OFFLINE-GmbH/oc-mall-plugin#795]
Is there possibility to create product bundles/groups in this plugin?
Basically I'm searching for ability to create bundles that will appear at frontend as one product, but when you add it to your cart, you will have there products separately. But if they are in cart at once, their price will change.

Or maybe do you plan add such a feature?

Thanks

**Comment by tobias-kuendig** [comment]
There is currently no such feature available or planned. It is however, relatively trivial to implement yourself: 

1. Add a new "Products group" model that groups products
2. When the product groups is added to cart, just use the [`addProduct` method on the Cart model](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/4e21bd22aa4d5c2d2f5503d4d9c04b207742f3a6/classes/traits/cart/CartActions.php#L26) to add each of your products. Via the `price` attribute on the created CartProduct model you can override any default prices.
