### ISSUE TITLE
Shop page

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#796]
I am working to build a Shop page displaying all the existing products from the catalogue. Not more than 100.
I need to display and group them by category. So far, I have been using some twig magic to make it happen but it reaches limits in performance. The sorting by category and sorting by price in Twig is pretty resource hungry.

i am thinking to extends the `products` component and override the `getItems()` method with the SQL query that would do the grouping and sorting. 

Would it be better to work with the `index` table or the `products` and `categories` tables?

**Comment by tobias-kuendig** [comment]
The index table is primarily used for filtering based on product properties. If you just want to display all categories with all products, you can use a simple Eloquent query:

```php
Category::with('publishedProducts')->get();
```

Also, if you really only want to display the products (no filtering) you might be better off just creating a new component that does only what your specific use-case needs.

**Comment by chrisvidal** [comment]
Thanks @tobias-kuendig 
I am currently exploring this Eloquent request right now and seems to do the job.

I still need some filtering though, through some properties.

**Comment by chrisvidal** [comment]
`Category::with('publishedProducts')->get();`

is there a way to grab the product properties at the same time? I am looking at doing the properties filtering with js diretcly

**Comment by tobias-kuendig** [comment]
Sure, these are just standard Eloquent relations:

```
Category::with('publishedProducts.image_sets.images', 'publishhedProducts.property_values')->get();
```

This should get you most of the data you need properly loaded. Also check out the `Products` and `Product` components to see how the relations are loaded there:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/6268b07ac97231055371f0505bc86491c9c0b30a/components/Product.php#L479

And of course the model definitions, where all relations are defined.

**Comment by chrisvidal** [comment]
thanks @tobias-kuendig
