### ISSUE TITLE
Class 'Hashids\Hashids' not found

### ISSUE THREAD

**Issue by Patrick-foreseers** [OFFLINE-GmbH/oc-mall-plugin#799]
When I click the product, exception is threw. Same problem when I add new address.

Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Hashids\Hashids' not found in /var/www/html/shop/plugins/offline/mall/classes/registration/BootServiceContainer.php:53
Stack trace:
#0 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Container/Container.php(749): OFFLINE\Mall\Plugin->OFFLINE\Mall\Classes\Registration\{closure}()
#1 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build()
#2 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve()
#3 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\Container\Container->make()
#4 /var/www/html/shop/vendor/october/rain/src/Foundation/Application.php(188): Illuminate\Foundation\Application->make()
#5 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(110): October\Rain\Foundation\Application->make()
#6 /var/www/html/shop/plugins/offline/mall/classes/traits/HashIds.php(35): app()
#7 /var/www/html/shop/vendor/twig/twig/src/Extension/CoreExtension.php(1507): OFFLINE\Mall\Components\WishlistButton->encode()
#8 /var/www/html/shop/storage/cms/twig/e9/e9bb3d64902916a4429697838cc5add99374194b74f78f9d2435b0a3238e848e.php(54): twig_get_attribute()
#9 /var/www/html/shop/vendor/twig/twig/src/Template.php(405): __TwigTemplate_562583a761aabc2aaa298ab53a6d46b5a5b3fd5c5a0049dab046917afa80eb0d->doDisplay()
#10 /var/www/html/shop/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#11 /var/www/html/shop/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#12 /var/www/html/shop/modules/cms/classes/Controller.php(1088): Twig\Template->render()
#13 /var/www/html/shop/modules/cms/twig/Extension.php(102): Cms\Classes\Controller->renderPartial()
#14 /var/www/html/shop/storage/cms/twig/ea/eaf7b2a9c4c7b97a0964ad58bcffe93e356ccdf5664347bd7c3226ab04c77129.php(74): Cms\Twig\Extension->partialFunction()
#15 /var/www/html/shop/vendor/twig/twig/src/Template.php(405): __TwigTemplate_64273b60f3db985e430294af5ca5800a9eef5c4dc51bd3e591691084f916608a->doDisplay()
#16 /var/www/html/shop/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#17 /var/www/html/shop/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#18 /var/www/html/shop/modules/cms/classes/Controller.php(1088): Twig\Template->render()
#19 /var/www/html/shop/modules/cms/twig/Extension.php(102): Cms\Classes\Controller->renderPartial()
#20 /var/www/html/shop/storage/cms/twig/5b/5b7969a35e1f0e5b672f68c5233c2b475ab13b01ccaa6444395009a899f967c2.php(46): Cms\Twig\Extension->partialFunction()
#21 /var/www/html/shop/vendor/twig/twig/src/Template.php(405): __TwigTemplate_fd19a80c9e35150b6a9e91553ef5741a89cb3afecf0d30e6de3b0743cb001474->doDisplay()
#22 /var/www/html/shop/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#23 /var/www/html/shop/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#24 /var/www/html/shop/modules/cms/classes/Controller.php(1088): Twig\Template->render()
#25 /var/www/html/shop/modules/cms/twig/Extension.php(102): Cms\Classes\Controller->renderPartial()
#26 /var/www/html/shop/storage/cms/twig/90/90221b1cfd1f4026064c8b4933ab666a4b22fd64446f35fb7105393c360bf764.php(43): Cms\Twig\Extension->partialFunction()
#27 /var/www/html/shop/vendor/twig/twig/src/Template.php(405): __TwigTemplate_0265478eca8b504d1b7f8a870e6876c3df7ff7a38b65a03d90baaf338b86380c->doDisplay()
#28 /var/www/html/shop/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#29 /var/www/html/shop/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#30 /var/www/html/shop/modules/cms/classes/Controller.php(1088): Twig\Template->render()
#31 /var/www/html/shop/modules/cms/classes/Controller.php(1217): Cms\Classes\Controller->renderPartial()
#32 /var/www/html/shop/modules/cms/twig/Extension.php(124): Cms\Classes\Controller->renderComponent()
#33 /var/www/html/shop/storage/cms/twig/8d/8d1a55bcfee4a32b57d3297cfa733053031fdeae456c4f96ec91bbe371c66884.php(47): Cms\Twig\Extension->componentFunction()
#34 /var/www/html/shop/vendor/twig/twig/src/Template.php(405): __TwigTemplate_b6ca4bcca0431b0dea0fa08df4067470f11929104ab513de2debf465143ff144->doDisplay()
#35 /var/www/html/shop/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#36 /var/www/html/shop/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#37 /var/www/html/shop/modules/cms/classes/Controller.php(1088): Twig\Template->render()
#38 /var/www/html/shop/modules/cms/twig/Extension.php(102): Cms\Classes\Controller->renderPartial()
#39 /var/www/html/shop/storage/cms/twig/90/9031c74242637bfa9c06bb08af6031cae5a44e03e14452650c1f5ec613aece43.php(108): Cms\Twig\Extension->partialFunction()
#40 /var/www/html/shop/vendor/twig/twig/src/Template.php(405): __TwigTemplate_e23e72e688bb94522e26ee0023aaf34f53c22b2c25f2980b44319ed06a08dbe3->doDisplay()
#41 /var/www/html/shop/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#42 /var/www/html/shop/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#43 /var/www/html/shop/modules/cms/classes/Controller.php(1088): Twig\Template->render()
#44 /var/www/html/shop/modules/cms/twig/Extension.php(102): Cms\Classes\Controller->renderPartial()
#45 /var/www/html/shop/storage/cms/twig/f3/f3f3b553fe10abeede7b75e9f0f998a9a1de0c12cc292ee5c4f85ff51d969d2d.php(151): Cms\Twig\Extension->partialFunction()
#46 /var/www/html/shop/vendor/twig/twig/src/Template.php(405): __TwigTemplate_85c3d989d7bcaaf8881a99880111fd8a884e7713d58c9fe6346b4dea45b909d7->doDisplay()
#47 /var/www/html/shop/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#48 /var/www/html/shop/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#49 /var/www/html/shop/modules/cms/classes/Controller.php(1088): Twig\Template->render()
#50 /var/www/html/shop/modules/cms/twig/Extension.php(102): Cms\Classes\Controller->renderPartial()
#51 /var/www/html/shop/storage/cms/twig/64/64d0a9fd12de2373385e45745adc6efe6925e199adebd8724f81669ba9a5cf2d.php(52): Cms\Twig\Extension->partialFunction()
#52 /var/www/html/shop/vendor/twig/twig/src/Template.php(405): __TwigTemplate_afbd200a9136f86ff2c0a01be021b845c95010a70e69f64f581aa2648349a29e->doDisplay()
#53 /var/www/html/shop/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#54 /var/www/html/shop/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#55 /var/www/html/shop/modules/cms/classes/Controller.php(1088): Twig\Template->render()
#56 /var/www/html/shop/modules/cms/classes/Controller.php(1217): Cms\Classes\Controller->renderPartial()
#57 /var/www/html/shop/modules/cms/twig/Extension.php(124): Cms\Classes\Controller->renderComponent()
#58 /var/www/html/shop/storage/cms/twig/5d/5d0f22a2e18cc5b131a92a7e008abedec07754e7d7b27b642cb81e9de6ffac0c.php(40): Cms\Twig\Extension->componentFunction()
#59 /var/www/html/shop/vendor/twig/twig/src/Template.php(405): __TwigTemplate_e2de56397b6ccc81300773c362dbc74333577ff4aaf45b16ba28f00708b83cb7->doDisplay()
#60 /var/www/html/shop/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#61 /var/www/html/shop/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#62 /var/www/html/shop/modules/cms/classes/Controller.php(425): Twig\Template->render()
#63 /var/www/html/shop/modules/cms/classes/Controller.php(225): Cms\Classes\Controller->runPage()
#64 /var/www/html/shop/modules/cms/classes/CmsController.php(50): Cms\Classes\Controller->run()
#65 [internal function]: Cms\Classes\CmsController->run()
#66 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#67 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#68 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch()
#69 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#70 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()
#71 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#72 /var/www/html/shop/plugins/rainlab/translate/classes/LocaleMiddleware.php(29): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#73 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): RainLab\Translate\Classes\LocaleMiddleware->handle()
#74 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#75 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#76 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#77 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#78 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#79 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#80 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#81 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#82 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle()
#83 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#84 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#85 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#86 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#87 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(68): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#88 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#89 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#90 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#91 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Pipeline\Pipeline->then()
#92 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRouteWithinStack()
#93 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\Routing\Router->runRoute()
#94 /var/www/html/shop/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute()
#95 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): October\Rain\Router\CoreRouter->dispatch()
#96 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#97 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#98 /var/www/html/shop/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(25): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#99 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#100 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#101 /var/www/html/shop/vendor/october/rain/src/Http/Middleware/TrustHosts.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#102 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): October\Rain\Http\Middleware\TrustHosts->handle()
#103 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#104 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#105 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then()
#106 /var/www/html/shop/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#107 /var/www/html/shop/index.php(43): Illuminate\Foundation\Http\Kernel->handle()
#108 {main}

OS: Ubuntu 18.04
PHP: 7.4.21

**Comment by tobias-kuendig** [comment]
Make sure that your composer dependencies are up-to-date:

> composer install

should install the hashids/hashids package for you (or give you an error if there is a dependency problem)

**Comment by Patrick-foreseers** [comment]
> Make sure that your composer dependencies are up-to-date:
> 
> > composer install
> 
> should install the hashids/hashids package for you (or give you an error if there is a dependency problem)

where to run it? The website is crashed after I ran the command in plugins/offline/mall

**Comment by damsfx** [comment]
I had the same problem again yesterday.

Removed the `/plugins/offline/mall`, `/vendor` directories and the `composer.lock` file.
Then run `composer dump-autoload` and `composer update` solve the issue for me.

**Comment by Patrick-foreseers** [comment]
The issue was happening on OctoberCMS 1.0, it works fine when I put this plugin into 2.0.
