### ISSUE TITLE
Querying products by a specific property

### ISSUE THREAD

**Issue by maartenmachiels** [OFFLINE-GmbH/oc-mall-plugin#800]
Hi @tobias-kuendig ,

I have a small question that ties into this [https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/759](https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/759)

In the above issue, we succesfully created a custom property "date" and implemented a sorting mechanism on the basis of this property. This setup was used to facilitate the sale of tickets for events.

Now, I'd like to set up a cron job to unpublish the product / event after the date (as mentioned in our custom property "date") has passed. So now, I'm trying to query the products that have the property "date" in the past, so I can loop over them and setting their published status to 0.

So my question is: is there an easy way to query the products on the basis of their properties? If so, how would we do this?

The below code obviously doesn't work, but this in broad terms is what I'm trying to do.

```
    $products = Product::where('date','>','2021-07-21')->get();
    if(count($products)) {
        foreach($products as $product) {
            $product->published = 0;
            $product->save();
        }
    }
```
Of course we could loop over all published products and then evaluate the property values per product, but this seems a little bit inefficient.

Could you kindly point me in the right direction? Thanks in advance.

**Comment by chrisvidal** [comment]
I would look around something like:
1. get the property Id for your `date` property: `$propertyId = Property::where('slug', 'date')->first()->id;`
2. from there you can query any product where it has this $propertyId with property_values matching your condition

```
$products = Product::whereHas('property_value', function($q) use ($propertyId) {
   $q->where('property_id', $propertyId)->where('index_value', '>', '2021-07-21');
})->get();
```

**Comment by maartenmachiels** [comment]
Hi @chrisvidal ,

Thanks so much for the information. I understand the logic, seems like a good way to do this.
I'm getting the following error message at the moment though:

```
Call to undefined method October\Rain\Database\QueryBuilder::property_value()
E:\Dropbox\Projects\_xampp\htdocs\brightlab\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php line 2483
```

Could you please have another look?

**Comment by tobias-kuendig** [comment]
It problably is `property_values`, plural:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/models/Product.php#L166

**Comment by maartenmachiels** [comment]
Hi @tobias-kuendig , this works like a charm. Thanks! This is so useful!
