### ISSUE TITLE
Filter by category doesn't work with MySQL Index driver

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-mall-plugin#803]
Hello,

This issue is related to [this other](https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/710) issue that had a [PR](https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/738).

I noticed that it works when your index driver is filesystem, but not MySQL, but I don't know why, indexing systems are quite obscure to me.

Even if it's related to category filtering, I think it's another problem, so I decided to create a new issue.

Best regards,

**Comment by tobias-kuendig** [comment]
Can you check if this change fixes the issue for you?

adf6757

**Comment by PubliAlex** [comment]
Your modification fixed the issue. Thank you

**Comment by tobias-kuendig** [comment]
Thank you for reporting and testing this!
