### ISSUE TITLE
Add price variable to page scope for easier theming

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-mall-plugin#804]
Hello,

I noticed something weird on the component product. When you update a product property, it's quite easy to deal with updated data because you associate the whole item object to $this->page['item'], same for stock with $this->page['stock']

The problem is that you don't do this for the price in the stockCheckResponse() method. Instead of that, you use the renderPartial() method and provide all variables by adding a $data array as parameters..

        $data['price'] = Price::fromArray($priceData);
        return [
            '.mall-product__price' => $this->renderPartial($this->alias . '::price', $data),
            '.mall-product__info' => $this->renderPartial($this->alias . '::info', $data),
            '.mall-product__add-to-cart' => $this->renderPartial($this->alias . '::addtocart', $data),
        ];

A consequence of that is that when you create your own theme for mall, you are obliged to create div using the same hardcoded classes if you want to get access to the refreshed object.

It would be better, like you already do it with stock and item, to add the new price  in $this->page['price']

The modification is minimal, just have to edit a line of code, replace this : 

`$data['price'] = Price::fromArray($priceData);`

By this : 

`$data['price'] = $this->page['price'] = Price::fromArray($priceData);`

Best regards,

Alex

**Comment by tobias-kuendig** [comment]
This is a good point! Would you mind creating a PR with this change?

**Comment by PubliAlex** [comment]
[PR Added](https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/813)
