### ISSUE TITLE
Ability to compare products

### ISSUE THREAD

**Issue by artistro08** [OFFLINE-GmbH/oc-mall-plugin#810]
Hey! So I'm looking into something for my clients where you can compare 2 or three more products. How exactly would I go about doing that? 

the flow would essentially be:

 - Person views product
 - Person clicks  "Compare button"
 - Person is presented products that are like the product and can select one 
 - once selected, they are able to view the description and quick anecdotes (additional info)

Is this doable and should we do it in PHP vs Javascript?

**Comment by tobias-kuendig** [comment]
This should be doable using standard October Components. Make a new «Comparision» Component that you can provide two products to. Then iterate over all properties and display them in a table.
