### ISSUE TITLE
mall.order.afterCreate is fired before the order products are attached to the order

### ISSUE THREAD

**Issue by maartenmachiels** [OFFLINE-GmbH/oc-mall-plugin#819]
Hi @tobias-kuendig ,

I'm trying to loop over all the products in the order via the `mall.order.afterCreate` event. Basically it's an extra column in the `offline_mall_order_products table`, that I need to populate upon creation of the order.

The problem is that `mall.order.afterCreate` is fired before the order products are attached to the order.  Therefore I cannot loop over the products of the order.

When I move [this line](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/8701c07350503b764c03cb08c2afc1470945a8a1/models/Order.php#L200) in the Order model:

             Event::fire('mall.order.afterCreate', [$order, $cart]);

to below this block...

            $cart
                ->loadMissing(['products.product.brand'])
                ->products
                ->each(function (CartProduct $entry) use ($order) {
                    $entry->moveToOrder($order);
                });

... the problem is solved and the order products are immediately accessible via the `mall.order.afterCreate` event.

Could I kindly request that we move this line? Or is there a reason why the event is triggered at the current line?
I'd be more than happy to submit a pull request. 

Thanks in advance for your response.

**Comment by tobias-kuendig** [comment]
Hey @maartenmachiels! Thank you for this input. This looks like it was simply an oversight and there is no problem with moving that line.

Fixed in https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/b104849606639f2929f676c189d52a16aefc8628

**Comment by maartenmachiels** [comment]
Thank you so much, Tobias!
