### ISSUE TITLE
Error when updating mall

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-mall-plugin#820]
When I update october 2 using php artisan october:update, it crash when it comes to the mall update, here is the error : 

```
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'offline_mall_shipping_method_discount' already exists   
  (SQL: create table `offline_mall_shipping_method_discount` (`id` int unsigned not null auto_increment primary key, `sh  
  ipping_method_id` int unsigned not null, `discount_id` int unsigned not null, `created_at` timestamp null, `updated_at  
  ` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB)           
```   

Best regards,

**Comment by tobias-kuendig** [comment]
This table is only created in this migration:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/0081e76c8d5d48cd1666476646d2de34487d57bd/updates/create_offline_mall_shipping_method_discount.php

This would mean, that October does not see this migration as run, but the table is present in your database.

What version does this query return for you?

```sql
SELECT * FROM `system_plugin_versions` WHERE code = 'OFFLINE.Mall'
```

Also, how many results does this query return?

```sql
SELECT * FROM `system_plugin_history` where code = 'OFFLINE.Mall'
```

**Comment by PubliAlex** [comment]
Sorry I can't give you the information, I updated mall by adding a small code that check the table existence before create it, so my installation is up to date now.

**Comment by tobias-kuendig** [comment]
Alright, I have to assume this was specific to your installation. Until other users complain, I'll close this issue for now.
