### ISSUE TITLE
 Connection refused offline_mall_notifications

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#848]
I'm seeing this error intermitterntly. Could be from any page. Table definitely exists.
OCMS 2.1.8, Mall 1.14.2.
Anyone any iseas? Thanks.

SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = dbname and table_name = offline_mall_notifications and table_type = 'BASE TABLE')

#0 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(743): Illuminate\Database\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
#1 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(723): Illuminate\Database\Connection->tryAgainIfCausedByLostConnection(Object(Illuminate\Database\QueryException), 'select * from i...', Array, Object(Closure))
#2 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(632): Illuminate\Database\Connection->handleQueryException(Object(Illuminate\Database\QueryException), 'select * from i...', Array, Object(Closure))
#3 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
#4 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(18): Illuminate\Database\Connection->select('select * from i...', Array)
#5 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Database\Schema\MySqlBuilder->hasTable('offline_mall_no...')
#6 /sites1/public_html/plugins/offline/mall/models/Notification.php(34): Illuminate\Support\Facades\Facade::__callStatic('hasTable', Array)
#7 /sites1/public_html/plugins/offline/mall/classes/events/MailingEventHandler.php(23): OFFLINE\Mall\Models\Notification::getEnabled()
#8 [internal function]: OFFLINE\Mall\Classes\Events\MailingEventHandler->__construct()
#9 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(843): ReflectionClass->newInstanceArgs(Array)
#10 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\Container\Container->build('OFFLINE\\Mall\\Cl...')
#11 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\Container\Container->resolve('OFFLINE\\Mall\\Cl...', Array, false)
#12 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(265): Illuminate\Foundation\Application->resolve('OFFLINE\\Mall\\Cl...', Array, false)
#13 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(October\Rain\Foundation\Application), Array)
#14 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\Container\Container->build(Object(Closure))
#15 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\Container\Container->resolve('MailingEventHan...', Array, true)
#16 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Foundation\Application->resolve('MailingEventHan...', Array)
#17 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\Container\Container->make('MailingEventHan...', Array)
#18 /sites1/public_html/vendor/october/rain/src/Foundation/Application.php(214): Illuminate\Foundation\Application->make('MailingEventHan...')
#19 /sites1/public_html/vendor/october/rain/src/Events/Dispatcher.php(177): October\Rain\Foundation\Application->make('MailingEventHan...')
#20 /sites1/public_html/vendor/october/rain/src/Events/Dispatcher.php(163): October\Rain\Events\Dispatcher->resolveSubscriber('MailingEventHan...')
#21 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): October\Rain\Events\Dispatcher->subscribe('MailingEventHan...')
#22 /sites1/public_html/plugins/offline/mall/classes/registration/BootEvents.php(43): Illuminate\Support\Facades\Facade::__callStatic('subscribe', Array)
#23 /sites1/public_html/plugins/offline/mall/classes/registration/BootEvents.php(25): OFFLINE\Mall\Plugin->registerGenericEvents()
#24 /sites1/public_html/plugins/offline/mall/Plugin.php(51): OFFLINE\Mall\Plugin->registerEvents()
#25 /sites1/public_html/modules/system/classes/PluginManager.php(288): OFFLINE\Mall\Plugin->boot()
#26 /sites1/public_html/modules/system/classes/PluginManager.php(271): System\Classes\PluginManager->bootPlugin(Object(OFFLINE\Mall\Plugin))
#27 /sites1/public_html/modules/system/ServiceProvider.php(105): System\Classes\PluginManager->bootAll()
#28 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): System\ServiceProvider->boot()
#29 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#30 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#31 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(October\Rain\Foundation\Application), Array, Object(Closure))
#32 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call(Object(October\Rain\Foundation\Application), Array, Array, NULL)
#33 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(856): Illuminate\Container\Container->call(Array)
#34 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(839): Illuminate\Foundation\Application->bootProvider(Object(System\ServiceProvider))
#35 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(System\ServiceProvider), 38)
#36 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(840): array_walk(Array, Object(Closure))
#37 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#38 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(219): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(October\Rain\Foundation\Application))
#39 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(156): Illuminate\Foundation\Application->bootstrapWith(Array)
#40 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Foundation\Http\Kernel->bootstrap()
#41 /sites1/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#42 /sites1/public_html/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#43 {main}

**Comment by tobias-kuendig** [comment]
This sounds like a problem with your server. Check your access rights and credentials, `Connection refused` almost certainly means you are missing permissions or your server is under heavy load.

**Comment by dathwa** [comment]
> This sounds like a problem with your server. Check your access rights and credentials, `Connection refused` almost certainly means you are missing permissions or your server is under heavy load.

Yeah. I suspected as much. Thought I'd put it out there anyway. Just seemed strange that it was only ever this table. Thanks.
