### ISSUE TITLE
Duplicate Email

### ISSUE THREAD

**Issue by hackolein** [OFFLINE-GmbH/oc-mall-plugin#882]
Hey,

i have create two accounts with different email addresses example1@example.com and example2@example.com. After that I logged in as example1@example.com and I can change the email in my profile in example2@example.com. Now I have two Accounts with the same email. So one user can't login or in worst case if the users have same password and the wrong user is before the other in DB, they get the wrong data. Is that a Rainlab/user or a mall problem?

**Comment by tobias-kuendig** [comment]
I'm pretty sure this is a Mall problem. I believe that we require e-mails to be non-unique for guest accounts. We override RainLab.Users validation here: https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/0ab7a3befe50228226ff957174e0441b1b85b94a/models/User.php#L17

We would have to check why (and if it is required that) the e-mail is no longer validated for uniqueness.

**Comment by hackolein** [comment]
Ok. For the guest order I also need a email, so it maybe make sense to make the email uniqueness. But when I change the user in the Backend it shows an error, duplicate email.

**Comment by SamBrishes** [comment]
This issue has been fixed and released with v3.2.0 / v3.2.1.

**Comment by chocolata** [comment]
Hi @SamBrishes 

I now have the issue that I cannot change any of the other fields on the profile page. If you leave the email address untouched and lets say change the password, the following error message appears.

`A user with this email address is already registered.`

This has the unfortunate consequence that people cannot really use their profile page to change their settings.

Can we fix this please?

**Comment by tobias-kuendig** [comment]
This is fixed in 3.3.0. Please let me know if the issue persists.
