### ISSUE TITLE
Property groups sort order

### ISSUE THREAD

**Issue by dimti** [OFFLINE-GmbH/oc-mall-plugin#884]
This in products filter component https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/0ab7a3befe50228226ff957174e0441b1b85b94a/components/ProductsFilter.php#L417

Need use correctly sort ordering key **relation_sort_order**, because in Category model in model relation definition with PropertyGroup use that name of the sort order field: https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/0ab7a3befe50228226ff957174e0441b1b85b94a/models/Category.php#L104

**Comment by tobias-kuendig** [comment]
Fixed in e540877, thank you for bringing this up!
