### ISSUE TITLE
Currency bug. Important!

### ISSUE THREAD

**Issue by anik1ng** [OFFLINE-GmbH/oc-mall-plugin#885]
Hi! I found important bug.

Look, product is 1495 eur:
<img width="1680" alt="Screenshot 2021-12-02 at 19 13 01" src="https://user-images.githubusercontent.com/505388/144420678-65f7db4f-d745-4783-b3cd-5332df078547.png">

Change currency to usd:
<img width="1680" alt="Screenshot 2021-12-02 at 19 19 44" src="https://user-images.githubusercontent.com/505388/144420764-15ee19ae-69a7-45e6-9883-841c27b0bcfa.png">

Ok, looks good. Price converted by currency rate, ok.

Now, create order, and look this order (price ok):
<img width="1680" alt="Screenshot 2021-12-02 at 19 13 27" src="https://user-images.githubusercontent.com/505388/144421323-1ba42c2f-0268-410e-bc80-9204f5c717fc.png">

Now, i change currency to usd and we can look bug:
<img width="1680" alt="Screenshot 2021-12-02 at 19 27 52" src="https://user-images.githubusercontent.com/505388/144421957-473fe8a4-c8cd-43eb-acde-667f2c187e80.png">
Price $1495, but right price will be $1995. Price not converted — it's bug.

And another trouble, it's wrong price in the backend order page!
I set on frontend EUR currency, look my backend orders page:
<img width="1680" alt="Screenshot 2021-12-02 at 19 30 34" src="https://user-images.githubusercontent.com/505388/144422357-1c1a8ae7-67cf-4972-9f9e-1169724d4334.png">

Now i change on frontend currency to USD, and again found bug:
<img width="1680" alt="Screenshot 2021-12-02 at 19 30 18" src="https://user-images.githubusercontent.com/505388/144422448-d53d302c-c05b-4283-8ead-b3298e0275d4.png">

**Comment by tobias-kuendig** [comment]
Fixed in #886, thank you!
