### ISSUE TITLE
An error "Class'Filebase\Database' not found" is displayed when adding products

### ISSUE THREAD

**Issue by forin777** [OFFLINE-GmbH/oc-mall-plugin#890]
An error "Class'Filebase\Database' not found" is displayed when adding products

**Comment by tobias-kuendig** [comment]
Make sure to install the `offline/jsonq` and `tmarois/filebase` composer packages if you use the file based index as described here:
https://offline-gmbh.github.io/oc-mall-plugin/getting-started/installation.html#optional-packages

Another option is to use the MySQL index by selecting it in the backend settings of the plugin.

Let me know if you need further help!
