### ISSUE TITLE
High overload, 504 error if in cart many products. Bug with cart?

### ISSUE THREAD

**Issue by anik1ng** [OFFLINE-GmbH/oc-mall-plugin#893]
If user add many products in cart. In my case 55 products in cart. Any site page for this user shutting down because site shows high load.

If disable cart component from front end pages, site again work fast and good. Home page with 55 products in cart loading for 30-40 sec, without products in cart for 1-2 sec.

I try find high load with clockwork, and i think what count total price leads to load.

**Comment by tobias-kuendig** [comment]
Can you get a sql query count for these pages?

**Comment by anik1ng** [comment]
> Can you get a sql query count for these pages and a log where we see what queries are run?

It's not sql query problem, look at screenshot:
![photo_2021-12-30 13 21 29](https://user-images.githubusercontent.com/505388/147727163-0600a8ae-6e49-4fed-8eea-03c1a069d490.jpeg)

SQL queries work fast (43ms). But site loading so long — 30+ sec

**Comment by tobias-kuendig** [comment]
It does not look like the MySQL queries are the problem. Do you use any image processing plugin? Do you resize images? Is it possible that someone uploaded a very big image?

Try removing any image outputs or disabling any image processing plugins next. Also try to load only a certain number of products first and see if the page works if you only display 3-4 products in a for loop.

**Comment by anik1ng** [comment]
> It does not look like the MySQL queries are the problem. Do you use any image processing plugin? Do you resize images? Is it possible that someone uploaded a very big image?
> 
> Try removing any image outputs or disabling any image processing plugins next. Also try to load only a certain number of products first and see if the page works if you only display 3-4 products in a for loop.

It's not product lists problem. It's [cart] component problem.

Look. I have a user, who add 55 products in cart and site will shutting down. Any page where placed [cart] component will be load 30-40-50-60 or more secs.

Step by step error case — i open backend, go to user list, and loggin as user (impersonate) who have 55 products in cart.
When i go to site main page, not product lists, not cart page. Just home page with cart price counter in header (component [cart]), and site will shutting down (load more 30-40-50 secs).

It's not images problem, it's cart problem. Problem counting price information to cart products.

**Comment by anik1ng** [comment]
How i see with xdebug, site down where Mall try calculate taxes — https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/0a329470b17d89e6f40c148fa5b2b7b6e4f67788/classes/totals/TotalsCalculator.php#L103

**Comment by anik1ng** [comment]
@tobias-kuendig Tobias, need you help to solve this problem. It's very important.

I create test platform. Clean installation OctoberCMS 1.1.9 and latest Mall with demo theme and demo products (php artisan mall:seed-demo). I created test user with a discount by customer group, and added 37 items to my cart (all demo products). And the site has slowed down a lot.

**Clockwork test:**

User with 1 product in cart:
<img width="1680" alt="Screenshot 2022-01-07 at 10 13 40" src="https://user-images.githubusercontent.com/505388/148486312-dd0f5243-df34-408c-85cf-bc588190f134.png">
Works good, 1 second to load home page.


User with 37 products in cart:
<img width="1680" alt="Screenshot 2022-01-07 at 09 55 15" src="https://user-images.githubusercontent.com/505388/148486457-08310d5d-bb82-4560-9dd6-ec44ed0d97a0.png">
Here we see the problem. More than 10 seconds to load home page.

It's not db problem:
<img width="1680" alt="Screenshot 2022-01-07 at 09 57 25" src="https://user-images.githubusercontent.com/505388/148486573-bfedf92e-5fed-47eb-9b92-ec2e7f13d171.png">

Models information:
<img width="1680" alt="Screenshot 2022-01-07 at 09 57 16" src="https://user-images.githubusercontent.com/505388/148486686-f8482cfc-83ae-4df1-8770-ebee18a27637.png">
To load home page with a cart count products, we get 12705 Currency models, 4200 ProductPrice models, and 2590 CartProduct models, maybe because of this and slows down the site? 


You can test it, here zipped testing website:
https://www.dropbox.com/s/fo3akgxcix52ejz/malltest.zip?dl=0

Just unzip and run, db dump in file `malltest.sql`. Admin login/password — admin/admin

**Comment by tobias-kuendig** [comment]
Thank you very much for your work on this issue!

Can you try and remove all the `$with` properties on the following models: `CartProduct`, `Cart`, `Variant` and `Product` and see if this solves the issue for you?

**Comment by anik1ng** [comment]
> Thank you very much for your work on this issue!
> 
> Can you try and remove all the `$with` properties on the following models: `CartProduct`, `Cart`, `Variant` and `Product` and see if this solves the issue for you?

You solution fix the problem. Big thanks! But without $with will everything work well?

**Comment by tobias-kuendig** [comment]
> But without $with will everything work well?

Yes, you can remove them. There might be certain actions that generate more SQL queries than needed without the `with` but given that your site does not work at all otherwise this is the better solution. 

I'll fix the performance issue in a future release.

**Comment by tobias-kuendig** [comment]
Implemented in 97c8d4a, thank you for bringing this issue to our attention!
