### ISSUE TITLE
Adding custom data to products component

### ISSUE THREAD

**Issue by vosco88** [OFFLINE-GmbH/oc-mall-plugin#896]
Hi, 

I am extending `Product` with many to many relationship with the `User` model (storing some interactions between users and products there). I want to display the data in product list for currently logged in user (for example showing whether they already liked it). 
I can get the data  displayed until I start using Filters on Category page. 

The partial gets refreshed normally, but the `{{user}}` variable that I use is not present anymore. Could you help of what could I do to still get the user data on partial refresh?

And related question - how could I extend filters component based on these? So filtering out the products that user has interacted with?

Thank you

**Comment by tobias-kuendig** [comment]
> The partial gets refreshed normally, but the {{user}} variable that I use is not present anymore. Could you help of what could I do to still get the user data on partial refresh?

Where is your `user` variable defined? You could try to set it in a custom component or even a cms page, then it should be accessible after the page refresh.

> And related question - how could I extend filters component based on these? So filtering out the products that user has interacted with?

You can create your own component that extends the Products component and override methods you want to change. Another option is that we include an Event::fire() call in the component that gives you the option to filter the returned $results before they are processed by the component. This should happen here: If you want to go this route feel free to submit a PR with the added Event:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/Products.php#L350

**Comment by vosco88** [comment]
Thank you, will check it out what fits better for my use case.

**Comment by tobias-kuendig** [comment]
Feel free to reply to this issue if you have any further questions.

**Comment by damsfx** [comment]
Hi @tobias-kuendig ,

Where would be the best position to trigger an event on the returned results?  
After [fetching results from index](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/Products.php#L350) or just before [paginate results](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/Products.php#L374)?
