### ISSUE TITLE
Sort order filter not working properly

### ISSUE THREAD

**Issue by bmiskoski** [OFFLINE-GmbH/oc-mall-plugin#897]
Hello,

There is an issue regarding the sort order filter on the category page.

When an user goes to the category page and chooses an option from the sort order drop-down, the very first choice works great, the partial with the products is updated and the URL is changed with the choice from the drop-down. Any other choice is not working, the URL doesn't change and the partial doesn't refresh. (the other filters work as expected)

I have tried this on a brand new October installation, installed the Mall plugin and set up the category page as per the setup documentation. Then added a couple test products and categories and the issue occurs. 

OctoberCMS version: 2.1.26
Mall plugin version: 1.15.5

First experienced this issue with the new 2.0 version of OctoberCMS.

**Comment by bmiskoski** [comment]
Hey,

After some digging of my own, I have seem to find the problem and a possible solution.

In the file \OFFLINE\Mall\Components\ProductsFilter.php on line 481 in the function getSortOrder() we return the input for sort or the optional fallback.

`return input('sort', $fallback);`

This seems to be the problem because once it reloads the partial of the products with the given sort criteria and change the URL, for example sort=price_high then for every new sort choice it will always get the URL sort value and won't show any changes.

I've changed the return value to:

`return request()->input('sort', $fallback);`

This way it takes the input value from the request, and not from the URL itself.

This change doesn't seem to break any relation to the other filters from the time I had to test the functionality out.

If you can check this out, I can open a PR if that is an acceptable solution.

All the best.

**Comment by tobias-kuendig** [comment]
This has been implemented in 7ec86a7 (post should get precedence over get)

Thank you for bringing this up!
