### ISSUE TITLE
Display totalDiscounts Pre taxes for pro clients

### ISSUE THREAD

**Issue by CarolinePublipresse** [OFFLINE-GmbH/oc-mall-plugin#899]
Hi, I'm trying to display total discounts pre taxes in cart. 

this is not a available actually in the _cart.totals_ variable (calculated in TotalsCalculator class). It would be a great improvement for B2B websites. Maybe we could choose in the Discount item form if it should apply on PreTax or PostTax products total. What do you think ?

In the meantime I tried to calculate it myself, but I'm having a very strange issue : I can't use the _totalDiscounts_ value. 
I see it in the dump of  the _cart.totals_ class, but impossible to access to it. It returns _null_. I can't undersand why because the other values are accessible with the same code.
See below :

![image](https://user-images.githubusercontent.com/84564072/155702017-9d98afea-a653-4614-a7b9-c19c97cddd70.png)
![image](https://user-images.githubusercontent.com/84564072/155702782-65dbe040-fc3e-4622-8546-47a6e0053811.png)

Have you any idea why it is behaving like this ?

**Comment by CarolinePublipresse** [comment]
I created a pull request to fix the non accesssible variable problem. 
#900

**Comment by tobias-kuendig** [comment]
Closed in #900
