### ISSUE TITLE
Price filters don't work correctly with CustomerGroup prices

### ISSUE THREAD

**Issue by tobias-kuendig** [OFFLINE-GmbH/oc-mall-plugin#90]
This won't be easy to fix since there is a lot of magic going on when using customer group specific prices.

Currently the price range filter will use the effective price values of all products - not the ones that apply for the CustomerGroup.

Somehow we have to get the lowest and highest price...

* when using global discounts
* when a specific price for a group was specified

... while honoring all automatic currency conversions.

**Comment by amdad** [comment]
I guess so. Not easy but, for sure worth it.  
Especially it works in a first place. Broke one function to quick fix of another is not way out.
