### ISSUE TITLE
Can't open general settings or products

### ISSUE THREAD

**Issue by ARL-Steve** [OFFLINE-GmbH/oc-mall-plugin#901]
On a fresh install of the mall plugin I get the following error when I try to open general settings or products 
```
Backend\Classes\FormField::getOptionsFromModel(): Return value must be of type array, Cms\Classes\CmsObjectCollection returned

~\modules\backend\classes\FormField.php line 642
```
All the other settings and pages work correctly. I've tried with and without seed data and the error is the same. This is on OctoberCMS v2.2.1. Any help or pointers would be most appreciated.

**Comment by dathwa** [comment]
Here's the quick fix from OFFLINE...

Add an additional ->toArray() 
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/models/GeneralSettings.php#L47

```
return Page
            ::listInTheme( Theme::getActiveTheme(), true)
            ->mapWithKeys(function($page) {
                return [$page->baseFileName => $page->title];
            })->toArray();
```

Note: any other issues on ocms2.2 on front end. add this to your .env file: `CMS_SECURITY_POLICY_V1=true`

**Comment by ARL-Steve** [comment]
Hi thanks for that.

The products page still won't open. The error is

```
Undefined array key "id"

~\plugins\offline\mall\classes\traits\HashIds.php line 17
```
This is failing at this line of code

```
public function getHashIdAttribute()
    {
        return app(Hasher::class)->encode($this->attributes['id']);
    }
```

Putting a debugger on this line and the model appears to be empty causing the exception.

**Comment by tobias-kuendig** [comment]
These are all compatibility issues with October 2.2. Looks like some work is required to get everything working.

**Comment by ARL-Steve** [comment]
At least it doesn't appear to be anything I've done. I'll downgrade for now. Thank you all for your help.
