### ISSUE TITLE
Loader not working properly

### ISSUE THREAD

**Issue by RobertCh2** [OFFLINE-GmbH/oc-mall-plugin#903]
Loading indicator (spinning circle, partial loader.htm) on Products page is displayed all the time in the corner. How to get it to work properly? And also on Payment page in the Cart is displayed for the moment in the corner, shifting layout of the page.

**Comment by tobias-kuendig** [comment]
Do you use a custom theme? Sounds like CSS issues to me. Compare your theme with the demo at https://mall.offline.swiss/ and check what is different

**Comment by RobertCh2** [comment]
No, I use standard theme. There are no differences. How is the loader switched on / off? By javascript?

**Comment by tobias-kuendig** [comment]
It happens here:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/cdf7a3240c25a12d42823348f1e3488350e429ab/components/products/scripts.htm#L5
