### ISSUE TITLE
Allow other modules to extend user

### ISSUE THREAD

**Issue by CarolinePublipresse** [OFFLINE-GmbH/oc-mall-plugin#906]
Hi, 
I created a plugin to extend user, to fill pro legal data. I added the fields to the register form, but my custom fields data was never saved to the user model. 
It comes from the Custommer class, on CreateUser() function. The $data array is rewriten with only the basic mall/user needed params. 

I proposed a pull request #905 
Let me know if it is valid, or if it migth have some unwanted consequences I didn't thought about.

**Comment by tobias-kuendig** [comment]
Fixed in #905
