### ISSUE TITLE
Add Russian language please

### ISSUE THREAD

**Issue by HomaEEE** [OFFLINE-GmbH/oc-mall-plugin#91]
I make translate to russian, I hope that this expand the audience
https://crowdin.com/project/mall-october-cms/ru#

**Comment by tobias-kuendig** [comment]
This is great, thank you!

I'm not familiar with crowdin, how do I get the translations out? When trying to open your project it seems to be "suspended":

![image](https://user-images.githubusercontent.com/8600029/50897232-ca230800-140b-11e9-894b-5aa36cb62bb8.png)

**Comment by HomaEEE** [comment]
[https://dropmefiles.com/iyh8W](url)

**Comment by tobias-kuendig** [comment]
Released as v1.0.4, thank you! :clap:

**Comment by Sicklou** [comment]
How can we propose a translation for the plugin ?

**Comment by tobias-kuendig** [comment]
You can create a pull request on GitHub with the new language files:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/tree/develop/lang
