### ISSUE TITLE
Will Mall work with Winter CMS?

### ISSUE THREAD

**Issue by qroft** [OFFLINE-GmbH/oc-mall-plugin#914]
I know that in theory and based on the "before 2.0" version the October CMS plugins should work without a problem with the Winter CMS. Can you say anything about if Mall will continue to work on future Winter CMS versions or will you only concentrate on an implementation within October CMS?
The plugin looks absolutely beautiful and super easy to handle, thanks for that!

**Comment by tobias-kuendig** [comment]
Thank you for reaching out. I cannot predict the future, but for the time being the plugin will probably remain compatible with both CMS platforms. After all, it's in everyone's interest to keep everything as backwards compatible as possible.

While we do not use Winter ourselves, we are always open for PRs from the community that fix any future compatibility issues.

**Comment by qroft** [comment]
Oh no :( I just tried to install it through the Winter CMS backend and it says that it needs the rainlab translate plugin. But that plugin has been substituted by the "winter.translate" plugin.
Unfortunately i am a mess with Github, but can i simply change that source within the code?

**Comment by mbnoimi** [comment]
@tobias-kuendig 
For me Winter is the future so I wish to see Mall compatible with it. October no longer community friendly (which is really frustrating).
I wish to see Mall works with Winter soon.
