### ISSUE TITLE
The MAC is Invalid

### ISSUE THREAD

**Issue by artistro08** [OFFLINE-GmbH/oc-mall-plugin#917]
I have no idea why this error appeared, but it's very short. I upgraded my install of OctoberCMS a while ago to v2 and I never changed the key. 

Is there a way to delete the encrypted content and start over without uninstalling and re-installing the plugin?

**Comment by artistro08** [comment]
I was able to delete the data and re-encrypt things

**Comment by papppeter** [comment]
hi @artistro08 , could you write down what you did exacly? It was related with paypal payment?

i have the same problem...

**Comment by artistro08** [comment]
@papppeter It's been so long since I had to deal with this that I don't even think I'll be a of help. Sorry man

**Comment by papppeter** [comment]
No worries, thanks for your answer. At the and we just deleted the encripted keys. and readded them.

i think the issue was i change app_key accidentaly.
