### ISSUE TITLE
It is recommended that resource files be placed in the plugin

### ISSUE THREAD

**Issue by ZhiweiWu0425** [OFFLINE-GmbH/oc-mall-plugin#918]
Access to remote cdn resources may be slow in some countries and regions
It is recommended that resource files be placed in the plugin
![image](https://user-images.githubusercontent.com/89636889/159686138-591c43a7-99ed-437e-a6fe-ff8c2695e905.png)

**Comment by tobias-kuendig** [comment]
Thank you @ZhiweiWu0425! This issue will be fixed in v3.2.2.
