### ISSUE TITLE
Error when trying to access the Offline Mall Dashboard from backend

### ISSUE THREAD

**Issue by StanleyBonhomme** [OFFLINE-GmbH/oc-mall-plugin#919]
Im using OctoberCMS v1 and as of late when trying to access the Offline Mal "**Catalogue**" settings from the backend it returns the following error:

**The partial 'modules/backend/widgets/form/partials/_field_dropdown.htm.htm' is not found.**
C:\laragon\www\myoctober\modules\system\traits\ViewMaker.php line 91

[Screenshot of error with stacktrace](https://photos.app.goo.gl/iXDcQLXMqGKE22ki9)

This error occurs when ever I try and edit a product that have variants. How can I solve this annoying issue. I'm getting ready to launch a ecommerce site for a client soon. Any help will be greatly appreciated.

**Comment by tobias-kuendig** [comment]
This is the fix for this issue: f21c6bacfa8335f2102bf2311e8565e952ee748b

I will release a new version tomorrow.

**Comment by tobias-kuendig** [comment]
v1.16.1 is available now. Thank you for reporting this bug!
