### ISSUE TITLE
Error on install (index idx_deleted_at already exists on "offline_mall_categories")

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-mall-plugin#92]
Hello,

When I try to install the module using the october CMS backend, I got the following error during install : 

    "SQLSTATE[HY000]: General error: 1 index idx_deleted_at already exists (SQL: create index "idx_deleted_at" on "offline_mall_categories" ("deleted_at"))" on line 664 of /vendor/laravel/framework/src/Illuminate/Database/Connection.php

For infos, I'm on SQLite.

Best regards,

Alex

**Comment by tobias-kuendig** [comment]
Thank you for the bug report.

Are you running the installation on a blank database?

The index gets created only here: https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/733b277fd6bf3b067a7fa0c7d4bee2e7172f9ae4/updates/create_offline_mall_categories.php#L30

So it shouldn't be created a second time. Can you confirm your database did not contain any `offline_mall_*` tables before the installation?

**Comment by PubliAlex** [comment]
Yes, my install is quite recent and "blank", only have some utility modules like twig_dump, responsive images... nothing crazy

When I saw the error, I looked for offline_mall tables in the database and manually delete them all in order to try to reinstall the module, but same error.

**Comment by tobias-kuendig** [comment]
Thank you, can you try again with the latest version 1.0.5?

I was able to fix some SQLite issues.

**Comment by tobias-kuendig** [comment]
The plugin requires php 7.1. It looks like you are on an older version.

**Comment by PubliAlex** [comment]
Ah ok, I'm on 7.0. I will upgrade !
