### ISSUE TITLE
Mall User Account Bug.

### ISSUE THREAD

**Issue by StanleyBonhomme** [OFFLINE-GmbH/oc-mall-plugin#922]
When i a user account is created on the frontend. Its populates the user profile and customer address with the wrong data.  For example if i create a front end user with the name John Smith. When i go to the account section under the first name and last name is not what I entered. See video link below:

[Video Proof](https://streamable.com/ge4kt1)

What would be the cause of this?

**Comment by tobias-kuendig** [comment]
Did you have the database properly emptied? Is it possible that old customer profiles are around that link to the same user id? In this case only the first customer profile will be fetched, not the newly created.

**Comment by StanleyBonhomme** [comment]
> Did you have the database properly emptied? Is it possible that old customer profiles are around that link to the same user id? In this case only the first customer profile will be fetched, not the newly created.

Hello @tobias-kuendig thanks for getting back to me on this issue. Indeed, the problem was what you stated. I had to empty the database properly to fix resolve the issue. Thanks for the suggestion and your help.
