### ISSUE TITLE
Remove Plugin force issue

### ISSUE THREAD

**Issue by MateThemes** [OFFLINE-GmbH/oc-mall-plugin#923]
Hello everyone

After deinstalling the Mall plugin and error occured.

The error message "Class "Barryvdh\DomPDF\ServiceProvider" not found" is displayed. I can not access the backend and the frontend.

What can I do to get the backend working again?

Thanks

**Comment by tobias-kuendig** [comment]
This is problably because of a dependency conflict. Try installing the dependency in your project directly:

```
composer require barryvdh/laravel-dompdf ^0.9
```

**Comment by MateThemes** [comment]
Thanks for your help now everything works fine again!
