### ISSUE TITLE
The payment provider I am using does not use Omnipay sdk, how can I solve it?

### ISSUE THREAD

**Issue by ZhiweiWu0425** [OFFLINE-GmbH/oc-mall-plugin#924]
The payment provider I am using does not use Omnipay sdk.
I am using Alipay official php SDK. The return value is json or GuzzleHttp\Psr7\Response. But it seems that Mall must use Symfony\Component\HttpFoundation\Response in various operations of payment. Include the handler inside result->success(). This has caused many payment platforms in China to be unable to add payment providers quickly and easily.

**Comment by tobias-kuendig** [comment]
There is no need to use Ominpay. Here is a payment provider from our Microcart plugin (that uses the same codebase as Mall) that does not use Omnipay: 
https://github.com/OFFLINE-GmbH/oc-microcart-plugin/blob/master/classes/payments/SixSaferPay.php

You can wrap your redirect URL in a Symfony response yourself and return that instead.

**Comment by ZhiweiWu0425** [comment]
Thanks for the guidance, it gave me ideas🎉
