### ISSUE TITLE
Does the mall support direct "buy now" for a certain item?

### ISSUE THREAD

**Issue by ZhiweiWu0425** [OFFLINE-GmbH/oc-mall-plugin#925]
Hi，I found that when an order is generated, "fromCart" must accept Cart data. Can't I directly purchase the current product?

**Comment by tobias-kuendig** [comment]
No, unfotunately this is out of the scope of this plugin. Maybe https://github.com/OFFLINE-GmbH/oc-microcart-plugin fits your needs better.
