### ISSUE TITLE
Unable to add user: 'customer_group' undefined.

### ISSUE THREAD

**Issue by venturism** [OFFLINE-GmbH/oc-mall-plugin#93]
When trying to add a user this exception is show: 
**Model 'RainLab\User\Models\User' does not contain a definition for 'customer_group'.**

RainLab/User : 1.4.6
OFFLINE/Mall : 1.0.6

**Comment by tobias-kuendig** [comment]
Thank you for this bug report. This problem has been fixed in 65c3fc2 and is released to the Marketplace in version 1.0.8.
