### ISSUE TITLE
Add to cart with services in Products components

### ISSUE THREAD

**Issue by kj4team** [OFFLINE-GmbH/oc-mall-plugin#930]
Hi guys,

Is there any way to make the add to cart button in the Products component? 

Thanks

**Comment by tobias-kuendig** [comment]
Hi @kj4team, there is an example in the docs that should help you:
https://offline-gmbh.github.io/oc-mall-plugin/components/products.html#example-implementations

**Comment by kj4team** [comment]
Hi @tobias-kuendig, I already read that. But that feature sends the product with/without variant straight to the cart, not open the services pop-up

**Comment by Tciferblatt** [comment]
I also did't find a solution how to add a product to cart from the category with services modal (pop-up).
I will be grateful for the hint...
