### ISSUE TITLE
PropertyGroup per Product.

### ISSUE THREAD

**Issue by mjauvin** [OFFLINE-GmbH/oc-mall-plugin#936]
Hi Tobias!

Would you accept a PR that adds PropertyGroups to the Product model?
I've got it mostly figured out, but it's a bit more challenging to add support for this in a plugin.

Thanks,

**Comment by tobias-kuendig** [comment]
Sounds great! Altough I wonder, did you think this through with features like the product filter? Filters are currently generated based on the category configuration. If you've got mixed Products in a Category it could get hard to generate matching filters for it.
