### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by RobinAdlung** [OFFLINE-GmbH/oc-mall-plugin#939]
Hi there! 

I was trying to install the plugin for October CMS V3 (Build 3.0.44)  following the guidelines of the documentation.
Unfortunately, it ended up returning the following error. 

![cmd_2022-06-14_11-55-22](https://user-images.githubusercontent.com/63674253/173550164-5fdae36f-dabf-46aa-940f-ed44fc562b8f.jpg)

I also couldn't reach the backend of my website anymore after installing this. 

Now I have to admit that I am still quite a beginner in working with October CMS and its plugins.
Perhaps I did something wrong when installing it? 

I hope that someone knows a solution, because plugin looked like I could handle implementing it compared to other even more complex plugins for OctoberCMS. ^^'

Thank you very much and have a great day!

**Comment by RobinAdlung** [comment]
Seems like it is due to the plugin not supporting October Version 3.x yet. I hope it will maybe work someday in the future.

**Comment by tobias-kuendig** [comment]
This should be fixed in the latest version, thank you for reporting the issue!
