### ISSUE TITLE
Undefined index: isActive on add item menu

### ISSUE THREAD

**Issue by PrestaSafe** [OFFLINE-GmbH/oc-mall-plugin#94]
Hi, when i put a category in the menu, it's return an exception. 

<img width="1291" alt="capture d ecran 2019-01-11 a 22 43 42" src="https://user-images.githubusercontent.com/4788787/51061139-76264800-15f2-11e9-94ab-3b47145502b5.png">
<img width="904" alt="capture d ecran 2019-01-11 a 22 44 09" src="https://user-images.githubusercontent.com/4788787/51061142-77f00b80-15f2-11e9-9b1e-208d3bde96dc.png">

Do you khnow where it came from ? I've the mall stater template. 
Thanks

**Comment by tobias-kuendig** [comment]
Thank you for your bug report! This problem was fixed in ced90cf and released to the marketplace as v1.0.10.
