### ISSUE TITLE
When  "An off-site payment has been completed" we are not redirected to "thank you page"

### ISSUE THREAD

**Issue by xyzqtc** [OFFLINE-GmbH/oc-mall-plugin#948]
Hello Tobias, we are using Qteco mallmolliepayments plugin and
It seems when we are redirected to "...checkout?return=return&oc-mall_payment_id=" as a returnUrl after successful payment we are not redirected to the thank you page.

It seems we cannot redirect from onRun method:

```
public function onRun()
{
        // An off-site payment has been completed
        if ($type = request()->input('return')) {
            return $this->handleOffSiteReturn($type);
            
            ...
}
```

I tried redirecting from onRender method and it works.

```
public function onRender()
{
        // An off-site payment has been completed
        if ($type = request()->input('return')) {
            return $this->handleOffSiteReturn($type);
}
```

Do you know any other solution to this problem so you can update the original code?

**Comment by xyzqtc** [comment]
```
public function onRun()
{
        // An off-site payment has been completed
        if ($type = request()->input('return')) {
            abort($this->handleOffSiteReturn($type);)
            
            ...
}
```
works too

**Comment by tobias-kuendig** [comment]
Are you sure the redirect does not work and it ides not some other issue? I am not aware of any breaking change  in that regard and redirects from `onRun` have worked since forever.

**Comment by xyzqtc** [comment]
Ah yes you are probably right!
I extended your component onRun() method and when calling parent::onRun in it its not redirecting.
So I copied your logic inside my onRun() method and it works fine.

**Comment by tobias-kuendig** [comment]
You have to make sure to also return any returns from the parent method:

```php
public function onRun()
{
    $originalReturn = parent::onRun();

    // Your custom stuff

	return $originalReturn;
}
```
