### ISSUE TITLE
Add custom fields to the database index

### ISSUE THREAD

**Issue by chocolata** [OFFLINE-GmbH/oc-mall-plugin#949]
Hi @tobias-kuendig 

I'm eager to start using the database index driver, but there is one big snag I would like your advice on.
Since our store features ticket sales for date based events, I created a custom plugin that extends the offline_mall_products table with two fields, `start_date` and `end_date`. I ended up going this route, after our discussion here: [https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/759](https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/759)

The problem is that whenever I try to use the database index driver, I get the following error, since my two custom fields are used for the sorting mechanism on the site:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'start_date' in 'order clause' (SQL: select `product_id` as `id`, `variant_id` as `other_id`, `is_ghost` from `offline_mall_index` where `index` = products and `published` = 1 and (JSON_CONTAINS(category_id, [3])) order by `start_date` asc)`

The weird thing is that the filebased index driver seems to pick up my custom fields without issue.  But I'd like to get away from the filebased index, as it has its own issues.

I've tried creating a migration that adds the two fields to the `offline_mall_index `table, but that table seems to get rebuilt whenever `php artisan mall:reindex` is run. And then my fields are dropped, and the values are never filled out.

So my question is: what is the recommended way to add two custom fields to the database index? Thanks in advance.

**Comment by chocolata** [comment]
Hi @tobias-kuendig 

Could you kindly have a look at this issue when you find a moment?
Thanks in advance.

**Comment by tobias-kuendig** [comment]
Hi @chocolata 

Sorry for the delayed response. 

I guess the easiest method would be to add a `mall.index.mysql.extendTable` event here:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/index/mysql/MySQL.php#L136

That event would receive the `$table` blueprint. Any event listener could add their own custom columns this way.

We could add another `mall.index.extendData` event here (move the data array to a variable and pass that to the event):
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/index/mysql/MySQL.php#L75

Event listeners for this event could add their own fields to the `$data` variable that is sent to the database.

Would that be enough for your use-case? Would you be willing to submit a PR with these changes?

**Comment by chocolata** [comment]
Thanks so much for your insights. I'll investigate thoroughly, do some testing and will try to provide a pull request soon.

**Comment by chocolata** [comment]
Hi Tobias,

I finally got round to making and testing the edits. Please find my pull request here:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/980

In my custom plugin, I'm doing the following in the boot method of Plugin.php

        // Allow adding the date field to the MySQL index
        Event::listen('mall.index.extendData', function($data) {
            $customIndexData = [];
            if(isset($data['start_date'])) {
                $customIndexData['start_date'] = $data['start_date'];
            }
            if(isset($data['end_date'])) {
                $customIndexData['end_date'] = $data['end_date'];
            }
            return $customIndexData;
        });

        // Extend the OFFLINE Mall MySQL index to accept our custom fields
        Event::listen('mall.index.mysql.extendTable', function() {
            Schema::table('offline_mall_index', function($table) {
                if (!Schema::hasColumn('offline_mall_index', 'start_date')) {
                    $table->timestamp('start_date')->nullable();
                }
                if (!Schema::hasColumn('offline_mall_index', 'end_date')) {
                    $table->timestamp('end_date')->nullable();
                }
                $table->index(['start_date', 'end_date'], 'idx_event');
            });
        });

I've tested thoroughly and it seems to work. Could you kindly review and consider these changes?

Thanks again.

**Comment by chocolata** [comment]
Sorry, I forgot to add the Event class at the top of the document:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/981

**Comment by cyril-design** [comment]
Hi !

I used these events but I have an error if I use `php artisan mall:reindex` command...

In MySQL.php line 306:
`str_contains(): Argument #2 ($needle) must be of type string, array given `

Thanks

**Comment by tobias-kuendig** [comment]
Can you change the second parameter here into a string and try again?

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/c7ea1ddcd63a066cad6a8b0b78035beaef8d4c8f/classes/index/mysql/MySQL.php#L306

```diff
        return $e->getCode() === '42000'
-            && str_contains($e->getMessage(), ['SQL syntax', 'near \'json']);
+            && str_contains($e->getMessage(), 'SQL syntax', 'near \'json');
```

**Comment by cyril-design** [comment]
`str_contains() expects exactly 2 arguments, 3 given ` ?

**Comment by tobias-kuendig** [comment]
@cyril-design did the wrong change. update Mall to version v3.0.19, the issue should be fixed in there.

**Comment by cyril-design** [comment]
Thanks @tobias-kuendig but I have the same error after `Dropping existing index...` in console

**Comment by tobias-kuendig** [comment]
@cyril-design try this line: https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/70220de7cb817684b33b1e59b55f2686d98425b8/classes/index/mysql/MySQL.php#L306

**Comment by cyril-design** [comment]
Perfect !
It works. Thanks
