### ISSUE TITLE
free shipping

### ISSUE THREAD

**Issue by ajsaces** [OFFLINE-GmbH/oc-mall-plugin#95]
I seem to be missing the logic with the free shipping option. 

(Initially I am testing your demo theme plus demo dataset)

For my project I dont even need shipping as is basically service based and is built into price. However for testing: 

I set a "Default Shipping" <= $100 = $10 
I set a separate "Free Shipping" > $100 = $0

Get exception errors on whole site if I set "Free Shipping" @ $0.00. Looks like when the discounts() functioning is applied (I have tested with/without a discounts example) 

see exception
![image](https://user-images.githubusercontent.com/46471237/51070218-eb952580-1691-11e9-87a7-42e0bb929aea.png)

**Comment by ajsaces** [comment]
By the way. I love this plugin. For my purposes is easily the best framework for what I need. Congrats. Apart from this minor issue which is probably even just me misinterpreting this is great work. I hope to support this when I get more into the dev on it. Cheers AJ

**Comment by ajsaces** [comment]
ok sorted. Just needed to add an "alternate shipping" record in discounts and issue sorted.

**Comment by tobias-kuendig** [comment]
Thanks for reporting the issue. The exception shouldn't occur, obviously. I'll take a look at it.

**Comment by tobias-kuendig** [comment]
This problem was fixed in a7f65df and released to the marketplace as v1.0.11

**Comment by ajsaces** [comment]
thanks mate
