### ISSUE TITLE
Error with Carbon Creator

### ISSUE THREAD

**Issue by webBook-cz** [OFFLINE-GmbH/oc-mall-plugin#954]
Hi,

after creating order I'm getting this error:

Carbon\Exceptions\InvalidFormatException: Unexpected data found.
Trailing data in /home/lessem/public_html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:676

![error](https://user-images.githubusercontent.com/14330711/189879913-d0b94815-bb93-4721-a387-c158bab045b8.PNG)

My setup:
- October 3.0.72
- Mall plugin 2.0.8
- PHP 8.0.22
- Composer 2.2.5

**Comment by xyzqtc** [comment]
Same error, did you fix it?

**Comment by xyzqtc** [comment]
This is happening because of this:
https://laravel.com/docs/7.x/upgrade#date-serialization

One solution is to set public $timestamps = false; in OFFLINE\Mall\Models\Currency

**Comment by xyzqtc** [comment]
Second solution is 
 in OFFLINE\Mall\Models\Currency
 
```
public function getDateFormat()
 {
    return 'Y-m-d H:i:s';
}
```

**Comment by damsfx** [comment]
Same error here after updating a site to Laravel 9.  
The issue come from the `toArray()` method used in Currency model.
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/97cd64446fb9437b1261c4cb5763d779fc12565c/models/Currency.php#L152

In Laravel v6, `toArray()` return a formated date like `2022-09-20 14:57:36`.  
In Laravel v9, `toArray()` return a formated date like `2022-09-20T14:57:36.000000Z`, and result in an issue when trying to convert a cart to order.

You need to delete your current session to see this issue.
