### ISSUE TITLE
Billing/Shipping name stays empty in Order Preview

### ISSUE THREAD

**Issue by georgij-** [OFFLINE-GmbH/oc-mall-plugin#973]
I'm facing an issue where the customer field stays empty in the order preview page. 

A proposed fix would be to change the null coalescing operator with a ternary operator.

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/c993a885d860b13cae5b2a6670545405559cba30/classes/customer/DefaultSignUpHandler.php#L73

In my tests, the "??" operator always chooses and returns an empty string (in this case if the user hasn't filled $addressData['address_name'] ) instead of choosing the $fullname variable.

**Comment by tobias-kuendig** [comment]
Thank you for this report! This has been fixed in 1e7ecb8

**Comment by georgijk5** [comment]
Thank you @tobias-kuendig for the swift response.

May I add that we can also include the same logic in the billing portion of the code, shown here?

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/c993a885d860b13cae5b2a6670545405559cba30/classes/customer/DefaultSignUpHandler.php#L63

Thanks again!

**Comment by georgij-** [comment]
Thank you @tobias-kuendig for the swift response.

May I add that we can also include the same logic in the billing portion of the code, shown here?

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/c993a885d860b13cae5b2a6670545405559cba30/classes/customer/DefaultSignUpHandler.php#L63

Thanks again!

**Comment by tobias-kuendig** [comment]
Good catch, thank you this is fixed!
