### ISSUE TITLE
Have you found a solution to the Double payment confirmation notification to client ?

### ISSUE THREAD

**Issue by CarolinePublipresse** [OFFLINE-GmbH/oc-mall-plugin#979]
Have you found a solution to the Double payment confirmation notification to client ? 
I'm having the same problem, and this makes Gmail block some mails in spam, before the client mailbox... So not in the client mailbox at all, even in spams section.

_Originally posted by @CarolinePublipresse in https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/877#issuecomment-1344082803_

**Comment by CarolinePublipresse** [comment]
I tried to figure it out, and it seems that the mail is sent twice because it is ine Order->AfterUpdate() function, that is called several times. 
A is_dirty() test is made that I don't understand well. 

Here are my logs tests  in /plugins/offline/mall/models/Order.php : 
```
public function afterUpdate()
    {
        trace_log('Order.php afterUpdate()');
        if ($this->isDirty('payment_state')) {
            // Don't trigger payment changes during the checkout flow. A mall.checkout.succeeded
            // Event will already be triggered in the PaymentRedirector.
            $flow = session()->get('mall.checkout.flow');
            if ($flow !== 'checkout') {
                trace_log('Order.php afterUpdate() isDirty[payment_state] fire mall.order.payment_state.changed');
                Event::fire('mall.order.payment_state.changed', [$this]);
            }
            // If the order became paid, distribute all virtual products.
            if ($this->payment_state === PaidState::class && $this->paid_at === null) {
                
                trace_log('Order.php afterUpdate() order became paid');
                if ($this->virtual_products->count() > 0) {
                    Queue::push(SendVirtualProductFiles::class, ['order' => $this->id]);
                }
                $this->paid_at = Carbon::today();
                $this->save();
            }
        }
        if ($this->isDirty('order_state_id')) {
            Event::fire('mall.order.state.changed', [$this]);
        }
        if ($this->isDirty('tracking_url') || $this->isDirty('tracking_number')) {
            Event::fire('mall.order.tracking.changed', [$this]);
        }
        if ($this->getOriginal('shipped_at') === null && $this->isDirty('shipped_at')) {
            Event::fire('mall.order.shipped', [$this]);
        }
    }
```
And the results : 
![image](https://user-images.githubusercontent.com/84564072/206750192-550de34f-747f-471e-9adb-8548e440ad9d.png)

How could we make a test to check if the payment really changes, or if it is already registered as paid ?

Or did I make a mistake on my Complete function that launches twice the order update ? 
Here is the function called from the distant payment service : 

```
public function completeIpn($response)
    {
        trace_log('Systempay.php completeIpn()');
        $responseAll = $response->all();
        $order = Order::findOrFail($responseAll['vads_order_id']);

        $this->setOrder($response->order);
        $result = new PaymentResult($this, $order);

        try {
            $response = $this->getGateway()->completePurchase($this->options($result))->send();
        } catch (Throwable $e) {
            return $result->fail([], $e);
        }

        $data = (array)$response->getData();
        
        $order->payment_transaction_id = $response->getTransactionReference();
        
        if (!$response->isSuccessful()) {
            Event::fire('mall.checkout.failed', [$result]); // mail to the admin
            return $result->fail($data, $response);
        }
        
        //return $result->success($data, null);
        Event::fire('mall.checkout.succeeded', [$result]); // mail to the admin
        return $result->success($data, $response);
    }
```

Any idea ? 
Thanks for your help

**Comment by CarolinePublipresse** [comment]
@PubliAlex Thank you very very much for this answer. It was driving me nuts !

**Comment by chocolata** [comment]
Hi @SamBrishes , could you kindly let us know if we might find a solution for this issue? 
I created a private plugin for the Mollie payment solution, and it seems that the webhook is always fired multiple times.

![image](https://github.com/OFFLINE-GmbH/oc-mall-plugin/assets/3584586/6b1d30e1-77aa-40c9-8fdd-82d44ecfbca4)

I'd like to create an invoice as soon as the Paymentstate is set to Paid, but as this triggers multiple times this creates undesirable results. I'm doing a lot of workarounds now, but I think it would be more efficient if we could solve this once and for all.

What do you think about this?

**Comment by tobias-kuendig** [comment]
Good catch @PubliAlex! Saving quietly should solve this issue :shushing_face: (b3e0a488)
