### ISSUE TITLE
Taxing per State

### ISSUE THREAD

**Issue by artistro08** [OFFLINE-GmbH/oc-mall-plugin#985]
Is there a way to add taxes per state? 

Here's an example. Let's say someone is buying from Detroit, United States. I want to charge them the Detroit tax when they checkout.

Is this possible with the current plugin state and if not, could you give me a head start to implement it? 

Would love to have this feature.

**Comment by tobias-kuendig** [comment]
A Tax model can currently only belong to a Country, so it is not possible out of the box:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/models/Tax.php#L52

To implement it, you'd have to add a state relation as well, and link it to RainLab.Locations' State model.
Then you'd have to filter by state here: https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/traits/FilteredTaxes.php#L25 

Then work backwards and see where this method is used.

**Comment by artistro08** [comment]
Closing as I am gonna create a custom plugin for my setup with this functionality. Thanks again!
