### ISSUE TITLE
mall:reindex fails

### ISSUE THREAD

**Issue by inalto** [OFFLINE-GmbH/oc-mall-plugin#987]
running mall reindex fails:

Dropping existing index...
Reindexing products...

In MySQL.php line 92:

  array_merge(): Argument #2 must be of type array, null given

it is a small bug, im fixing it.

$customIndexData arrives as:

array:1 [▼
  0 => null
]

which tecnically is not empty.

**Comment by inalto** [comment]
fix for:
TypeError: array_merge(): Argument #2 must be of type array, null given in **/home/quiyou/public_html/plugins/offline/mall/classes/index/mysql/MySQL.php:92**

#988

**Comment by tobias-kuendig** [comment]
Closed in #988
