### ISSUE TITLE
Can not seed demo on WINTER CMS

### ISSUE THREAD

**Issue by nowhinjing-ever** [OFFLINE-GmbH/oc-mall-plugin#995]
I am trying to load the demo on to winter CMS, all goes fine until I try to seed-demo when I get a large red banner saying :
 
The "name" argument does not exist.

Would you help me, please.

**Comment by tatisminou** [comment]
development.ERROR: Symfony\Component\Console\Exception\InvalidArgumentException: The "name" argument does not exist. in /var/www/html/vendor/symfony/console/Input/ArrayInput.php:188
Stack trace:
#0 /var/www/html/vendor/symfony/console/Input/ArrayInput.php(127): Symfony\Component\Console\Input\ArrayInput->addArgument()
#1 /var/www/html/vendor/symfony/console/Input/Input.php(52): Symfony\Component\Console\Input\ArrayInput->parse()
#2 /var/www/html/vendor/symfony/console/Command/Command.php(271): Symfony\Component\Console\Input\Input->bind()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(152): Symfony\Component\Console\Command\Command->run()
#4 /var/www/html/vendor/symfony/console/Application.php(1022): Illuminate\Console\Command->run()
#5 /var/www/html/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand()
#6 /var/www/html/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(193): Illuminate\Console\Application->run()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(336): Illuminate\Console\Application->call()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\Foundation\Console\Kernel->call()
#11 /var/www/html/plugins/offline/mall/console/SeedDemoData.php(103): Illuminate\Support\Facades\Facade::__callStatic()
#12 /var/www/html/plugins/offline/mall/console/SeedDemoData.php(55): OFFLINE\Mall\Console\SeedDemoData->cleanup()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): OFFLINE\Mall\Console\SeedDemoData->handle()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\Container\BoundMethod::call()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call()
#19 /var/www/html/vendor/symfony/console/Command/Command.php(312): Illuminate\Console\Command->execute()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(152): Symfony\Component\Console\Command\Command->run()
#21 /var/www/html/vendor/symfony/console/Application.php(1022): Illuminate\Console\Command->run()
#22 /var/www/html/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand()
#23 /var/www/html/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\Console\Application->run()
#26 /var/www/html/artisan(33): Illuminate\Foundation\Console\Kernel->handle()
#27 {main}

**Comment by cyril-design** [comment]
Same error with a fresh OcotberCMS (3.51) installation

**Comment by tobias-kuendig** [comment]
Someone needs to figure out how to call the Artisan command on the different Laravel versions correctly:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/console/SeedDemoData.php#L100

**Comment by cyril-design** [comment]
I have just installed a very very fresh oc install and everything works perfectly ( and again thank you for your work ) !

Laravel Framework: 9.52.16
