### ISSUE TITLE
Override `Payments/Stripe` default `stripe\form.htm`

### ISSUE THREAD

**Issue by matteo-palazzo** [OFFLINE-GmbH/oc-mall-plugin#997]
Hi guys,

I'm trying to customize the `stripe/form.htm` by copying the template inside my theme folder `partials/mall/payments/stripe/form.htm`, but I get a `Cms\Classes\CmsException` "Unknown 'put' tag".

It seems that the `(new Twig)->parse(...)` in `OFFLINE\Mall\Classes\Payments\PaymentProvider:150` cannot resolve the `{% put scripts %}` tag, but the `Twig` instance defined a few lines below can do it. Should we use the same `Twig` instance for both overridden template and default template?

@mattia-marchiorato

**Comment by tobias-kuendig** [comment]
Resolved in #998
